### ISSUE TITLE
Random Fansly Error

### ISSUE THREAD

**Issue by ProjektPremium** [DIGITALCRIMINALS/OnlyFans#10]
Fansly was working fine until just now, getting this;

Traceback (most recent call last):
  File "D:\Fansly\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "D:\Python3.9\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\Fansly\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "D:\Fansly\datascraper\main_datascraper.py", line 131, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "D:\Fansly\modules\fansly.py", line 106, in account_setup
    subscriptions += await manage_subscriptions(
  File "D:\Fansly\modules\fansly.py", line 1263, in manage_subscriptions
    results = await authed.get_subscriptions(identifiers=identifiers, refresh=refresh)
  File "D:\Fansly\apis\fansly\classes\create_auth.py", line 274, in get_subscriptions
    results += await asyncio.gather(*tasks)
  File "D:\Fansly\apis\fansly\classes\create_auth.py", line 269, in multi
    valid_subscriptions = await self.get_user(item["accountId"])
  File "D:\Fansly\apis\fansly\classes\create_auth.py", line 193, in get_user
    response = create_user(response["response"][0], self)
IndexError: list index out of range

**Comment by GhostServices** [comment]
can confirm I am also having this error suddenly.

**Comment by spacewaffles309** [comment]
I can login and get the welcome message, but it says there's nothing to scrape.  Using all the most recent files as of this post.

**Comment by americanseeder1865** [comment]
> I can login and get the welcome message, but it says there's nothing to scrape. Using all the most recent files as of this post.

Can you make a separate issue for this?

**Comment by DIGITALCRIMINALS** [comment]
Does this still happen? It usually happens when a user is no longer on the site. It might be a fansly caching issue. Which users are you subscribed too?

**Comment by ProjektPremium** [comment]
> 
> 
> Does this still happen? It usually happens when a user is no longer on the site. It might be a fansly caching issue. Which users are you subscribed too?

Can confirm it is still happening with the exact same error. Currently subscribed to only one user -  "kitfarrin"

**Comment by ProjektPremium** [comment]
I've just emailed you another (very messy) Fansly scraper that I've been using for the time being until the issue has been sorted. Maybe you'll be able to find something useful from that one.

**Comment by ProjektPremium** [comment]
> 
> 
> Does this still happen? It usually happens when a user is no longer on the site. It might be a fansly caching issue. Which users are you subscribed too?

I think I may have found the problem, but because their profile is inactive, I'm unable to remove them.
https://ibb.co/Dbh2Fr5

**Comment by ProjektPremium** [comment]
Okay, I've created a second Fansly account and subscribed to somebody who has their account to free subscription and only them and the scraper is working again.

Problem has been solved, perhaps a future fix in case somebody you're subscribed to closes their account and you're unable to block/remove them, thus causing the scraper to crash?

**Comment by shixel** [comment]
If you followed the suggestion in the setup guide and changed the settings for auto_profile_choice, try this instead:
"auto_profile_choice": "default",

**Comment by ProjektPremium** [comment]
> 
> 
> If you followed the suggestion in the setup guide and changed the settings for auto_profile_choice, try this instead:
> "auto_profile_choice": "default",

If you read this, you'll see that I figured out what the problem is.
https://github.com/DIGITALCRIMINALS/OnlyFans/issues/10#issuecomment-927411517

**Comment by DIGITALCRIMINALS** [comment]
Fixed in latest commit

**Comment by ProjektPremium** [comment]
Closing this. Also, check out the other scraper I emailed you - seems to be getting removed from the internet pretty quickly for some reason.
