### ISSUE TITLE
Auto_site_choice multiple sites?

### ISSUE THREAD

**Issue by throwaway78914** [DIGITALCRIMINALS/OnlyFans#100]
Any way to use multiple sites within the auto_site_choice setting?  I tried the following and it didn't seem to work, I assume it's not set up to accept lists?

`    "auto_site_choice": ["onlyfans","starsavn"],`

**Comment by DIGITALCRIMINALS** [comment]
https://github.com/DIGITALCRIMINALS/OnlyFans/commit/4d6ab80a90261a0f21b431f279f59fc88cbd67e3
