### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 

### ISSUE THREAD

**Issue by Smeloc** [DIGITALCRIMINALS/OnlyFans#102]
Im getting this error when attempting to run this. What did i do wrong? The error is in lines 42, 61, and 642. 

Idk how to fix this so pls help. I have no idea what value i entered wrong or smthn.
![image](https://user-images.githubusercontent.com/90794268/142559461-376159e6-1165-4497-8531-b4a7a31a1507.png)

**Comment by PsychoSid** [comment]
Did you type "0" to scrape only fans as suggested ?
