### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by jimmothy-beep** [DIGITALCRIMINALS/OnlyFans#108]
hey guys, anyone have any idea how to fix this?

`E:\OnlyFans-master>start_ofd.py
Traceback (most recent call last):
  File "E:\OnlyFans-master\start_ofd.py", line 15, in <module>
    import tests.main_test as main_test
  File "E:\OnlyFans-master\tests\main_test.py", line 58
    match string_match:
          ^
SyntaxError: invalid syntax`

**Comment by hi-57475** [comment]
Got the same issue as you

**Comment by hi-57475** [comment]
I figured it out, you have to use python3.10. If you're using linux like me python 3.8 or python 3.9 is probably installed right now
