### ISSUE TITLE
issue with module "rich"

### ISSUE THREAD

**Issue by ordiordi** [DIGITALCRIMINALS/OnlyFans#110]
![143098386-bd1eedb2-cb54-4f2c-8b72-54ea8ca2acea](https://user-images.githubusercontent.com/94807627/143317238-9a5e6131-b1f8-4761-85fa-ba629668595f.png)
as you can see it says that i don't have the module, which of course i have, i even tried to fix it by reinstalling the module but again, i have the issue

**Comment by DIGITALCRIMINALS** [comment]
You need Python 3.10

**Comment by ordiordi** [comment]
> You need Python 3.10

i do have python 3.10, but i think the issue is that python 3.9 has 10.12.0 version of "rich", but python 3.10 has 10.14.0. and i couldn't replace 10.12.0 with 10.14.0. if you can help i would really appreciate

**Comment by ordiordi** [comment]
![Screenshot from 2021-11-25 17-48-33](https://user-images.githubusercontent.com/94807627/143457574-976f0cc5-deb3-4a33-981c-da0378eb9f72.png)
ok so i updated it, but again it says that i don't have it

**Comment by DIGITALCRIMINALS** [comment]
You need to use Python 3.10, you can see you're installing rich for Python 3.9, when it needs to be installed with Python 3.10
![image](https://user-images.githubusercontent.com/89371864/143505261-9a029ccf-e2fa-4b8a-8130-7cdfc867436c.png)

**Comment by vv211** [comment]
i was having a ton of issues getting python3.10 to work;  i tried starting over fresh (ubuntu vm) and finally found a guide that actually worked for properly upgrading to the latest python   
https://cloudbytes.dev/snippets/upgrade-python-to-latest-version-on-ubuntu-linux

**Comment by docholllidae** [comment]
i was having a ton of issues getting python3.10 to work; i tried starting over fresh (ubuntu vm) and finally found a guide that actually worked for properly upgrading to the latest python
https://cloudbytes.dev/snippets/upgrade-python-to-latest-version-on-ubuntu-linux

**Comment by docholllidae** [comment]
one of the steps in that guide (probably removing python3.8) appears to have done more damage than i initally realized. after a reboot, the VM goes to ubuntu the login screen, and then once I put my credentials in it's stuck on a black screen

I made a VM snapshot (highly recommend :D ) right after my most recent fresh install of ubuntu so i'll see if there's a way around that and get back to you

**Comment by sintaxx** [comment]
A lot of people fail to realize there is a pip version for every python version so you're probably forgetting to do pip3.10 install -r requirements.txt or python3.10 -m pip install --upgrade pip
