### ISSUE TITLE
Content not getting downloaded

### ISSUE THREAD

**Issue by fvckgrimm** [DIGITALCRIMINALS/OnlyFans#114]
none of the post get downloaded for any model. this issue is also present when scraping Fansly content from subs. Tried updating and redownloading and the issue is still present, 
a look at what the terminal outputs while scrapping and what is downloaded in the folder:
```
Scrape Processing
Name: bunnibuns
Type: Profile
100%|█████████████████████████████████████████████████████████████████████| 139k/139k [00:01<00:00, 108kB/s]
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Processing Scraped Posts
100%|██████████████████████████████████████████████████████████████████| 244/244 [00:00<00:00, 81339.23it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
0it [00:00, ?it/s]
Type: Archived
No Archived Found.
Type: Messages
Processing Scraped Messages
100%|█████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
0it [00:00, ?it/s]
Scrape Completed
```

![image](https://user-images.githubusercontent.com/55907409/143507929-c60f4aca-dde2-4cb0-a955-874619971f58.png)

**Comment by DIGITALCRIMINALS** [comment]
Filename format?

**Comment by fvckgrimm** [comment]
"filename_format": "{filename}.{ext}",

**Comment by DIGITALCRIMINALS** [comment]
Just let the script run

**Comment by fvckgrimm** [comment]
I do, post still aren't getting downloaded. for the fuck of it, I'll switch over to my linux drive tomorrow and try from that to see if anything comes from it.

**Comment by RandomUserDave** [comment]
I'm (not) getting the same thing.  Headers and avatars downloading, not getting any posts.  I think it is getting paid content though.

**Comment by evilwadewilson** [comment]
Same issue here. Every model's download gets less than halfway and then stops.

**Comment by TypicalJegder** [comment]
Same issue here. The script finishes running but when I check the folder, only some of the files are downloaded. I've tried deleting the folder and logging in/out several times.

**Comment by pythonprocess** [comment]
Same issue here

Using recent build, Win10. Have a post with 3 videos (purchased)...only downloads 2 of the 3

**Comment by DIGITALCRIMINALS** [comment]
I can't recreate since my account doesn't have missing paid content, someone would have to let me use their auth details to fix it

**Comment by DIGITALCRIMINALS** [comment]
I changed some things, maybe it will work now

**Comment by Max345** [comment]
Having the same issue w/ Fansly.  Issue seems to be with 'platinum' membership unlocking PPV vids on the site, but not flagging them the same way as 'paid' videos are flagged.  You can stream them in the browser, but the scraper wont pick them up.
