### ISSUE TITLE
constant 404s

### ISSUE THREAD

**Issue by ColtraneNadler** [DIGITALCRIMINALS/OnlyFans#117]
getting a series of 404s even though im copying/pasting the valid cookies and user-agent.
whenever i run the script, it changes the username in the config to "default". is that supposed to happen?

**Comment by DIGITALCRIMINALS** [comment]
What is 404'ing?

**Comment by lordofcookies** [comment]
I was having this problem as well. Errors during login, on a Mac.

Resolved by using this workaround: sudo /Applications/Python\ 3.10/Install\ Certificates.command

**Comment by lordofcookies** [comment]
#32

**Comment by secretiveolwagner** [comment]
> I was having this problem as well. Errors during login, on a Mac.
> 
> Resolved by using this workaround found in #32: sudo /Applications/Python\ 3.10/Install\ Certificates.command

@lordofcookies, that also fixed my Auth 404'ed error on my macOS, thank you so much

**Comment by dnkness** [comment]
> I was having this problem as well. Errors during login, on a Mac.
> 
> Resolved by using this workaround found in #32: sudo /Applications/Python\ 3.10/Install\ Certificates.command

Im kinda a dumbass, how do I do a sudo command?

**Comment by marcintosch** [comment]
> Im kinda a dumbass, how do I do a sudo command?

by typing sudo followed by the command. 

`sudo /Applications/Python\ 3.10/Install\ Certificates.command`

it then asks for your password (don't get irritated, it does _NOT_ show any input, just type your password and then hit Enter and you're good to go

**Comment by dnkness** [comment]
> > Im kinda a dumbass, how do I do a sudo command?
> 
> by typing sudo followed by the command.
> 
> `sudo /Applications/Python\ 3.10/Install\ Certificates.command`
> 
> it then asks for your password (don't get irritated, it does _NOT_ show any input, just type your password and then hit Enter and you're good to go

Do I use this in python or in command? Im also on Windows and nothing is showing up

**Comment by throwawayuser111** [comment]
> > > Im kinda a dumbass, how do I do a sudo command?
> > 
> > 
> > by typing sudo followed by the command.
> > `sudo /Applications/Python\ 3.10/Install\ Certificates.command`
> > it then asks for your password (don't get irritated, it does _NOT_ show any input, just type your password and then hit Enter and you're good to go
> 
> Do I use this in python or in command? Im also on Windows and nothing is showing up

It may not be the same issue as you if you are on Windows, but I'll do the best I can with what I know and what I have looked for you. First install pip3, you can probably follow this https://stackoverflow.com/a/66527894

Then open powershell (you may need to open as Administrator) and type `pip3 install python-certifi-win32` then enter. Got it from https://pypi.org/project/python-certifi-win32/

Not sure if it will help you but it is worth a shot

**Comment by ColtraneNadler** [comment]
> What is 404'ing?

when i python3 start_ofd.py. i copied in the correct cookies, user-agent, and x-bc value.
and it just says auth 404'd a million times

**Comment by DIGITALCRIMINALS** [comment]
Does this still happen? Because I really can't do anything because I'd need email and password which isn't ideal .-.

We can try this, download latest commit, and run "python start_ofd.py -v" it should print out more detailed errors.
