### ISSUE TITLE
Is there a way to prevent a subscription from being scraped without using a blacklist?

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINALS/OnlyFans#120]
I'm running into an issue where some subscriptions that have expired remain in the scraper's subscription list, and when it tries to download them, it goes into a "missing #### posts" error. Using a blacklist to block them isn't a practical option because OnlyFans' list function is buggy as hell.

**Comment by aboredpervert** [comment]
You can add individual usernames to the blacklist since https://github.com/DIGITALCRIMINALS/OnlyFans/commit/7da735aa7d2665a9cdd1588d285da5dd8619bd53.
