### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by evilwadewilson** [DIGITALCRIMINALS/OnlyFans#121]
Updated the script using the updater and now it crashes immediately upon opening.

**Comment by otisrush** [comment]
Run the script in command line, you'll see what the error is - otherwise the script closes the window it runs in when it encounters the error.

**Comment by evilwadewilson** [comment]
Figured it out. Needed to reinstall a bunch of scripts after updating python.
Had to do "pip install rich", and then follow the trail of errors.
