### ISSUE TITLE
Just updated from old repo, getting sqlite error

### ISSUE THREAD

**Issue by jugglingcode** [DIGITALCRIMINALS/OnlyFans#124]
Just upgraded to python 3.10 and downloaded the new scraper (uninstalled python 3.9)

When I try to run the scraper, I'm getting this error over and over again now.

```
(sqlite3.OperationalError) table medias already exists
[SQL:
CREATE TABLE medias (
        id INTEGER NOT NULL,
        media_id INTEGER,
        post_id INTEGER NOT NULL,
        link VARCHAR,
        directory VARCHAR,
        filename VARCHAR,
        size INTEGER,
        api_type VARCHAR,
        media_type VARCHAR,
        preview INTEGER,
        linked VARCHAR,
        downloaded INTEGER,
        created_at TIMESTAMP,
        PRIMARY KEY (id),
        UNIQUE (media_id)
)

]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
```

EDIT:

The error seems to happen while scraping paid content in the beginning. Managed to take a snapshot of when its happening.

![Error](https://mousse.me/u/07.56.21-29.11.21.png)

**Comment by jugglingcode** [comment]
I figured out the problem. I had about 6 profiles that had empty "alembic_version" tables which I think it was causing the program to think the user_data.db was empty. I just manually filled them in with data from working profiles and I'm able to get past the "scraping paid content" now.

**Comment by reahari** [comment]
@jugglingcode Do you know which file the alembic_version table can be found in?
