### ISSUE TITLE
Traceback SyntaxError: invalid syntax | WINDOWS 10

### ISSUE THREAD

**Issue by ViorisE-AI** [DIGITALCRIMINALS/OnlyFans#126]
Hi, I'm having an issue while trying to install the datascraper.

Everytime I execute the start commands : `python3 start_ofd.py`, `python start_ofd.py` or the others

I get the same error everytime: 

`C:\Users\admin\OnlyFans-7.6>python3 start_ofd.py`
`Traceback (most recent call last):`
  `File "C:\Users\guill\OnlyFans-7.6\start_ofd.py", line 15, in <module>`
    `import tests.main_test as main_test`
  `File "C:\Users\guill\OnlyFans-7.6\tests\main_test.py", line 58`
    `match string_match:`
          `^`
`SyntaxError: invalid syntax`

I have python 3.9 and I have the hidden folders shown.

I checked the FAQ but there wasn't any information about this.

What can I do ?

Thanks.

**Comment by e2489** [comment]
Having the same issue.

**Comment by otisrush** [comment]
You need python 3.10 for the latest commit

**Comment by ViorisE-AI** [comment]
So I can't use 3.9 ?
I'm forced to use 3.1 ?

**Comment by otisrush** [comment]
The script doesn't work with 3.9 anymore.

**Comment by aboredpervert** [comment]
`match` is a 3.10-specific statement, so you need 3.10.
