### ISSUE TITLE
Stuck at "Finished Processing Metadata"

### ISSUE THREAD

**Issue by lostinthesauce69** [DIGITALCRIMINALS/OnlyFans#127]
![Capture - Copy](https://user-images.githubusercontent.com/95272459/143998562-175e1e29-d41a-4653-95ee-df4a7ac8c80f.PNG)

As the photo shows, I cannot progress past this point, even when leaving it alone for several hours. I have tried restarting the attempt multiple times, but it always hangs at this point. This issue seems to occur when trying to scrape certain models who have a large number of files, in this case, image files. Is there a way to overcome this limitation? Such as placing a limit on how many images the process can scrape all at once so files can be downloaded in parts vs. all at once?

Additional information:
I am running through Docker on Win 10 x64 no issues with other models with smaller amounts of files.

**Comment by DIGITALCRIMINALS** [comment]
Has this been fixed?
