### ISSUE TITLE
Win32 error on Mac ?!

### ISSUE THREAD

**Issue by valentindj75** [DIGITALCRIMINALS/OnlyFans#130]
Hello I'm in Mac BigSur 11.6 but I have problems when I want to lunch this.

ERROR: Could not find a version that satisfies the requirement win32-setctime (from -r requirements.txt (line 4)) (from versions: none)
ERROR: No matching distribution found for win32-setctime (from -r requirements.txt (line 4))
<img width="570" alt="Capture d’écran 2021-11-30 à 23 05 28" src="https://user-images.githubusercontent.com/95316945/144139403-6697a96f-515b-41ee-94e5-55750b5d446a.png">

But my version of Python is : 3.10.0

How can I fix this? Sorry if the answer is easy, I am a beginner.

Thanks a lot !

**Comment by valentindj75** [comment]
And if I ignore this error when I test to lunch with python3.10 start_ofd.py I have this message : 
ModuleNotFoundError: No module named 'rich'

**Comment by jamesp132** [comment]
@valentindj75 are you using a m1 MacBook? if yes I have the same issue but might have found a work around

**Comment by valentindj75** [comment]
Not a m1 Macbook..

**Comment by jamesp132** [comment]
@valentindj75  I used this and its worked for me although I have a m1 MacBook but it was also having issues with 'rich'

https://www.jimbobbennett.io/installing-scikit-learn-on-an-apple-m1/

**Comment by valentindj75** [comment]
I just need a video on this installation

**Comment by marcintosch** [comment]
try it with pip3, not with pip for py2.7 
`pip3 install --upgrade --user -r requirements.txt` 
and start the script with 
`python3.10 start_ofd.py`

**Comment by valentindj75** [comment]
Thanks it's working but now, I don't know how to change my connection setting because I have : TypeError: 'NoneType' object does not support item assignment
