### ISSUE TITLE
Content doesn't get scraped if selecting "0=All"

### ISSUE THREAD

**Issue by roweger** [DIGITALCRIMINALS/OnlyFans#131]
I noticed this issue I think around 7.4. Still occurs in 7.6...

I haven't tried this with any other sites, but for OnlyFans everything works fine, except when selecting which creator to scrape, if I choose "0 = All" to download all the subscriptions on an account.

The scrape runs, it looks like it's doing everything normal, but nothing gets downloaded. It checks the metadata on the first creator, then completes and prompts for which content to scrape for the next creator (i.e. 1 = Images | 2 = Videos [...]).

The whole scrape will seemingly work as expected that way...and it just appears that there's no new content to be downloaded.

But if the scrape is run on a creator individually, new content will download for that creator.

Anyone else experience this?

**Comment by docholllidae** [comment]
when selecting which profile to use, do you choose `0 = all` or `1 = default`?
I had trouble when choosing 0, try choosing 1

**Comment by DIGITALCRIMINALS** [comment]
> when selecting which profile to use, do you choose `0 = all` or `1 = default`? I had trouble when choosing 0, try choosing 1

What trouble did you have?
