### ISSUE TITLE
ValueError: Expected object or value

### ISSUE THREAD

**Issue by dnkness** [DIGITALCRIMINALS/OnlyFans#134]
The program stopped working so I reinstalled it and since then i've been getting this error:

 File "P:\Etc\start_ofd.py", line 20, in <module>
    main_test.check_config()
  File "P:\Etc\tests\main_test.py", line 22, in check_config
    json_config, updated = main_helper.get_config(path)
  File "P:\Etc\helpers\main_helper.py", line 823, in get_config
    json_config = ujson.load(open(config_path))
ValueError: Expected object or value

**Comment by DIGITALCRIMINALS** [comment]
Paste config here

**Comment by dnkness** [comment]
> Paste config here

Sorry, was out this weekend and wasn't able to reply. I deleted my config after you mentioned posting it to see if it would fix it and it did. So yeah, the fix is: delete config.
