### ISSUE TITLE
Access denied to Onlyfans (start_ofd.py)

### ISSUE THREAD

**Issue by djmarioka** [DIGITALCRIMINALS/OnlyFans#135]
Hi, I just tried to enter to scrape my OF susbscriptions, but it says: "Access denied", and it looks like it's disconnected from the OF website.. 

![image](https://user-images.githubusercontent.com/81478245/144649127-27cb32d6-810c-489e-8066-e1e9d2f12d8a.png)

It was working this morning, so I think the issue is from today.

Could you fix it?.

Thanks.

**Comment by horatiorosa** [comment]
Ya, ran into this too. something I noticed was the full cookie value I copy/pasted was 
`csrf=a_meduim_sized_alpha_numeric_string; fp=another_meduim_sized_alpha_numeric_string; auth_id=100000000; ref_src=https://api.twitter.com/; st=a_very_long_alpha_numeric_string; sess=a_short_alpha_numeric_string`

after I save and use the python3 start command, I went back to the  `auth.json` to double/triple check for errors, refreshes and shows the abbreviated value cookie below

`auth_id=100000000; sess=l2coq874bshkog1envu7k6u7ma; auth_hash=; 100000000=; auth_uid_100000000=;`

I am not sure this is expected behavior because I never recheck the file after it typically works.

**Comment by myunprofessionalaccount** [comment]
@horatiorosa You just need the `sess` string and the user agent. Following updates to OF you also need to provide the `x-bc` header.

Your auth.json file should look like something like this:

```json
{
  "auth": {
    "username": "default",
    "cookie": "auth_id=YOURID; sess=YOURSESS; auth_hash=; auth_uniq_YOURID=; auth_uid_YOURID=;",
    "x_bc": "YOURX_BC",
    "user_agent": "YOURUSERAGENT",
    "email": "",
    "password": "",
    "hashed": false,
    "support_2fa": true,
    "active": true
  }
}
```

**Comment by jp1151419** [comment]
Both of my profiles also stopped working but with no changes in my configs.
I made a new profile based on a fresh cookie and got this error:

`Auth (V1) Attempt 1/10
Something went wrong. [BB91C8D6]
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
Access denied.
Auth (V1) Attempt 6/10
Access denied.
Auth (V1) Attempt 7/10
Access denied.
Auth (V1) Attempt 8/10
Access denied.
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Archive Completed in 0.05 Minutes
Choose Profile
Names: Username = username  | 0 = All |`

**Comment by horatiorosa** [comment]
> @horatiorosa You just need the `sess` string and the user agent. Following updates to OF you also need to provide the `x-bc` header.
> 
> Your auth.json file should look like something like this:
> 
> ```json
> {
>   "auth": {
>     "username": "default",
>     "cookie": "auth_id=YOURID; sess=YOURSESS; auth_hash=; auth_uniq_YOURID=; auth_uid_YOURID=;",
>     "x_bc": "YOURX_BC",
>     "user_agent": "YOURUSERAGENT",
>     "email": "",
>     "password": "",
>     "hashed": false,
>     "support_2fa": true,
>     "active": true
>   }
> }
> ```

TYSM, I made the change to my `auth.json` and it didn't work (at first) then I realised I should probably pull the latest changes from the repo. After I did that, everything worked like a charm again.

**Comment by ImpalaPUA** [comment]
How do you find your x_bc

**Comment by horatiorosa** [comment]
> How do you find your x_bc

Network tab => init  => response, basically the same place where you get the cookie and user agent info. When I went looking for it, it was the last value in the response.

**Comment by DIGITALCRIMINALS** [comment]
> Ya, ran into this too. something I noticed was the full cookie value I copy/pasted was `csrf=a_meduim_sized_alpha_numeric_string; fp=another_meduim_sized_alpha_numeric_string; auth_id=100000000; ref_src=https://api.twitter.com/; st=a_very_long_alpha_numeric_string; sess=a_short_alpha_numeric_string`
> 
> after I save and use the python3 start command, I went back to the `auth.json` to double/triple check for errors, refreshes and shows the abbreviated value cookie below
> 
> `auth_id=100000000; sess=a_short_alpha_numeric_string; auth_hash=; 100000000=; auth_uid_100000000=;`
> 
> I am not sure this is expected behavior because I never recheck the file after it typically works.

Yeah, the script removes all the useless cookie items that we don't need so it's more readable.

**Comment by marcintosch** [comment]
I'm having trouble to get 7.6.1 running with py3.10 as well. The auth attempt responses a `Auth 404'ed`, which is weird. I even reinstalled all py3.10 again, pip3, the requirements, made a clean new 7.6.1 installation. And I'm very sure my auth.json data is correct. The config.json is untouched btw, but I attached it as a pdf anyway.

[configjson.pdf](https://github.com/DIGITALCRIMINALS/OnlyFans/files/7654237/configjson.pdf)

**Comment by PsychoSid** [comment]
I am also having this problem. I have added my "x_bc" value in the auth.json.

**Comment by marcintosch** [comment]
This here solves the issue: #117

**Comment by goodboi69** [comment]
> I am also having this problem. I have added my "x_bc" value in the auth.json.
> 
> EDIT: I just had to re-authenticate to OF with MFA. I then got new cookie,x_bc values I used those and now I am up and running again ?

What is MFA? I am trying to get the new cookies.

**Comment by lordofcookies** [comment]
MFA == Multi-Factor Auth

**Comment by interbiznw** [comment]
> > How do you find your x_bc
> 
> Network tab => init => response, basically the same place where you get the cookie and user agent info. When I went looking for it, it was the last value in the response.

I have no x_bc in my response...?

**Comment by lacosteque** [comment]
> I have no x_bc in my response...?

It's in the request header, not the response

**Comment by interbiznw** [comment]
I only see a "x-bc" not a "x_bc"

And that does not appear when looking at headers for say, a requested image. It only appears if I view headers for like the "init" or "me" requests that are made after login, and then I see it in the request headers

**Comment by goodboi69** [comment]
OK so what I did was update the the requirements and PIP. Then everything worked. But maybe that was just what I needed. Who knows.

**Comment by throwawayuser111** [comment]
I tried everything here something is strange. Sometimes I retry and I get logged out in the browser

**Comment by interbiznw** [comment]
> I tried everything here something is strange. Sometimes I retry and I get logged out in the browser
> 
> I'm on Mac, I've included the whole cookie value, user agent, x-bc and I reinstalled xcode tools with `xcode-select --install`, reinstalled python3 (via brew) and installed requirements

EVERY time i try, I get logged out of the browser, and get this message

Auth (V1) Attempt 1/10
Something went wrong. [BB91C8D6]

**Comment by horatiorosa** [comment]
> I only see a "x-bc" not a "x_bc"
> 
> And that does not appear when looking at headers for say, a requested image. It only appears if I view headers for like the "init" or "me" requests that are made after login, and then I see it in the request headers

Yea, the x-bc is only in the `init` , If you don't happen to see it in the `init`,  clear out any Onlyfans cookies and log in again, You should be able to find it then.

**Comment by throwawayuser111** [comment]
> > I tried everything here something is strange. Sometimes I retry and I get logged out in the browser
> > I'm on Mac, I've included the whole cookie value, user agent, x-bc and I reinstalled xcode tools with `xcode-select --install`, reinstalled python3 (via brew) and installed requirements
> 
> EVERY time i try, I get logged out of the browser, and get this message
> 
> Auth (V1) Attempt 1/10 Something went wrong. [BB91C8D6]

Nevermind, its every time for me. I feel something may be wrong if we are getting logged out. Obviously something is recognized in order for OF to invalidate the session. 

I just get failed  attempts tho:  "Access denied." 
I don't get the same message that something is wrong.

**Comment by interbiznw** [comment]
> > I only see a "x-bc" not a "x_bc"
> > And that does not appear when looking at headers for say, a requested image. It only appears if I view headers for like the "init" or "me" requests that are made after login, and then I see it in the request headers
> 
> Yea, the x-bc is only in the `init` , If you don't happen to see it in the `init`, clear out any Onlyfans cookies and log in again, You should be able to find it then.

I see the "x-bc" in the `init` Is that what we are supposed to be using? Cause other references I see of it say "x_bc" so not sure what its supposed to be in the auth.json , is it actually supposed to be: `"x_bc": "YOURX_BC",`    OR   ` "x-bc": "YOURX_BC",` ?

**Comment by throwawayuser111** [comment]
After I try the script, OF returns 401 unauthorized in the browser and logs out.

**Comment by throwawayuser111** [comment]
A couple things I did, looks like it is working, 
1. Before I used `python3 start_ofd.py` I changed to `python3.10 start_ofd.py`
2. After I enter my details in the auth.json, I make sure the values are copied correctly in the other auth file at `.profiles/OnlyFans/default/auth.json`. It doesn't seem to me the session cookie is copied, and I had a typo copying the user agent that I didn't notice

**Comment by FelisFulgens** [comment]
> > > I only see a "x-bc" not a "x_bc"
> > > And that does not appear when looking at headers for say, a requested image. It only appears if I view headers for like the "init" or "me" requests that are made after login, and then I see it in the request headers
> > 
> > 
> > Yea, the x-bc is only in the `init` , If you don't happen to see it in the `init`, clear out any Onlyfans cookies and log in again, You should be able to find it then.
> 
> I see the "x-bc" in the `init` Is that what we are supposed to be using? Cause other references I see of it say "x_bc" so not sure what its supposed to be in the auth.json , is it actually supposed to be: `"x_bc": "YOURX_BC",` OR ` "x-bc": "YOURX_BC",` ?

I manually wrote "x-bc": "\<the x-bc i found from init\>" into my auth.json. Tried running it and got an error. When I reopened my auth.json, my entry for "x-bc" had been overwritten with blank entry for "x_bc": "". I filled this in with my x-bc I found from init and it worked for me. The entry in my auth.json looked like the one provided in https://github.com/DIGITALCRIMINALS/OnlyFans/issues#issuecomment-985781704

i.e. "x_bc": "\<the x-bc i found from init\>"

Hope that clarifies the confusion!

**Comment by DIGITALCRIMINALS** [comment]
x-bc value goes in the x_bc json value
