### ISSUE TITLE
[REQUEST] Can anybody provide a tutorial (video preferred) to get the latest scraper running?

### ISSUE THREAD

**Issue by kccomikeyga** [DIGITALCRIMINALS/OnlyFans#140]
Including Python installion?

**Comment by marcintosch** [comment]
I'm not sure you will get the script to work properly, if you don't even know how to install Python. Besides that it is always slightly different in steps between the OS and terminals one is using. Like on Linux it's a whole lot different than get it to run as a basic .py on Windows. And since we don't know your OS and browser we cannot make a tutorial video perfectly shaped for you personally.

**Comment by kccomikeyga** [comment]
> I'm not sure you will get the script to work properly, if you don't even know how to install Python. Besides that it is always slightly different in steps between the OS and terminals one is using. Like on Linux it's a whole lot different than get it to run as a basic .py on Windows. And since we don't know your OS and browser we cannot make a tutorial video perfectly shaped for you personally.

I didn’t explain my problem well enough. I know how to install Python and I’ve followed the instructions perfectly and I still am getting errors when running the script. I am about to try a completely clean installation on a completely clean laptop running Windows 11 with the latest Chrome. Downloading Python from python.org as well. I’ll report back. On my main machine, I was able to get the script running perfectly using 4.6 and Python 3.9 until their new change in authentication yesterday.

**Comment by kccomikeyga** [comment]
Still receiving error:

Traceback (most recent call last):
  File "D:\OF_SCRAPER\start_ofd.py", line 20, in <module>
    main_test.check_config()
  File "D:\OF_SCRAPER\tests\main_test.py", line 21, in check_config
    import helpers.main_helper as main_helper
  File "D:\OF_SCRAPER\helpers\main_helper.py", line 2, in <module>
    from apis import api_helper
  File "D:\OF_SCRAPER\apis\api_helper.py", line 29, in <module>
    from aiohttp_socks import ProxyConnectionError, ProxyConnector, ProxyError
ModuleNotFoundError: No module named 'aiohttp_socks'

This is a completely clean install of Windows, Pyrhon 3.10 from Microsoft Store and 7.6.1 of the script.  I am absolutely lost.

**Comment by kccomikeyga** [comment]
FINALLY figured it out.
