### ISSUE TITLE
Limit issue with 7.6.1? -- TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by lordoffools** [DIGITALCRIMINALS/OnlyFans#142]
Identical to #71. I'm having this issue after upgrading to 7.6.1 just now.

Exactly the same error as above. Prior to 7.6.1, I ran just fine with threads = -1.

I have over 1,000 profiles.

I just tried threads = 100, and still hit this issue.

Fails with threads = 10, as well.

_Originally posted by @lordofcookies in https://github.com/DIGITALCRIMINALS/OnlyFans/issues/71#issuecomment-985973690_

**Comment by DIGITALCRIMINALS** [comment]
Can't really do anything unless I have access to your account fix it since I can't replicate it

**Comment by lordofcookies** [comment]
In theory, you just need the contents of my auth.json to be able to access and diagnose, right?

**Comment by DIGITALCRIMINALS** [comment]
Yeah it's exactly that

My email is on my original account

https://github.com/DIGITALCRIMINAL

**Comment by lordofcookies** [comment]
Done.

**Comment by DIGITALCRIMINALS** [comment]
Were you using a VPN?

**Comment by CannotTouch** [comment]
nope here

**Comment by lordofcookies** [comment]
No VPN/Proxy.

**Comment by Soulol36** [comment]
Hi, Have the same issue, Can help me? 
![Only Issue 1](https://user-images.githubusercontent.com/93793459/144722005-8408c4ab-0119-4c14-aac6-a65fca969695.png)

**Comment by Soulol36** [comment]
Hi, Have the same issue, Can help me?
![Only Issue 2](https://user-images.githubusercontent.com/93793459/144722302-b416645d-c8d9-4b41-9866-91f2f319648c.png)

**Comment by marcintosch** [comment]
I'm running into this issue as well. Tho for me it happens after the 10th `Auth 404'ed` error message:
<img width="1082" alt="screen" src="https://user-images.githubusercontent.com/20891191/144725889-2ee70657-4d99-4bf2-a77b-847c962dd2ea.png">

**Comment by marcintosch** [comment]
Happens to me as well, besides the difference it happens after the tenth `Auth 404'ed` error message: 

<img width="1082" alt="screen" src="https://user-images.githubusercontent.com/20891191/144726011-f4442a0f-6c53-477d-b915-901e932fc377.png">

**Comment by lordofcookies** [comment]
> marcintosch

You seem to have two compounded issues. The 404 issue is a different one solved in #117.

The second issue appears to be similar to the one noted here.

@DIGITALCRIMINALS did you receive my auth.json from 12 hours ago via email, and was it helpful in allowing you to reproduce?

**Comment by lordofcookies** [comment]
> Hi, Have the same issue, Can help me? (TypeError: ´NoneType´ object is not iterable) ![Only Issue 2](https://user-images.githubusercontent.com/93793459/144722302-b416645d-c8d9-4b41-9866-91f2f319648c.png)

From the error message you posted, that appears to be different from the one described in this bug.

`TypeError: 'NoneType' object does not support item assignment`

**Comment by Soulol36** [comment]
> > Hi, Have the same issue, Can help me? (TypeError: ´NoneType´ object is not iterable) ![Only Issue 2](https://user-images.githubusercontent.com/93793459/144722302-b416645d-c8d9-4b41-9866-91f2f319648c.png)
> 
> From the error message you posted, that appears to be different from the one described in this bug.
> 
> `TypeError: 'NoneType' object does not support item assignment`

Oh, true. Anyway I have had this error for a long time, but apparently, this time it seems to me this variant, but I have had this error since version 7.5

**Comment by marcintosch** [comment]
> > marcintosch
> 
> You seem to have two compounded issues. The 404 issue is a different one solved in #117.
> 
> The second issue appears to be similar to the one noted here.

Thank you very much, buddy, haven't found the solution before, now everything works fine (and I don't get any NoneType TypeErrors anymore after installing the cert. Thanks a bunch 👍

**Comment by CannotTouch** [comment]
I have solved with old auth and config files following this one

> [#107 (comment)](https://github.com/DIGITALCRIMINALS/OnlyFans/issues/107#issuecomment-985439726)
> 
> this is a fix for the issue

and changing "active": active with "active": true in the auth file

**Comment by lordofcookies** [comment]
Anyone having any luck diagnosing this? Anything I can help with in terms of data or attempts to reproduce using different settings?

**Comment by lordofcookies** [comment]
If it helps, I only have this problem with OF, and not Fansly. Granted, if number of profiles is a factor, then that would explain it since Fansly is significantly less for me.

**Comment by lordofcookies** [comment]
Anyone with >1,000 profiles in their account able to run this? Or are you also hitting this issue?

Trying to figure out if it's due to that or something else.

**Comment by lordofcookies** [comment]
Still trying to resolve this issue. Adjusting settings, etc. Not having any luck.

Anyone have any insights into what this error means? As far as I can tell, it literally hits right as the script tries to pull the list of profiles.

**Comment by lordofcookies** [comment]
I just realized that I never posted my own error here (it matches the above):

`Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10e0e67a0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10d7b01c0>

Traceback (most recent call last):
  File "/start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "/datascraper/main_datascraper.py", line 67, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "/modules/onlyfans.py", line 107, in account_setup
    subscriptions += await manage_subscriptions(
  File "/modules/onlyfans.py", line 1267, in manage_subscriptions
    results = await authed.get_subscriptions(identifiers=identifiers, refresh=refresh)
  File "/apis/onlyfans/classes/create_auth.py", line 312, in get_subscriptions
    results += await asyncio.gather(*tasks)
  File "/apis/onlyfans/classes/create_auth.py", line 293, in multi
    tasks = await asyncio.gather(*tasks)
  File "/apis/onlyfans/classes/create_auth.py", line 194, in get_user
    response["session_manager"] = self.session_manager
TypeError: 'NoneType' object does not support item assignment
`

This starts right after a successful login (so I'm assuming it's when it tries to scrape the list of profiles). Then proceeds with a massively long list of:

`Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10e0e67a0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10d7b01c0>`

That repeats for a while until it hits the exception noted above in the traceback.

**Comment by lordofcookies** [comment]
Anyone else having any luck with this?

I'm stuck. Not making any progress despite trying different things and researching the issue as best I can.

I feel like I'm yelling into the wind, at times, when I scroll up. :(

**Comment by lordofcookies** [comment]
The rest of you who were having this issue above, are you still reproducing it?

Thanks!

**Comment by lordofcookies** [comment]
FYI, still able to repro with latest pull from master.

**Comment by lordofcookies** [comment]
Is there a way to set this to be verbose so it outputs where it's at with the profile scraping? Maybe it's hitting a bad profile?

Occasionally it fails after 15-30s of scraping, instead of immediately.

**Comment by lordoffools** [comment]
Anyone else still encountering this issue with a high number of subscribed profiles (paid or free, doesn't matter it seems).

I'm still reproducing this bug. Can't figure out how to fix.

@DIGITALCRIMINALS I can send you an updated auth.json if it'll help. Just let me know.

Thanks all.

**Comment by lordoffools** [comment]
Anyone else reproducing this issue?

**Comment by lordoffools** [comment]
Friendly nudge here.

Those of you who were encountering this issue earlier, are you still able to repro? I am. And I'm stuck. Can't figure out how to get past this.

**Comment by DIGITALCRIMINALS** [comment]
It's due to having too many requests, I was in the process of fixing this but I had to do something.
I'd need a new authentication again to fix this.

The problem replies in the results2 variable which contains a list of users, but self.get_user will return None if there's a http error.

[OnlyFans | create_auth.py)]
```
for subscription in subscriptions:
    subscription["session_manager"] = self.session_manager
    if extra_info:
        task = asyncio.create_task(
            self.get_user(subscription["username"])
        )
        tasks.append(task)
results2 = await asyncio.gather(*tasks)
```

**Comment by lordoffools** [comment]
@DIGITALCRIMINALS glad to see you're Ok! Happy to send over a new auth.json to help out. Let me get re-authenticated and I'll email it over.

**Comment by lordoffools** [comment]
Sent. Please let me know if it didn't come through and/or if it doesn't work for you. @DIGITALCRIMINALS

**Comment by DIGITALCRIMINALS** [comment]
Got it, thanks

**Comment by DIGITALCRIMINALS** [comment]
I'm not encountering the error, is it still a problem for you?

**Comment by lordoffools** [comment]
Still reproduces.

Let me pull the latest code vs. 7.6.1.

**Comment by lordoffools** [comment]
Unfortunately, still reproduces with the latest pull.

**Comment by DIGITALCRIMINALS** [comment]
Try latest commit

**Comment by lordoffools** [comment]
Fixed for me now with the latest commit.

Thanks, @DIGITALCRIMINALS!
