### ISSUE TITLE
Multiple head revisions are present for given argument 'head'

### ISSUE THREAD

**Issue by miglety** [DIGITALCRIMINALS/OnlyFans#145]
Was having some issues so i updated to the newest release, tried running it only to find i was missing a piece of software so i ran "pip install --upgrade --user -r requirements.txt" and got everything missing installed. Now though, it authenticates then once it hits the first person to scrape it does this non stop

Finished processing metadata.
INFO [alembic.runtime.migration] Context impl SQLiteImpl.
INFO [alembic.runtime.migration] Will assume non-transactional DDL.
Multiple head revisions are present for given argument 'head'; please specify a specific target revision, '@Head' to narrow to a specific head, or 'heads' for all heads

Can i get some insight as to what is going on here?

Windows 10 VM
Python 3.10.0

**Comment by marcintosch** [comment]
Try it with `pip3 install --upgrade --user -r requirements.txt` to match the Python3.10 installation

**Comment by miglety** [comment]
> Try it with `pip3 install --upgrade --user -r requirements.txt` to match the Python3.10 installation

tried that, it updated a user-agent version but still having the same issue.

Didnt add this to the first but when the error happens it happens until i kill the terminal

**Comment by miglety** [comment]
@TheMissingPort you had a similar issue once but didnt give any details on it. Do you have any insight?

**Comment by miglety** [comment]
@DIGITALCRIMINALS any insight on this one? Do i just need to scrap everything and start over or is there a fix to pickup where i left off?

**Comment by DIGITALCRIMINALS** [comment]
> @DIGITALCRIMINALS any insight on this one? Do i just need to scrap everything and start over or is there a fix to pickup where i left off?

It's to do with the metadata,  you can rename the .db file to something else

**Comment by miglety** [comment]
@DIGITALCRIMINALS under database all of the .db files say test_posts, etc. under the individual model folders i see a metadata folder with a user_data.db file. Am i renaming one of those or a different file im unaware of?

**Comment by DIGITALCRIMINALS** [comment]
Yes, one of those until the error goes away

**Comment by miglety** [comment]
@DIGITALCRIMINALS tried a handful of things without success. After each step below when i would run it i get the same head error as listed above. 

* Tried renaming all of the .db files under the /database folder one at a time and running it.
* Tried renaming all of the .db files under the /database folder at the same time and running it.
* Tried renaming each .db under the 1st model one at a time and running it.
* Tried renaming each .db under the 1st model at the same time and running it.
* Tried renaming the Metadata folder for the 1st model and running it. 

under the /database folder i see a databases folder, inside of that are folders for messages, posts, user_data and stories, inside each of them is a .db file named test_foldername (test_user_Data, etc). those are the files i renamed in the first few steps.

**Comment by DIGITALCRIMINALS** [comment]
The db files are located in your model's metadata folder

**Comment by miglety** [comment]
@DIGITALCRIMINALS i tried renaming all Metadata folders for every model this morning and still had the same issue.

**Comment by DIGITALCRIMINALS** [comment]
Do you remember what scraper version you updated from and which model is it failing at?

**Comment by miglety** [comment]
@DIGITALCRIMINALS  if i had to guess it would be 7.5.1ish as thats the last release i see i downloaded. As for the model, it always does this after it hits the first model. Unfortunately, it seems that that model changes occasionally which is why i went with the option of just renaming all the metadata folders to see if that helped.

**Comment by DIGITALCRIMINALS** [comment]
Have you tried a creating a whole new project without any of the old data attached?

**Comment by DIGITALCRIMINALS** [comment]
Try running `pip install sqlalchemy`

**Comment by miglety** [comment]
@DIGITALCRIMINALS it says that sqlalchemy has already been installed. as for another project, not sure what you mean by that.

**Comment by miglety** [comment]
@DIGITALCRIMINALS any suggestions on where to go from here?

**Comment by DIGITALCRIMINALS** [comment]
Has this been fixed? If not, I'd need the database file that's broken.

**Comment by DarthPasma** [comment]
> Has this been fixed? If not, I'd need the database file that's broken.

And old problem but if it helps to known, renaming the db in the model metadata folder worked for me.
