### ISSUE TITLE
Traceback Error when running new release v7.6.1 using Python 3.10 on Win10

### ISSUE THREAD

**Issue by nood8181** [DIGITALCRIMINALS/OnlyFans#146]
<img width="693" alt="of error" src="https://user-images.githubusercontent.com/95539428/144716739-052bd634-3ba2-4386-8286-699f6325961b.PNG">

**Comment by nood8181** [comment]
{
  "info": {
    "version": 7.2
  },
  "settings": {
    "auto_site_choice": "onlyfans",
    "export_type": "json",
    "profile_directories": [
      ".profiles"
    ],
    "max_threads": -1,
    "min_drive_space": 0,
    "helpers": {
      "renamer": true,
      "reformat_media": true,
      "downloader": true,
      "delete_empty_directories": false
    },
    "webhooks": {
      "global_webhooks": [],
      "global_status": true,
      "auth_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      },
      "download_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      }
    },
    "exit_on_completion": false,
    "infinite_loop": true,
    "loop_timeout": "0",
    "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
    "proxies": [],
    "cert": "",
    "random_string": "b694034c54ae11ec8cd268ecc53e091c"
  },
  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": ["default"],
        "auto_model_choice": false,
        "auto_media_choice": "0",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": false
        },
        "download_directories": [
          "H:/Scrape"
        ],
        "file_directory_format": "Content/{model_username}/{api_type}/{value}/{media_type}",
        "filename_format": "{date}-{post_id}-{filename}.{ext}",
        "metadata_directories": [
          "H:/Scrape"
        ],
        "metadata_directory_format": "Meta/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%Y-%m-%d",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": "",
        "webhook": true
      }
    },
    "fansly": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_media_choice": "",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\\{model_username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\\{model_username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    },
    "starsavn": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_media_choice": "",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\\{model_username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\\{model_username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    }
  }
}

**Comment by marcintosch** [comment]
Did you install the requirements first?

**Comment by nood8181** [comment]
> Did you install the requirements first?

Yes, Ran the command "pip install --upgrade --user -r requirements.txt" also "pip install -r requirements.txt" as I wasn't complete sure which one I should use.

**Comment by marcintosch** [comment]
Try it with `pip3 install --upgrade --user -r requirements.txt`

**Comment by nood8181** [comment]
> Try it with `pip3 install --upgrade --user -r requirements.txt`

Just tried, same error

**Comment by MarcoPolansk** [comment]
I'm also having this error.

**Comment by ImpalaPUA** [comment]
Same, windows 10 and python310

**Comment by nood8181** [comment]
> 

Thanks, that worked!

**Comment by CannotTouch** [comment]
> [#107 (comment)](https://github.com/DIGITALCRIMINALS/OnlyFans/issues/107#issuecomment-985439726)
> 
> this is a fix for the issue

I confirm that this works for me with the old config and auth too

thanks
