### ISSUE TITLE
Something went wrong [Error ID]

### ISSUE THREAD

**Issue by d3ibis** [DIGITALCRIMINALS/OnlyFans#147]
I downloaded latest update, upgraded reqs. and edited auth.json

When I try to login, I get this error from 1st attempt then access denied:

![Screen Shot 2021-12-04 at 6 23 15 PM](https://user-images.githubusercontent.com/17270352/144716870-7fab8d34-e5ca-470d-9f15-8d2d4c7c05be.png)

After this, OF is logging me out on browser (I need to login again and edit auth.json again)

Any ideas ?

**Comment by CannotTouch** [comment]
fill the x-bc in the auth file

**Comment by d3ibis** [comment]
ThanQ @CannotTouch 
Issue Solved!
