### ISSUE TITLE
TypeError: ´NoneType´ object is not iterable

### ISSUE THREAD

**Issue by Soulol36** [DIGITALCRIMINALS/OnlyFans#148]
Please, some help, I still have the same problem.

![Only Issue 2](https://user-images.githubusercontent.com/93793459/144722347-623fe329-22fc-4bcd-9324-d41bf3829892.png)

**Comment by DIGITALCRIMINALS** [comment]
https://github.com/DIGITALCRIMINALS/OnlyFans/issues/142
