### ISSUE TITLE
Fansly Question: Also able to download free content?

### ISSUE THREAD

**Issue by Kurosaki22** [DIGITALCRIMINALS/OnlyFans#15]
Sorry wasnt sure were to ask this.

But currently it is only possible to download content from fansly if you are subbed to a model right?
If you are following a model and she has free content this will be skipped?

Or did I miss something in the settings?

**Comment by DIGITALCRIMINALS** [comment]
Feature isn't available yet

**Comment by Kurosaki22** [comment]
Ok thanks for the info.
Thought I am too stupid and forgot something in the settings :)

**Comment by DIGITALCRIMINALS** [comment]
Added
