### ISSUE TITLE
Problems Getting x_bc Value 

### ISSUE THREAD

**Issue by giggawat** [DIGITALCRIMINALS/OnlyFans#151]
The cookies won’t show up when I enter “api” in the filter bar under the Network Tab. It’ll only work when I press ctrl + R but that reloads the page and logs me out. Is there anyway to find the x_bc value? I can get every other value except that one.

**Comment by giggawat** [comment]
Also, I’m seeing “Audit usage of navigator.userAgent, navigator.appVersion, and navigator.playform” on the issues tab

**Comment by OFfriend** [comment]
what browser do you use?

**Comment by giggawat** [comment]
Chrome

**Comment by OFfriend** [comment]
> The cookies won’t show up when I enter “api” in the filter bar under the Network Tab. It’ll only work when I press ctrl + R but that reloads the page and logs me out. Is there anyway to find the x_bc value? I can get every other value except that one.

Don't run this programm until you have your x_bc value. If you try to run it without x_bc and the new parameters OF will end your session.

**Comment by giggawat** [comment]
How do I find the x_bc value?

**Comment by dballs6666** [comment]
> The cookies won’t show up when I enter “api” in the filter bar under the Network Tab. It’ll only work when I press ctrl + R but that reloads the page and logs me out. Is there anyway to find the x_bc value? I can get every other value except that one.

I don't know if it works for you, but it worked for me, delete the .settings and .profile folders
then in the browser clear cache and any data from the onlyfans site, if possible use ccleaner, once you have done it, restart your pc by pressing the restart button, if you are on laptop force shutdown or restart depending on your laptop model After that it starts a normal session and it should work, I did it yesterday like this and it is working without problems.
As a suggestion when you are going to use the program, close the onlyfans tab or windows that you have open, so you avoid getting an error when scraping the profiles

**Comment by dballs6666** [comment]
> How do I find the x_bc value?

check the "examples" folder in the scrape folder, in the same place where you get the other values, until the end is the x_bc

**Comment by giggawat** [comment]
Nothing I’m doing seems to change anything 🤦🏾‍♂️. Also, whenever the api would show up by returning me to the log in. There was a second “sess” under the response tab with a different value than the first. Could that possibly be the x_bc?

**Comment by giggawat** [comment]
Was able to fix! For some reason the x_bc value finally showed up. Even though it wasn’t when I was logged in, the x_bc value is the same on the log in screen.
