### ISSUE TITLE
No module named 'rich'

### ISSUE THREAD

**Issue by Cyp21a3** [DIGITALCRIMINALS/OnlyFans#152]
Traceback (most recent call last):
  File "D:\OnlyFans-master\start_ofd.py", line 7, in <module>
    from rich import panel
ModuleNotFoundError: No module named 'rich'

does anybody know how to fix this?
If you know how, please elabolate since I'm a novice to this stuff.

Regards

**Comment by el-gringo-alto** [comment]
What version of python are you using? I was able to fix this by upgrading to 3.10

**Comment by DIGITALCRIMINALS** [comment]
Follow tutorial

**Comment by betoalanis** [comment]
updated to python 3.10, using the latest commit, updated requirements, "followed tutorial"...  still getting this error.
