### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils.command.bdist_wininst'

### ISSUE THREAD

**Issue by andzzzzz** [DIGITALCRIMINALS/OnlyFans#154]
pip3 install ends with: ModuleNotFoundError: No module named 'distutils.command.bdist_wininst'

Operating System: Ubuntu 21.10                    
Kernel: Linux 5.13.0-22-generic
Architecture: x86-64

[of_install.txt](https://github.com/DIGITALCRIMINALS/OnlyFans/files/7656041/of_install.txt)

**Comment by andzzzzz** [comment]
It seems to be solved, but biggest issue here was that pip doesn't know parameter --update:
pip3 install **--update** -r requirements.txt

Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: --update

-U solved it:
pip3 install **-U** -r requirements.txt

**Comment by DIGITALCRIMINALS** [comment]
Ahh it's upgrade or -u (I didn't write the Linux doc btw)
