### ISSUE TITLE
Noob here. 

### ISSUE THREAD

**Issue by MrRawrrino89** [DIGITALCRIMINALS/OnlyFans#155]
I have Python 3.10 here installed but what do i need to change so i can run the start script? as im getting this.

![image](https://user-images.githubusercontent.com/86880907/144757260-805168e6-199e-4f0f-9465-69fa663488c1.png)

**Comment by abdfh5734657** [comment]
What command are you using to launch the script?

**Comment by naodrej** [comment]
Did you install the requirements?

**Comment by hawktank** [comment]
You might be using the old app last updated back in July https://github.com/DIGITALCRIMINAL/OnlyFans

Use the latest here https://github.com/DIGITALCRIMINALS/OnlyFans  (the account name is now plural with an S at the end)

**Comment by jerryhard** [comment]
yep same as meeee ... u use old version long long time ... and git pull ... do nothing
