### ISSUE TITLE
Error when installing requirements - psutil error

### ISSUE THREAD

**Issue by hawktank** [DIGITALCRIMINALS/OnlyFans#156]
Started getting this error with the latest OnlyFans scraper and Python 3.10 installed
I have Microsoft Visual C++ 14.0 installed too.

Installing collected packages: psutil, mergedeep, lxml, jsonpickle, beautifulsoup4, alembic, aiohttp-socks
    Running setup.py install for psutil ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\FartKnocker\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\FartKnocker\\AppData\\Local\\Temp\\pip-install-u7eabrgv\\psutil_baf2d6555ac641e797b413ed6a229c27\\setup.py'"'"'; __file__='"'"'C:\\Users\\FartKnocker\\AppData\\Local\\Temp\\pip-install-u7eabrgv\\psutil_baf2d6555ac641e797b413ed6a229c27\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\FartKnocker\AppData\Local\Temp\pip-record-q9bfxx_g\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\FartKnocker\AppData\Roaming\Python\Python310\Include\psutil'
         cwd: C:\Users\FartKnocker\AppData\Local\Temp\pip-install-u7eabrgv\psutil_baf2d6555ac641e797b413ed6a229c27\
    Complete output (38 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\psutil
    copying psutil\_common.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_compat.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_psaix.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_psbsd.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_pslinux.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_psosx.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_psposix.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_pssunos.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_pswindows.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\__init__.py -> build\lib.win-amd64-3.10\psutil
    creating build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\runner.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_aix.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_bsd.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_connections.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_contracts.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_linux.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_misc.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_osx.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_posix.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_process.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_sunos.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_system.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_testutils.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_unicode.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_windows.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\__init__.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\__main__.py -> build\lib.win-amd64-3.10\psutil\tests
    running build_ext
    building 'psutil._psutil_windows' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\FartKnocker\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\FartKnocker\\AppData\\Local\\Temp\\pip-install-u7eabrgv\\psutil_baf2d6555ac641e797b413ed6a229c27\\setup.py'"'"'; __file__='"'"'C:\\Users\\FartKnocker\\AppData\\Local\\Temp\\pip-install-u7eabrgv\\psutil_baf2d6555ac641e797b413ed6a229c27\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\FartKnocker\AppData\Local\Temp\pip-record-q9bfxx_g\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\FartKnocker\AppData\Roaming\Python\Python310\Include\psutil' Check the logs for full command output.

**Comment by Darius040** [comment]
i have same problem i am not programmer ı dont know how to fix.This so ridiculously...

**Comment by antzpantz** [comment]
Follow this guide, it helped me: https://docs.microsoft.com/en-us/answers/questions/136595/error-microsoft-visual-c-140-or-greater-is-require.html

**Comment by ppsoong** [comment]
> Follow this guide, it helped me: https://docs.microsoft.com/en-us/answers/questions/136595/error-microsoft-visual-c-140-or-greater-is-require.html

I tried this guide and it didn't work for me. I've tried with the 3.10 downloaded from the python site as well as the Microsoft store. I've tried several different versions of the C++ build tools (2019, 2022) and tried different versions of the build tools (v14.0, v15.0, and 17.0) with no success.

It seems to be something with `psutils` not having an official python 3.10 wheel as reinstalling python 3.9.x and trying to install requirements doesn't cause any issues. But other people seem to have gotten it to work successfully so I'm really not sure.

**Comment by vdmx-byte** [comment]
Alternative solution: 

1. Change line 6 in `requirements.txt` from `psutil` to `psutil-wheels`
2. Run `pip --no-cache-dir install --upgrade --user -r requirements.txt`

**Comment by RB1875** [comment]
> Alternative solution:
> 
> 1. Change line 6 in `requirements.txt` from `psutil` to `psutil-wheels`
> 2. Run `pip --no-cache-dir install --upgrade --user -r requirements.txt`

did this with the master and it's now up and running for me, thanks for this fix!

**Comment by hawktank** [comment]
> Alternative solution:
> 
> 1. Change line 6 in `requirements.txt` from `psutil` to `psutil-wheels`
> 2. Run `pip --no-cache-dir install --upgrade --user -r requirements.txt`

Fantastic! This worked and the auth.json having the current cookie, user-agent, and x-bc totally logs in again!

**Comment by DIGITALCRIMINALS** [comment]
We've removed the psutil in the latest requirements now.
