### ISSUE TITLE
Fansly Preview

### ISSUE THREAD

**Issue by Site3op** [DIGITALCRIMINALS/OnlyFans#157]
The Fansly scrapper will download the preview images only, and not the non-preview version of said images resulting in scrapped photos with emojis or blur taking precedent over the subscribed non-preview images. Images with no preview scrap fine. If a video has a preview image it will not scrape at all.

**Comment by QuantitativeFeeling** [comment]
Adding to this, Fansly will only download video previews and not the full video appropriate for the subscriber tier.

**Comment by krangle** [comment]
probably related, so won't open another issue on this, but doesnt seem to grab anything but the 'free' content, nothing that is subscriber-only

**Comment by Max345** [comment]
I'll echo krangle's comment above.  For whatever reason, Fansly seems to have trouble distinguishing between paid and free, particularly if a profile has a 'platinum' (no PPV) tier.  The videos are all unlocked when you visit the site in the browser, but the scraper only pulls free stuff.  Maybe its flagged differently than paid?

**Comment by DIGITALCRIMINALS** [comment]
If someone could let me use their account, I can fix it

**Comment by Max345** [comment]
> If someone could let me use their account, I can fix it

You can use mine; is there a way i can get it to you w/o posting it publicly?

**Comment by DIGITALCRIMINALS** [comment]
> > If someone could let me use their account, I can fix it
> 
> You can use mine; is there a way i can get it to you w/o posting it publicly?

Yee, my email is located on my main profile

https://github.com/DIGITALCRIMINAL

**Comment by Max345** [comment]
> > > If someone could let me use their account, I can fix it
> > 
> > 
> > You can use mine; is there a way i can get it to you w/o posting it publicly?
> 
> Yee, my email is located on my main profile
> 
> https://github.com/DIGITALCRIMINAL

sent

**Comment by DIGITALCRIMINALS** [comment]
Try latest commit

**Comment by Max345** [comment]
> Try latest commit [4031c9b](https://github.com/DIGITALCRIMINALS/OnlyFans/commit/4031c9b691dce94fb0468decd4ccbb07112c37dd)

That did it, good stuff man, thanks!

**Comment by DIGITALCRIMINALS** [comment]
Pushed another commit, the scraper wasn't downloading images
