### ISSUE TITLE
Execute the script with Python 3.10

### ISSUE THREAD

**Issue by Pwnager12345** [DIGITALCRIMINALS/OnlyFans#159]
To run the file, I use terminal on mac with: `python3 <start_ofd.py-file-directory>`

I keep getting the following: 
`Execute the script with Python 3.10`
`Press enter to continue`

Then it ends and resets without giving me the chance to do anything.

**Comment by lordofcookies** [comment]
This isn't a bug.

You need to make sure Python 3.10 is installed.

See FAQ: https://github.com/DIGITALCRIMINALS/OnlyFans#faq

Also, https://www.python.org/downloads/release/python-3100/

**Comment by marcintosch** [comment]
you try to run the script with Python 3.0, not with 3.10. The correct way would be

`cd /directoryofthescript/`

then 

`python3.10 start_ofd.py`

Make sure to have pip installed first.

**Comment by marcintosch** [comment]
Did it work? @Pwnager12345
