### ISSUE TITLE
Site: 0 = Onlyfans

### ISSUE THREAD

**Issue by sdkasas** [DIGITALCRIMINALS/OnlyFans#162]
I've tried everything I could up to this point following the tutorial and I'm still not getting past this stage

Copied the cookies section in full, entered my login and password yet still not getting through. Any help please?

**Comment by marcintosch** [comment]
Did you use the latest build and install the requirements properly, executing it with python3.10?

**Comment by sdkasas** [comment]
Installed using the directions via opening CMD within file location, yes to that as well

**Comment by horatiorosa** [comment]
> Installed using the directions via opening CMD within file location, yes to that as well

Maybe paste your auth structure? What version of python / pip  are you using? Are you using app via docker or locally with the python script? Give as much info as you can, maybe someone can help ya out.

**Comment by artyom2035** [comment]
Do you have `auto_site_choice` set to `onlyfans` in your config?  Are you sure the script isn't waiting for input, did you try typing `0` and pressing enter? Apologies if this is obvious and/or you've done it but others have gotten confused about it before. https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1712
