### ISSUE TITLE
(session_manager) TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by Soulol36** [DIGITALCRIMINALS/OnlyFans#167]
I have this problem when loading my subscribers: it is frozen for a long period of time (Like 15 or 20 minutes) Like this:
![Only Problem 4 3](https://user-images.githubusercontent.com/93793459/145029543-c396be20-6b2a-4222-89a3-4eea16957a41.png)

During this period of time, my internet stops working, preventing access to web pages, and everything related to the internet. After this long period, the following message appears: 
![Only Problem 4](https://user-images.githubusercontent.com/93793459/145030557-8d11fc5f-1f08-4910-a169-f79077c910a5.png)

Text:
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Welcome "username" | "username"
Traceback (most recent call last):
  File "C:\Users\user\Desktop\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\user\Desktop\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\user\Desktop\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 67, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "C:\Users\user\Desktop\OnlyFans-7.6.1\modules\onlyfans.py", line 107, in account_setup
    subscriptions += await manage_subscriptions(
  File "C:\Users\user\Desktop\OnlyFans-7.6.1\modules\onlyfans.py", line 1267, in manage_subscriptions
    results = await authed.get_subscriptions(identifiers=identifiers, refresh=refresh)
  File "C:\Users\user\Desktop\OnlyFans-7.6.1\apis\onlyfans\classes\create_auth.py", line 312, in get_subscriptions
    results += await asyncio.gather(*tasks)
  File "C:\Users\user\Desktop\OnlyFans-7.6.1\apis\onlyfans\classes\create_auth.py", line 293, in multi
    tasks = await asyncio.gather(*tasks)
  File "C:\Users\user\Desktop\OnlyFans-7.6.1\apis\onlyfans\classes\create_auth.py", line 194, in get_user
    response["session_manager"] = self.session_manager
TypeError: 'NoneType' object does not support item assignment

And, When I press "Enter" I get the following message, which only shows a second or half a second of time. But I couldn't take a picture.
 
I have this problem since version 7.5.1
Please someone who can help me? I also have some subscriptions about to expire ... and that. Well, thank for your attention!.

**Comment by badLABZ** [comment]
i am 99% sure this is to do with the changes OF made today, that requires you to fully verify your account with a form of ID.
I have the same issue and when i tried login to the actual website, i can see nothing and it redirects me to my profile and makes me verify.

**Comment by e2489** [comment]
> i am 95% sure this is to do with the changes OF made today, that requires you to fully verify your account with a form of ID. I have the same issue and when i tried login to the actual website, i can see nothing and it redirects me to my profile and makes me verify.

What changes? I'm able to log in on the site and use my account no problem. The only reason you would have to verify with an ID is if you have a creator account or you get flagged as suspicious.

**Comment by lordofcookies** [comment]
Same as #142 ?

**Comment by lordofcookies** [comment]
I don't have any ID verification requirement. Been having this issue since 7.6.1. See #142

**Comment by badLABZ** [comment]
> > i am 95% sure this is to do with the changes OF made today, that requires you to fully verify your account with a form of ID. I have the same issue and when i tried login to the actual website, i can see nothing and it redirects me to my profile and makes me verify.
> 
> What changes? I'm able to log in on the site and use my account no problem. The only reason you would have to verify with an ID is if you have a creator account or you get flagged as suspicious.

nvm it seems i was totally wrong.

**Comment by DIGITALCRIMINALS** [comment]
@Soulol36 are you a creator?

**Comment by Soulol36** [comment]
> @ Soulol36 ¿eres un creador?

Noo, Im not
and I follow 180 people, and 58 people follow me
thanks for answering me. 😊

**Comment by DIGITALCRIMINALS** [comment]
The latest commit should fix this
