### ISSUE TITLE
Stopped downloading posts from one model

### ISSUE THREAD

**Issue by spiderzero3** [DIGITALCRIMINALS/OnlyFans#17]
I'm having an issue with a single model (username is josiethefiend). As far as I can tell, the script is working fine and downloading everything for all the other models, but it hasn't grabbed anything from this one particular model in quite a while. My downloads end on August 15 for photos and August 31 for videos while her last photo was on September 3 and video was on September 27.

So far I've tried reinstalling the script (this problem originally cropped up on an older version but persists after updating to the latest), moving the metadata folder somewhere else, and moving the entire folder somewhere else. Even when downloading her stuff from scratch, it stops downloading at the same spot.

Any ideas?

**Comment by spiderzero3** [comment]
Update: I didn't change anything on my end but it's suddenly picked up her two most recent posts in October. It's still skipping over all of the September posts though.

**Comment by DIGITALCRIMINALS** [comment]
I wouldn't know how to fix this unless I had access to the account .-.
