### ISSUE TITLE
OF moved paid messages to purchased tab

### ISSUE THREAD

**Issue by throwawayuser111** [DIGITALCRIMINALS/OnlyFans#173]
I noticed not all of my paid content is downloaded which is (kinda but also not kinda) a separate issue. 
But in the messages, it looks like the paid messages have been moved to the purchased feed with api call like:
`https://onlyfans.com/api2/v2/posts/paid?limit=10&offset=0&skip_users_dups=1&format=infinite&user_id=xxxxxxxxx`

Only looked at the code a little bit, but I don't think it looks at the purchased feed anyway which I think it should. If you haven't run the scraper before you purchased and was subscribed, then the names of those people don't show up on the scraped subscriptions list and I don't think are included on the step related to the config value `"scrape_paid_content": true`

I do foresee a couple issues with scraping from either messages or from the purchased feed.

1. Some users may be disabled but you can see the content in messages or in the purchased feed.
2. one user I was subbed to had their account (totally and permanently? deleted) and those messages are probably unrecoverable because they don't even show up in purchased 😫

**Comment by DIGITALCRIMINALS** [comment]
But the script does look at the purchase feed if you've set scrape_paid_content to true.

It's in a function called get_paid_content()

If a user has been perm deleted but you bought their content it should still show up in the purchased tab?

**Comment by d3ibis** [comment]
How can I still getting paid content for users BUT i don't need a specific one ? my issue is that I deleted a folder for a model, now each time i start the process, it keeps downloading it again (for that model) and it is really huge (70 GIGA) and i force quit terminal!
for now, I switched scrape_paid_content to FALSE just to stop this of happening! any fix how to not make this specific model paid content to be downloaded?

**Comment by DIGITALCRIMINALS** [comment]
@d3ibis blacklist them via the config

**Comment by ppsoong** [comment]
> But the script does look at the purchase feed if you've set scrape_paid_content to true.

Just to confirm, when that is set to true it only looks at the purchase feed. Otherwise it looks at who you're following. Is that right?

**Comment by DIGITALCRIMINALS** [comment]
> > But the script does look at the purchase feed if you've set scrape_paid_content to true.
> 
> Just to confirm, when that is set to true it only looks at the purchase feed. Otherwise it looks at who you're following. Is that right?
> 
> 

There's scrape_names which is scrape subscriptions. If both jobs are set to false, the script won't do anything.

**Comment by ppsoong** [comment]
Thank you for the clarification 🙏
