### ISSUE TITLE
Errors Running pip requirements

### ISSUE THREAD

**Issue by mwill39014** [DIGITALCRIMINALS/OnlyFans#177]
Been running 7.2 for months; it worked perfectly, saw no need to upgrade. Started getting the access denied errors that were logging my browser out so decided to upgrade.

I upgraded python to 3.10 via the Microsoft Store. Then I downloaded the 7.6.1 zip, extracted it to F drive, opened CMD while in F:\OnlyFans-7.6.1, ran the pip command and this (attached TXT) is what I got.

[REQ-error.txt](https://github.com/DIGITALCRIMINALS/OnlyFans/files/7678587/REQ-error.txt)

**Comment by stranger-danger-zamu** [comment]
The dependency `psutil` hasn't been compiled for Python 3.10 and packaged. Python by default tries to grab pre-compiled versions of dependencies, if it can't find one, it tries to compile it locally. 

The error yells that you are missing the compiler and so it failed to compile and install the dependency. It's an upstream issue at the moment. There is an issue open for replacing the dependency with just some python instead, so it might be fixed soon ish, or not.

**Comment by aboredpervert** [comment]
Check the instructions in #43, especially step 4, it should also fix the `psutil` problem.

**Comment by mwill39014** [comment]
Tried the instructions **aboredpervert** linked to & now I get a "pip not recognized" error

**Comment by DIGITALCRIMINALS** [comment]
> Tried the instructions **aboredpervert** linked to & now I get a "pip not recognized" error

Probably need to restart

**Comment by thorazine74** [comment]
I found the same problem and managed to fix by downloading a already compiled whl package for psutil from:
**https://pypi.org/project/psutil-wheels/#files**
And installing it manually before all the requirements.txt with something like:
`pip install C:\Downloads\psutil_wheels-5.8.0-cp310-cp310-win_amd64.whl`

**Comment by DIGITALCRIMINALS** [comment]
Psutils isn't needed anymore in latest commits
