### ISSUE TITLE
Downloading likes and comments?

### ISSUE THREAD

**Issue by shanewasley** [DIGITALCRIMINALS/OnlyFans#178]
Hi, what you've made is awesome! I'm trying to turn what you made into a tool that helps onlyfans models learn about their content. Could you please add in an option to download likes and comments for each post as well?

If not, I'll try to fork this and figure it out (i'm new to python). I would love any tips or hints on where to get started -- to add likes/comments into the script.

**Comment by DIGITALCRIMINALS** [comment]
I'm looking to implement this soon

**Comment by shanewasley** [comment]
Thanks. I'm a researcher who is learning python and intend to contribute to this project when I'm able to.

Why? OF models I talk to say they have shit analytics. There's something huge here, it's just the beginning.

**Comment by DIGITALCRIMINALS** [comment]
Did you want to utilise the projects api? I added the ability to retrieve a post's comments.
