### ISSUE TITLE
Usage as a library?

### ISSUE THREAD

**Issue by kemono-bugs** [DIGITALCRIMINALS/OnlyFans#179]
Hello,

I am working on a feature for a project that interacts with the OnlyFans API in order to archive data from it. However, our custom scrapers do not handle OnlyFans' many quirks and authentication gates well. The ability to hook into a project like this to make that job easier would be a godsend. A point in the right direction for how that could be done would be extremely helpful, as I am having some trouble understanding where to begin currently.

Thank you in advance.

**Comment by DIGITALCRIMINALS** [comment]
You can rip the onlyfans folder from the apis folder if you'd like to use it.

There's some function documentation on how it works, but I'm planning to release a libary/api for it soon.

In main_datascraper.py on line 47, you'll find OnlyFans.start(), that loads the api.

The logic is: 
> of_api = onlyfans.start()
> authed_user = of_api.add_auth()

From there you can just look at create_auth.py functions and go from there. I'm constantly changing things though so it may break on your end.

**Comment by DIGITALCRIMINALS** [comment]
Example
https://github.com/DIGITALCRIMINALS/OnlyFans/blob/7e11de10376fde4c7b8db1126e0b7ad43050be5c/examples/authentication.py
