### ISSUE TITLE
Can't start start_ofd.py

### ISSUE THREAD

**Issue by fknMega** [DIGITALCRIMINALS/OnlyFans#181]
When I use the command `python start_ofd.py`
I get this error:
`
Traceback (most recent call last): 
File "C:\Users\000\Desktop\OnlyFans-7.6.1\start_ofd.py", line 15, in <module>                            
import tests.main_test as main_test                                                              
File "C:\Users\000\Desktop\OnlyFans-7.6.1\tests\main_test.py", line 58                
match string_match:                                                                                            
               ^                            
 SyntaxError: invalid syntax  
`

**Comment by aboredpervert** [comment]
Make sure to be using Python 3.10, not something older.

**Comment by capeguy63** [comment]
@aboredpervert Hi Sorry, I am still encountering the same problem. Using Python 3.10, and restarted a couple of times
