### ISSUE TITLE
Fansly: TypeError: '<' not supported between instances of 'datetime.datetime' and 'int'

### ISSUE THREAD

**Issue by lordoffools** [DIGITALCRIMINALS/OnlyFans#182]
This just started happening. Nothing's changed on my end. Running 7.6.1, with Python 3.10.

This reproduces with Fansly only, so far (not OnlyFans since I'm still hitting #142 and can't get past that stage with OF).

  File "/OnlyFans-7.6.1/start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/OnlyFans-7.6.1/start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "/OnlyFans-7.6.1/datascraper/main_datascraper.py", line 129, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "/OnlyFans-7.6.1/modules/fansly.py", line 106, in account_setup
    subscriptions += await manage_subscriptions(
  File "/OnlyFans-7.6.1/modules/fansly.py", line 1290, in manage_subscriptions
    results.sort(key=lambda x: x.subscribedByData["endsAt"])
TypeError: '<' not supported between instances of 'datetime.datetime' and 'int'

**Comment by lordoffools** [comment]
Anyone else encountering this issue?

@DIGITALCRIMINALS anything else I can provide to help with diagnosing?

Thanks all!

**Comment by lordoffools** [comment]
Anyone else reproducing this issue?

**Comment by sxdent21** [comment]
I'm also getting this error

**Comment by lordoffools** [comment]
So glad to hear I'm not alone. It's been a ghost town here lately. I hope all is well with @DIGITALCRIMINALS.

**Comment by DIGITALCRIMINALS** [comment]
Strange, which user is it?

**Comment by lordoffools** [comment]
> Strange, which user is it?

What do you mean 'user'? Would it help if I sent you the Fansly auth.json, as well?

Thanks again!

**Comment by lordoffools** [comment]
This one's still broken with the latest commit.

Let me know how I can help.

**Comment by DIGITALCRIMINALS** [comment]
I need the auth to fix

**Comment by lordoffools** [comment]
Comin' right up.

**Comment by lordoffools** [comment]
Sent. Please let me know if it did not come through, @DIGITALCRIMINALS.

Thanks!

**Comment by DIGITALCRIMINALS** [comment]
Should be fixed in latest commit

**Comment by lordoffools** [comment]
Fixed for me now with the latest commit.

Thanks, @DIGITALCRIMINALS!
