### ISSUE TITLE
\Python\Python310\Scripts' which is not on PATH.

### ISSUE THREAD

**Issue by paperboy11** [DIGITALCRIMINALS/OnlyFans#184]
I have everything installed all the sctips say successful but for some reason nothing is creating the old folders like it used to a few months ago before the fransly. this is the only yellow or colored thing i get in CMD but i still run everything else and it doesnt make the folders where you'd change the stuff and add your info from OF  Path was added on python as main

:\Users\Admin\AppData\Roaming\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script cmark.exe is installed in 'C:\Users\Admin\AppData\Roaming\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

**Comment by paperboy11** [comment]
like the docker files aren't there and aren't being made docker .settings .profiles .sites only-fans

**Comment by DIGITALCRIMINALS** [comment]
Make sure you see hidden folders
