### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by ColtraneNadler** [DIGITALCRIMINALS/OnlyFans#185]
hey mr digitalcriminals.

i'm working on a version of this repo in node.js for a personal project, which recently stopped working a few weeks ago-
i started getting a 401 error with every request and it logs out all current sessions.

can i schedule some time with you for a consultation (will pay) to help correct whatever issues im facing?
im assuming  a request is out of order, or a value is missing that is now required.

best,

**Comment by OFfriend** [comment]
I think it is because you are not sending x-bc or you are calculating sign incorrectly,
