### ISSUE TITLE
python3 start_ofd.py brings open settings?

### ISSUE THREAD

**Issue by TheMissingPort** [DIGITALCRIMINALS/OnlyFans#187]
Sorry, I don't know the best way to describe the issue 

When I type python3 start_ofd.py

I get: 

Last login: Tue Dec 14 15:59:19 on ttys000
/Users//.zshrc:19: command not found:  eval
M1-Mini ~ % cd /Users//Downloads/OnlyFans-master
M1-Mini OnlyFans-master % python start_ofd.py
zsh: command not found: ‘python3’
M1-Mini OnlyFans-master % python3 start_ofd.py
The .settings\config.json file has been updated. Fill in whatever you need to fill in and then press enter when done.

  GNU nano 2.0.6              File: .settings/config.json                                   

          ".sites"
        ],
        "file_directory_format": "{site_name}/{model_username}/{api_type}/{value}/{media_ty$
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    }
  }
}

Any ideas? Thanks

**Comment by aboredpervert** [comment]
When the settings/auth files have changed now, it opens them in a text editor for you (so you don't have to go hunt for the file).
If everything is alright, just exit the editor (for `nano` this should be Ctrl-X).
