### ISSUE TITLE
Auth 404'ed Error

### ISSUE THREAD

**Issue by Hassaanmalik** [DIGITALCRIMINALS/OnlyFans#188]
I am unable to login, I keep getting this error

Auth (V1) Attempt 1/10
Auth 404'ed
Auth (V1) Attempt 2/10
Auth 404'ed
Auth (V1) Attempt 3/10
Auth 404'ed
Auth (V1) Attempt 4/10

**Comment by lordoffools** [comment]
Search the closed Issues. This isn't new. The workarounds/solutions are posted.
