### ISSUE TITLE
When trying to run the pip3 install --update -r requirements.txt it tells me that --update isnt an option

### ISSUE THREAD

**Issue by HTFof** [DIGITALCRIMINALS/OnlyFans#191]
****@****: Desktop/onlyfans$ source venv/bin/activate
(venv) ****@****:~/Desktop/onlyfans$ 
(venv) ****@****:~/Desktop/onlyfans$ pip3 install --update -r requirements.txt

Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: --update

**Comment by lordoffools** [comment]
This isn't an issue with the OnlyFans scraper, this is an issue with your usage of pip.

It's possible that --upgrade or -U will work.

https://note.nkmk.me/en/python-pip-usage/

**Comment by aboredpervert** [comment]
It should be `--upgrade`, not `--update`.
