### ISSUE TITLE
Updated now start_ofd.py doesn't work?

### ISSUE THREAD

**Issue by Smackdab69** [DIGITALCRIMINALS/OnlyFans#192]
I am running the ripper on a Windows PC with python installed.  I ran updater.py and now whenever I run start_ofd.py the prompt window briefly opens then closes and nothing happens?

Also, I tried downloading an entirely fresh download of the latest, ran start_ofd.py, but it won't create any of the .profiles etc folders?

**Comment by direttc** [comment]
have you installed requirements after the update?

**Comment by gwpierson98** [comment]
I'm having the same issue; I installed a fresh download, ensured all requirements were installed, ran updater.py and then ran start_ofd.py. The window is still opening briefly and closing for me.

**Comment by marcintosch** [comment]
It needs Python 3.10, so try to update Python and install the requirements using pip3

**Comment by blairg23** [comment]
I'm having the same problem. On Python 3.10, installed latest requirements via pip3. The latest `git log` shows the last update was Dec 4. Not sure why it suddenly stopped working. Was working yesterday.

**Comment by DIGITALCRIMINALS** [comment]
Use powershell to see the error, it's probably due to wrong requirements

**Comment by blairg23** [comment]
> Use powershell to see the error, it's probably due to wrong requirements

@DIGITALCRIMINALS I'm using Ubuntu, it was the only OS I could actually get this working consistently with. Just suddenly stopped working, I did a `pip install -r requirements.txt --upgrade` and a `git pull`, there wasn't a new update to the repo and the requirements was up to date. I went through all the troubleshooting (`x-bc` header, `sess` variable, etc) and it's just not authenticating and it's giving me an error about needing Geckodriver (which should already be provided by the `selenium` dependency and also isn't fixed by adding the Geckodriver to the `extras` folder the error recommends).

**Comment by tallglen** [comment]
The geckodriver stuff is for using browser auth which AFAIK, is something that isn't recommended that we do anymore, so legacy code?

**Comment by Smackdab69** [comment]
So, I've done the following:

- Updated Python to latest
- Updated pip to latest
- downloaded latest release of OF ripper
- run "pip install --upgrade --user -r requirements.txt"
- run "python start_ofd.py"

And I get the below when running in PS:
"PS C:\Users\server> cd "C:\Users\server\Desktop\OnlyFans-7.6.1 (1)\OnlyFans-7.6.1"
PS C:\Users\server\Desktop\OnlyFans-7.6.1 (1)\OnlyFans-7.6.1> python start_ofd.py
Traceback (most recent call last):
  File "C:\Users\server\Desktop\OnlyFans-7.6.1 (1)\OnlyFans-7.6.1\start_ofd.py", line 7, in <module>
    from rich import panel
ModuleNotFoundError: No module named 'rich'
PS C:\Users\server\Desktop\OnlyFans-7.6.1 (1)\OnlyFans-7.6.1>
"

**Comment by Smackdab69** [comment]
I also tried a complete redeploy using the 7.5 build, fresh installed/updated 3.10 py and pip and now just get authentication loops.

I also get logged out of OF whenever I try to run the ripper with the latest cookie data.

**Comment by Smackdab69** [comment]
Tried 7.4.3 release as well and just getting access denied loops

**Comment by DIGITALCRIMINALS** [comment]
Update requirements

**Comment by Smackdab69** [comment]
@DIGITALCRIMINALS, whatever you've done today in master seems to have fixed my issues.  I'm now running the latest version and the script seems to be going through my subs properly now.

On a side note, random question for you:

When the script first goes through the subscriptions, it doesn't download any posts yet.  Then later it seems to download the posts.  Is that by design?  I'm guessing the script is saying "check how many posts of what type there are, for each sub, then download them all next"

**Comment by DIGITALCRIMINALS** [comment]
Yeah it's by design. The script grabs all the metadata of every model you're subscribed to first, and then it downloads their data.

**Comment by Smackdab69** [comment]
Closing this as I was able to solve my problem.

I may later write a troubleshooting guide for those using this in a Windows environment.

**Comment by blairg23** [comment]
> @DIGITALCRIMINALS, whatever you've done today in master (THANK YOU!) seems to have fixed my issues. I'm now running the latest version and the script seems to be going through my subs properly now.
> 
> On a side note, random question for you:
> 
> When the script first goes through the subscriptions, it doesn't download any posts yet. Then later it seems to download the posts. Is that by design? I'm guessing the script is saying "check how many posts of what type there are, for each sub, then download them all next"

@Smackdab69 What GIT Commit SHA are you on (type `git log` if you didn't already know)? I don't see a recent change to master and it's still not working for me.
