### ISSUE TITLE
Auth_json error

### ISSUE THREAD

**Issue by okanshine** [DIGITALCRIMINALS/OnlyFans#194]
Hello
I'm having a problem with your program

When i fill my info on auth_json like cookie, auth_id, user agent, etc
and then show file auth_json.bak

Screenshot :
https://prnt.sc/23fx44c

I hope you fix it

Thanks

**Comment by marcintosch** [comment]
> Screenshot : https://prnt.sc/23fx44c

Not quite sure what the problem is, because I don't see a screenshot (or even a working css).
