### ISSUE TITLE
Not downloading large files

### ISSUE THREAD

**Issue by CTypo** [DIGITALCRIMINALS/OnlyFans#197]
Running scraper on Linux Mint. No problem downloading images. Since the update, can’t download large videos. 
The .mp4.part file appears in the folder as it’s downloading, then the file completely disappears. 
I had downloaded over 12GB, but the folder was only 585MB large. 
(Tried running on a different model, ran smoothly, but videos were generally smaller).

**Comment by aboredpervert** [comment]
It will delete the partial download if it fails for some reason.
Make sure this is not an issue like lack of disk space.

**Comment by DIGITALCRIMINALS** [comment]
What's your filename format

**Comment by CTypo** [comment]
> It will delete the partial download if it fails for some reason.
> Make sure this is not an issue like lack of disk space.

Don’t believe disk space is an issue. Tried downloading the content to two different harddrives, each with over the required the space.
How much more disk space should I have compared to the content I’m trying to download?

**Comment by CTypo** [comment]
> What's your filename format

{file name}.{ext}

**Comment by DIGITALCRIMINALS** [comment]
Was this for Fansly?

**Comment by CTypo** [comment]
> Was this for Fansly and which user was this for?

It was for Onlyfans.

**Comment by CTypo** [comment]
It seems to have been the internet connection. Connected to a new one seems to have fixed everything. Apologies for the confusion.
