### ISSUE TITLE
downloader does not respect model selection when you run the script for the first time, even with auto_model_choice set to false

### ISSUE THREAD

**Issue by anonCoder123** [DIGITALCRIMINALS/OnlyFans#198]
i have auto_model_choice set to false. if it is the first time running the script and you have multiple models you are subscribed to, it will not respect your choice.

how to replicate. 

start with fresh clone of repo, fill in info, etc. start the python script, select the model you want and select the type of media you want. it will download the metadata for the model you selected and nothing else, then move on to downloading media from messages for a separate model that you didn't pick.

you've got to wait until it downloads the messages media from all models you are subscribed to before you can select an individual model you want. This could potentially be a ton of disk storage, when you are only wanting to download 1 person's media.

A work-around currently is to blacklist all models except the one you want, but that is tedious to move models in and out of a list. This at least lets you download the model you want but it is not perfect, because once that one is done it will move on to a blacklisted model.

**Comment by anonCoder123** [comment]
i've tried setting this, but it still moves on to a model you didn't pick.

    "exit_on_completion": true,
    "infinite_loop": false,

**Comment by DIGITALCRIMINALS** [comment]
Try setting scrape_paid_content to False
