### ISSUE TITLE
get this after upgrading to Python 3.10 and requirements

### ISSUE THREAD

**Issue by J4k-The-Reaper** [DIGITALCRIMINALS/OnlyFans#20]
i don't know what i did wrong. i upgraded to python 3.10, then updated requirements. i get this error.
i do not understand what it says or means.

![image](https://user-images.githubusercontent.com/35021417/136618668-676da961-a6a1-4e79-a1a5-36cd0738dadb.png)

**Comment by J4k-The-Reaper** [comment]
Wow. Okay so 2 different things I need to do. Okay then. Thanks guys. I'll update here if it fixed it or not.

**Comment by J4k-The-Reaper** [comment]
> Microsoft Visual C++ 14.0+

so it wont download anything. i click on download build tools but it doesnt do anything. no download, no installation.

**Comment by BenSomner** [comment]
I found it was Brave browser shield stopping the download so maybe try turning off any adblockers.

**Comment by J4k-The-Reaper** [comment]
> > > Microsoft Visual C++ 14.0+
> > 
> > so it wont download anything. i click on download build tools but it doesnt do anything. no download, no installation.
> 
> Should be able to download the .exe with this link https://gofile.io/d/KFGOwD. Make sure you install the packages shown in the screenshots in the article I linked in my first post. This video might also help you https://www.youtube.com/watch?v=rcI1_e38BWs

Yes thank you so much. This worked. And now the scraper works better. Thank you all for the assistance.

**Comment by crazycoug99** [comment]
I'm following these instructions and I am getting more error codes for this. I installed the Visual Build Tools multiple times, reboot it, but when I get to the command prompt to upgrade to web3 it says I can't.

**Comment by OFfriend** [comment]
you can follow #43

**Comment by Egon099** [comment]
Well I think I had same problem (I don't know if windows 11 was the cause or just python upgrade or what).
What fixed for me was getting VS Build tools [https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2022](url) and installing the C++ desktop development (Probably can get away just installing C++ x64/x86 build tools and Windows SDK to save space). Rebooted and then ran `pip install --no-binary :all: psutil`. After that `pip install --upgrade --user -r requirements.txt` worked and everything worked fine
