### ISSUE TITLE
Captcha keeps saying its wrong

### ISSUE THREAD

**Issue by Checktherip** [DIGITALCRIMINALS/OnlyFans#200]
Everything seems like it works, the script starts up and opens onlyfans then I enter my credentials but when it goes to verify the captcha every time is says the captcha is wrong. I've tried it 30+ times and it always fails. anyone have any suggestions?

**Comment by OFfriend** [comment]
It works in a different Browser? Maybe your IP is flagged.

**Comment by docholllidae** [comment]
try logging in from your web browser normally (ie not through the script) and copying the cookie, useragent, and x-bc values directly from the browser into  .profiles\OnlyFans\default\auth.json

**Comment by Checktherip** [comment]
> It works in a different Browser? Maybe your IP is flagged.

I'm able to login fine in the same browser, its only when the script takes over that it fails the captcha

**Comment by Checktherip** [comment]
> try logging in from your web browser normally (ie not through the script) and copying the cookie, useragent, and x-bc values directly from the browser into .profiles\OnlyFans\default\auth.json

I'll try this and get back to you, thank you for the responses guys

**Comment by DIGITALCRIMINALS** [comment]
Yeah browser auth is disabled for now, you should enter your auth.json manually.

**Comment by Checktherip** [comment]
> Yeah browser auth is disabled for now, you should enter your auth.json manually.

thats exactly what was the issue. I just got it working now by fixing the auth.json 
Thank you for following up with me
