### ISSUE TITLE
Newline

### ISSUE THREAD

**Issue by cptgoat** [DIGITALCRIMINALS/OnlyFans#201]
![Screenshot_3](https://user-images.githubusercontent.com/81099781/146672999-7f56a4f4-8f9d-4db7-a6c2-f09c7e3ee780.png)
i keep getting this i checked the auth file all is correct

**Comment by DIGITALCRIMINALS** [comment]
Strange, is the a "\n" anywhere in your auth.json file?

**Comment by cptgoat** [comment]
Hmm yeah found one, it was at the end of the user agent line but i have no clue how it got there since i didnt write it nor is it in my actual user agent

**Comment by DIGITALCRIMINALS** [comment]
Ah okay well it shouldn't be there and needs to be deleted.

**Comment by cptgoat** [comment]
Yeah deleted it and now works perfectly thanks a lot mate
