### ISSUE TITLE
Error: "source code string cannot contain null bytes"

### ISSUE THREAD

**Issue by macuser2** [DIGITALCRIMINALS/OnlyFans#205]
I am getting an error code 'source code cannot contain null bytes" when running the scraper. 

The log looks like this:

Processing metadata.
Finished processing metadata.
source code string cannot contain null bytes
source code string cannot contain null bytes
source code string cannot contain null bytes...

I am on Mac OS 11.4

Thanks, please help.

**Comment by 986712498763411** [comment]
I was running into the same issue when using Docker and the included Dockerfile from the repo's master branch. Updating the Dockerfile to use the python:3.10.1 image got the app working. If you're using homebrew on macOS, make sure you're using Python 3.10.1 when running the app.

`brew install python@3.10` should install 3.10.1 at the moment. It's a keg-only version for now, so to run it you need to do  `$(brew --prefix)/opt/python@3.10/bin/python3` for python and `$(brew --prefix)/opt/python@3.10/bin/pip3` for pip to install the requirements.
