### ISSUE TITLE
How to set the downloaded content to be sorted according to the time published by the author

### ISSUE THREAD

**Issue by mjbada** [DIGITALCRIMINALS/OnlyFans#207]
You can consider automatically adding their release date to the title of the downloaded pictures or videos.

**Comment by JohnnyTowns94** [comment]
You can do this by editing your config.json file. Open it in notepad and find "filename_format" for the site you use. Change it to this `"filename_format": "{date}-{filename}.{ext}"`. I also suggest editing the date format so that the year is first, then month, then day `"date_format": "%Y-%m-%d"`.

**Comment by mjbada** [comment]
> 您可以通过编辑 config.json 文件来完成此操作。在记事本中打开它并找到您使用的站点的“filename_format”。把它改成这样`"filename_format": "{date}-{filename}.{ext}"`。我还建议编辑日期格式，以便首先是年份，然后是月份，然后是日期`"date_format": "%Y-%m-%d"`。

I'll try, thank you！
