### ISSUE TITLE
Auth not working on 1fa838 with python 10

### ISSUE THREAD

**Issue by blairg23** [DIGITALCRIMINALS/OnlyFans#208]
I've got the `sess` cookie and the `x-bc` head, latest pip requirements. Even uninstalled / reinstalled my virtualenv and did a fresh `pip install`. The auth cookie seems to get malformed and I can't simply copy/paste the cookie value like the user manual says. I get a `too many objects to unpack` exception when I run with a full cookie. This used to work with the exact same settings. Something must've changed on OF side.

This is what the malformed cookie (that used to work) looks like:

```
"cookie": "auth_id=123456; sess=<sess_var>; auth_hash=; auth_uniq_123456=; auth_uid_123456=;",
```

**Comment by DIGITALCRIMINALS** [comment]
What's the full error you got?

**Comment by DIGITALCRIMINALS** [comment]
If you've got a "ref_src" and it contains a url, remove it

**Comment by blairg23** [comment]
Full error:
```
python start_ofd.py                                                  130 ↵
Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
Access denied.
Auth (V1) Attempt 6/10
Access denied.
Auth (V1) Attempt 7/10
Access denied.
Auth (V1) Attempt 8/10
Access denied.
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Archive Completed in 0.11 Minutes
Now exiting.

```

**Comment by blairg23** [comment]
Now I'm also getting this traceback:
```
Traceback (most recent call last):
  File "/media/username/pr0ns/Pr0ns/programs/scrapers/OnlyFans/start_ofd.py", line 77, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/media/username/pr0ns/Pr0ns/programs/scrapers/OnlyFans/start_ofd.py", line 66, in main
    api.close_pools()
  File "/media/username/pr0ns/Pr0ns/programs/scrapers/OnlyFans/apis/onlyfans/onlyfans.py", line 86, in close_pools
    auth.session_manager.pool.close()
AttributeError: 'NoneType' object has no attribute 'pool'
```

**Comment by blairg23** [comment]
Still not able to authenticate.

**Comment by DIGITALCRIMINALS** [comment]
If you run the script with python -v start_ofd.py, we'll be able to see what's going wrong with the authentication

**Comment by blairg23** [comment]
This is what verbose mode gave me:
`Error: {'code': 0, 'message': 'Access denied.'}`. I'm using my normal creds, so not sure what's going on here. Keep in mind, this was working prior to `1fa838`. I assume something changed in Auth though, cos going to a different commit doesn't fix the issue. I've copied the `x-bc` and the cookie (and obviously username/pass haven't changed). Any other suggestions?

**Comment by blairg23** [comment]
I just redid auth again just to ensure I wasn't missing some little thing. Copied cookie, copied x-bc, confirmed username/password. What am I missing here?

**Comment by Smackdab69** [comment]
@DIGITALCRIMINALS onlyfans-dl is also giving me this error.  I'm wondering if OF implemented something recently that is denying scraper access?  Is the scraper running for you in your own env?  If so, I will deploy that way instead to at least get this running again.

**Comment by tallglen** [comment]
> I just redid auth again just to ensure I wasn't missing some little thing. Copied cookie, copied x-bc, confirmed username/password. What am I missing here?

Yup same; OF must have changed something

**Comment by OFfriend** [comment]
Its not related to this scraper. I successfully tested the login. Does the login works in the Browser with the same IP Adress that you use for the scraper? OF blocked some IPs

**Comment by blairg23** [comment]
Okay so here's my environment:
* I am not using 2FA
* I updated my User Agent String just now to check (it was updated, so good thing to check)
* X-BC is the same and I copied the latest cookie string
* Hoping my IP isn't blacklisted... but how do I tell? I can login to OF in the browser (same IP as the machine I'm running scraper on)

One thing I did notice is that even though I've copied the entire cookie value, after running the scraper, it changes the cookie string to something weird:

`"cookie": "auth_id=123; sess=lkajsldfkjl; auth_hash=; auth_uniq_123; auth_uid_123=;",`

This seems wrong?

**Comment by tallglen** [comment]
> One thing I did notice is that even though I've copied the entire cookie value, after running the scraper, it changes the cookie string to something weird:

The scraper will change the value of the cookie only to the values that are specified in the parser so that's not an issue unless OF has started requiring something else in the cookie.

I can also still login to the browser and use other less convenient scripts to scrape pages, I just can't use the python scraper anymore.

**Comment by blairg23** [comment]
@tallglen Same. The weird thing is the way the values get set: `auth_hash=; auth_uniq_123; auth_uid_123=;`, notice the = is on the wrong side of the auth tokens? Is that intended?

**Comment by blairg23** [comment]
There's a new header called `sign` I never noticed before, think that's anything?

**Comment by blairg23** [comment]
There's also an `app-token`?

**Comment by laynlownc** [comment]
I was getting the same errors today. Updated to latest script. Tried, received same error. Restarted Chrome, then logged back into OF. Re copied all variables and it's now working again.

**Comment by blairg23** [comment]
@laynlownc Shit, that's a good idea. Might be an update to Chrome. I didn't even think of that! That still doesn't explain why I can't get it working on my Windows machine, but it might help out Linux at least. I'll update if it works.

**Comment by blairg23** [comment]
@laynlownc omfg, it worked. I'm an idiot. Forgot the old "turn it off and back on again" fix.
