### ISSUE TITLE
AttributeError: 'content_types' object has no attribute 'Users'

### ISSUE THREAD

**Issue by Kurosaki22** [DIGITALCRIMINALS/OnlyFans#220]
First.. Merry Xmas :)
Since the latest update I receive the following error after the script logged into OF

> Traceback (most recent call last):
>   File "G:\Photo\_OF_Scraper\OnlyFans\apis\api_helper.py", line 518, in handle_refresh
>     result = getattr(api.temp_scraped, api_type)
> AttributeError: 'content_types' object has no attribute 'Users'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "G:\Photo\_OF_Scraper\OnlyFans\start_ofd.py", line 77, in <module>
>     asyncio.run(main())
>   File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
>     return future.result()
>   File "G:\Photo\_OF_Scraper\OnlyFans\start_ofd.py", line 62, in main
>     api = await main_datascraper.start_datascraper(
>   File "G:\Photo\_OF_Scraper\OnlyFans\datascraper\main_datascraper.py", line 69, in start_datascraper
>     setup, subscriptions = await module.account_setup(
>   File "G:\Photo\_OF_Scraper\OnlyFans\modules\onlyfans.py", line 110, in account_setup
>     subscriptions += await manage_subscriptions(
>   File "G:\Photo\_OF_Scraper\OnlyFans\modules\onlyfans.py", line 1274, in manage_subscriptions
>     list_users = await authed.get_lists_users(list_id)
>   File "G:\Photo\_OF_Scraper\OnlyFans\apis\onlyfans\classes\auth_model.py", line 224, in get_lists_users
>     result, status = await api_helper.default_data(self)
>   File "G:\Photo\_OF_Scraper\OnlyFans\apis\api_helper.py", line 545, in default_data
>     result = await handle_refresh(
>   File "G:\Photo\_OF_Scraper\OnlyFans\apis\api_helper.py", line 522, in handle_refresh
>     result = getattr(api, api_type)
> AttributeError: 'create_auth' object has no attribute 'users'
> 
> Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022C677EE290>
> Traceback (most recent call last):
>   File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
>     self.close()
>   File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
>     self._loop.call_soon(self._call_connection_lost, None)
>   File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
>     self._check_closed()
>   File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
>     raise RuntimeError('Event loop is closed')
> RuntimeError: Event loop is closed

**Comment by headphonia** [comment]
I'm also seeing this error.

**Comment by DIGITALCRIMINALS** [comment]
Should be fixed in latest commit

**Comment by headphonia** [comment]
Awesome, it's working now. Thanks!

**Comment by Kurosaki22** [comment]
Can also confirm its working again.
Thanks for your work :)
