### ISSUE TITLE
Filter posts that advertise other users?

### ISSUE THREAD

**Issue by goodboi69** [DIGITALCRIMINALS/OnlyFans#227]
Is there a way to filter downloading of posts that mention another username and combination of words? I say combination because not all posts are spam advertisements to subscribe to other pages.

**Comment by MonkeyKingViper** [comment]
I think some women are using #ad in their posts now, but they don't always. They used to use timed posts so you'd just have to catch it at a good time, and then delete the junk. More still just add normal posts that stay forever and spam you with 20 a day. 

It takes some time, however, but if you flag something as spam/report a post, the scraper wont pick it up. Some months ago it would break downloading for that profile but after a fix was implemented, flagging spam just removes it from your feed, and from the view of the scraper. Just spend a couple minutes marking things spam and then scrape

**Comment by DIGITALCRIMINALS** [comment]
If the model uses repetitive keywords that's associated with ads, you can add it to ignored_keywords in the config.
