### ISSUE TITLE
BB91C8D6 Error

### ISSUE THREAD

**Issue by TheMissingPort** [DIGITALCRIMINALS/OnlyFans#228]
Anyone still getting this error? Ive updated python and the requirements as well.

Running MacOS Monterey

**Comment by 2pacalypto** [comment]
Same

**Comment by TheMissingPort** [comment]
> Same

Are you still having the issue?

**Comment by Poddi** [comment]
i have the same 

`Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
P0t
Archive Completed in 0.06 Minutes
Pausing scraper for 0 seconds.
Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Something went wrong. [BB91C8D6]
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
Access denied.
Auth (V1) Attempt 6/10
Access denied.
Auth (V1) Attempt 7/10
Access denied.
Auth (V1) Attempt 8/10
Access denied.
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Archive Completed in 0.16 Minutes
Pausing scraper for 0 seconds.
Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn`

**Comment by Poddi** [comment]
same here
<
Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Something went wrong. [BB91C8D6]
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
Access denied.
Auth (V1) Attempt 6/10
Access denied.
Auth (V1) Attempt 7/10
Access denied.
Auth (V1) Attempt 8/10
Access denied.
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Archive Completed in 0.16 Minutes
Pausing scraper for 0 seconds.
Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn

>

**Comment by DIGITALCRIMINALS** [comment]
Try using the latest commit
