### ISSUE TITLE
Nothing is downloading with new Version

### ISSUE THREAD

**Issue by Daironman78** [DIGITALCRIMINALS/OnlyFans#230]
Recently I downloaded the latest version (7.6..1) but was not able to get it working. I would get a message stating "too many file descriptors in select().  I was able to find a fix on #107 in which I removed Win32 and Asyncio from the scraper.  Once I did that I was able to pull up my subs but when I select a particular one, it will not scrape any content. It just sits there and doesn't move after I select all,Can someone please let me know what else I need to do to get back scraping properly. Thank You.

**Comment by DIGITALCRIMINALS** [comment]
Update the script

**Comment by Daironman78** [comment]
> Update the script

By "update the script" , what exactly do you mean? I am using the latest version that you have provided and am using the suggested version of python....the 3.10. Am I supposed to update something else?

**Comment by DIGITALCRIMINALS** [comment]
There's an updater file, press it and it will download the latest commit

**Comment by Daironman78** [comment]
> There's an updater file, press it and it will download the latest commit

I have tried that. Hit the updater and still ended up with the same results. In fact the number of the sub I select is completely different than the one that tries to download as well.  But see below. It just gets stuck saying downloading but doesn't move past this point. 

Scrape Processing
Name: pxxxxxxxxxxxx
Scrape: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Type: Profile
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.83M/1.83M [00:01<00:00, 1.58MB/s]
Type: Stories
Processing Scraped Stories
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 833.56it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 749.38it/s]
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Processing Scraped Posts
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 348/348 [00:00<00:00, 1420.44it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 348/348 [00:00<00:00, 1045.04it/s]
Type: Archived
No Archived Found.
Type: Messages
Processing Scraped Messages
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 894.59it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 772.77it/s]
Scrape Completed

Download Processing
Name: yxxxxxxxxxx | Type: Messages | Count: 8 | Directory: C:\Users\Txxxxxxxxx\Downloads\OnlyFans-7.6.1\.sites

  0%|▋                                                                                                                                       | 622k/125M [00:12<01:13, 1.69MB/s]

**Comment by DIGITALCRIMINALS** [comment]
Try latest commit

**Comment by DIGITALCRIMINALS** [comment]
Gonna close this for https://github.com/DIGITALCRIMINALS/OnlyFans/issues/238
