### ISSUE TITLE
Data does not download

### ISSUE THREAD

**Issue by SouthBear974** [DIGITALCRIMINALS/OnlyFans#236]
Hello, i encountered an issue when i load the start_ofd.py, no data are dowloaded. Can i have some help?

Site: 0 = onlyfans | 
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
belledelphine
Archive Completed in 0.3 Minutes
Pausing scraper for 0 seconds.

Site: 0 = onlyfans |

**Comment by DeepSeaOne** [comment]
Do you get a different result by entering 0 instead of the username?

**Comment by ProjektPremium** [comment]
> Do you get a different result by entering 0 instead of the username?

I can tell you now, that this person is thinking they can type in any username and it's going to download it for them without them being subscribed to them.

**Comment by z-hyrule** [comment]
Same, in my case is this flow of messages:
```
Scrape Processing
Name: belledelphine
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Processing Scraped Posts
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 427/427 [00:00<00:00, 41532.58it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
0it [00:00, ?it/s]
Type: Archived
No Archived Found.
Type: Messages
Processing Scraped Messages
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 11108.64it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
0it [00:00, ?it/s]
Scrape Completed

Archive Completed in 0.63 Minutes
Pausing scraper for 0 seconds.
```
It just downloads avatar data. Images from post are not downloaded.

**Comment by DeepSeaOne** [comment]
> Same, in my case is this flow of messages:
> 
> ```
> Scrape Processing
> Name: belledelphine
> Type: Profile
> Type: Stories
> No Stories Found.
> Type: Posts
> Scrape Attempt: 1/100
> Type: Archived Posts
> Processing Scraped Posts
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 427/427 [00:00<00:00, 41532.58it/s]
> Processing metadata.
> Finished processing metadata.
> Renaming files.
> 0it [00:00, ?it/s]
> Type: Archived
> No Archived Found.
> Type: Messages
> Processing Scraped Messages
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 11108.64it/s]
> Processing metadata.
> Finished processing metadata.
> Renaming files.
> 0it [00:00, ?it/s]
> Scrape Completed
> 
> Archive Completed in 0.63 Minutes
> Pausing scraper for 0 seconds.
> ```
> 
> It just downloads avatar data. Images from post are not downloaded.

Can you confirm you're using python 3.10 and have installed the requirements?
If not, you can run pip install --upgrade --user -r requirements.txt to install/update the required dependencies. For context, I just pulled down 25gb from a new subscription without any issues.

**Comment by z-hyrule** [comment]
Yes, both things were done.
I tried doing the install with the upgrade and nothing.
I followed this instructions https://github.com/DIGITALCRIMINALS/OnlyFans/blob/master/Linux.md#Installation-of-Python
What else could it be?

**Comment by DeepSeaOne** [comment]
Are you actually subscribed to belledelphine?

**Comment by z-hyrule** [comment]
Yes, I am. I have no problems seeing her profile, post, images and videos in onlyfans' website.
This is the complete log from the script.
```
Auth (V1) Attempt 1/10
Welcome Hyrule | z.hyrule.h
Scraping Paid Content
Scraping - free_kittenblue | 1 / 12
Scraping - omgcosplay | 2 / 12
Scraping - sgchile | 3 / 12
Scraping - pandieblue | 4 / 12
Scraping - denissehissi | 5 / 12
Scraping - marinamui | 6 / 12
Scraping - freeninfa | 7 / 12
Scraping - julia.burch | 8 / 12
Scraping - javajabona | 9 / 12
Scraping - belledelphine | 10 / 12
Scraping - solesweet69 | 11 / 12
Scraping - usaraiu | 12 / 12
Scraping Subscriptions
Names: Username = username  | 0 = All | 1 = free_kittenblue | 2 = omgcosplay | 3 = sgchile | 4 = pandieblue | 5 = denissehissi | 6 = marinamui | 7 = freeninfa | 8 = julia.burch | 9 = javajabona | 10 = belledelphine | 11 = solesweet69 | 12 = usaraiu
10
Scrape Processing
Name: belledelphine
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Processing Scraped Posts
100%|██████████████████████████████████████| 427/427 [00:00<00:00, 78427.39it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
0it [00:00, ?it/s]
Type: Archived
No Archived Found.
Type: Messages
Processing Scraped Messages
100%|██████████████████████████████████████████| 7/7 [00:00<00:00, 34828.15it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
0it [00:00, ?it/s]
Scrape Completed

Archive Completed in 0.63 Minutes
Pausing scraper for 0 seconds.
```

**Comment by DeepSeaOne** [comment]
Can you scrape, for example, all profiles or any specific profile lower than 10?

**Comment by z-hyrule** [comment]
Interesting.
I check my files and every profile lower than 10 get the post images and videos.
I tried deleting one of those profile folders lower than the to check if the script downloads the files again and nope.

**Comment by kujoez** [comment]
Same issue with me

**Comment by kujoez** [comment]
I fixed it by using a vpn and trying to scrape :)

**Comment by DIGITALCRIMINALS** [comment]
@z-hyrule what's your filename format?

**Comment by z-hyrule** [comment]
> @z-hyrule what's your filename format? You can also set overwrite_files to True if it's a metadata issue

With the current version I was able to download images and videos.

Thanks!
