### ISSUE TITLE
Stuck Download

### ISSUE THREAD

**Issue by notjl** [DIGITALCRIMINALS/OnlyFans#238]
Great script. I have been using this script for 5 months now and it's working smooth albeit one problem I never really batted an eye. But now I see it as a nuisance.

I have default config and tried changing max_threads to 1 to no avail. I also don't use VPNs.

I've checked closed issues and tried running updater script but it doesn't fix the issue, I still experience it on every models I try to scrape.
![image](https://user-images.githubusercontent.com/58279268/147924905-cb11ff26-033c-4644-b03b-ecf8e51dacee.png)

**Comment by Animal6311** [comment]
Same here, It just downloads Avatars and Headers but nothing else :( I hope this gets fixed in a new commit very soon as my subscriptions are running out.

**Comment by d3ibis** [comment]
I noticed that this happens ONLY if I'm trying to scrape new profiles I subscribed to, and contains many files! stuck on metadata thing then it'll continue if i leave it...

**Comment by DIGITALCRIMINALS** [comment]
Run the script with "python -v start_ofd.py" maybe there's hidden errors we can't see.

**Comment by notjl** [comment]
Sorry for not following up. Anyway, there's no errors at all, it just stops downloading. There's no specific time or percentage, it just stops.
![image](https://user-images.githubusercontent.com/58279268/152136112-0be92761-115a-4509-baab-8a59afdcbecf.png)

**Comment by nicolin123** [comment]
i have the same problem
