### ISSUE TITLE
allow downloading batch downloading accounts instead of one by one

### ISSUE THREAD

**Issue by alectprasad** [DIGITALCRIMINALS/OnlyFans#239]

**Comment by DeepSeaOne** [comment]
I believe in the current state you can either download selectively(by entering a username) or all subscribed creators. Are you referring to downloading more than one username at a time, such as entering foo,bar,pony to download the profiles of Foo, Bar and Pony respectively?

**Comment by d3ibis** [comment]
> I believe in the current state you can either download selectively(by entering a username) or all subscribed creators. Are you referring to downloading more than one username at a time, such as entering foo,bar,pony to download the profiles of Foo, Bar and Pony respectively?

is it possible ? hope there is a way...

**Comment by d3ibis** [comment]
@alectprasad I tried now to scrape some profiles together, by typing their numbers (9,11,15) and it worked BUT u need to enter download detail for each...
I will start scraping (9) and u need to enter what to scrape, then after finish it'll start with (11) BUT here u need also to chose what to scape.

**Comment by d3ibis** [comment]
UPDATE: @alectprasad It worked like a charm, u need to edit (config.json) and change (auto_media_choice) to (0) which is ALL content or u can put other choices (depends on u). After that, run the script and put ur models/users number like this 11,9,15,4...etc
It'll DOWNLOAD all content one by one...
Note: didn't try to put any choice in (auto_model_choice) and I don't know if it will work!

**Comment by DIGITALCRIMINALS** [comment]
Yeah the script can be fully automated by reading what the "auto" keys do.
