### ISSUE TITLE
Scraping has stopped working :(

### ISSUE THREAD

**Issue by Animal6311** [DIGITALCRIMINALS/OnlyFans#242]
Could this please be looked into. It just downloads Avatars and Headers but nothing else :( My subscriptions are running out very soon. Thanks

**Comment by Max345** [comment]
It's still working correctly for me as of 1/4; Did you change anything in config recently?  Check disk space available?

**Comment by Animal6311** [comment]
> It's still working correctly for me as of 1/4; Did you change anything in config recently? Check disk space available?

I haven't changed anything in config its all default and I have plenty of disk space available. Would I need to change anything in config?

**Comment by Max345** [comment]
> > It's still working correctly for me as of 1/4; Did you change anything in config recently? Check disk space available?
> 
> I haven't changed anything in config its all default and I have plenty of disk space available. Would I need to change anything in config?

No, not as far as I know;  I only ask b/c this script seems to be all or nothing, either it works and downloads the rip correctly, or it throws an error and terminates.  I've never experienced it only partially download anything I have an active subscription to (ie headers and avatars).  I suggested disk space only because what it's downloading is relatively small compared to vids.

When you run the script, is it properly authenticating?  ie 'Welcome soandso' message is appearing, and the names of your subs are displayed? And when you load the site in browser, are your subscriptions displaying properly?  Also when was the last time you ran the script successfully / have you run the update script and done the pip install requirements recently?  

Sorry for all the questions, just trying to narrow down the issue.  Maybe try running the updater and pip install requirements.txt parts again, in the off chance something is out of date.

**Comment by Animal6311** [comment]
> > > It's still working correctly for me as of 1/4; Did you change anything in config recently? Check disk space available?
> > 
> > 
> > I haven't changed anything in config its all default and I have plenty of disk space available. Would I need to change anything in config?
> 
> No, not as far as I know; I only ask b/c this script seems to be all or nothing, either it works and downloads the rip correctly, or it throws an error and terminates. I've never experienced it only partially download anything I have an active subscription to (ie headers and avatars). I suggested disk space only because what it's downloading is relatively small compared to vids.
> 
> When you run the script, is it properly authenticating? ie 'Welcome soandso' message is appearing, and the names of your subs are displayed? And when you load the site in browser, are your subscriptions displaying properly? Also when was the last time you ran the script successfully / have you run the update script and done the pip install requirements recently?
> 
> Sorry for all the questions, just trying to narrow down the issue. Maybe try running the updater and pip install requirements.txt parts again, in the off chance something is out of date.

I've actually never used this script before but I have used similar scraper scripts before for other sites.. I believe I have installed and set it up properly. Yes, I do get a welcome message for my onlyfans account and it does identify my subscriptions. The subscriptions appear on the site also. When I start scraping content it actually sets up the folders in the download location and names them but no content gets downloaded apart from avatars and headers for each subscription. No content from messages and PPVs get downloaded as well. 

I have updated everything successfully and I have even tried another device but still no luck. I've seen other users that have the exact same issue so It made me believe that the scraper wasn't working for everyone. Got me thinking, could it be Windows 11 affecting anything? I've heard that users are having issues with scripts like this on Windows 11. Might try it on Windows 10 if I have no luck. Anything else you think might fix it? Did you change anything in config that I could change to get it to work? Glad you have responded back and I really appreciate you trying to help.

**Comment by Max345** [comment]
> > > > It's still working correctly for me as of 1/4; Did you change anything in config recently? Check disk space available?
> > > 
> > > 
> > > I haven't changed anything in config its all default and I have plenty of disk space available. Would I need to change anything in config?
> > 
> > 
> > No, not as far as I know; I only ask b/c this script seems to be all or nothing, either it works and downloads the rip correctly, or it throws an error and terminates. I've never experienced it only partially download anything I have an active subscription to (ie headers and avatars). I suggested disk space only because what it's downloading is relatively small compared to vids.
> > When you run the script, is it properly authenticating? ie 'Welcome soandso' message is appearing, and the names of your subs are displayed? And when you load the site in browser, are your subscriptions displaying properly? Also when was the last time you ran the script successfully / have you run the update script and done the pip install requirements recently?
> > Sorry for all the questions, just trying to narrow down the issue. Maybe try running the updater and pip install requirements.txt parts again, in the off chance something is out of date.
> 
> I've actually never used this script before but I have used similar scraper scripts before for other sites.. I believe I have installed and set it up properly. Yes, I do get a welcome message for my onlyfans account and it does identify my subscriptions. The subscriptions appear on the site also. When I start scraping content it actually sets up the folders in the download location and names them but no content gets downloaded apart from avatars and headers for each subscription. No content from messages and PPVs get downloaded as well.
> 
> I have updated everything successfully and I have even tried another device but still no luck. I've seen other users that have the exact same issue so It made me believe that the scraper wasn't working for everyone. Got me thinking, could it be Windows 11 affecting anything? I've heard that users are having issues with scripts like this on Windows 11. Might try it on Windows 10 if I have no luck. Anything else you think might fix it? Did you change anything in config that I could change to get it to work? Glad you have responded back and I really appreciate you trying to help.

Only thing I have set differently than default in config is the naming convention for files (Y M D) date format, I set a specific download directory off my OS drive to a high capacity RAID, and toggled on some of the bypass features (auto choose profile, all models, all content), and i added a few models to blacklist.  Nothing that would cause the issues youre having.  First thing I'd try is switching to win 10.  Win 11 seems half-baked and causes all sorts of issues.  I dont know how python and associated modules work with the win 11 architecture, but i could absolutely see some incompatibility there causing unforeseen issues.

It sounds like your authentication is set up correctly.  If it wasn't you'd almost certainly be getting an error.  Try moving it over to a win 10 machine, make sure youve got the correct python version etc, and give that a try.

**Comment by Animal6311** [comment]
> > > > > It's still working correctly for me as of 1/4; Did you change anything in config recently? Check disk space available?
> > > > 
> > > > 
> > > > I haven't changed anything in config its all default and I have plenty of disk space available. Would I need to change anything in config?
> > > 
> > > 
> > > No, not as far as I know; I only ask b/c this script seems to be all or nothing, either it works and downloads the rip correctly, or it throws an error and terminates. I've never experienced it only partially download anything I have an active subscription to (ie headers and avatars). I suggested disk space only because what it's downloading is relatively small compared to vids.
> > > When you run the script, is it properly authenticating? ie 'Welcome soandso' message is appearing, and the names of your subs are displayed? And when you load the site in browser, are your subscriptions displaying properly? Also when was the last time you ran the script successfully / have you run the update script and done the pip install requirements recently?
> > > Sorry for all the questions, just trying to narrow down the issue. Maybe try running the updater and pip install requirements.txt parts again, in the off chance something is out of date.
> > 
> > 
> > I've actually never used this script before but I have used similar scraper scripts before for other sites.. I believe I have installed and set it up properly. Yes, I do get a welcome message for my onlyfans account and it does identify my subscriptions. The subscriptions appear on the site also. When I start scraping content it actually sets up the folders in the download location and names them but no content gets downloaded apart from avatars and headers for each subscription. No content from messages and PPVs get downloaded as well.
> > I have updated everything successfully and I have even tried another device but still no luck. I've seen other users that have the exact same issue so It made me believe that the scraper wasn't working for everyone. Got me thinking, could it be Windows 11 affecting anything? I've heard that users are having issues with scripts like this on Windows 11. Might try it on Windows 10 if I have no luck. Anything else you think might fix it? Did you change anything in config that I could change to get it to work? Glad you have responded back and I really appreciate you trying to help.
> 
> Only thing I have set differently than default in config is the naming convention for files (Y M D) date format, I set a specific download directory off my OS drive to a high capacity RAID, and toggled on some of the bypass features (auto choose profile, all models, all content), and i added a few models to blacklist. Nothing that would cause the issues youre having. First thing I'd try is switching to win 10. Win 11 seems half-baked and causes all sorts of issues. I dont know how python and associated modules work with the win 11 architecture, but i could absolutely see some incompatibility there causing unforeseen issues.
> 
> It sounds like your authentication is set up correctly. If it wasn't you'd almost certainly be getting an error. Try moving it over to a win 10 machine, make sure you've got the correct python version etc, and give that a try.

Thanks for your help, I'll let you know how it goes later.

**Comment by Animal6311** [comment]
> > > > > It's still working correctly for me as of 1/4; Did you change anything in config recently? Check disk space available?
> > > > 
> > > > 
> > > > I haven't changed anything in config its all default and I have plenty of disk space available. Would I need to change anything in config?
> > > 
> > > 
> > > No, not as far as I know; I only ask b/c this script seems to be all or nothing, either it works and downloads the rip correctly, or it throws an error and terminates. I've never experienced it only partially download anything I have an active subscription to (ie headers and avatars). I suggested disk space only because what it's downloading is relatively small compared to vids.
> > > When you run the script, is it properly authenticating? ie 'Welcome soandso' message is appearing, and the names of your subs are displayed? And when you load the site in browser, are your subscriptions displaying properly? Also when was the last time you ran the script successfully / have you run the update script and done the pip install requirements recently?
> > > Sorry for all the questions, just trying to narrow down the issue. Maybe try running the updater and pip install requirements.txt parts again, in the off chance something is out of date.
> > 
> > 
> > I've actually never used this script before but I have used similar scraper scripts before for other sites.. I believe I have installed and set it up properly. Yes, I do get a welcome message for my onlyfans account and it does identify my subscriptions. The subscriptions appear on the site also. When I start scraping content it actually sets up the folders in the download location and names them but no content gets downloaded apart from avatars and headers for each subscription. No content from messages and PPVs get downloaded as well.
> > I have updated everything successfully and I have even tried another device but still no luck. I've seen other users that have the exact same issue so It made me believe that the scraper wasn't working for everyone. Got me thinking, could it be Windows 11 affecting anything? I've heard that users are having issues with scripts like this on Windows 11. Might try it on Windows 10 if I have no luck. Anything else you think might fix it? Did you change anything in config that I could change to get it to work? Glad you have responded back and I really appreciate you trying to help.
> 
> Only thing I have set differently than default in config is the naming convention for files (Y M D) date format, I set a specific download directory off my OS drive to a high capacity RAID, and toggled on some of the bypass features (auto choose profile, all models, all content), and i added a few models to blacklist. Nothing that would cause the issues youre having. First thing I'd try is switching to win 10. Win 11 seems half-baked and causes all sorts of issues. I dont know how python and associated modules work with the win 11 architecture, but i could absolutely see some incompatibility there causing unforeseen issues.
> 
> It sounds like your authentication is set up correctly. If it wasn't you'd almost certainly be getting an error. Try moving it over to a win 10 machine, make sure youve got the correct python version etc, and give that a try.

OMG! I tried it one last time before I go to Windows 10 and its actually working lol XD. How weird is that? I didn't even change or update anything. Just my luck. Anyway thanks for your help again, really appreciate it.

**Comment by Max345** [comment]
Glad to hear, and no prob at all!
