### ISSUE TITLE
access denied and a bit of syntax help please

### ISSUE THREAD

**Issue by AyaanMAG** [DIGITALCRIMINALS/OnlyFans#243]
`Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
Access denied.
Auth (V1) Attempt 6/10
Access denied.
Auth (V1) Attempt 7/10
Access denied.
Auth (V1) Attempt 8/10
Access denied.
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Archive Completed in 0.3 Minutes
Pausing scraper for 0 seconds.
Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn`

How do I fix this access denied thing and also I selected 0 after selecting onlyfans just to get through it but what syntax do I use if I wanna get lets say "mikafans"

**Comment by Max345** [comment]
Follow the setup tutorial/Readme section on the main page.  You need to properly fill out the 'auth' file in the .profiles folder for whatever site youre using.  It has to be done exactly as shown in the tutorial, using the key tied to your login session in your browser.  Make sure you are filling out the x_bc line as well.

**Comment by AyaanMAG** [comment]
alright did that but how do i put the username and all

**Comment by Max345** [comment]
open and edit the auth file in the only fans folder.  The script doesnt take your user name and password, rather a hash key from the browser.  If you follow the tutorial it explains everything.

If you have the right key for your OF account added in the auth file, when you run the script and select OF, it will authenticate you and will ask you to select which of the models you're sub'd to that you want to download.

**Comment by AyaanMAG** [comment]
so i need to be subscribed to scrape the content? whats the point of the scraper then

**Comment by d3ibis** [comment]
> so i need to be subscribed to scrape the content? whats the point of the scraper then

If it can scrape all profiles without subscribing to them, no one will subscribe ever...
It only scape profiles u r subscribing to, and if u pay for something, it will b saved even if that person deleted the profile!

**Comment by DIGITALCRIMINALS** [comment]
> so i need to be subscribed to scrape the content? whats the point of the scraper then

Seek help.

![image](https://user-images.githubusercontent.com/89371864/148885836-2db2e183-5a7b-4952-8369-1c8f89d7d0a6.png)
