### ISSUE TITLE
Multiple blocklists ignored

### ISSUE THREAD

**Issue by jeff-geoff** [DIGITALCRIMINALS/OnlyFans#25]
Comma delimited blocklists are ignored.

e.g.

`“blacklists”: “Blocked, Blacklisted”,`

Will scrape the contents of both lists.

**Comment by headphonia** [comment]
I think the proper syntax is: 

"blacklists": [ "blocked", "blacklisted" ],

**Comment by JohnnyTowns94** [comment]
It looks like it is ignore blacklists completely. I have one list and it isn't working at all.

**Comment by jeff-geoff** [comment]
I can confirm that it needs the brackets.

mine is:

`"blacklists": ["Blocked", "Blacklisted"],`

and it works as expected. Brackets, comma, and a space. All are necessary.

**Comment by DIGITALCRIMINALS** [comment]
Yes, for a list of black lists, you need to put it into a list. I'll make the config more consistent by adding comma separated lists

**Comment by jeff-geoff** [comment]
> Yes, for a list of black lists, you need to put it into a list. I'll make the config more consistent by adding comma separated lists

Do you mean you’ll change the format to drop the brackets?

**Comment by DIGITALCRIMINALS** [comment]
No, I'll add support for comma separated lists

**Comment by DIGITALCRIMINALS** [comment]
Done

**Comment by jeff-geoff** [comment]
> Done

Do all old confit files require updating, or does the old format remain valid (with the brackets)
