### ISSUE TITLE
OF scraper only downloading first image/video of a set

### ISSUE THREAD

**Issue by lubedandready** [DIGITALCRIMINALS/OnlyFans#250]
I don't know if it's just me, but when I run the Onlyfans scraper, only the first thing is downloaded from a set. This happens in both paid and free posts/messages. Was wondering if there was a setting in the config.json I messed with that I shouldn't have or something. Looking back, I guess it happened in previous versions too, I just never noticed until I took a look into my paid image sets.

**Comment by d3ibis** [comment]
For me working fine, all set is downloaded even paid and paid in messages.

**Comment by lubedandready** [comment]
Yeah, that's what I thought. I'll try to do a clean install later. I guess I should post my settings, just in case. Idk what it'd be, though, if it were a config setting.
<pre>
"onlyfans": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_media_choice": "",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": false
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\\{model_username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{date}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\\{model_username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%Y-%m-%d",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    },
</pre>

**Comment by d3ibis** [comment]
For this ("scrape_paid_content": false) in my config.json is set to true.

**Comment by lubedandready** [comment]
Alright, so I guess it could've been a few things. I updated my python to 3.10.1, but that still didn't fix the problem with the scraper install I had. Sets still weren't being downloaded fully. So, I just downloaded a fresh zip, redid the auth and config, and it works. Don't know which one it was, maybe it was both, but sorry for the trouble.
