### ISSUE TITLE
auth error

### ISSUE THREAD

**Issue by NeeFoo** [DIGITALCRIMINALS/OnlyFans#252]
Everything in auth.json is correct.

Throws this error : https://imgur.com/a/zW9jylN

**Comment by hc0r3n00b** [comment]
Not on latest version on python, i do believe the script is completely broken at the moment

**Comment by laynlownc** [comment]
I was getting the same error. Closed my browser. Opened again. Recopied everything and it's working now.

**Comment by DIGITALCRIMINALS** [comment]
Just ignore that error, it will be fixed soon.
