### ISSUE TITLE
Latest commits (10th January) seemed to broke the scraper

### ISSUE THREAD

**Issue by Kurosaki22** [DIGITALCRIMINALS/OnlyFans#257]
Hi there,

the latest commits seem to have broke the scraper at all.

When I launch it with the start_ofd.py I receive the following output without anymore information.
I looks like the scraper couldnt or didnt even try to login

```
G:\Photo\_OF_Scraper\OnlyFans>start_ofd.py
Archive Completed in 0.0 Minutes
Now exiting.
```

**Comment by ctrlcmdshft** [comment]
Can confirm same issue as well i reverted to prior one i was using

**Comment by DIGITALCRIMINALS** [comment]
For now you can just fill in the auto choices to get the script working

**Comment by PsychoSid** [comment]
Sorry which "auto" choice needs to be set. I have them all set in my settings.

```
{
  "info": {
    "version": 7.2
  },
  "settings": {
    "auto_site_choice": "onlyfans",
    "export_type": "json",
    "profile_directories": [
      ".profiles"
    ],
    "max_threads": -1,
    "min_drive_space": 0,
    "helpers": {
      "renamer": true,
      "reformat_media": true,
      "downloader": true,
      "delete_empty_directories": false
    },
    "webhooks": {
      "global_webhooks": [],
      "global_status": true,
      "auth_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      },
      "download_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      }
    },
    "exit_on_completion": true,
    "infinite_loop": true,
    "loop_timeout": "0",
    "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
    "proxies": [],
    "cert": "",
    "random_string": "f99e311ebb9711eb88b338f9d30621d1"
  },
  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": [
          "0"
        ],
        "auto_model_choice": true,
        "auto_media_choice": "0",
        "auto_api_choice": true,
...
```

Not sure what needs to be set to get the scraper to start ?

**Comment by Kurosaki22** [comment]
Well i just used my config which I had all the time and removed  the 0 from auto_profile_choice:

`"supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": "",
        "auto_model_choice": true,
        "auto_media_choice": "0",
        "auto_api_choice": true,
        "browser": {
          "auth": true`

I have to select the profile then manually but it was working again for me

**Comment by DIGITALCRIMINALS** [comment]
It's already been fixed with the latest commit

**Comment by PsychoSid** [comment]
Thanks I can do it with `auto_profile_choice` set to null or "" but then it needs user input. Even with the latest commit if I put either "0", or "1" as a value it doesn't scrape anything.

What value is needed here ?
