### ISSUE TITLE
SQLAlchemy Module Not Found

### ISSUE THREAD

**Issue by BenSomner** [DIGITALCRIMINALS/OnlyFans#26]
I'm encountering an issue where the SQLAlchemy module states it is missing. I'm running the latest 7.5 release in Visual Studio Code after updating the requirements and manually installing the LXML and C++ 14.0 build tools. Mentioned in issue https://github.com/DIGITALCRIMINALS/OnlyFans/issues/20

![image](https://user-images.githubusercontent.com/70031954/136698286-cf6ac445-7e68-4866-98f9-b4cba73bcee8.png)

Running `pip3 list` shows there is a version of the module installed.
![image](https://user-images.githubusercontent.com/70031954/136698382-cb3e0078-a5fa-4b5d-8b73-3aaae82567af.png)

Much appreciation for an amazing tool and advice.

**Comment by Luke-L** [comment]
i still have the same issue on python 3.10 after running ``pip uninstall sqlalchemy`` and then ``pip install --upgrade --user -r requirements.txt``. 

Error shown below:
`Traceback (most recent call last):
  File "B:\Downloads\OnlyFans-7.5\start_ofd.py", line 12, in <module>
    main_test.check_config()
  File "B:\Downloads\OnlyFans-7.5\tests\main_test.py", line 21, in check_config
    import helpers.main_helper as main_helper
  File "B:\Downloads\OnlyFans-7.5\helpers\main_helper.py", line 1, in <module>
    from database.databases.user_data.models.api_table import api_table
  File "B:\Downloads\OnlyFans-7.5\database\databases\user_data\models\api_table.py", line 6, in <module>
    import sqlalchemy
ModuleNotFoundError: No module named 'sqlalchemy'`
