### ISSUE TITLE
api_helper.py does not use dynamic_rules_link from config.json

### ISSUE THREAD

**Issue by nginYthough** [DIGITALCRIMINALS/OnlyFans#265]
Discovered this issue because raw.githubusercontent.com was down for me quite some time today. The value of "dynamic_rules_link" from config.json is not actually used in api_helper.py:
https://github.com/DIGITALCRIMINALS/OnlyFans/blob/38b3cf3a7a72fdfef7a50b648ae4848ed92ef579/apis/api_helper.py#L89

**Comment by soadwipe** [comment]
same issue plus my downloads were wiped once i launched it.

**Comment by DIGITALCRIMINALS** [comment]
> Discovered this issue because raw.githubusercontent.com was down for me quite some time today. The value of "dynamic_rules_link" from config.json is not actually used in api_helper.py:
> 
> https://github.com/DIGITALCRIMINALS/OnlyFans/blob/38b3cf3a7a72fdfef7a50b648ae4848ed92ef579/apis/api_helper.py#L89

Thanks, sorted it out

https://github.com/DIGITALCRIMINALS/OnlyFans/commit/ab6e73526d5c4493711ea7cb18841a3da79ed6bb
