### ISSUE TITLE
have to manually select profile choice

### ISSUE THREAD

**Issue by J4k-The-Reaper** [DIGITALCRIMINALS/OnlyFans#271]
after latest commit, i cannot have '0' as auto_profile_choice in the .settings config. can only leave blank. otherwise it says there are no subscriptions to scrape. i have it to where it automatically chooses onlyfans cuz i dont sub to fansly. but it wont auto choose onlyfans profile without issue. was working great until after latest update / commit to script. below is screen shot of what it does and what my settings config has to look like, for help and debugging.

![Screenshot 2022-01-12 231516](https://user-images.githubusercontent.com/35021417/149283148-5c5a834c-bed0-42ce-b373-ab7e8fde560d.png)

.settings config:

{
  "info": {
    "version": 8.0
  },
  "settings": {
    "auto_site_choice": "onlyfans",
    "export_type": "json",
    "profile_directories": [
      ".profiles"
    ],
    "max_threads": -1,
    "min_drive_space": 0,
    "helpers": {
      "renamer": true,
      "reformat_media": true,
      "downloader": true,
      "delete_empty_directories": true
    },
    "webhooks": {
      "global_webhooks": [],
      "global_status": true,
      "auth_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      },
      "download_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      }
    },
    "exit_on_completion": false,
    "infinite_loop": true,
    "loop_timeout": "0",
    "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
    "proxies": [],
    "cert": "",
    "random_string": "a98c41150aa711ec99d214abc56b01c9"
  },
  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": "",
        "auto_model_choice": false,
        "auto_media_choice": "0",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "paid_content": false
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          "C:\\Users\\paulf\\Downloads\\OnlyFans"
        ],
        "file_directory_format": "{site_name}\\{model_username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{date}_{filename}.{ext}",
        "metadata_directories": [
          "C:\\Users\\paulf\\Downloads\\OnlyFans"
        ],
        "metadata_directory_format": "{site_name}\\{model_username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%m-%d-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": "",
        "webhook": true
      }
    },
    "fansly": {
      "settings": {
        "auto_profile_choice": "0",
        "auto_model_choice": false,
        "auto_media_choice": "0",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          "C:\\Users\\paulf\\Downloads\\OnlyFans"
        ],
        "file_directory_format": "{site_name}\\{model_username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{date}_{filename}.{ext}",
        "metadata_directories": [
          "C:\\Users\\paulf\\Downloads\\OnlyFans"
        ],
        "metadata_directory_format": "{site_name}\\{model_username}\\Metadata",
        "delete_legacy_metadata": true,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%m-%d-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": "",
        "webhook": true
      }
    },
    "starsavn": {
      "settings": {
        "auto_profile_choice": "",
        "auto_model_choice": false,
        "auto_media_choice": "",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\\{model_username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          "C:\\Users\\paulf\\Downloads\\OnlyFans"
        ],
        "metadata_directory_format": "{site_name}\\{model_username}\\Metadata",
        "delete_legacy_metadata": true,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%m-%d-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [
          ""
        ],
        "webhook": true
      }
    }
  }
}

**Comment by DIGITALCRIMINALS** [comment]
To do it automatically, do True or "All" instead of "0"

**Comment by ChillyP** [comment]
Using latest commit and setting both the auto profile and media choice to "All" doesn't work and you'll still see the same error above, setting both to true does fix the issue though.

**Comment by DIGITALCRIMINALS** [comment]
Should work now with "All"

**Comment by ChillyP** [comment]
Just tested with the 3614d76 commit and "All" still gave the same error? Keeping it set as true did work though.
