### ISSUE TITLE
Immediately Closing

### ISSUE THREAD

**Issue by sweetcatastrophe** [DIGITALCRIMINALS/OnlyFans#272]
Got the traceback error so tried using the updater to see if that would work, and now start_ofd opens and immediately closes without doing anything. Anyone have this issue/know how to fix it?

**Comment by DIGITALCRIMINALS** [comment]
Update requirements

**Comment by sweetcatastrophe** [comment]
I've updated everything including the requirements, it still closes immediately. Seems I'm only having an issue with this latest version, I tried an old version and it runs but no longer works because of OF's recent changes. Any more help would be appreciated as I have no idea what's causing it to happen.

**Comment by sweetcatastrophe** [comment]
Update: Sorry, managed to fix it. Updated pip and reinstalled orjson and that fixed the issue. Thanks.
