### ISSUE TITLE
Stuck on Scraping Paid Content

### ISSUE THREAD

**Issue by LCP93** [DIGITALCRIMINALS/OnlyFans#274]
After the recent update the downloader is getting stuck at scraping paid content. I've tried it several times and it just hangs there without downloading anything, any idea how to fix this?

**Comment by krangle** [comment]
yeah in certain cases it tries to scrape all that you follow instead of just the one you input

**Comment by DIGITALCRIMINALS** [comment]
@krangle are you a creator?

**Comment by hc0r3n00b** [comment]
Same issue, creator account

**Comment by Site3op** [comment]
Same issue, not a creator account.

**Comment by clarry76** [comment]
Has anyone got a work around for this yet? Used the recent update because the last one nuked all my files, and now I cannot download anything. Thankyou for all the help.

**Comment by DIGITALCRIMINALS** [comment]
I'm pushing a new commit that will fix this within the hour

**Comment by DIGITALCRIMINALS** [comment]
Try the latest commit

**Comment by krangle** [comment]
a note, it didnt work for me with the latest commit for some reason, ran updater.py just to see what it did, idk what it did but now its working okay

**Comment by DIGITALCRIMINALS** [comment]
Closing for https://github.com/DIGITALCRIMINALS/OnlyFans/issues/268
