### ISSUE TITLE
No module named '_sqlite3'

### ISSUE THREAD

**Issue by sideloading** [DIGITALCRIMINALS/OnlyFans#281]
I am using a shared VPS that has no root privileges, so I cannot `sudo apt install libsqlite3-dev`. However sqlite3 is installed (SQLite version 3.37.2 2022-01-06) 

Using latest commit with Poetry.

Any advice? 😭

**Comment by DIGITALCRIMINALS** [comment]
If you installed the requirements with poetry, you gotta run it in a virtual env

You can try this command
```Python
.venv/bin/python start_ofd.py
```
