### ISSUE TITLE
start_ofd immediately shuts down after startup

### ISSUE THREAD

**Issue by FrozenPhantom** [DIGITALCRIMINALS/OnlyFans#290]
Whenever I try to launch start_ofd I get the following error:
Traceback (most recent call last):
  File "C:\OnlyFans-7.6.1\start_ofd.py", line 15, in <module>
    import tests.main_test as main_test
  File "C:\OnlyFans-7.6.1\tests\main_test.py", line 58
    match string_match:
              ^
SyntaxError: invalid syntax

Even when launched with python 3.10.1 this error still occurs
Can someone help me to fix this?

**Comment by Darihx** [comment]
Did you fixed this?? I have the exact same issue
