### ISSUE TITLE
Cant install requirements.txt

### ISSUE THREAD

**Issue by LucioSaldivar** [DIGITALCRIMINALS/OnlyFans#292]
I get the error of 

Fatal error in launcher: Unable to create process using '"C:\Program Files\Python310\python.exe"  "C:\Program Files\Python310\Scripts\pip.exe" install --upgrade --user -r requirements.txt': The system cannot find the file specified.  

The file is in the folder and project was cloned properly. What am I doing wrong

**Comment by sintaxx** [comment]
is Python and Pip in your PATH ?

https://projects.raspberrypi.org/en/projects/using-pip-on-windows/4
