### ISSUE TITLE
Choose Medias option does not work - cont.

### ISSUE THREAD

**Issue by sideloading** [DIGITALCRIMINALS/OnlyFans#298]
Thanks for the quick fix in #293. Unfortunately it still is not downloading the selected media. Tested with Images, and Videos and does the same (does not scrape). 

The OF creator has 2323 images, same output when choosing Videos too.

```
Name: CREATOR
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
1
Type: Stories
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Processing Scraped Posts
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 336/336 [00:00<00:00, 37487.99it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 335/335 [00:18<00:00, 17.69it/s]
Type: Archived
Type: Chats
Type: Messages
Processing Scraped Messages
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 4595.66it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 41.97it/s]
Type: Highlights
Type: MassMessages
Scrape Completed
```

**Comment by hammerheaddf** [comment]
I'm experiencing the same issue with auto_media_choice set to "0".

**Comment by DIGITALCRIMINALS** [comment]
Then set it to True and not "0"

**Comment by DIGITALCRIMINALS** [comment]
> Thanks for the quick fix in #293. Unfortunately it still is not downloading the selected media. Tested with Images, and Videos and does the same (does not scrape).
> 
> The OF creator has 2323 images, same output when choosing Videos too.
> 
> ```
> Name: CREATOR
> Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
> 1
> Type: Stories
> Type: Posts
> Scrape Attempt: 1/100
> Type: Archived Posts
> Processing Scraped Posts
> 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 336/336 [00:00<00:00, 37487.99it/s]
> Processing metadata.
> Finished processing metadata.
> Renaming files.
> 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 335/335 [00:18<00:00, 17.69it/s]
> Type: Archived
> Type: Chats
> Type: Messages
> Processing Scraped Messages
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 4595.66it/s]
> Processing metadata.
> Finished processing metadata.
> Renaming files.
> 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 41.97it/s]
> Type: Highlights
> Type: MassMessages
> Scrape Completed
> ```

Commit should fix
https://github.com/DIGITALCRIMINALS/OnlyFans/commit/3137237f1e52cb0db698bdb80e951a67c5c8c8c2

**Comment by sideloading** [comment]
@DIGITALCRIMINALS have tried the latest commit but still having the same output, finishes without downloading anything. 

Choosing 0 = All, works still. 

The user_data.db has all the content in it. Any verbose output I can enable to help troubleshoot?

**Comment by DIGITALCRIMINALS** [comment]
I was tired af and I forgot to push something. but this commit should do it

https://github.com/DIGITALCRIMINALS/OnlyFans/commit/ade4de8b9e294093d1bd5a063835bea450610687

**Comment by sideloading** [comment]
Thank you @DIGITALCRIMINALS! It is working again now :)
