### ISSUE TITLE
Filename_format "{date}" includes file resolution erroneously on images.

### ISSUE THREAD

**Issue by HistoricTheater** [DIGITALCRIMINALS/OnlyFans#299]
Adding the "{date}" variable to "filename_format" for OF results in an image named "2022-01-17_1000x1000_xxx.jpg" instead of "2022-01-17_xxx.jpg", it is grabbing the resolution of the image somewhow.However, video and audio files are correctly resulting in the correct "{date}_{filename}" format.Using just "{filename}" correctly names the file just the filename without resolution.
config.json
```
"filename_format": "{date}_{filename}.{ext}"
"date_format": "%Y-%m-%d"
```

**Comment by DIGITALCRIMINALS** [comment]
Onlyfans includes resolution in their image filenames

**Comment by HistoricTheater** [comment]
They dont, if you JUST use {filename} you do not get anything but the string for that file.
