### ISSUE TITLE
Fansly not downloading video file, possibly 4k error?

### ISSUE THREAD

**Issue by singularitysky** [DIGITALCRIMINALS/OnlyFans#303]
A model just released a 4k video file on Fansly, which I haven't seen before.  Scraper only downloaded a 4.5 mb file, actual file should be in the range of 821mb judging from her OF release, which downloaded fine.

**Comment by DIGITALCRIMINALS** [comment]
which model

**Comment by singularitysky** [comment]
Model is Lilysins.

She just posted some more 4K and it looks like it was just that one video for some reason

**Comment by DIGITALCRIMINALS** [comment]
Latest commit might have fixed it.
