### ISSUE TITLE
Auth problem every version past December 27

### ISSUE THREAD

**Issue by Lanneer487** [DIGITALCRIMINALS/OnlyFans#306]
I get an auth error when I update to the latest version.
The last version working for me is ed356dc from December 27.
Does someone has a fix for this?

**Comment by roelfoubert** [comment]
But why does the auth file works with older version and not the new one?

**Comment by thavajero** [comment]
You need to fill out the x-bc parameter in the auth file

**Comment by roelfoubert** [comment]
I fill out the x-bc parameter but on the newest version I get the error and on the old one it works perfectly.

**Comment by roelfoubert** [comment]
I've done everything but I will stay with the latest release from 3 December.
This version works perfect

**Comment by digitaljdr** [comment]
I'm having the same problem, after using the updater to update my existing directory and I even downloaded a new zip and went through the process and im having the same problem. I'm going to have to roll back my updates.

**Comment by DIGITALCRIMINALS** [comment]
Is this still broken?

**Comment by Lanneer487** [comment]
I always get the same error.

`Traceback (most recent call last):
  File "/usr/src/app/./start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/usr/src/app/./start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "/usr/src/app/datascraper/main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "/usr/src/app/datascraper/main_datascraper.py", line 55, in default
    await main_helper.process_profiles(api, global_settings)
  File "/usr/src/app/helpers/main_helper.py", line 976, in process_profiles
    json_auth = temp_json_auth["auth"]
KeyError: 'auth'
`
but when I use the same configuration on an older version it works perfectly.

**Comment by NilsSjoberg** [comment]
Getting the same error. The old version @Lanneer487 specified works.

**Comment by aukeba** [comment]
Can you link to the version that's working for you? I've went so far as to completely reinstall macOS and start with a fresh build of python and the latest commit but I'm still getting an auth error even though everything is filled out correct

**Comment by Lanneer487** [comment]
https://github.com/DIGITALCRIMINALS/OnlyFans/releases/tag/v7.6.1

**Comment by Lanneer487** [comment]
Now my version has also the auth error

**Comment by DIGITALCRIMINALS** [comment]
Use latest commit
