### ISSUE TITLE
updated to 7.6.1 and Python 3.10.2, now getting ModuleNotFoundError

### ISSUE THREAD

**Issue by robotprom** [DIGITALCRIMINALS/OnlyFans#311]
I updated to 7.6.1, and Python 3.10.2. Ran `pip install --upgrade --user -r requirements.txt` with no problems, and everything updated or installed with no errors. 

When I try to run updater.py, I get:

```
Traceback (most recent call last):
  File "C:\Users\cgeor_000\Desktop\OnlyFans-7.6\updater.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

I then tried a fresh install of 7.6.1, and  `pip install --upgrade --user -r requirements.txt`  again ran without issue. When I ran start_ofd.py, I now get: 

```
Traceback (most recent call last):
  File "C:\Users\c000\Desktop\OnlyFans-7.6\start_ofd.py", line 7, in <module>
    from rich import panel
ModuleNotFoundError: No module named 'rich'
```

I'm stumped as to what to do next. These modules were installed when I ran the pip install command (\I've attached it's output) but it's acting like it's not seeing it. Is this a PATH issue with Python?

[pipoutput.txt](https://github.com/DIGITALCRIMINALS/OnlyFans/files/7902018/pipoutput.txt)

**Comment by nomimani** [comment]
same issue:
Traceback (most recent call last):
  File "/home/office/Desktop/OnlyFans-master/start_ofd.py", line 10, in <module>
    from helpers.main_helper import OptionsFormat
  File "/home/office/Desktop/OnlyFans-master/helpers/main_helper.py", line 21, in <module>
    import classes.make_settings as make_settings
  File "/home/office/Desktop/OnlyFans-master/classes/make_settings.py", line 6, in <module>
    from yarl import URL
ModuleNotFoundError: No module named 'yarl'

**Comment by hiiragizawakun** [comment]
same issue... 

`pi@raspberrypi:~/Downloads/OnlyFans-7.6.1 $ python3.10 start_ofd.py
Traceback (most recent call last):
  File "/home/pi/Downloads/OnlyFans-7.6.1/start_ofd.py", line 7, in <module>
    from rich import panel
ModuleNotFoundError: No module named 'rich'
pi@raspberrypi:~/Downloads/OnlyFans-7.6.1 $ pip install rich
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: rich in /home/pi/.local/lib/python3.9/site-packages (11.0.0)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /home/pi/.local/lib/python3.9/site-packages (from rich) (0.9.1)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in /home/pi/.local/lib/python3.9/site-packages (from rich) (0.4.4)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /home/pi/.local/lib/python3.9/site-packages (from rich) (2.11.2)
pi@raspberrypi:~/Downloads/OnlyFans-7.6.1 $ `

I tried installing rich and I noticed that rich is in python 3.9. 

If I remove python 3.9, it will remove pip functionality.

If I reinstall pip again, it will bring back python3.9.

**Comment by DIGITALCRIMINALS** [comment]
Use Python 3.10.1 (uninstall older versions if you have too)
