### ISSUE TITLE
[Edge Case?] Paid content that was "resent" is not downloading

### ISSUE THREAD

**Issue by jaysomm** [DIGITALCRIMINALS/OnlyFans#312]
I seem to have found a weird edge case, but i cant figure out the root cause when trying to debug. For example: ive probably purchased at least a dozen or so paid images from a user in DM. However, the scrape only finds six images. I believe the missing ones are the images that were "resent" by the creator from when my subscription had lapsed.

Any ideas why this might be the case, and/or how to fix?

**Comment by DIGITALCRIMINALS** [comment]
Which site is it related too?

**Comment by aboredpervert** [comment]
This happens when they re-send the exact same media, it has the same media ID, has already been marked as downloaded before so is not downloaded again.

**Comment by jaysomm** [comment]
onlyfans

------- Original Message -------

**Comment by DIGITALCRIMINALS** [comment]
Resent content should have "linked_" prepended to it's filename, is this not the case?
