### ISSUE TITLE
Blacklist isnt followed if you have paid content

### ISSUE THREAD

**Issue by HistoricTheater** [DIGITALCRIMINALS/OnlyFans#314]
Using "Blacklisted" adding them to a list or listing the username in the "blacklists" option dosent actually prevent them from being downloaded again if you delete their folder.
Use case: The creator in question is no longer active and i've moved them to a backup drive, i no longer want their content or paid messages to be downloaded any more.

**Comment by DIGITALCRIMINALS** [comment]
It works for me if I move them to a blacklist

**Comment by HistoricTheater** [comment]
I created a "Blacklist" list on OF and moved them there and set "blacklists": "Blacklisted" in the settings(case sensitive) however,the messages are still being scraped when i remove the model folder

**Comment by DIGITALCRIMINALS** [comment]
There's a new job called "Messages" in the config. I forgot to apply the blacklist to that. You can turn it off until I fix it.

**Comment by DIGITALCRIMINALS** [comment]
erm you can turn messages back on now .-.

https://github.com/DIGITALCRIMINALS/OnlyFans/pull/805/commits/2e6afe408bb8303dd9d42f8f59c7319542228e5b
