### ISSUE TITLE
Onlyfans Auth 404?

### ISSUE THREAD

**Issue by adamperez** [DIGITALCRIMINALS/OnlyFans#32]
Can't find any information on this issue (and sorry @DIGITALCRIMINALS if this falls into an "auth issue", but I am totally lost). Just updated everything to the latest commit, Python 3.10, all requirements installed. I've updated my `auth.json` file to match what the cookie has in the network console, as well as whatever information I can get from the Onlyfans Cookie Helper, but I keep getting this Auth 404 error. 

Is it simply a configuration issue? Am I missing something?

EDIT: I've also noticed whenever you run the script, it resets your `auth.json` file

**Comment by dnkness** [comment]
> Resolved by running `sudo /Applications/Python\ 3.10/Install\ Certificates.command`

How do you run a sudo command?

**Comment by lordoffools** [comment]
> > Resolved by running `sudo /Applications/Python\ 3.10/Install\ Certificates.command`
> 
> How do you run a sudo command?

I highly recommend doing a Google search for some of these types of questions since it really depends on your computer, OS, setup, etc.

https://www.google.com/search?q=how+do+I+run+sudo&oq=how+do+I+run+sudo
