### ISSUE TITLE
Traceback/FileNotFoundError (legacy_metadata folder not being created)

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINALS/OnlyFans#320]
Anyone know what the problem is here?

> Scrape Processing
> Name: kimmyxkimm
> INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
> INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
> INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
> INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
> Traceback (most recent call last):
> File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 805, in move
> os.rename(src, real_dst)
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'X:\\OnlyFans\\OnlyFans\\kimmyxkimm\\Metadata\\Archived.db' - 'X:\\OnlyFans\\OnlyFans\\kimmyxkimm\\Metadata\\__legacy_metadata__\\Archived.db'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\username\Desktop\OnlyFans-master\start_ofd.py", line 66, in
> asyncio.run(main())
> File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
> return loop.run_until_complete(main)
> File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
> return future.result()
> File "C:\Users\username\Desktop\OnlyFans-master\start_ofd.py", line 52, in main
> api = await main_datascraper.start_datascraper(config, site_name)
> File "C:\Users\username\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 129, in start_datascraper
> await default(datascraper)
> File "C:\Users\username\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 101, in default
> await main_helper.process_jobs(datascraper, subscription_list, site_settings)
> File "C:\Users\username\Desktop\OnlyFans-master\helpers\main_helper.py", line 1044, in process_jobs
> await datascraper.start_datascraper(authed, subscription.username)  # type: ignore
> File "C:\Users\username\Desktop\OnlyFans-master\modules\module_streamliner.py", line 73, in start_datascraper
> await main_helper.fix_sqlite(api, subscription_directory_manager)
> File "C:\Users\username\Desktop\OnlyFans-master\helpers\main_helper.py", line 446, in fix_sqlite
> shutil.move(archived_database_path, f"{new_filepath}")
> File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 825, in move
> copy_function(src, real_dst)
> File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 434, in copy2
> copyfile(src, dst, follow_symlinks=follow_symlinks)
> File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 256, in copyfile
> with open(dst, 'wb') as fdst:
> FileNotFoundError: [Errno 2] No such file or directory: 'X:\\OnlyFans\\OnlyFans\\kimmyxkimm\\Metadata\\__legacy_metadata__\\Archived.db'

**Comment by badchoices** [comment]
The folder does not exist. Try creating the folder `X:\OnlyFans\OnlyFans\kimmyxkimm\Metadata\legacy_metadata` you may also need to copy `archive.db` and rename it to `Archived.db`

**Comment by doththouevenhoist** [comment]
I just wanna say that I recently experienced the same problem that's isolated to one particular model's page (nobody else's when I try to scrape each model's page separately) and @badchoices's solution worked well for me.  I just had to create the folder and file and everything was fine.

I suspect maybe it's because this was a holdover from when I last scraped the model's page using a much older version of the scraper.

**Comment by DIGITALCRIMINALS** [comment]
@doththouevenhoist yes, the script converts all old metadata to new format xxx.db and then places it in the legacy_metadata folder.

For some reason it's not creating the folder automatically. I'll have to look into it.

**Comment by KlfJoat** [comment]
I have had a similar-looking problem pop up on the latest commit.

I notice it's for a model I no longer subscribe to. I notice that the script is now going over all models, not just ones I'm currently subscribed to. Seems like it might have something to do with the change to grab Messages content for models you're not subscribed to?
