### ISSUE TITLE
OnlyFans acces attemp logout

### ISSUE THREAD

**Issue by jk-cz-git** [DIGITALCRIMINALS/OnlyFans#325]
Did OF changed something last days? If I copy sess id from cookie and then try to download OF site, i get error Access denied and my OF account is loged out in Chrome (explorer) .

**Comment by DeepSeaOne** [comment]
If you run the scraper with the wrong info it will kill that session. Make sure you're using valid values(use the cookie helper if you need to)

**Comment by jk-cz-git** [comment]
Please, what is cookie helper? I use Chrome console and Chrome addon for read cookies.

I am right, that x_bc and auth_id does not change between sessions? Only sess is changing, isn't it?

**Comment by jk-cz-git** [comment]
Ok, i am fine now. Problem was wrong value in user-agent after Chrome update...
