### ISSUE TITLE
Updated `file_directory_format` not being applied

### ISSUE THREAD

**Issue by adamperez** [DIGITALCRIMINALS/OnlyFans#33]
I've updated my `file_directory_format` in config to read:
```
"file_directory_format": "{site_name}/{model_username}/{media_type}",
```
but when I run the onlyfans scraper, it seems to use the default version of `file_directory_format`. Am I missing a directory level that is required?

**Comment by DIGITALCRIMINALS** [comment]
Does this still happen?

**Comment by ElSandu** [comment]
Yes, it happens to me running docker in unraid, don´t know how to fix it.

**Comment by DIGITALCRIMINALS** [comment]
Does it only happen in docker and works outside of it?

**Comment by ElSandu** [comment]
In fact It doesn´t happen now (not sure of what I did) but it is not happening now, I have reinstalled the docker three or four times, so...
