### ISSUE TITLE
Possible to convert metadata to new format for models I'm no longer subscribed to?

### ISSUE THREAD

**Issue by ricguy91** [DIGITALCRIMINALS/OnlyFans#331]
Is there a sub script I can run manually for this by any chance?

Recently set up stash on my media server, and there are tools to scrape the OF metadata generated by this tool, but I can only get it to work on models I subscribed to recently enough that their metadata is in the db format rather than the seperate json files.

Just curious.  Thanks.

**Comment by ALonelyJuicebox** [comment]
Hey-- I'm the author of one of the aforementioned tools ([OFMetadataToStash](https://github.com/ALonelyJuicebox/OFMetadataToStash)). If you can provide me with an example JSON file I can probably write a utility that will generate a SQLite database file for it.

**Comment by ALonelyJuicebox** [comment]
Sorry about the delay! Of course. Either way though, we should probably hop onto Discord to exchange email addresses/maybe even the files themselves.

I'm most active on Stash's discord. Username Juicebox.
https://discord.gg/2TsNFKt

**Comment by DIGITALCRIMINALS** [comment]
I'm working on make OFRenamer a standalone thing, but it's not ready yet.

**Comment by DIGITALCRIMINALS** [comment]
It's usable, but it's not entirely user friendly yet.

https://github.com/DIGITALCRIMINALS/UltimaScraperRenamer
