### ISSUE TITLE
unable to start.

### ISSUE THREAD

**Issue by garthilna** [DIGITALCRIMINALS/OnlyFans#333]
Have had this issue and I am unable to go further.
ran pip install --upgrade --user -r requirements.txt
then
python start_ofd.py 
the output is as follows: 

PS D:\OF\OnlyFans-master> python start_ofd.py
Traceback (most recent call last):
  File "D:\OF\OnlyFans-master\start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "D:\OF\OnlyFans-master\helpers\main_helper.py", line 836
    match options_type:
          ^
SyntaxError: invalid syntax

not sure how to proceed.

**Comment by DIGITALCRIMINALS** [comment]
Use Python 3.10
