### ISSUE TITLE
start_ofd.py won't open, ModuleNotFoundError: No module named 'orjson'

### ISSUE THREAD

**Issue by hawktank** [DIGITALCRIMINALS/OnlyFans#335]
Did a clean install of the latest version of OnlyFans, 
ran:   
**pip install poetry**
and
 **poetry install**
no errors on these

**python start_ofd.py** gets an error about **orjson** not found
double clicking **start_ofd.py** just opens/closed a cmd prompt in a split second.

Using Python 3.10.2, but 3.10.1 gives the same error.

Ran **poetry update** which updated parts of poetry, then **poetry install** - no fix.

The error output when trying to open **start_ofd.py** :
```
H:\My Documents\GitHub\OnlyFans>python start_ofd.py
Traceback (most recent call last):
  File "H:\My Documents\GitHub\OnlyFans\start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "H:\My Documents\GitHub\OnlyFans\helpers\main_helper.py", line 23, in <module>
    import orjson
ModuleNotFoundError: No module named 'orjson'
```

**Comment by hawktank** [comment]
Ok, I fixed it by manually installing the orjson module - **pip install --upgrade orjson**

**Comment by Arragon5xpwm** [comment]
run the program with `poetry run python ./start_ofd.py` instead and it should work without manual install via pip
