### ISSUE TITLE
Dockerfile needs update

### ISSUE THREAD

**Issue by Arragon5xpwm** [DIGITALCRIMINALS/OnlyFans#336]
needs to use poetry too

```
From e13a6c26cf13d921fe0d57059ca5267aaeedcb19 Mon Sep 17 00:00:00 2001
From: Arragon5xpwm <not@given.invaild>
Date: Sun, 6 Feb 2022 22:29:31 +0100
Subject: [PATCH] Dockerfile updated

---
 Dockerfile | 13 +++++++------
 1 file changed, 7 insertions(+), 6 deletions(-)

diff --git a/Dockerfile b/Dockerfile
index 524c430..0ee1f5a 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,10 +1,11 @@
-FROM python:3.10
+FROM python:3^M
 
 WORKDIR /usr/src/app
 
-COPY requirements.txt ./
-RUN pip install --no-cache-dir -r requirements.txt
+COPY pyproject.toml .^M
+COPY poetry.lock .^M
+RUN pip install --no-cache-dir poetry^M
+RUN poetry install^M
 
-COPY . .
-
-CMD [ "python", "./start_ofd.py" ]
+COPY . . ^M
+CMD [ "poetry", "run", "python", "./start_ofd.py" ]^M
-- 
2.29.1
```

**Comment by marianvlad** [comment]
Same problem. `requirements.txt: no such file or directory`

**Comment by stranger-danger-zamu** [comment]
Better not do that as that pulls in a lot of poetry only deps and inflates the container for no reason.

---

Long term, once the code base is worked over a bit more, you should be able to:

```bash
poetry build
docker build --build-arg VERSION=$(poetry version -s) -t $REPO/OnlyFans:$$(poetry version -s) .
```

And that's it.
The `poetry build` set should package the code as a python wheel and the Dockerfile would reflect just copying over the wheel (or better yet using multistage containers and build the wheel inside stage 1).


The Dockerfile would then (roughly) look like:

```Dockerfile
FROM python:3.10

ARG VERSION
WORKDIR /usr/src/app

COPY ./dist/OnlyFans-$VERSION-py3-none-any.whl .
RUN pip install --upgrade --no-cache-dir pip wheel && \
    pip install --no-cache-dir ./OnlyFans-$VERSION-py3-none-any.whl

CMD ["start-ofd']
```

---

Of course the code isn't there yet, so for now it's best to just do this instead:

```bash
poetry export --without-hashes -E performance -o requirements.txt
docker build -t $REPO/OnlyFans:$(poetry version -s) .
```

**Comment by Arragon5xpwm** [comment]
Wouldn't this require to install und run poetry outside the container?  The server itself that builds the container would need to have python installed.

**Comment by stranger-danger-zamu** [comment]
That's what multistage builds are for so that you can just tell it to docker build and it'll do everything in a container. For now installing poetry outside is normal since it's part of the dev toolkit?

**Comment by stranger-danger-zamu** [comment]
Multistage Dockerfile

```Dockerfile
FROM python:3.10 AS builder

ARG VERSION
RUN python -m pip install --upgrade pip wheel poetry

WORKDIR /code
COPY . /code/

RUN poetry build

FROM python:3.10 AS final

ARG VERSION
WORKDIR /usr/src/app
COPY --from=builder /code/dist/OnlyFans-$VERSION-py3-none-any.whl .
RUN pip install --upgrade --no-cache-dir pip wheel && \
    pip install --no-cache-dir ./OnlyFans-$VERSION-py3-none-any.whl

CMD ["start-ofd"]

```

Simple as:
```bash
export VERSION=$(poetry version -s)
docker build --build-arg=VERSION=${VERSION} -t $REPO/OnlyFans:${VERSION} .
```
If you don't have poetry installed, then just set the `VERSION` variable manually.

Of course, this still doesn't work at the moment, but hopefully soon it will.
