### ISSUE TITLE
The scaper doesn't support the stars who doesn't using English

### ISSUE THREAD

**Issue by wangweiqi20020221** [DIGITALCRIMINALS/OnlyFans#338]
Hi, when I tried to copying a star using Chinese, I got an error about gbk encoding. The gbk encoding doesn't support languages such as Chinese, so I changed it to utf-8 and the script works. Here's how I change it:

In the file /helpers/main_helper.py, line 937:
temp_json_auth = ujson.load(open(user_auth_filepath, encoding="utf-8"))

I added encoding="utf-8" in the def open().

I tried to push my editing to your amazing project, but I didn't find ".git" file in this project, so I submit this issue.

**Comment by JohnwicK7382** [comment]
can i contact you?

**Comment by DIGITALCRIMINALS** [comment]
> Hi, when I tried to copying a star using Chinese, I got an error about gbk encoding. The gbk encoding doesn't support languages such as Chinese, so I changed it to utf-8 and the script works. Here's how I change it:
> 
> In the file /helpers/main_helper.py, line 937: temp_json_auth = ujson.load(open(user_auth_filepath, encoding="utf-8"))
> 
> I added encoding="utf-8" in the def open().
> 
> I tried to push my editing to your amazing project, but I didn't find ".git" file in this project, so I submit this issue.

You're using an outdated version of the scraper. The latest commit already includes utf-8 for importing json files.

I'll also keep in mind that some languages aren't supported by default due to encoding.
