### ISSUE TITLE
Im new to python and stuff can any1 help me how to start and continue 

### ISSUE THREAD

**Issue by JohnwicK7382** [DIGITALCRIMINALS/OnlyFans#339]
Heyy Im new to python and stuff can any1 help me how to start and continue  I tried pip user req line it doesnt work i tried power shell no use would really appreciate if any 1 can help me thanks

**Comment by reahari** [comment]
without more info best you can do is ask on reddit https://www.reddit.com/r/Piracy/comments/oy3coc/how_to_run_digitalcriminal_onlyfans_data_scraper/

**Comment by DIGITALCRIMINALS** [comment]
requirements.txt doesn't even exist anymore. Just follow the main page tutorial.
