### ISSUE TITLE
Is Python 3.10.1 necessary?

### ISSUE THREAD

**Issue by KlfJoat** [DIGITALCRIMINALS/OnlyFans#340]
Hi,

Linux user here. I'm not going to ask for Linux support, as I know you primarily use Windows. I'm working on managing the Linux differences myself. But I do want to ask if you can make things a tiny bit easier on Linux users.

Since you just removed it, I'm trying to convert from `pip`+`requirements.txt` to `poetry`. And I'm hung up a bit on the `poetry` requirement for Python 3.10.1.

It's easy for Ubuntu users to get Python 3.10.0 with bugfixes. That's in repo for Ubuntu 21.10.  
It's easy for Ubuntu users to get Python 3.10.2. That's in the deadsnakes PPA (20.04 & 18.04).

But for 3.10.1, that would require most Ubuntu or Red Hat users to build Python from source. Doable, but rather involved.

So is 3.10.1 necessary for what will be v8.0.0 of your tool? If not, could you loosen up the `poetry` constraint? If it's necessary, that's fine, I'll do the extra work.  Of course, I'll submit the instructions to Linux.md when I get it working.

Thanks!

**Comment by stranger-danger-zamu** [comment]
You could just edit the file and bump the version in the `pyproject.toml` file?

**Comment by KlfJoat** [comment]
> You could just edit the file and bump the version in the `pyproject.toml` file?

I'm trying to create instructions for others. "Edit the project source code and diverge, making sure you don't try to merge conflicting commits" isn't very friendly.

Also, the `poetry.lock` file should be updated (and committed to the project) [per the Poetry docs](https://python-poetry.org/docs/master/basic-usage/#commit-your-poetrylock-file-to-version-control). So that'll be 2 files you're managing diverged from upstream, with a procedure to create one from the other. More complexity.

And I don't know if the script is on 3.10.1 because there's a bug in 3.10.0 he's avoiding or if he just downloaded the latest Windows version from Python.org. I do know that in #311 he told someone to downgrade from 3.10.2 to 3.10.1. So only he can tell me if I can go up or down. If I can't, I can't, I'll deal with it if I have to. But I won't know for sure until I ask.

**Comment by KlfJoat** [comment]
> Ah you didn't mention anything about making instructions for others in the OP.

But I did. I said:  "I'll submit the instructions to Linux.md when I get it working."

> I tested with python3.10.2 and it works without an issue, so I think it's user error on the submitter's part.

But DIGITALCRIMINALS said in that ticket to downgrade to 3.10.1. I'd rather listen to them since it's their app. 

> As for the edit I proposed you do, it was to address the python 3.10.1 issue mentioned in the OP.

It seems you misunderstand how Poetry works. [Per the documentation](https://python-poetry.org/docs/master/basic-usage/#installing-with-poetrylock):

> running `install` when a `poetry.lock` file is present resolves and installs all dependencies that you listed in `pyproject.toml`, but Poetry uses the exact versions listed in `poetry.lock`

DIGITALCRIMINALS has committed a `poetry.lock` file, so the only way a local change to the `pyproject.toml` file will "take" is if the user also deletes the `poetry.lock` file, updates `pyproject.toml`, then runs `poetry install` to create a new local copy of `poetry.lock`. As I said above, "that'll be 2 files you're managing diverged from upstream, with a procedure to create one from the other. More complexity."

I appreciate that you're trying to help, but I've already thought about all of the things you've brought up that were relevant. My question is about the intent of the author. You cannot answer my question.

**Comment by stranger-danger-zamu** [comment]
Lol, I'm about to push the PR that'd make all this irrelevant I'm literally trying to help you from wasting a ton of time, but to each their own.

**Comment by KlfJoat** [comment]
But your PR doesn't update the `poetry.lock` file... It could cause a problem with the repo if it was accepted, since `poetry.lock` was created from a more stringent `pyproject.toml` file. You'd likely cause the exact kind of dependency problem that Poetry is designed to prevent if it's used properly.

**Comment by stranger-danger-zamu** [comment]
Wrong PR, I didn't push it since it's not ready since somethings need to be discussed (see #343). 

And for the most part I don't care if most people can't use this. If they can't figure it out, then :shrug: . It's not rocket science.  I however would like to make packaging this a bit nicer just so I can configure it without some arcane directories or relying on docker mounts or symlinks.

**Comment by DIGITALCRIMINALS** [comment]
My dev environment is Linux now, well Arch Linux.

I made 3.10.1 the minimum because there was a bug with asyncio and semaphores, also I don't plan to bump the python requirement up every time a minor version is released.

I'll merge https://github.com/DIGITALCRIMINALS/OnlyFans/pull/342/commits/0c8cea72077155a32a70949168dcd833ac2a9bd0

Hopefully the bug doesn't return for 3.10 users.

**Comment by KlfJoat** [comment]
FYI, the asyncio bug hasn't hit me until today. Now I'm getting a lot of problems there. 

Looks like I need to get a newer Python.
