### ISSUE TITLE
Scrape stuck on "Download Processing"

### ISSUE THREAD

**Issue by bthomaser** [DIGITALCRIMINALS/OnlyFans#344]
I log on successfully to my OnlyFans, it sees the models, and when I choose one to scrape (even one with almost no content), it starts the scrape and then is stuck on Download Processing.

It looks like it's downloading but there's no network activity, and the progress bar is not moving.

```
C:\***\OnlyFans-master>python start_ofd.py
Choose Sites: 0 = All | 1 = OnlyFans | 2 = Fansly | 3 = StarsAVN
1
Choose Profiles: 0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Welcome myuser | myuser
Choose Subscriptions: 0 = All | 1 = model1 | 2 = model2 | 3 = model3 | 4 = model4 | 5 = model5
2
Scraping Paid Content
Scraping - model1 | 1 / 5
Scraping - model2 | 2 / 5
Scraping - model3 | 3 / 5
Scraping - model4 | 4 / 5
Scraping - model5 | 5 / 5
Scraping Subscriptions
Scrape Processing
Name: model2
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
1
Type: Stories
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Processing Scraped Posts
100%|████████████████████████████████████████████████████████████████████████████████| 19/19 [00:00<00:00, 2377.37it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|████████████████████████████████████████████████████████████████████████████████| 19/19 [00:00<00:00, 2536.02it/s]
Type: Archived
Type: Chats
Type: Messages
Type: Highlights
Type: MassMessages
Scrape Completed

Download Processing
Name: model2 | Type: Posts | Count: 35 | Directory: .sites

  0%|▏                                                                               | 416k/247M [00:17<04:39, 880kB/s]
```

I installed the newest release, made sure it's up to date, and installed all the modules.
Running Python 3.10.2.
Tried running as administrator.

Thanks for any help, and thanks very much for maintaining this project!

**Comment by exenen** [comment]
Did you get this issue figured out? I'm getting the same issue.  Mine will start to download and then just stop instantly and the files look like they've started to download but there's a bunch of temp files that are  0 bytes.

**Comment by stevenrun** [comment]
Same issue here... Python is hammering one CPU but nothing appears to be happening anywhere in terms of disk / network activity.

**Comment by stevenrun** [comment]
YMMV, but I turned "reformat_media": to false in my settings.json and that appears to have fixed things for me

**Comment by bthomaser** [comment]
@stevenrun That did the trick for me too! Thanks!
