### ISSUE TITLE
Unableinstall please help！

### ISSUE THREAD

**Issue by SandyLam123** [DIGITALCRIMINALS/OnlyFans#348]
python is not recognized please help！
pip : The "pip" entry cannot be recognized as the name of a cmdlet, function, script file or runnable program
![111](https://user-images.githubusercontent.com/99605741/153761311-63fb573e-5320-4a11-9bbe-6b999dbdd8ca.jpg)

**Comment by DIGITALCRIMINALS** [comment]
You need to install pip properly
