### ISSUE TITLE
can someone make a youtube video or a video tutrioal of what to do because i keep on having problems starting start_ofd.py 

### ISSUE THREAD

**Issue by p5ismyname** [DIGITALCRIMINALS/OnlyFans#349]
saying  [Errno 2] No such file or directory

**Comment by reahari** [comment]
lol gonna need a lot more info than that ^_^

tried reading the readme? What's your os etc

**Comment by p5ismyname** [comment]
my os is Windows 10 Pro. OS build 19043.1526

**Comment by clarry76** [comment]
I found this pdf file in one of these threads of how to install and get the onlyfans downloader to work.
You can grab it here [https://www.mediafire.com/file/m9rnf338qet2v8f/document.pdf/file](url)
Credit to original uploader...can't remember where I got it.
Hope it helps, worked flawlessly for me.

**Comment by DIGITALCRIMINALS** [comment]
You need to post the full error

**Comment by MrFrio** [comment]
> I found this pdf file in one of these threads of how to install and get the onlyfans downloader to work.
> You can grab it here [https://www.mediafire.com/file/m9rnf338qet2v8f/document.pdf/file](url)
> Credit to original uploader...can't remember which thread it was.
> Hope it helps, worked flawlessly for me.

Problem is, that file doesn’t seem to exist anymore

**Comment by headphonia** [comment]
Works for me, copy the link and paste it in the address bar instead of clicking on it.

**Comment by mathiastravolta** [comment]
Hello there friends, I'm trying to run start_ofd.py without any success :( I'm getting this error, do anyone have any idea to fix that? Thanks in advance
C:\Users\admin\Desktop\OnlyFans-7.6.1>python start_ofd.py
  File "start_ofd.py", line 38
    async def main():
            ^
SyntaxError: invalid syntax

**Comment by DIGITALCRIMINALS** [comment]
> async def main():
> ^
> SyntaxError: invalid syntax

You're not using Python 3.10.1
