### ISSUE TITLE
Not Scrapping All Content

### ISSUE THREAD

**Issue by Site3op** [DIGITALCRIMINALS/OnlyFans#35]
The fansly scrapper is still having a problem scrapping tiered content. I can get base subscription content for the most part - a couple of pictures. But the tiered content (higher tiers that ARE unlocked) have a problem scrapping for some reason.

**Comment by ttrv65ebyng** [comment]
I'm having a similar issue in which a creator's **only tier** is called *All Access* (and I have confirmed I have access to all content through the site itself), however, when scraping all content (0), I only get about half of their images, and 1/20th of their video content. No error messages. On release 7.5 with Python 10.

**Comment by LoopinfiIity** [comment]
had the same issue. i was actually lucky to find this other script on github for fansly . it worked out good for me maybe try it here link https://github.com/Avnsx/fansly

**Comment by ttrv65ebyng** [comment]
> had the same issue. i was actually lucky to find this other script on github for fansly . it worked out good for me maybe try it here link https://github.com/Avnsx/fansly

Yep, I ended up using that script for now. Thanks!

**Comment by conymant** [comment]
I had a problem with the installation, and therefore found this tool. I used it mainly for Onlyfans but it also works with Fansly.
https://github.com/montroly/fansyloader

**Comment by DIGITALCRIMINALS** [comment]
Can anyone recommend a cheap higher tier model?

**Comment by Site3op** [comment]
> Can anyone recommend a cheap higher tier model?

Would be willing to give you access to the account so you can see for yourself

**Comment by YJu3SkYQ24** [comment]
It doesn't seem uniform. There's one model who I have a higher-tier subscription for that has all their media scraped and another where only the first media of any given post is scraped. DM me if you want model names or details.

**Comment by DIGITALCRIMINALS** [comment]
@Site3op if you still wanna help, you can send the auth.json to my email address, which is datahoarders@protonmail.com

**Comment by Site3op** [comment]
> @Site3op if you still wanna help, you can send the auth.json to my email address, which is [datahoarders@protonmail.com](mailto:datahoarders@protonmail.com)

Sent, I hope you fix it good sir.

**Comment by DIGITALCRIMINALS** [comment]
> > @Site3op if you still wanna help, you can send the auth.json to my email address, which is [datahoarders@protonmail.com](mailto:datahoarders@protonmail.com)
> 
> Sent, I hope you fix it good sir.

Thanks working on it now. Which one is the high tier model though?

**Comment by Site3op** [comment]
> > > @Site3op if you still wanna help, you can send the auth.json to my email address, which is [datahoarders@protonmail.com](mailto:datahoarders@protonmail.com)
> > 
> > 
> > Sent, I hope you fix it good sir.
> 
> Thanks working on it now. Which one is the high tier model though? Loony?

I replied to the email.
