### ISSUE TITLE
Not able to install poetry (poetry install)

### ISSUE THREAD

**Issue by DigBick98** [DIGITALCRIMINALS/OnlyFans#352]
Hi, always used to be able to use OF Downloader but since being forced to upgrade to 7.6.1 I've had nothing but issues.

I've followed all instructions, tried all methods I can find online however I still cannot get "poetry install" command to work.

Please help me!

Yes I've used "pip install --upgrade pip" and upgraded to the latest version however the warning message wont go away....

TIA!

WARNING: You are using pip version 21.2.4; however, version 22.0.3 is available.
You should consider upgrading via the 'C:\Users\Business\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.
PS C:\Users\Business\Desktop\OnlyFans-7.6.1> poetry install
poetry : The term 'poetry' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ poetry install
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (poetry:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by DigBick98** [comment]
PS C:\Users\Business\Desktop\OnlyFans-7.6.1> python start_ofd.py
Traceback (most recent call last):
  File "C:\Users\Business\Desktop\OnlyFans-7.6.1\start_ofd.py", line 7, in <module>
    from rich import panel
ModuleNotFoundError: No module named 'rich'

**Comment by E0911CD45B19686** [comment]
You don't install poetry with the command `poetry install`, that install the dependencies needed by this tool. You install poetry by running `pip install poetry`. It's all in the [README](https://github.com/DIGITALCRIMINALS/OnlyFans/blob/master/README.md#installation-commands).

After you install poetry you might need to open a new terminal for windows to find the new binary.

**Comment by Sasquatch00** [comment]
@E0911CD45B19686 so is `poetry install` not a command that needs to be ran? It's highlighted like it is but I get the same error that 'poetry' is not recognized etc...  It doesn't matter if I try it in the same powershell window or a new one.

**Comment by E0911CD45B19686** [comment]
You need to run **both** commands. The error "poetry is not recognized" means that poetry is not installed, so first you need to install poetry by running `pip install poetry`. If it installs correctly you should see a message similar to:

> Successfully installed SecretStorage-3.3.1 cachecontrol-0.12.10 cachy-0.3.0 certifi-2021.10.8 cffi-1.15.0 charset-normalizer-2.0.12 cleo-0.8.1 clikit-0.6.2 crashtest-0.3.1 cryptography-36.0.1 distlib-0.3.4 filelock-3.6.0 html5lib-1.1 idna-3.3 importlib-metadata-4.11.1 jeepney-0.7.1 keyring-23.5.0 lockfile-0.12.2 msgpack-1.0.3 packaging-20.9 pastel-0.2.1 pexpect-4.8.0 pkginfo-1.8.2 platformdirs-2.5.0 **poetry-1.1.13 poetry-core-1.0.7** ptyprocess-0.7.0 pycparser-2.21 pylev-1.4.0 pyparsing-3.0.7 requests-2.27.1 requests-toolbelt-0.9.1 shellingham-1.4.0 six-1.16.0 tomlkit-0.10.0 urllib3-1.26.8 virtualenv-20.13.1 webencodings-0.5.1 zipp-3.7.0

If you already had it installed then when you run `pip install poetry` you would see a messages similar to: 

>Requirement already satisfied: poetry in /usr/local/lib/python3.10/site-packages (1.1.13)
>Requirement already satisfied: poetry-core<1.1.0,>=1.0.7 in /usr/local/lib/python3.10/site-packages (from poetry) (1.0.7)

If you see any other messages poetry might have had an error installing, paste it here.

Second, only _after_ poetry is installed, you need to run `poetry install` in the scraper directory to install all the dependencies. Then you can run `poetry run python ./start_ofd.py` to start the scraper.

**Comment by E0911CD45B19686** [comment]
Your python install didn't tell windows where to find pip installed packages. Try running `c:\users\sasquatch\appdata\roaming\python\python310\site-packages\poetry install` instead. If that works you can fix the problem by adding `c:\users\sasquatch\appdata\roaming\python\python310\site-packages` to your PATH by following https://stackoverflow.com/a/44272417. This way you can just do `poetry install` without the full path.

**Comment by Sasquatch00** [comment]
@E0911CD45B19686  Thanks for all you help on this. I added the path using the guide and attempted in a fresh window results below:

H:\OnlyFans-master>poetry install
Traceback (most recent call last):
  File "C:\Users\Sasquatch\AppData\Roaming\Python\Python310\site-packages\poetry\poetry.py", line 4, in <module>
    from poetry.core.packages import ProjectPackage
  File "C:\Users\Sasquatch\AppData\Roaming\Python\Python310\site-packages\poetry\poetry.py", line 4, in <module>
    from poetry.core.packages import ProjectPackage
ModuleNotFoundError: No module named 'poetry.core'; 'poetry' is not a package

**Comment by E0911CD45B19686** [comment]
🤷 You're having problems with python/pip, not the scraper, and I don't use windows so I can't help any further

**Comment by Sasquatch00** [comment]
Ahh, Ok. I'll remove/reinstall python. Thanks again for your help, I really appreciate it.

**Comment by Sasquatch00** [comment]
That worked, Did full uninstall of Python and reinstalled, had to add 'C:\Users\Sasquatch\AppData\Roaming\Python\Python310\Scripts' to path as well

**Comment by DIGITALCRIMINALS** [comment]
When installing on Windows, make sure to select the option to add Python to path, so you don't have to do it yourself.
