### ISSUE TITLE
Incomplete scrape of paid content 

### ISSUE THREAD

**Issue by melbandera** [DIGITALCRIMINALS/OnlyFans#353]
Hello y'all. Saw a couple of similar closed issues but didn't notice any solutions. I have purchased some paid message content that I am unable to scrape. The scraper will grab some of this content but not all of it. It fails to download the same set of videos with repeated tries. Happens with the most recent pull. I am not certain if partial scraping is limited to this single profile, but I can say I am completely unable to do is scrape content of models with lapsed subscriptions, even if I purchased PPV.

```
{
  "info": {
    "version": 8.0
  },
  "settings": {
    "auto_site_choice": "",
    "export_type": "json",
    "profile_directories": [
      ".profiles"
    ],
    "max_threads": -1,
    "min_drive_space": 0,
    "helpers": {
      "renamer": true,
      "reformat_media": true,
      "downloader": true,
      "delete_empty_directories": false
    },
    "webhooks": {
      "global_webhooks": [],
      "global_status": true,
      "auth_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      },
      "download_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      }
    },
    "exit_on_completion": false,
    "infinite_loop": true,
    "loop_timeout": 0,
    "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
    "proxies": [],
    "cert": "",
    "random_string": "64785a5473b311ec855e8a094eea7fb1"
  },
  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_media_choice": "",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{model_username}/{api_type}/{value}/{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    },
    "fansly": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_media_choice": "",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{model_username}/{api_type}/{value}/{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    },
    "starsavn": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_media_choice": "",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{model_username}/{api_type}/{value}/{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    }
  }
}
```

**Comment by JohnnyTowns94** [comment]
I think something has changed recently because I have noticed that the scraper is processing a lot less paid content than usual.

**Comment by aizenn1** [comment]
I have the same problem, I'm trying to scrape a model content with 200+ videos but I only getting 22 does anyone have the same problem nowadays? I have tried with 2 other models and the same problem not downloading the whole content just a few of it! Btw the models posting non PPV vids so the vids not locked or something, I think onlyfans changed the api or something! Check this screenshot: https://imgur.com/FY6xoE0 as you can see the process getting stopped on 25%

**Comment by HistoricTheater** [comment]
I'm not having this issue however i notice your config is missing a few options that i have filled in, and im getting full rips

```      
       "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_media_choice": "",
        "auto_api_choice": true,
```
Where i have
```
      "settings": {
        "auto_profile_choice": "default",
        "auto_model_choice": true,
        "auto_media_choice": true,
        "auto_api_choice": true,
```
I suggest filling those in so it automatically runs everything and checking again,this may or may not change anything but its worth trying

**Comment by artyom2035** [comment]
In my case, one thing could pinpoint is that it seems if paid content has a preview video 'slide' whatever it's called won't download. Even occurred with a message that I unlocked yesterday.  There are others instances for which I can't isolate a reason - maybe age?

When my NAS crashed ~4 months ago the script only redownload the newest paid content (~5-6 months old) from currently subscribed models. It wouldn't redownload any paid from expired subs or older content from current subs. Tried lots of different commits/releases unsuccessfully. No setting in the config, i.e. 'paid_content', 'overwrite_files', auto choices, or deleting metadata etc. would trigger a redownload for me either.

I'd also been following these similar "paid content" issues hoping for a fix but they'd always get closed/resolved for the individual that opened it, so I figured the problem was with on my end.  

Eventually gave up and ended up using a combination of jdownloader, IDM, and a browser extension to manually redownload everything from the purchased tab. Took a long time, the filenames/dates are jacked up, but at least I have em & now I back up my paid directories.

**Comment by Sasquatch00** [comment]
@aizenn1 I am having the same issue as you are. It seems like the scraper is having an issue with larger video files, as most of the time it freezes when up against a download over 200MB. It then says it completed but the progress bar shows that it did not complete. I'm trying to scrape a profile that has 5 remaining posts to download with 1.2GB of data, and It will show completed after 100MB-200MB downloaded on average. I will restart the same profile scrape and it shows the same 5 remaining posts and 1.2GB.

**Comment by JohnnyTowns94** [comment]
It's appears it is only downloading content from current subscriptions. The scraper would usually download all paid content regardless.

**Comment by DIGITALCRIMINALS** [comment]
The only way I can fix this is to use someone's auth.json details.

**Comment by artyom2035** [comment]
> The only way I can fix this is to use someone's auth.json details.

@digitalcriminals You can have mine. How do I get it to you?

**Comment by DIGITALCRIMINALS** [comment]
> > The only way I can fix this is to use someone's auth.json details.
> 
> @digitalcriminals You can have mine. How do I get it to you?
> 

My email is on my main account @digitalcriminal

**Comment by artyom2035** [comment]
Sent it your way

**Comment by ashby-lat** [comment]
Hey there, sorry, was out of town. Tested the changes [here](https://github.com/DIGITALCRIMINALS/OnlyFans/issues/353#issuecomment-1045632102) but that had no impact. Still experiencing the same issue—an identical subset of content is being scraped every time. Lmk if y'all need anything more from me

**Comment by DIGITALCRIMINALS** [comment]
I'll be pushing the fix within 24hrs

**Comment by DIGITALCRIMINALS** [comment]
@artyom2035 Thanks for helping, the fix has been pushed.

https://github.com/DIGITALCRIMINALS/OnlyFans/commit/a922b75a0d78fbc946accf0f7e9efd6204a91db9
