### ISSUE TITLE
can't find .profiles/default/auth.json

### ISSUE THREAD

**Issue by diffracteD** [DIGITALCRIMINALS/OnlyFans#356]
Hi,
I installed pip3 install poetry.
Once it finished successfully, I ran poetry install which failed.
Furthermore, can't find .profiles/default/auth.json.
Please help.
Thanks.

**Comment by browntown-13** [comment]
you need to navigate to the onlyfans-master folder in terminal/powershell  (using command cd) before you run poetry install.

.profiles/default/auth.json won't be created until the first time you successfully run the program, after which point it will be created as a hidden folder.

**Comment by diffracteD** [comment]
I installed poetry using: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3

I went to Downloads>onlyfans-master. When I run poetry install I get this error:Abhiseks-MacBook-Air:OnlyFans-master ```
user$ ls
Dockerfile       classes          extras           requirements.txt
LICENSE          database         get-pip.py       start_ofd.py
README.md        datascraper      helpers          tests
apis             examples         modules          updater.py
user$ poetry install

  RuntimeError

  Poetry could not find a pyproject.toml file in /Users/user/Downloads/OnlyFans-master or its parents

  at ~/.poetry/lib/poetry/_vendor/py3.8/poetry/core/factory.py:369 in locate
      365│             if poetry_file.exists():
      366│                 return poetry_file
      367│ 
      368│         else:
    → 369│             raise RuntimeError(
      370│                 "Poetry could not find a pyproject.toml file in {} or its parents".format(
      371│                     cwd
      372│                 )
      373│             )
user$
``` 
Am I doing something wrong here?
Please advise. Thanks

**Comment by browntown-13** [comment]
I don't know man, I'm a beginner too. You'll have to wait for someone more knowledgeable lol. Sorry :P

**Comment by SausagesForMe** [comment]
I have no idea about all this poetry stuff BUT the .settings .sites & .profiles folders are, to my understanding, hidden by default.  In Windows 10 you can view hidden files using the "View" Tab on the top of the file explorer windows, in the "Show/hide" section click the box on the left of "hidden items" the "." folders should now be visible, you can unhide them by right clicking then -Properties => Attributes => Uncheck the hidden attribute.  Hopefully that was helpful, sorry I can't help with the other stuff.

**Comment by diffracteD** [comment]
I'm using mac. I do not see any .profile in my home directory. I though installation of poetry will create it. Not sure if I'm doing anything wrong. Poetry wants some file to run as I posted above.

**Comment by browntown-13** [comment]
poetry does not make the hidden folders. Running start_ofd.py for the first time creates them.

**Comment by DIGITALCRIMINALS** [comment]
You inputted "belledelphine" when it's not even in the list of names. Enter 1 instead.
