### ISSUE TITLE
There's nothing to scrape

### ISSUE THREAD

**Issue by rougeguy** [DIGITALCRIMINALS/OnlyFans#358]
Hello,
im a bit lost on how to add certain models to scrape from.
Do i have to subscribe to them on the website? (which wouldnt make sense bc thats the whole point of this)

best regards

**Comment by JohnnyTowns94** [comment]
Yes you have to be subscribed to a model. The whole point of this is to scrape content from models you are subscribed to.

**Comment by DIGITALCRIMINALS** [comment]
Cringe
