### ISSUE TITLE
traceback error for fansly 

### ISSUE THREAD

**Issue by slubinga** [DIGITALCRIMINALS/OnlyFans#362]
ive been getting this while trying to download fansly content 

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145BA0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145630>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145810>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B1459F0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145BD0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145660>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145840>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145A20>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145C00>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145690>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145870>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145A50>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145C30>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B1456C0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B1458A0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145C60>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145510>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B1456F0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B1176A0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145AB0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145720>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145900>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145AE0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145390>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145570>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145750>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145B10>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B1453C0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B1455A0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145780>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145960>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145B40>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B1457B0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145990>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145B70>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B145600>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F71B1457E0>
Traceback (most recent call last):
  File "D:\Downloads\House of Ballons\Wicked Games\fansly\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\samue\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\samue\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\Downloads\House of Ballons\Wicked Games\fansly\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "D:\Downloads\House of Ballons\Wicked Games\fansly\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 129, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "D:\Downloads\House of Ballons\Wicked Games\fansly\OnlyFans-7.6.1\modules\fansly.py", line 106, in account_setup
    subscriptions += await manage_subscriptions(
  File "D:\Downloads\House of Ballons\Wicked Games\fansly\OnlyFans-7.6.1\modules\fansly.py", line 1264, in manage_subscriptions
    results2 = await authed.get_subscriptions(identifiers=identifiers, refresh=refresh)
  File "D:\Downloads\House of Ballons\Wicked Games\fansly\OnlyFans-7.6.1\apis\fansly\classes\create_auth.py", line 310, in get_subscriptions
    results += await asyncio.gather(*tasks)
  File "D:\Downloads\House of Ballons\Wicked Games\fansly\OnlyFans-7.6.1\apis\fansly\classes\create_auth.py", line 300, in multi
    valid_subscriptions.following
AttributeError: 'error_details' object has no attribute 'following'

**Comment by DIGITALCRIMINALS** [comment]
Use the latest commit.
