### ISSUE TITLE
ModuleNotFoundError: No module named 'extras.OFRenamer'

### ISSUE THREAD

**Issue by ddescham74** [DIGITALCRIMINALS/OnlyFans#363]
The title says it all.
When I use the script I have this errors:
`Traceback (most recent call last):`
`  File "/home/dimitri/Bureau/OnlyFans-7.6.1/start_ofd.py", line 66, in <module>
    asyncio.run(main())`
`  File "/home/dimitri/.pyenv/versions/3.10.1/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)`
`  File "/home/dimitri/.pyenv/versions/3.10.1/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()`
`  File "/home/dimitri/Bureau/OnlyFans-7.6.1/start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)`
`  File "/home/dimitri/Bureau/OnlyFans-7.6.1/datascraper/main_datascraper.py", line 129, in start_datascraper
    await default(datascraper)`
`  File "/home/dimitri/Bureau/OnlyFans-7.6.1/datascraper/main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)`
`  File "/home/dimitri/Bureau/OnlyFans-7.6.1/helpers/main_helper.py", line 1044, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)  # type: ignore`
`  File "/home/dimitri/Bureau/OnlyFans-7.6.1/modules/module_streamliner.py", line 80, in start_datascraper
    await self.prepare_scraper(subscription, key)`
`  File "/home/dimitri/Bureau/OnlyFans-7.6.1/modules/module_streamliner.py", line 249, in prepare_scraper
    await self.process_scraped_content(master_set, content_type, subscription)`
`  File "/home/dimitri/Bureau/OnlyFans-7.6.1/modules/module_streamliner.py", line 296, in process_scraped_content
    await process_metadata(`
`  File "/home/dimitri/Bureau/OnlyFans-7.6.1/classes/prepare_metadata.py", line 630, in process_metadata
    import extras.OFRenamer.start_ofr as ofrenamer`
`ModuleNotFoundError: No module named 'extras.OFRenamer'`

**Comment by DIGITALCRIMINALS** [comment]
How are you running the script? Double clicking or using cmd?

**Comment by ddescham74** [comment]
Using cmd

**Comment by DIGITALCRIMINALS** [comment]
Try `poetry run python ./start_ofd.py`

**Comment by ddescham74** [comment]
Oh! Apparently that works just fine! Thanks for the help!
