### ISSUE TITLE
No module named 'yarl'

### ISSUE THREAD

**Issue by jimmothy-beep** [DIGITALCRIMINALS/OnlyFans#364]
Hi all, im having an issue running the scraper ive re-ran `poetry install` and confirmed that its installed correctly when I run `poetry run python3.10 ./start_ofd.py` I get the following error;

`The currently activated Python version 3.9.0 is not supported by the project (^3.10.1).
Trying to find and use a compatible version. 
Using python3 (3.10.2)
Traceback (most recent call last):
  File "/Users/jn/Downloads/OnlyFans-master/./start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "/Users/jn/Downloads/OnlyFans-master/helpers/main_helper.py", line 21, in <module>
    import classes.make_settings as make_settings
  File "/Users/jn/Downloads/OnlyFans-master/classes/make_settings.py", line 6, in <module>
    from yarl import URL
ModuleNotFoundError: No module named 'yarl'
`

**Comment by axelrafn** [comment]
You'll need to install yarl with: 
`pip install yarl`

**Comment by Animal6311** [comment]
Same problem :( I did the "pip install yarl" but more and more no module error came up. Any other solutions?

**Comment by axelrafn** [comment]
I was testing this earlier today after I came upon this thread, got into the same issue.
What I did was I deactivated the venv I was in and activated it again, then ran poetry install again.
That seemed to fix all dependencies I came across.

**Comment by DIGITALCRIMINALS** [comment]
You need to make sure poetry is install requirements for 3.10 (venv?) and not 3.9

**Comment by jimmothy-beep** [comment]
sorry.. venv?

**Comment by axelrafn** [comment]
> sorry.. venv?

Yes, the virtual environment you create in python to run the script.

**Comment by jimmothy-beep** [comment]
So after deleting everything including python and reinstalling its now saying no module named orjson.

Only issue is I can see that it installed when I ran poetry install? Any ideas for that one

**Comment by axelrafn** [comment]
> So after deleting everything including python and reinstalling its now saying no module named orjson.
> 
> 
> 
> Only issue is I can see that it installed when I ran poetry install? Any ideas for that one

Did you run poetry install within the venv? If not, do that.

**Comment by Animal6311** [comment]
I've literally tried everything that's been mentioned and even tried on another pc but I still get the same problem :( I managed to create a venv and activate it but I couldn't get poetry to install in it. I'm probably doing something wrong.

**Comment by Animal6311** [comment]
Does anyone know anything else I could do?

**Comment by axelrafn** [comment]
First of all, what OS are you using?

**Comment by Animal6311** [comment]
Windows 11 and it has worked on here before.

**Comment by DIGITALCRIMINALS** [comment]
You need to do pip install poetry

**Comment by rafaelsousa221** [comment]
yes, i already did pip install poetry

**Comment by Animal6311** [comment]
Anyone know a fix yet?

**Comment by M00N-dev** [comment]
> Anyone know a fix yet? I keep getting this: ModuleNotFoundError: No module named 'dateutil'

pip install python-dateutil

**Comment by yermumz** [comment]
Instead of using 'pip install dateutil', use 'pip install python-dateutil'

From there on just install all the missing modules and you'll get it working.

**Comment by Animal6311** [comment]
> pip install python-dateutil

Thanks soo much! You've just solved my problem and everything is working now Finally :) Thank you

**Comment by jimmothy-beep** [comment]
Im still getting the same error
