### ISSUE TITLE
Takes forever, then stops

### ISSUE THREAD

**Issue by LFS900** [DIGITALCRIMINALS/OnlyFans#367]
So I've been trying to scrape content but for the last... 2 weeks it's been going really slow. Now in the past week, I select onlyfans (0), then default (1). I select the model and it just gets stuck at "Scrape Attempt: 1/100". I've been waiting for an hour now. It's not gonna happen. I Redownloaded the zip file, unpacked it, filled in the same info but the issue isn't gone. When it does continue and sometimes it does, it gets stuck at "Type: Messages". I've been waiting another 2 hours now for that to move.

**Comment by DIGITALCRIMINALS** [comment]
Which model

**Comment by LFS900** [comment]
Any I choose. If I choose "all", I have to correct myself. It takes extremely long and gets stuck at "Scraping Paid Content" for 10 minutes or even longer. However, it does work eventually. But if I choose any girl, it does not get passed "Type: Messages" even after an hour.

**Comment by DIGITALCRIMINALS** [comment]
Which model

**Comment by LFS900** [comment]
All of them but to give an example... Selti

**Comment by DIGITALCRIMINALS** [comment]
How many cores does your CPU have

**Comment by LFS900** [comment]
4

**Comment by DIGITALCRIMINALS** [comment]
Hmm is this for OnlyFans or Fansly?

**Comment by DIGITALCRIMINALS** [comment]
If you've got a lot of subscriptions, it could take awhile to grab all of them

**Comment by LFS900** [comment]
I only have about 9 atm. But I've had many in the past. Does it remember those when it scrapes for content or does it only depend on the active subscriptions? I've had 21 at once in the past and it worked way faster back then.

**Comment by DIGITALCRIMINALS** [comment]
Only depends on active.

It's not normal to take forever on 9, but only if you've got hundreds...

Maybe it's your Internet? You can try putting max_threads to 1 in the config settings.

**Comment by LFS900** [comment]
What does that actually do? I tried it but it didn't change much. It might just be my internet then. Though nothing has changed in the past years. I'm using "ALL" lately since that's the only thing that still works... but I've noticed before it doesn't always scrap everything. I'll keep an eye on how true that is and if it's too severe, I might contact you again! Thanks for the help!
