### ISSUE TITLE
Finished processing metadata. INFO  [alembic.runtime.migration] Context impl SQLiteImpl. 

### ISSUE THREAD

**Issue by ghost** [DIGITALCRIMINALS/OnlyFans#37]
I get the following warnings even after re-installing:

Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 5493253cc03c, content

It's the same for some posts, etc. This is an example of what the progress bar says: 

9/9 [00:00<00:00, 542.11it/s]

**Comment by wmorales1** [comment]
I should also add that 4-5 days ago it was working perfectly, but now I get this. Nothing has changed in my subscriptions.

**Comment by OFfriend** [comment]
that's normal if the database model changed
