### ISSUE TITLE
Profile choice not working and stuck only downloading the avatars and headers (OnlyFans)

### ISSUE THREAD

**Issue by username4482** [DIGITALCRIMINALS/OnlyFans#377]
Was working fine, then I started getting an access denied response so I deleted and reinstalled with updated profile information. Now, when I attempt to scrape I'll select a profile and it will force itself on to a profile that's not even in the list of profiles I'm subscribed to. (a profile I used to sub to). So blocked that profile that kept overriding my choices for it to only be replaced by another. So I just worked my way through until I got on the profile I initially was intending to rip and realized, even though I selected all content, it would only rip the avatars and headers on each profile.
![1](https://user-images.githubusercontent.com/101299707/157561817-2e9279d4-64ee-4321-a6a9-6ea870ef117d.PNG)
![2](https://user-images.githubusercontent.com/101299707/157561819-19ec8e01-6d38-47ac-9540-fbd4de3306a0.PNG)
![3](https://user-images.githubusercontent.com/101299707/157561820-c5b98b5c-4ff0-4fc7-ab4f-04b676ebdf4d.PNG)

Messages is empty, only the profile avatar and header are scraped. I've reinstalled more than a few times, making sure I properly inserted my account information through Chrome. If you could help me out, it'd be much appreciated. Thanks :)

**Comment by slickgslickg** [comment]
Same here- I think this is the same issue as: https://github.com/DIGITALCRIMINALS/OnlyFans/issues/380

**Comment by jerryhard** [comment]
Same for me

**Comment by DIGITALCRIMINALS** [comment]
https://github.com/DIGITALCRIMINALS/OnlyFans#jobs

If you only want subscriptions, then set up your jobs correctly.
