### ISSUE TITLE
Model selection scrapes wrong model

### ISSUE THREAD

**Issue by melbandera** [DIGITALCRIMINALS/OnlyFans#378]
Hi hi. I just pulled from the repo and now when I try to scrape content from a particular model (model1) scraper instead attempts to scrape content from model2, who I no longer sub to. i did `find . -type f -print | xargs grep "[model2]"` and found a file, which I deleted. However, this did not impact the behavior of the scraper. Any ideas what's going on?

**Comment by ashby-lat** [comment]
Should add I get the basics but am not great at the CLI—I tried another command `grep -rnw  -e '[model2]'` and am getting no results other than files synced from my Google Drive instance.

**Comment by username4482** [comment]
Ah, same thing is happening to me.

**Comment by ashby-lat** [comment]
Well, it does, I guess...it's a model I'm not subbing to but it's creating the folder structure and grabbing the avatar etc.

**Comment by ashby-lat** [comment]
Very odd. If I block the model on my expired subscriptions pages, that will change `model2` to a different model, one I may or may not be subscribed to.

**Comment by ashby-lat** [comment]
I let it cycle through all the subscriptions it suggested I scrape instead of the target model. It eventually suggested model1 but didn't download anything beyond metadata, profile/avatar, etc.

**Comment by ashby-lat** [comment]
👋 checking to see if I should be monitoring a different thread or if I need to provide more information.

**Comment by DIGITALCRIMINALS** [comment]
The missing PPVs should be fixed by now
