### ISSUE TITLE
Marked as 'Scrape Complete', nothing downloaded/no folders created

### ISSUE THREAD

**Issue by sideloading** [DIGITALCRIMINALS/OnlyFans#380]
Hi, using the latest commit e6afe4d, via poetry installation (Python 3.10.1).

After choosing model, and selecting Choose Medias: 0, it starts and finishes the scrape but nothing has been downloaded, then goes to the next(?) model instead.

Not sure if there is any verbose I can enable to help with this. Metadata location in config.json is as default

Running via `poetry run python ./start_ofd.py`

```
$ poetry run python ./start_ofd.py
Choose Profiles: 0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Welcome sideloading | u<>
Choose Subscriptions: 0 = All | ... | 10 = model
10
Scraping Paid Content
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0 (even 1, 2 doesn't scrape?)
Type: Messages
Processing Scraped Messages
100%|███████████████████████████████████████████████████████████████████████████████████████| 143/143 [00:00<00:00, 4133.54it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|███████████████████████████████████████████████████████████████████████████████████████| 112/112 [00:00<00:00, 1015.90it/s]
Scrape Completed
Scrape Processing
Name: <model number 8>
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
```

**Comment by sideloading** [comment]
Filename format is `"filename_format": "{date} {text} id{media_id}.{ext}",`

**Comment by DIGITALCRIMINALS** [comment]
Maybe latest commit fixes it.

**Comment by sideloading** [comment]
Thank you @DIGITALCRIMINALS  :) working now!

**Comment by DIGITALCRIMINALS** [comment]
Try this filename `{filename}.{ext}`

**Comment by sideloading** [comment]
Hi @DIGITALCRIMINALS, tested with `{filename}.{ext}` and still it marks as scrape completed, then goes to the next model

**Comment by slickgslickg** [comment]
Hello - I am also having the same problem, and tried {filename}.{ext}. Any ideas would be much appreciated!

**Comment by slickgslickg** [comment]
@sideloading have you managed to fix this? I am still getting the error.

**Comment by username4482** [comment]
Yeah, i'm interested as well. Same issue. :(

**Comment by sideloading** [comment]
@slickgslickg No I haven't. And @DIGITALCRIMINALS seems to be MIA so hope they're OK 😫

**Comment by hawktank** [comment]
Yeah still getting this issue too.

**Comment by Bun-Bun** [comment]
I am also experiencing this issue. Scrape finds media but doesn't download anything except for the profile pictures. No errors displayed even with the script invoked with -v.

Python 3.10.3

**Comment by spoobles** [comment]
I've got the same problem. On Win 10, python 3.10, master at the latest branch and updated python modules. I run the script, fill in the json and run the scrape.

I get a list of my subscribed accounts, and select one, then select what to scrape.

The .sites\OnlyFans\account\Metadata\user_data.db file is created, and the download folder for the account is too, with subfolders. The only thing that actually downloads are the profile pics. Once it says the scrape is completed, it prompts to start a scrape of the last account in my sub list.


On Win 10, python 3.10, master at the latest branch and updated python modules. I run the script, fill in the json and run the scrape.

I get a list of my subscribed accounts, and select one, then select what to scrape.

The .sites\OnlyFans\one\Metadata\user_data.db file is created, and the download folder for the account is too, with subfolders. The only thing that actually downloads are the profile pics. Once it says the scrape is completed, it prompts to start a scrape of the last account in my sub list.

Welcome User | username
Choose Subscriptions: 0 = All | 1 = one | 2 = two | 3 = three | 4 = four | 5 = five | 6 = six | 7 = seven | 8 = eight | 9 = nine
3
Scraping Subscriptions
Scrape Processing
Name: three
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
100%|████████████████████████████████████████████████████████████████████| 740k/740k [00:00<00:00, 1.25MB/s]
Type: Stories
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Scrape Attempt: 1/100
Processing Scraped Posts
100%|████████████████████████████████████████████████████████████████| 521/521 [00:00<00:00, 1356.77it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|█████████████████████████████████████████████████████████████████████| 521/521 [00:00<00:00, 763.93it/s]
Type: Archived
Type: Chats
Type: Messages
Processing Scraped Messages
100%|██████████████████████████████████████████████████████████████| 4/4 [00:00<?, ?it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|███████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 500.87it/s]
Type: Highlights
Type: MassMessages
Scrape Completed

Scraping Message Content
Scrape Processing
Name: nine
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts

**Comment by simonrule** [comment]
me too im having same issue today
