### ISSUE TITLE
[Feature Request] Post Proccess Un-Subbed Accounts

### ISSUE THREAD

**Issue by HistoricTheater** [DIGITALCRIMINALS/OnlyFans#387]
Use Case: I changed my "file_directory_format" and the renamer only works on active subs its pulling down. If there was a way to process old rips that are no longer actively subscribed too,but are in the .sites folder, to be included in the scan or a separate scan that can be called with a switch to tell the program to restructure all folders in .sites to the config setting

**Comment by A-Random-Mf** [comment]
This would be an extremely useful feature

**Comment by DIGITALCRIMINALS** [comment]
https://github.com/DIGITALCRIMINALS/UltimaScraperRenamer

It's not complete or optimised and it'll only go through Posts.

It'll create a __settings__ folder with config.json inside.
Just point ultima_scraper_directory key to the scraper root directory
