### ISSUE TITLE
FileNotFoundError relating to __legacy_metadata__ folder

### ISSUE THREAD

**Issue by A-Random-Mf** [DIGITALCRIMINALS/OnlyFans#388]
Issue: Im running the latest commit. The script finishes the Scraping Subscriptions phase and begins the Scraping Message Content. It processes through a few models and then throws the following error on processing model 1. Model 1 is an existing free account im no longer subbed to.  I have not blacklisted, blocked or restricted the model.

Error: https://pastebin.com/YbVSDd1i

**Comment by avekifes** [comment]
I think I have the same issue. Blacklisting the model doesn't seem to be a workaround.

**Comment by tintinhamans** [comment]
I am also experiencing this issue running through the provided Dockerfile which I presume is the validated setup.

**Comment by xantror** [comment]
I am also experiencing this issue running through the provided Dockerfile (022b6a8) which I presume is the validated setup.

**Comment by xantror** [comment]
If I manually create the folder `Metadata/__legacy_metadata__` and move all files in `Metadata` into this new folder, it seems to proceed. Going to use this workaround for now, I'm sure there's already a fix on the way 🙂

**Comment by DIGITALCRIMINALS** [comment]
I don't know if I fixed this, but feel free to reopen
