### ISSUE TITLE
missing content from fansly scrape

### ISSUE THREAD

**Issue by soadwipe** [DIGITALCRIMINALS/OnlyFans#389]
after multiple scrapes of the same model I've come to realize that some of the content from their post are not being scraper.

**Comment by YESANDNOTHENYESAGAIN** [comment]
try going to -> .settings -> config.json 

Then go to the settings and change: 



            "posts": true,
            "comments": true

**Comment by DIGITALCRIMINALS** [comment]
Probably fixed by now
