### ISSUE TITLE
Unable to create auth.json and config.json by running start_ofd

### ISSUE THREAD

**Issue by hjforg** [DIGITALCRIMINALS/OnlyFans#39]
Receiving this error when I run start_ofd.  I've already done a fresh install of Python 3.10 and VS as well as new extract of the OF7.5 folder. I was able install requirements.txt and update PIP through powershell.

> Traceback (most recent call last):
>   File "Y:\OnlyFans-7.5\start_ofd.py", line 12, in <module>
>     main_test.check_config()
>   File "Y:\OnlyFans-7.5\tests\main_test.py", line 21, in check_config
>     import helpers.main_helper as main_helper
>   File "Y:\OnlyFans-7.5\helpers\main_helper.py", line 2, in <module>
>     from apis import api_helper
>   File "Y:\OnlyFans-7.5\apis\api_helper.py", line 30, in <module>
>     from aiohttp_socks import ProxyConnectionError, ProxyConnector, ProxyError
> ModuleNotFoundError: No module named 'aiohttp_socks'

Also if I try to re-run the powershell command to reinstall requirements.txt I now receive these errors.

> ERROR: Command errored out with exit status 1:
> command: 'C:\Users\xxxx\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\pip-install-akmwbwee\\psutil_c9fcac39155047dca3c19650cb10de28\\setup.py'"'"'; __file__='"'"'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\pip-install-akmwbwee\\psutil_c9fcac39155047dca3c19650cb10de28\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\xxxxx\AppData\Local\Temp\pip-record-4k30b9nr\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\xxxxx\AppData\Local\Programs\Python\Python310\Include\psutil'
> cwd: C:\Users\xxxxxx\AppData\Local\Temp\pip-install-akmwbwee\psutil_c9fcac39155047dca3c19650cb10de28\
> Complete output (38 lines):
> running install
> running build
> running build_py
> creating build
> creating build\lib.win-amd64-3.10
> creating build\lib.win-amd64-3.10\psutil
> copying psutil\_common.py -> build\lib.win-amd64-3.10\psutil
> copying psutil\_compat.py -> build\lib.win-amd64-3.10\psutil
> copying psutil\_psaix.py -> build\lib.win-amd64-3.10\psutil
> copying psutil\_psbsd.py -> build\lib.win-amd64-3.10\psutil
> copying psutil\_pslinux.py -> build\lib.win-amd64-3.10\psutil
> copying psutil\_psosx.py -> build\lib.win-amd64-3.10\psutil
> copying psutil\_psposix.py -> build\lib.win-amd64-3.10\psutil
> copying psutil\_pssunos.py -> build\lib.win-amd64-3.10\psutil
> copying psutil\_pswindows.py -> build\lib.win-amd64-3.10\psutil
> copying psutil\__init__.py -> build\lib.win-amd64-3.10\psutil
> creating build\lib.win-amd64-3.10\psutil\tests
> copying psutil\tests\runner.py -> build\lib.win-amd64-3.10\psutil\tests
> copying psutil\tests\test_aix.py -> build\lib.win-amd64-3.10\psutil\tests
> copying psutil\tests\test_bsd.py -> build\lib.win-amd64-3.10\psutil\tests
> copying psutil\tests\test_connections.py -> build\lib.win-amd64-3.10\psutil\tests
> copying psutil\tests\test_contracts.py -> build\lib.win-amd64-3.10\psutil\tests
> copying psutil\tests\test_linux.py -> build\lib.win-amd64-3.10\psutil\tests
> copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-3.10\psutil\tests
> copying psutil\tests\test_misc.py -> build\lib.win-amd64-3.10\psutil\tests
> copying psutil\tests\test_osx.py -> build\lib.win-amd64-3.10\psutil\tests
> copying psutil\tests\test_posix.py -> build\lib.win-amd64-3.10\psutil\tests
> copying psutil\tests\test_process.py -> build\lib.win-amd64-3.10\psutil\tests
> copying psutil\tests\test_sunos.py -> build\lib.win-amd64-3.10\psutil\tests
> copying psutil\tests\test_system.py -> build\lib.win-amd64-3.10\psutil\tests
> copying psutil\tests\test_testutils.py -> build\lib.win-amd64-3.10\psutil\tests
> copying psutil\tests\test_unicode.py -> build\lib.win-amd64-3.10\psutil\tests
> copying psutil\tests\test_windows.py -> build\lib.win-amd64-3.10\psutil\tests
> copying psutil\tests\__init__.py -> build\lib.win-amd64-3.10\psutil\tests
> copying psutil\tests\__main__.py -> build\lib.win-amd64-3.10\psutil\tests
> running build_ext
> building 'psutil._psutil_windows' extension
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
> ----------------------------------------
> ERROR: Command errored out with exit status 1: 'C:\Users\xxxx\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xxxxx\\AppData\\Local\\Temp\\pip-install-akmwbwee\\psutil_c9fcac39155047dca3c19650cb10de28\\setup.py'"'"'; __file__='"'"'C:\\Users\\xxxxxxxx\\AppData\\Local\\Temp\\pip-install-akmwbwee\\psutil_c9fcac39155047dca3c19650cb10de28\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\xxxxxx\AppData\Local\Temp\pip-record-4k30b9nr\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\Include\psutil' Check the logs for full command output. 

I tried to reinstall the VS Build Tools and try again but it results in the same error.

**Comment by leofera257** [comment]
Same here

**Comment by OFfriend** [comment]
check #43

**Comment by wmorales1** [comment]
Version 7.5.1 is unable to create the files for me in linux Pop_OS, but version 7.5 works fine. The problem is not in the setup since I used the same to try both versions. 7.5.1 just sends " Execute the script with Python 3.10. Press enter to continue", and after pressing enter nothing happens but again, 7.5 works fine.
