### ISSUE TITLE
model selection scrapes all models 

### ISSUE THREAD

**Issue by yermumz** [DIGITALCRIMINALS/OnlyFans#390]
After selecting the model, the scraper started by scraping the selected model, then moved on to scrape all models

**Comment by MonkeyKingViper** [comment]
The tool has scraped all models to start for quite a while now. Just doesn't download them.

Personally I wish that wouldn't happen because I have one particular model that for some reason pauses the scraper for upwards of 10 minutes

**Comment by yermumz** [comment]
The previous version I used started by scraping all models for paid subscriptions but only scraped the selected model afterwards. The latest version starts by scraping the selected model, then proceeds to scrape paid subscriptions, followed by scraping all models twice, only to end up with stuck downloads. In fact, I did a couple of attempts and the downloads never got past the first model in the subscription list

**Comment by DarthPasma** [comment]
Mine start downloading all metadata since update the script triying to fix the non paid content downloads problem, but it just does that, doesn't download any content, even created a folder named onlyfans with metadata

**Comment by yermumz** [comment]
If it isn't downloading, try to install the modules from the old requirements.txt

**Comment by DarthPasma** [comment]
> If it isn't downloading, try to install the modules from the old requirements.txt

I did, the script start, but when i select any mode, ask for the media type and it just start the scrapping process, then proceed to the next model for some reason, and then stop and ask again for the type of media

**Comment by yermumz** [comment]
Look for older commits before commit #551132b and the zip

**Comment by wobbleninja** [comment]
As I wrote here https://github.com/DIGITALCRIMINALS/OnlyFans/issues/397#issuecomment-1079346378 try this.

>_Temporarily for a solution until we get an official fix, edit your config.json under .settings folder and change it so it won't scrape messages (from true to false). It'll still scrape messages, nevertheless._

**Comment by yermumz** [comment]
It seems like if scraping messages is set to true, the scraper scrapes messages from all models after scraping the selected models. Temporary fix is as mentioned by @wobbleninja by disabling scraping messages in config.json
