### ISSUE TITLE
Blacklist not working

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINALS/OnlyFans#391]
Am I the only one who's finding that the blacklist feature isn't working? Maybe it's only affecting certain models, but I have one model on multiple blacklists and the ripper is still trying to process the account.

**Comment by fl4shbook** [comment]
I'm under the impression that changes introduced by commit [ae02a77](https://github.com/DIGITALCRIMINALS/OnlyFans/commit/ae02a773b009cf31ae874d4af57e4b136122002e) are bypassing the blacklists.

Could you check if that's the case for you ?

**Comment by avekifes** [comment]
Sorry, I'm clueless with this kind of stuff. How would I roll back just this commit?

**Comment by DIGITALCRIMINALS** [comment]
Fixed blacklists

https://github.com/DIGITALCRIMINALS/OnlyFans/commit/2e6afe408bb8303dd9d42f8f59c7319542228e5b
