### ISSUE TITLE
unknown error with new version

### ISSUE THREAD

**Issue by dballs6666** [DIGITALCRIMINALS/OnlyFans#392]
i am getting this error

Traceback (most recent call last):
  File "G:\User\OnlyFans-master\start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "G:\User\OnlyFans-master\helpers\main_helper.py", line 23, in <module>
    import orjson
ModuleNotFoundError: No module named 'orjson'

**Comment by xantror** [comment]
Did you already install all the needed dependencies? Don't know which version you are coming from but sometime last month `requirements.txt` was removed.

`pip install poetry
poetry install`

**Comment by mediaburnwayne** [comment]
I have the same issue. Ran pip install poetry  
poetry install and poetry update. still get error

**Comment by mediaburnwayne** [comment]
Problem resolved 

pip install orjson

**Comment by MonkeyKingViper** [comment]
I had to do this too. Wonder why it isn't in the poetry file? That might not be the proper description but it works
