### ISSUE TITLE
Also issue with temp_json_auth["auth"] - OF

### ISSUE THREAD

**Issue by clouds123xxx** [DIGITALCRIMINALS/OnlyFans#399]
I have the same issue as https://github.com/DIGITALCRIMINALS/OnlyFans/issues/324

I am also on MacOS, i did what was suggested there. The line number was different, but I found it and changed, the difference was that it tries to login 10 times before crashing, unlike before that it crashed immediately after choosing OF.   

In helpers/main_helper.py, find the function remove_mandatory_files (starts at line 1181 in current version). In that function, change the line (1183) from:

folders = [x for x in files if x not in matches]

to:

folders = [x for x in files if x.name not in matches]

**Comment by d3ibis** [comment]
I wrote the issue u mentioned, now just updated the script and had the same issue!

opened main_helper.py using atom and change the line (1195)

From:
folders = [x for x in files if x not in matches]
To:
folders = [x for x in files if x.name not in matches]

and now working normally, showed all my subscriptions.

**Comment by DIGITALCRIMINALS** [comment]
This was an issue to do with special files, like .DS_STORE

it's been fixed now

https://github.com/DIGITALCRIMINALS/UltimaScraperAPI/commit/08fe70f39a472b0d98938fac6c877d913312da38
