### ISSUE TITLE
DOWNLOAD STOPPED ONLYFANS

### ISSUE THREAD

**Issue by nicolin123** [DIGITALCRIMINALS/OnlyFans#402]
i have 1 account with 1 suscription "narduchita" and when i download the model all is good but in the first 2.3 mb the download stops and freeze, my app is updated and i dont understand how to fix

**Comment by nicolin123** [comment]
i have this error when i run python -v start_ofd.py
ModuleNotFoundError: No module named 'helpers.main_helper'

**Comment by nicolin123** [comment]
I turned "reformat_media": to false in my settings.json and that appears to have fixed things for me!!!

**Comment by jerryhard** [comment]
> I turned "reformat_media": to false in my settings.json and that appears to have fixed things for me!!!

This don't help for me ... but my onlyfans only show that download something , but folder been empty

**Comment by emskia-bgp** [comment]
> I turned "reformat_media": to false in my settings.json and that appears to have fixed things for me!!!

This method also helped me a lot !

**Comment by Vardamir85** [comment]
> > I turned "reformat_media": to false in my settings.json and that appears to have fixed things for me!!!
> 
> This don't help for me ... but my onlyfans only show that download something , but folder been empty

Same here, but also when i select to download images only it try to download all and jump to other models also.
I tried with 10 diferent models and its always the same

**Comment by emskia-bgp** [comment]
That's why I am downloading everything. This is better than latest version, because it is only creating empty folders....

**Comment by michaelworthy96** [comment]
Open the "config.json" file in the ".settings" folder. Find "reformat_media": true and change it to false. That worked for me.
