### ISSUE TITLE
Why is it trying to scrape models that I'm not even subscribed to anymore?

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINALS/OnlyFans#403]
I can't scrape a thing right now because of this annoying legacy metadata error, and what's worse is that I'm not even subscribed to the account anymore.

> Scrape Processing
> Name: feliceherrig
> INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
> INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
> INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
> INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
> Traceback (most recent call last):
> File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 805, in move
> os.rename(src, real_dst)
> FileNotFoundError: [WinError 3] The system cannot find the path specified: 'X:\\OnlyFans\\OnlyFans\\feliceherrig\\Metadata\\Archived.db' - 'X:\\OnlyFans\\OnlyFans\\feliceherrig\\Metadata\\__legacy_metadata__\\Archived.db'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\username\Desktop\OnlyFans-master\start_ofd.py", line 66, in
> asyncio.run(main())
> File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
> return loop.run_until_complete(main)
> File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
> return future.result()
> File "C:\Users\username\Desktop\OnlyFans-master\start_ofd.py", line 52, in main
> api = await main_datascraper.start_datascraper(config, site_name)
> File "C:\Users\username\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 131, in start_datascraper
> await default(datascraper)
> File "C:\Users\username\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 101, in default
> await main_helper.process_jobs(datascraper, subscription_list, site_settings)
> File "C:\Users\username\Desktop\OnlyFans-master\helpers\main_helper.py", line 1055, in process_jobs
> await datascraper.start_datascraper(authed, username,whitelist=["Messages"])
> File "C:\Users\username\Desktop\OnlyFans-master\modules\module_streamliner.py", line 73, in start_datascraper
> await main_helper.fix_sqlite(api, subscription_directory_manager)
> File "C:\Users\username\Desktop\OnlyFans-master\helpers\main_helper.py", line 446, in fix_sqlite
> shutil.move(archived_database_path, f"{new_filepath}")
> File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 825, in move
> copy_function(src, real_dst)
> File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 434, in copy2
> copyfile(src, dst, follow_symlinks=follow_symlinks)
> File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 256, in copyfile
> with open(dst, 'wb') as fdst:
> FileNotFoundError: [Errno 2] No such file or directory: 'X:\\OnlyFans\\OnlyFans\\feliceherrig\\Metadata\\__legacy_metadata__\\Archived.db'
> 
> C:\Users\username\Desktop\OnlyFans-masterpause
> Press any key to continue . . .

**Comment by avekifes** [comment]
I think I was able to get around it by turning off the scraping of messages.

**Comment by RuneDemomn** [comment]
This is caused by new api options relating to messages. The script will loop around and try scraping posts from unsubscribed accounts if you received any messages form them in the past. For now it is best to disable scraping messages.

**Comment by ppsoong** [comment]
How do you disable message scraping? I don't see it in my settings.

I did notice that despite having 7.6.1, my settings still says:

```
{
  "info": {
    "version": 7.2
```

I've tried deleting the `config.json` but it creates another 7.2 version.

**Comment by ppsoong** [comment]
> How do you disable message scraping? I don't see it in my settings.
> 
> I did notice that despite having 7.6.1, my settings still says:
> 
> ```
> {
>   "info": {
>     "version": 7.2
> ```
> 
> I've tried deleting the `config.json` but it creates another 7.2 version.

Fixed this by running `updater.py` and then rerunning the script. Now I have version 8.0.
