### ISSUE TITLE
Missing content from OF

### ISSUE THREAD

**Issue by MonkeyKingViper** [DIGITALCRIMINALS/OnlyFans#404]
Background: I redid my naming scheme for downloaded media to better group content from models that upload multiple times per day. Post ID is a great point.

Issue: After removing all the media from a model (renamed the folder) and doing a fresh download, I noticed while auditing later that one particular model is missing 600ish photos and some videos. Specifically the page @maeurn1. Media tab says 3043 broken into 2686i/345v/3a. My folder right now is sitting at 2053i/285v/3a. Can confirm specific posts that did not download.

The model only does PPVs in messages. I'd been using the more recent 7.6 scraper up to today, and upgraded to the new 8.0 to see if that fixed anything. It did not.

**Comment by jerryhard** [comment]
same problem, all lok like work, but folder is empty, only subfolders

**Comment by MonkeyKingViper** [comment]
I'm at least getting downloads. I just have no idea how much content is actually missing. Through my audits I was finding that some are deleting a lot of their content, but also that things in messages are disappearing, as well as the oldest dated posts. That's all explainable. What isn't is posts that just simply didn't download

**Comment by ppsoong** [comment]
I'm also missing content. I bought a bundle of videos and none of them were downloaded. I double checked and have the scrapper set to download paid content.

**Comment by offf1989** [comment]
I've had a lot of issues with messages, paid and free, not coming down. @DIGITALCRIMINALS I'm happy to share my auth file if you'll tell me where to send it.

**Comment by DIGITALCRIMINALS** [comment]
> I've had a lot of issues with messages, paid and free, not coming down. @DIGITALCRIMINALS I'm happy to share my auth file if you'll tell me where to send it.

Send it to my email on @DIGITALCRIMINAL
