### ISSUE TITLE
OnlyFans Access Denied

### ISSUE THREAD

**Issue by jsinfate** [DIGITALCRIMINALS/OnlyFans#405]
Is anyone else getting access denied when trying to scrape OnlyFans?
I first ran the updater then ran the program and I get access denied. 
Adding screen shot.

![OF](https://user-images.githubusercontent.com/98183995/161117163-33140fcf-1cff-42e4-91a1-74d9a408dbca.jpg)

**Comment by Jarsky** [comment]
Same here, haven't been able to get it to work for over a week now. 
I also tried resetting my 2fa to generate a new x_bc key, but still the same

**Comment by MonkeyKingViper** [comment]
Make sure you're clearing cookies, getting a fresh session token, update your user agent, and copy the x_bc

**Comment by Jarsky** [comment]
> Make sure you're clearing cookies, getting a fresh session token, update your user agent, and copy the x_bc

Turned out I needed to delete the old docker image and pull a new one.

**Comment by jsinfate** [comment]
Finally got back in. I had to clear out my browser and found out it was giving me a CAPTCHA. Refreshed my cookie sess and x_bc and verified my useragent. 
Thank you guys!
