### ISSUE TITLE
cant start scraper....new computer

### ISSUE THREAD

**Issue by J4k-The-Reaper** [DIGITALCRIMINALS/OnlyFans#406]
i got a new desktop. still a noob at installing/using.....so i'm still trying to figure out how to properly install this. thing is....python 3.10 is installed with PATH. Poetry installed and updated. clicking start_ofd doesnt work. cant even setup profile/settings.
![Screenshot 2022-04-01 061627](https://user-images.githubusercontent.com/35021417/161271999-94147711-d9c5-41c1-b212-1a29978656fb.png)

**Comment by J4k-The-Reaper** [comment]
oh. i forgot to install build tools for visual studio. just did but still getting an error.
![Screenshot 2022-04-01 065118](https://user-images.githubusercontent.com/35021417/161277402-c3265704-046a-46e0-b4d3-594e0d8ce592.png)

**Comment by MonkeyKingViper** [comment]
try reinstalling the poetrylock? If not, do "pip install (name of the object it says doesn't exist)"

That worked for me the other day

**Comment by J4k-The-Reaper** [comment]
really? that will take forever! but okay. how do i reinstall poetrylock?

**Comment by yermumz** [comment]
Instead of using 'pip install dateutil', use 'pip install python-dateutil'
