### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by dickscheney** [DIGITALCRIMINALS/OnlyFans#407]
Still running into the Access Denied error. Have reviewed prior issues and tried everything that seemed to be a solution (browser agent, flush chrome cache/cookies/etc, x_bc) with the exception of deleting and re-installing python and the scraper scripts. So far nothing is working. Thoughts?

**Comment by TheMissingPort** [comment]
Same issue

**Comment by Rhysdabeast** [comment]
Maybe try using this https://github.com/M-rcus/OnlyFans-Cookie-Helper if you haven't already. This allows you to copy the values you need and paste them into the auth.json file.

**Comment by dickscheney** [comment]
> Maybe try using this https://github.com/M-rcus/OnlyFans-Cookie-Helper if you haven't already. This allows you to copy the values you need and paste them into the auth.json file.

Already have tried. Not a first-time user/installer. Just stopped functioning some time in the past week.

**Comment by TheMissingPort** [comment]
> > Maybe try using this https://github.com/M-rcus/OnlyFans-Cookie-Helper if you haven't already. This allows you to copy the values you need and paste them into the auth.json file.
> 
> Already have tried. Not a first-time user/installer. Just stopped functioning some time in the past week.

I got it working. Turned out I had to update my user agent. it slightly changed

**Comment by rjy7wb** [comment]
the x_bc changed, when you load the site look for the "init" request for all the info.

**Comment by dickscheney** [comment]
> the x_bc changed, when you load the site look for the "init" request for all the info.

did that. tried the user agent as well. still not working

**Comment by MonkeyKingViper** [comment]
It 100% is your auth file. No one can help you put the correct info in.

**Comment by neil-ui** [comment]
I had the same issue - I've been using this scraper for a while now without issues then it stopped working a few weeks back. I had to do several rounds of clearing Chrome cookies, updating auth.json, getting Access Denied, clearing Chrome cookies, updating auth.json, etc. then finally it just started working.
Sorry if this isn't the techincal solution you were after, but I was equally as frustrated as you that it stopped working but this worked for me.

**Comment by CarotMagic** [comment]
> > > Maybe try using this https://github.com/M-rcus/OnlyFans-Cookie-Helper if you haven't already. This allows you to copy the values you need and paste them into the auth.json file.
> > 
> > 
> > Already have tried. Not a first-time user/installer. Just stopped functioning some time in the past week.
> 
> I got it working. Turned out I had to update my user agent. it slightly changed

I just want to say this was the answer for me. Update your USER AGENT! If youre not sure, I just updated my browser (Chrome) and it generated a new User Agent. I also use OnlyFans Cookie Grabber as well and it was inputting an outdated User Agent.
