### ISSUE TITLE
7.6.1 having issues running

### ISSUE THREAD

**Issue by tobi-polar** [DIGITALCRIMINALS/OnlyFans#410]
I installed python 3.10.4, I did a fresh download of 7.6.1,I ran 'pip install poetry', 'poetry install'. I went to run the start_ofd.py and it instantly closes. I have used earlier versions of the tool. This version flat out refuses to work for me.

**Comment by xxtensazenxx** [comment]
Hello, It would be very helpful to the overall community to actually DETAIL what you did to fix said issue, for other who are having it.
