### ISSUE TITLE
Scraper is deleting files with similar file names

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINALS/OnlyFans#417]
I've been experimenting with Topaz Video AI, a program that's used to upscale videos into a higher resolution. The file names for the upscaled videos are identical to the source files aside from a differentiator at the end. So, something like:

Original file: [2020-08-22] 5f41ad0b7f81ffb3bcf42_source
Upscaled file: [2020-08-22] 5f41ad0b7f81ffb3bcf42_source_3840x2160_ghq-5

Here's where the weirdness starts. If both files are kept in the same directory and I run the scraper, one or the other file is deleted or renamed. With one model, the original file was deleted and replaced with the upscaled version, which the scraper renamed with the file name of the original. In another case, I think it was the upscaled file that was deleted.

And it gets crazier. In the second situation, I deleted the upscaled file and re-ran the scraper, hoping to get the original file back, but the scraper can't locate the video file anymore even though it still exists on the model's account.

**Comment by DIGITALCRIMINALS** [comment]
Anything that is located in the model's folder will be automatically sorted by the reformatter.
If you want the original file back, set overwrite_files to True

**Comment by avekifes** [comment]
I still don't get why the scraper would touch files that have a different file name. I'm also hesitant on enabling the overwrite_files function...if I set that to true, will the scraper delete files that were previously scraped but no longer exist on the model's account?

**Comment by MonkeyKingViper** [comment]
> I still don't get why the scraper would touch files that have a different file name. I'm also hesitant on enabling the overwrite_files function...if I set that to true, will the scraper delete files that were previously scraped but no longer exist on the model's account?

Very interested in this too. I wonder if that's why some downloads have been incomplete. I use {model_username} {date} {post_id} - {filename}.{ext} to try to make sure everything is unique, but if the scraper is doing something internally...idk. I'm a pleb, I just use the tool cause it works

**Comment by DIGITALCRIMINALS** [comment]
If the local file doesn't match the remote file's bytes, it will get overwritten, but if it does match it'll get skipped.
