### ISSUE TITLE
project still live? error when running start_ofd.py

### ISSUE THREAD

**Issue by chenks** [DIGITALCRIMINALS/OnlyFans#420]
is this project still live and working?

trying to run on windows 11. installed all the pre-requisites.
get an error

```
C:\of>python start_ofd.py
Traceback (most recent call last):
  File "C:\of\start_ofd.py", line 15, in <module>
    import tests.main_test as main_test
  File "C:\of\tests\main_test.py", line 58
    match string_match:
          ^
SyntaxError: invalid syntax
```

**Comment by V4n1X** [comment]
Check for Python 3.10

**Comment by Jarsky** [comment]
>     match string_match:
>           ^
> SyntaxError: invalid syntax
> ```

This would appear that you arent using Python 3.10. Make sure you're using this version and not an earlier version.
