### ISSUE TITLE
Paid Content Issue....only downloading stuff I've bought already

### ISSUE THREAD

**Issue by BrikBronson** [DIGITALCRIMINALS/OnlyFans#422]
Hey there, 

I'm under the assumption that if I'm subscribed to the model I can scrape all of her Paid content. The issue I'm having is it only downloads the paid content that I've paid for? I'm using Firefox and have updated the pyproject.toml file already. Anyone have an idea of how to fix this?

**Comment by megaabc1** [comment]
If by paid content you meant pay to unlock posts, i believe onlyfans doesn't serve the actual data to those who haven't paid for the post yet and there's a good chance nothing the devs can do about it

**Comment by Jarsky** [comment]
> 

You can only download content you've paid for. The scraper cannot scrape content that isn't available to you.

**Comment by MonkeyKingViper** [comment]
> Hey there,
> 
> I'm under the assumption that if I'm subscribed to the model I can scrape all of her Paid content. The issue I'm having is it only downloads the paid content that I've paid for? I'm using Firefox and have updated the pyproject.toml file already. Anyone have an idea of how to fix this?

Please read the FAQ on the main page...your question is addressed at the bottom
