### ISSUE TITLE
Fansly no longer scraping PPV previews

### ISSUE THREAD

**Issue by e2489** [DIGITALCRIMINALS/OnlyFans#426]
This works fine in the latest release (7.6.1), but purchased PPV content wasn't being scraped. I updated to the latest commit and now that works fine, but PPV previews (that haven't been purchased) are no longer being scraped.

**Comment by lordoffools** [comment]
Strangely, I wonder if this is related to the issue I'm facing: Fansly scrapes stop while scraping Messages, and then don't actually proceed with downloading what was pre-scraped.

Are you having that issue? Wondering if that deserves its own bug.
