### ISSUE TITLE
Scraper starts download then stops after one photo

### ISSUE THREAD

**Issue by HTFof** [DIGITALCRIMINALS/OnlyFans#427]
OS Name	Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044
Python 3.10.4

I dont get any error codes but after 1 or 2 pictures it just stops downloading. Ive let the scraper run for a few hours with no change. I have redownloaded the scraper multiple times thinking it was just an error on my end but no luck

`Download Processing
Name: aNAMEREMOVED| Type: Posts | Count: 3772 | Directory: .sites

  0%|▍                                                                            | 10.8M/2.18G [00:14<01:14, 29.1MB/s]`

**Comment by HTFof** [comment]
Using version 7.6.1

**Comment by ricguy91** [comment]
I'm having the same issue on the latest commit.  Oddly enough, it seems to only be happening on my Win 11 machine running under Parallels on a Mac Studio.  I wonder if it's some kind of a network glitch with parallels where it's dropping a packet or something and the download gets stuck.

**Comment by ricguy91** [comment]
Just confirmed that it doesn't happen on Win 10 running under parallels on an Intel Mac Mini.

**Comment by ricguy91** [comment]
interestingly, I spun up an ubuntu VM on the same Mac studio, and that version runs without issue.  very weird.

**Comment by michaelworthy96** [comment]
Open the "config.json" file in the ".settings" folder. Find "reformat_media": true and change it to false. That worked for me.

**Comment by lennier1** [comment]
I had the same issue on Windows 10. It's working much better after setting "reformat_media" to false, so thanks for that tip.
