### ISSUE TITLE
Windows Install / Python 3.10

### ISSUE THREAD

**Issue by OFfriend** [DIGITALCRIMINALS/OnlyFans#43]
I sent you here because you have the following Error: `ModuleNotFoundError: No module named 'sqlalchemy'` or `ModuleNotFoundError: No module named 'aiohttp_socks'`

Follow these instructions:

1. Remove all old python versions
2. Reboot
3. Install [Python 3.10.1](https://www.python.org/downloads/windows/) (64-Bit) with pip
4. Install [Microsoft Build Tools for Visual Studio 2019](https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2019). 
5. In Build tools, install **C++ build tools** and ensure the latest versions of **MSVCv142 - VS 2019 C++ x64/x86 build tools** and **Windows 10 SDK** (**for Windows 11 pick Windows 11 SDK**) or are checked. 
6. Reboot
7. You can't pip install lxml. Go to https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml and download `lxml‑4.6.3‑cp310‑cp310‑win_amd64.whl` **If you have installed Python 3.10 32-Bit download** `lxml‑4.6.3‑cp310‑cp310‑win32.whl`
8. `pip install --upgrade --user <path to lxml‑4.6.3‑cp310‑cp310‑win_amd64.whl>`
9. Follow normal instructions

**Comment by Soulol36** [comment]
Hi bro, you know, you were able to help me solve the problem with starting python with the "OFScraper", but now it won't let me load the profiles.
Here is my post issue that I made, I hope you can help me, thank you.
"https://github.com/DIGITALCRIMINALS/OnlyFans/issues/82#issue-1046184928"

**Comment by championofdeath** [comment]
Unfortunately even after doing all of this I still get the error..

**Comment by Balasia** [comment]
Just here to say this doesn't work. I troubleshooted for over 2 hours and still get filtered. for one think the lxml shit is on 4.6.4 now and even when typing pip install --upgrade --user <path to lxml‑4.6.3‑cp310‑cp310‑win_amd64.whl> still get ANOTHER error.

**Comment by championofdeath** [comment]
To me it installs correctly.. the 4.6.4 version.. but still doesnt work

**Comment by kccomikeyga** [comment]
> 

Still having this issue with Scraper 4.6 after following the steps provided.

**Comment by docholllidae** [comment]
try my suggestion on #110

**Comment by left1000** [comment]
So it's a bit strange. before following these steps I get errors trying to install psutil
after following these steps I'm still getting those errors. I must have chosen something incorrectly.


`    Running setup.py install for psutil ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python3.10.0\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\Temp\\pip-install-bk889f9l\\psutil_a19eea7abdcc4fa8a84f659e6b154e9f\\setup.py'"'"'; __file__='"'"'D:\\Temp\\pip-install-bk889f9l\\psutil_a19eea7abdcc4fa8a84f659e6b154e9f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'D:\Temp\pip-record-m800y576\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python3.10.0\Include\psutil'
         cwd: D:\Temp\pip-install-bk889f9l\psutil_a19eea7abdcc4fa8a84f659e6b154e9f\
    Complete output (38 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\psutil
    copying psutil\_common.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_compat.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_psaix.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_psbsd.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_pslinux.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_psosx.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_psposix.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_pssunos.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\_pswindows.py -> build\lib.win-amd64-3.10\psutil
    copying psutil\__init__.py -> build\lib.win-amd64-3.10\psutil
    creating build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\runner.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_aix.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_bsd.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_connections.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_contracts.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_linux.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_misc.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_osx.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_posix.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_process.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_sunos.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_system.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_testutils.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_unicode.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\test_windows.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\__init__.py -> build\lib.win-amd64-3.10\psutil\tests
    copying psutil\tests\__main__.py -> build\lib.win-amd64-3.10\psutil\tests
    running build_ext
    building 'psutil._psutil_windows' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Python3.10.0\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\Temp\\pip-install-bk889f9l\\psutil_a19eea7abdcc4fa8a84f659e6b154e9f\\setup.py'"'"'; __file__='"'"'D:\\Temp\\pip-install-bk889f9l\\psutil_a19eea7abdcc4fa8a84f659e6b154e9f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'D:\Temp\pip-record-m800y576\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python3.10.0\Include\psutil' Check the logs for full command output.`


I've got the following in my visual studio installer:

MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.29-16.10)
and
Windows 10 SDK 10.0.20348.0

this is all a tiny bit strange for me because psutil is properly installed and working for python 3.9 but not python 3.10

anyone got a clue?

**Comment by DIGITALCRIMINALS** [comment]
We no longer need PSUTIL :pray:

**Comment by championofdeath** [comment]
wdym bro
