### ISSUE TITLE
Progress bar has been kept at 0%

### ISSUE THREAD

**Issue by wwwtianzhen** [DIGITALCRIMINALS/OnlyFans#433]
![微信截图_20220427124533](https://user-images.githubusercontent.com/50664816/165442989-3950bbf5-a2ac-4a01-9116-0ae14e379261.png)
![setting](https://user-images.githubusercontent.com/50664816/165443497-68459f00-7d74-47e4-99ef-9b9f7ae76b2d.png)
![jobs](https://user-images.githubusercontent.com/50664816/165443506-4ac41c6b-5315-4c2f-98f9-af44fb239617.png)

win11 python 3.10.4
The progress bar remains 0 percent  when i start donwload the post about 1 hour,the teminal  do not have any response.
i dk what happened.

**Comment by michaelworthy96** [comment]
Open the "config.json" file in the ".settings" folder. Find "reformat_media": true and change it to false. That worked for me.
