### ISSUE TITLE
If messages are set to true in the config.json scrapper will try to start scraping models which I'm no longer subbed to

### ISSUE THREAD

**Issue by lEtranger1942** [DIGITALCRIMINALS/OnlyFans#434]
Basically the title. Turning off message scraping fixes this issue.

Would be nice for this setting to work, since sometimes I get messages which are not PPV and they dont download. 

I am using python3.10.3 with the latest commits from GitHub.

If you need more info let me know

**Comment by DIGITALCRIMINALS** [comment]
This is the intended behaviour, to download all messages regardless if they're subscriptions.
