### ISSUE TITLE
Processing Scraped Messages

### ISSUE THREAD

**Issue by CannotTouch** [DIGITALCRIMINALS/OnlyFans#436]
with the latest commits d417277182d3833dd0c99d206e374a30981c7bd1 on of when you submit a model name it start to scrape a lot of model messages scraping like the avatar/header (not sure, but it don't scrape the pics and video in them).
 It's strange indeed i don't know how better say it.

**Comment by CannotTouch** [comment]
Basically seems it scrapes avatar/header of all the models subscribed even if you pass it a single name

**Comment by CannotTouch** [comment]
putting the messages on false fix it seems (and it scrapes from messages of the model name submitted)

**Comment by DIGITALCRIMINALS** [comment]
Removed scraping profile at this time
