### ISSUE TITLE
Fansly error after choosing username to download

### ISSUE THREAD

**Issue by zeldatp151** [DIGITALCRIMINALS/OnlyFans#438]
version 7.6.1 run on dedicated server running ubuntu 20.04 , worked fine since I updated to 7.6.1 in Dec, until today, last used successfully 3 days ago. Onlyfans side still works.

```
Scrape Processing
Name: CarryKeycos
Type: Profile
Traceback (most recent call last):
  File "/media/server/OnlyFans/./start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/media/server/OnlyFans/./start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "/media/server/OnlyFans/datascraper/main_datascraper.py", line 156, in start_datascraper
    await main_helper.process_names(
  File "/media/server/OnlyFans/helpers/main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "/media/server/OnlyFans/modules/fansly.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "/media/server/OnlyFans/modules/fansly.py", line 778, in prepare_scraper
    await profile_scraper(
  File "/media/server/OnlyFans/modules/fansly.py", line 290, in profile_scraper
    filename: str = media_options["filename"].replace("..", ".")
KeyError: 'filename'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/server/OnlyFans/./start_ofd.py", line 107, in <module>
    input()
KeyboardInterrupt
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f0e60ebdc90>


```

**Comment by AndreeMu** [comment]
yeah  ugh seems like Fansly did a weird update ...

i am just using this now instead https://github.com/Avnsx/fansly it seems to work :D

**Comment by e2489** [comment]
Latest commit works, release is broken now. This is unfortunate because the latest commit doesn't grab previews whereas the release did (https://github.com/DIGITALCRIMINALS/OnlyFans/issues/426).

**Comment by GooseWhoIsLoose** [comment]
> Latest commit works, release is broken now. This is unfortunate because the latest commit doesn't grab previews whereas the release did (#426).

What do I need to do to get the latest commit? I'm brand new to github

**Comment by bitternjaded** [comment]
> @e2489 @GooseWhoIsLoose @DIGITALCRIMINALS Anyone know where or what that "commit" is because I cant find it and im getting the same error

Having the same exact issue here. python 3.10+. OF side works, Fansly gives exact error msg without the second error.

**Comment by passeee** [comment]
> Having the same exact issue here. python 3.10+. OF side works, Fansly gives exact error msg without the second error.

You need to download the lastest release and then on the start page you need to download the code as master.zip or some then and you need to unzip it and replace the folders from the release with the new ones

**Comment by bitternjaded** [comment]
> You need to download the lastest release and then on the start page you need to download the code as master.zip or some then and you need to unzip it and replace the folders from the release with the new ones

Doing this now makes the start_ofd open and close without doing anything.
