### ISSUE TITLE
Weird error/bug with models starting with the letter C

### ISSUE THREAD

**Issue by demib72** [DIGITALCRIMINALS/OnlyFans#439]
Hello, while running the script, I am running into a strange issue with models starting with the letter C. At least I thought it was a free/paid issue.

Type: Posts
Scrape Attempt: 1/100
Missing 6200 Posts... Retrying...
Scrape Attempt: 2/100
Missing 6200 Posts... Retrying...
Scrape Attempt: 3/100
Missing 12400 Posts... Retrying...
Scrape Attempt: 4/100
Missing 16533 Posts... Retrying...
Scrape Attempt: 5/100
Missing 15500 Posts... Retrying...
Scrape Attempt: 6/100
Missing 12420 Posts... Retrying...
Scrape Attempt: 7/100
Missing 10366 Posts... Retrying...
Scrape Attempt: 8/100
Missing 8900 Posts... Retrying...

The numbers seem to jump around with each attempt. It eventually stalls out at the 41st attempt. I am not sure of the source since it just stalls out. I'll let it be and update this should it exit finally.

**Comment by naodrej** [comment]
I'm getting the same errors with few random models. Not all of them start with a C. Something must've changed because it was scraping fine yesterday.
