### ISSUE TITLE
Scraper deleted all posts to models I am no longer subscribed to.

### ISSUE THREAD

**Issue by eloxole** [DIGITALCRIMINALS/OnlyFans#447]
It keeps Profile, Metadata and Message folder but deleted the rest.

Happened after I updated to v 8.0

{
  "info": {
    "version": 8.0
  },
  "settings": {
    "auto_site_choice": "",
    "export_type": "json",
    "profile_directories": [
      ".profiles"
    ],
    "max_threads": -1,
    "min_drive_space": 0,
    "helpers": {
      "renamer": true,
      "reformat_media": true,
      "downloader": true,
      "delete_empty_directories": false
    },
    "webhooks": {
      "global_webhooks": [],
      "global_status": true,
      "auth_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      },
      "download_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      }
    },
    "exit_on_completion": false,
    "infinite_loop": true,
    "loop_timeout": 0,
    "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
    "proxies": [],
    "cert": "",
    "random_string": "bf6c8ec8c82311ec8fdf1c9957bb10ec"
  },
  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": [0],
        "auto_model_choice": false,
        "auto_api_choice": true,
        "auto_media_choice": "0",
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "messages": true,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{model_username}/{api_type}/{value}/{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    },
    "fansly": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_api_choice": true,
        "auto_media_choice": "",
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "messages": true,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{model_username}/{api_type}/{value}/{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    },
    "starsavn": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_api_choice": true,
        "auto_media_choice": "",
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "messages": true,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{model_username}/{api_type}/{value}/{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    }
  }
}

**Comment by avekifes** [comment]
Did anyone else run into this? Because this is worrisome.

**Comment by hydr0homiee** [comment]
This is also happening to me. I don't know why and it appears recent.

My settings are below.

```
"onlyfans": {
"settings": {
"auto_profile_choice": [0],
"auto_model_choice": true,
"auto_api_choice": true,
"auto_media_choice": "0",
"browser": {
"auth": true
},
"jobs": {
"scrape": {
"subscriptions": true,
"messages": false,
"paid_content": false
},
"metadata": {
"posts": true,
"comments": false
}
},
````

**Comment by avekifes** [comment]
Does this happen when you try to update all subscriptions at once, or also when you only update individual accounts?

**Comment by eloxole** [comment]
For me, it happened when I update all subscriptions.

**Comment by hydr0homiee** [comment]
Same

**Comment by A-Random-Mf** [comment]
@DIGITALCRIMINALS Was the [Remove rename_duplicates function](https://github.com/DIGITALCRIMINALS/OnlyFans/commit/85aec02065f6065c5b99b6caedec20ce947ffc2d) the fix to this issue?

**Comment by DIGITALCRIMINALS** [comment]
> @DIGITALCRIMINALS Was the [Remove rename_duplicates function](https://github.com/DIGITALCRIMINALS/OnlyFans/commit/85aec02065f6065c5b99b6caedec20ce947ffc2d) commit the fix to this issue?

No, and I have no idea that causes it since there's no delete operations in the script, only overwrites.

**Comment by left1000** [comment]
I had a similar issue occur for me. Not only did it delete everything but it even said my date of folder creation was today, making me think I'd never made the rip in the first place. Thankfully I had a backup.

Going to stick to 7.6.1 as the issue never occurs for me on 7.6.1 and occurred for me the first time I tried running the current update/commit.

I actually was and only ever have run individual model scrapes. After I ran the current commit/update for one model it just moved to the next model, and when I selected a media type, it just nuked that model's entire prior scrape/rip.

Thankfully I noticed after 2 models, and 1 was backed up and 1 I'd never ripped anyways.

**Comment by hydr0homiee** [comment]
@left1000 Are you having issues downloading content? Like do you end up with missing content using the 7.6.1 version? (See #587)

I might try downgrading to 7.6.1, I remember I upgraded because I kept getting an error that got fixed once I upgraded. But now I'm not able to download like any content in messages.

**Comment by left1000** [comment]
I haven't gotten any messages to test recently. But I am running 7.6.1 plus https://github.com/DIGITALCRIMINALS/OnlyFans/issues/585 I made this code edit manually myself as it's required to get 7.6.1 working right.

**Comment by DIGITALCRIMINALS** [comment]
It shouldn't be happening anymore since I've removed many delete functions...
