### ISSUE TITLE
Scraper not extracting data.

### ISSUE THREAD

**Issue by BrokenInds** [DIGITALCRIMINALS/OnlyFans#448]
The title says it all. 
The Scarper will run the process and make the folders but no data will be on the folders like nothing was downloaded at all, completely empty.
I did a fresh install of python and this code but no luck.

Any possibility of a fix?

**Comment by BrokenInds** [comment]
Found a Fix!

https://github.com/DIGITALCRIMINALS/OnlyFans/issues/397

**Comment by hsg120** [comment]
Hey @BrokenInds, just wanted to thank you for coming back and linking the 'fix'. I spent the last few days with this same issue and couldn't find a resolution so, really appreciate you sharing your findings!

**Comment by hsg120** [comment]
@ppsoong yes sure, I've got it pasted below. Literally all I changed were the two lines that were indicated in https://github.com/DIGITALCRIMINALS/OnlyFans/issues/397

> {
  "info": {
    "version": 8.0
  },
  "settings": {
    "auto_site_choice": "",
    "export_type": "json",
    "profile_directories": [
      ".profiles"
    ],
    "max_threads": -1,
    "min_drive_space": 0,
    "helpers": {
      "renamer": true,
      "reformat_media": true,
      "downloader": true,
      "delete_empty_directories": false
    },
    "webhooks": {
      "global_webhooks": [],
      "global_status": true,
      "auth_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      },
      "download_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      }
    },
    "exit_on_completion": false,
    "infinite_loop": true,
    "loop_timeout": 0,
    "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
    "proxies": [],
    "cert": "",
    "random_string": "232eb1a6ca7011eca1314d7f4e60ca26"
  },
  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_api_choice": true,
        "auto_media_choice": "",
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "messages": false,
            "paid_content": false
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{model_username}/{api_type}/{value}/{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    },
    "fansly": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_api_choice": true,
        "auto_media_choice": "",
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "messages": true,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{model_username}/{api_type}/{value}/{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    },
    "starsavn": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_api_choice": true,
        "auto_media_choice": "",
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "messages": true,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{model_username}/{api_type}/{value}/{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    }
  }
}

**Comment by simonrule** [comment]
> [hsg120](/hsg120)

im facing that scraper doesnt scrape all images and videos miss some. are you facing this issue ?

**Comment by MonkeyKingViper** [comment]
> @ppsoong yes sure, I've got it pasted below. Literally all I changed were the two lines that were indicated in #397

Your fix doesn't work for me. When I scrape, I see the files appear for about a second, and then disappear.

The tool shouldn't be deleting anything...just downloading. This is why I made sure to get the commit earlier than this new one that seems to delete things.

**Comment by MonkeyKingViper** [comment]
@hsg120 
> @ppsoong yes sure, I've got it pasted below. Literally all I changed were the two lines that were indicated in #397 

This fix doesn't work for me. When I scrape, I see the files appear for about a second, and then disappear.

The tool shouldn't be deleting anything...just downloading. This is why I made sure to get the commit earlier than this new one that seems to delete things.
