### ISSUE TITLE
Dowload Directory (windows)

### ISSUE THREAD

**Issue by Yesnotoester** [DIGITALCRIMINALS/OnlyFans#449]
Hi,

Im trying to run the script on my windows laptop

Onlyfans-Master is on my desktop, and i run it in docker

It works when i save under ".sites", the problem is that i only have 20 gbs on my C:

Trying to send it to my USB external 1tb SSD "P:/Scraper/.sites" doesn't work

If i put Onlyfans-Master on P: , i cant boot it in docker

What is the syntax i need to use to make it work ?

Thank you,

**Comment by antithesis-b** [comment]
Writing 
```
"metadata_directories": [
          "D:/People"
        ]
```
in the .config has worked fine for me on Windows 10 for sending it to my external USB HD. Could you try posting the relevant section of your .config

**Comment by Yesnotoester** [comment]
> Writing
> 
> ```
> "metadata_directories": [
>           "D:/People"
>         ]
> ```
> 
> in the .config has worked fine for me on Windows 10 for sending it to my external USB HD. Could you try posting the relevant section of your .config

Thanks for answering, here is the code : 

`  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": [2],
        "auto_model_choice": false,
        "auto_api_choice": true,
        "auto_media_choice": "All",
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "messages": false,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          "P:/Scraper"
        ],
        "file_directory_format": "{site_name}/{model_username}/{api_type}/{value}/{media_type}",
        "filename_format": "{date}_{model_username}_{filename}.{ext}",
        "metadata_directories": [
          "P:/Scraper"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%Y-%m-%d",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": ["-LowPriority"],
        "webhook": true
      }
    },`



I tried removing the ".sites" part from "P:/Scraper/.sites", doesn't work



This, metadata can be found in "C:/ ... /desktop/Onlyfan-master/.sites/Onlyfans" 
Nothing to be seen in "P:" , it "download" into the void

`        "download_directories": [
          ".site"
        ],
        "metadata_directories": [
          "P:/Scraper"
        ],`



This, "download" but nothing to be seen in "P:"

`        "download_directories": [
          "P:/Scraper"
        ],
        "metadata_directories": [
          "P:/Scraper"
        ],`



This, downloads can be found in "C:/ ... /desktop/Onlyfan-master/.sites" 
But, metadata isnt in "P:"

`        "download_directories": [
          "P:/Scraper"
        ],
        "metadata_directories": [
          ".sites"
        ],`



Even tried to change "Scraper" for "People" , notting

**Comment by Yesnotoester** [comment]
Well, while trying to make it work i did something that broke it, 

Then i starter to piece together crumb by crumb the way to make it work,

I realized that first time i installed it i had made it work with docker kindoff by accident

When i first installed it i wasn't able to install poetry because there is no real pointer for windows in the README that specify that we need to check a ADVANCED checkbox when we install python on windows, so i ended up running it from the python/310 folder and sort of made it work thru docker. i honestly can't say how/why it was working

So in the end i run Poetry and saving to external work like a charm, i assume docker needed something more to export to another disk

I ended up writing myself a guide for the next time i need to do this : 

    How to install OnlyFansDowloader on Windows 10 :
    
    Unzip Olnyfans-Master on desktop
    
    Install Python 3.10.X+ and pip: **If you forgot something folowing while installing, re-run the python installer and clic [modify]
    
	    Be sure to check :
				    [x] install pip
				    [x] py laucher
	    Then clic Advanced : 
				    [x]Associate files with Python
				    [x]Create shortcuts for installed applications
				    [x]Add Python to environment variables
	    
    
	    Notice "Add to path" while installing, this allow to start those scripts (storred in "C:\Users\YOU\AppData\Local\Programs\Python\Python310") from anywhere w/o writing the full path
    
    
    
    Open PowerShell (at the right path) :
    
	    Go to "C:\Users\YOU\Desktop\OnlyFans-master"
	    
	    Clic on [File], to the top left of [Home]
    
	    Launch PowerShell
    
	    Be sure it says "PS C:\Users\YOU\Desktop\OnlyFans-master>" at the top of the PowerShell window
		    if its says "PS C:\Users\YOU\Desktop\OnlyFans-master\SOMETHING-ELSE>" you had a file selected with your mouse
    
    
    
    Update pip and install dependencies (from PowerShell):
    
	    Now that we installed python and added it to path everything should be simple :
    
	    Intallation Commands, in PowerShell Type :
		    "pip install --upgrade pip" [Enter]
		    "pip install poetry" [Enter]
		    "poetry install" [Enter]
    
    Start OnlyFansDownloader (from PowerShell) :
    
	    Start Commands, in PowerShell Type :
		    "poetry run python ./start_ofd.py"
