### ISSUE TITLE
Request: update screen after script completes

### ISSUE THREAD

**Issue by jeff-geoff** [DIGITALCRIMINALS/OnlyFans#45]
When you re-attach to a docker container, the container does not show the terminal’s history. Which means that if you run the script in docker in the background, then come back to the container by saying `docker attach` You are greeted only with a blank screen. Solving this problem would require some sort of updates to the output after the script finishes. Rather than just saying “success! Please press any key to continue.” There would need to be some sort of re-printing feedback, or moving text. But at least this way it would be possible to tell the status of the last run when coming back in to the container. Hope that makes sense…

**Comment by artyom2035** [comment]
Are you familiar with `docker logs -tf --tail [number of lines] [CONTAINER]` ?

`-t` will show timestamps so you know when whatever happened
`-f` will follow log output of running container
`--tail` will obviously allow you to choose number of lines from end of file.
