### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by jimmothy-beep** [DIGITALCRIMINALS/OnlyFans#452]
Hi, ive ran the steps as described in the install instructions but when I go to run start_ofd.py I have tried all the suggestions and get no where, the only one that gives me anything is `poetry run python ./start_ofd.py` and I get this response

`The currently activated Python version 3.9.0 is not supported by the project (^3.10).
Trying to find and use a compatible version. 
Using python3 (3.10.2)
Traceback (most recent call last):
  File "/Users/j/Downloads/OnlyFans-master/./start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "/Users/j/Downloads/OnlyFans-master/helpers/main_helper.py", line 837
    match options_type:
          ^
SyntaxError: invalid syntax`

**Comment by MonkeyKingViper** [comment]
I'd reread the error message REALLY carefully...the first line tells you exactly what's wrong

**Comment by jimmothy-beep** [comment]
Im confused, it states that its tried using 3.9 it didn't work so it used 3.10

**Comment by jimmothy-beep** [comment]
3.10
