### ISSUE TITLE
[WARNING] Newest commit may delete content from unsubbed profiles

### ISSUE THREAD

**Issue by hydr0homiee** [DIGITALCRIMINALS/OnlyFans#453]
I noted it in #447 but figure I should repost for visibility.

I noticed a few profiles I previously ripped and am no longer subscribed to had most of the content wiped. All affected profiles have a modified date after the most recent commit on April 25th. This includes paid content that is not being re-downloaded when I run the scraper for paid content only.

I am using the latest commit from April 25th and python 3.10.4.

**Comment by simonrule** [comment]
i want to ask you something does it download everything for you? im talking about free content.

**Comment by hydr0homiee** [comment]
No, it seems like the scraper misses some files.

**Comment by simonrule** [comment]
> No, it seems like the scraper misses some files.

im having same issue

**Comment by DIGITALCRIMINALS** [comment]
Gonna close this since we have a thread already.
