### ISSUE TITLE
getting issue when i do python start_ofd.py step to make .john file 

### ISSUE THREAD

**Issue by cuenta111** [DIGITALCRIMINALS/OnlyFans#454]
getting this issue when i do python start_ofd.py step to make .john file 

e:\of>python start_ofd.py
Traceback (most recent call last):
  File "e:\of\start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "e:\of\helpers\main_helper.py", line 23, in <module>
    import orjson
ModuleNotFoundError: No module named 'orjson'

anyone got solution for this?

**Comment by nerdperv** [comment]
pip install orjson

It wasn't getting installed by the requirements.txt list I guess. I did that and it worked.
