### ISSUE TITLE
OF auth change?

### ISSUE THREAD

**Issue by nerdperv** [DIGITALCRIMINALS/OnlyFans#458]
It's been a while since I scraped. Monday I got all updated and got it working and scraped subs. Tuesday I subbed to a new model and when I tried to start a scrape I got Access Denied errors. I logged into the OF site just fine, grabbed the cookie information and updated auth.json again. Same access denied message on the script when I attempt I am also logged out of OF in my chrome window.  Every time I get new cookie info. 

Looks like they changed things up again or am I just doing something wrong in the script config? Again, it worked fine on the 9th then without any changes it did not work on the 10th.

**Comment by hydr0homiee** [comment]
I'm still able to use it. I think it's something else on your end.

**Comment by nerdperv** [comment]
> I'm still able to use it. I think it's something else on your end.

Thanks! I'll keep fucking with it. Glad it's still working for you!

**Comment by nerdperv** [comment]
Today I deleted my install. filled out the auth info, and it worked just fine. I'll have to remember to try redownloading and starting from scratch next time :)
