### ISSUE TITLE
Script is working but not downloading

### ISSUE THREAD

**Issue by Leboxis** [DIGITALCRIMINALS/OnlyFans#461]
![image](https://user-images.githubusercontent.com/97406795/168451110-d19e1fab-d730-4f58-bf85-b378d55f300c.png)
And there choosing number dont impact, and it's always "stories" (it's not an option btw)
![image](https://user-images.githubusercontent.com/97406795/168451131-7a00d57a-d919-4d46-844c-c186867b5c39.png)
If someone can help me to fix it please thanks

**Comment by MonkeyKingViper** [comment]
Probably #448 but that fix didn't work for me

**Comment by Yesnotoester** [comment]
Had something similar trying to dld anywhere else than the main folder using docker. Maybe it's that ? #449
