### ISSUE TITLE
profile avatar & headers are the only images that download

### ISSUE THREAD

**Issue by smellfungus96** [DIGITALCRIMINALS/OnlyFans#465]
all of the media links are in the db, but they were not downloaded even though directories were made for them

**Comment by Yesnotoester** [comment]
It's just not very clearly said, but it start by creating all folder and dld avatar and metadata, then it will dld all messages for all your subscription (that is a temporary fix to be sure you get them all) you need to wait while its processing the metadata and it will eventually start downloading. it will start dld all messages for all your subscription (that is a temporary fix to be sure you get them all) then process whom you chose

**Comment by rovingman** [comment]
Got the same issue. None of the Messages, Posts (Free or Paid) stuff gets dl'ed, though the folders are set up. The script also then goes on to a random model (as far as I can tell), but with same problem - downloading only profile images. I've not set to auto-dl all models, so I enter the index of the model I want, but this happens.

**Comment by smellfungus96** [comment]
> Got the same issue. None of the Messages, Posts (Free or Paid) stuff gets dl'ed, though the folders are set up. The script also then goes on to a random model (as far as I can tell), but with same problem - downloading only profile images. I've not set to auto-dl all models, so I enter the index of the model I want, but this happens.
> 
> Edit: Managed to make scraping work with temporary solution from [#397](https://github.com/DIGITALCRIMINALS/OnlyFans/issues/397#issuecomment-1079346378).

the solution(s) described on #397 do not work for me. you're lucky lol

**Comment by tacbliw** [comment]
I've got the same issue. I'm using docker version and got nothing but the avatar and header. It looks like it realize the content was there but unable to download them.
![image](https://user-images.githubusercontent.com/19433926/171922843-2672141f-17d9-4ec3-81a5-5aba68d6db67.png)

**Comment by tacbliw** [comment]
Good news, I got it working by setting `"messages": false,` and leave everything as it is in `config.json`. It still scrape the messages although disabled.

**Comment by ryann1234** [comment]
> 

amazing that fixed it for me thanks a lot
