### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by thracianx** [DIGITALCRIMINALS/OnlyFans#475]
Installed poetry and the requirements file and when I try to run start_ofd.py, it gives me the below error

Traceback (most recent call last):
  File "E:\rips\OnlyFans-7.6.1\start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "E:\rips\OnlyFans-7.6.1\helpers\main_helper.py", line 823
    match options_type:
          ^
SyntaxError: invalid syntax

I tried double-clicking start_ofd.py to open it but the cmd windows pops up for a second and disappears. Any help is appreciated

**Comment by hydr0homiee** [comment]
#471
