### ISSUE TITLE
hey, its stops running after downloading 1 or 2 photos

### ISSUE THREAD

**Issue by shxwme** [DIGITALCRIMINALS/OnlyFans#477]
![Przechwytywanie](https://user-images.githubusercontent.com/106408500/170788816-46a7787b-5089-4a67-96c0-13bf5aa9d253.PNG)

**Comment by shxwme** [comment]
could some1 pls help me figure this out?

**Comment by DIGITALCRIMINALS** [comment]
Should be fixed
