### ISSUE TITLE
The app started downloading paid content from someone I am not subscribed to....

### ISSUE THREAD

**Issue by goodboi69691** [DIGITALCRIMINALS/OnlyFans#478]
Like the title says.. when I started the app today, it just randomly(?) started downloading paid content from a user that I have never heard of nor ever subscribed to. Not really an issue, I just thought ya'll should know :D
![Screenshotaaaaa](https://user-images.githubusercontent.com/106436200/170826784-a22e75d4-84da-49b9-b5d1-eff8e8f86448.jpg)

**Comment by MonkeyKingViper** [comment]
It's the paid content you bought from them in messages while you were subbed. This is new functionality so you can buy PPVs from the girls that message you without you subbing to them
