### ISSUE TITLE
Install all requirements

### ISSUE THREAD

**Issue by misterscraper** [DIGITALCRIMINALS/OnlyFans#481]
Whats the best command to use to get all the requirements installed? I can't seem to find the requirements.txt and everytime i run the start command some kind of module is missing

**Comment by GooseWhoIsLoose** [comment]
[howtousereadme.pdf](https://github.com/DIGITALCRIMINALS/OnlyFans/files/8803856/howtousereadme.pdf)
[README.md](https://github.com/DIGITALCRIMINALS/OnlyFans/files/8803857/README.md)

https://www.youtube.com/watch?v=uP4N2Ftg5us

I've found it's easiest to get the stuff for auth.json while using Edge, but Firefox and Chrome should work fine too.

The YouTube video does a pretty good job of explaining stuff some stuff, as does the PDF. Once you get it all set up, use the command `python start_ofd.py` to launch. Just double clicking it doesn't work for me, not sure why.

I'm happy to help answer more questions :)

**Comment by misterscraper** [comment]
> [howtousereadme.pdf](https://github.com/DIGITALCRIMINALS/OnlyFans/files/8803856/howtousereadme.pdf) [README.md](https://github.com/DIGITALCRIMINALS/OnlyFans/files/8803857/README.md)
> 
> https://www.youtube.com/watch?v=uP4N2Ftg5us
> 
> I've found it's easiest to get the stuff for auth.json while using Edge, but Firefox and Chrome should work fine too.
> 
> The YouTube video does a pretty good job of explaining stuff some stuff, as does the PDF. Once you get it all set up, use the command `python start_ofd.py` to launch. Just double clicking it doesn't work for me, not sure why.
> 
> I'm happy to help answer more questions :)
> 
> Oh, open that .md file in a text editor. It's the official one, straight from this github. The pdf I found on Reddit.

in that .pdf it says about the requirements.txt file, that doesn't appear in the last commit.

**Comment by GooseWhoIsLoose** [comment]
I'm not quite sure what you mean. There's absolutely a requirements.txt file in the most recent commit

![image](https://user-images.githubusercontent.com/31820042/171153145-e3ef90b9-09a2-4dbd-b14d-2be2d9e1a981.png)

Could I see a screenshot of your folder? And have you tried just using the pip install --upgrade --user -r requirements.txt command?

It took me a while to get this working too, don't stress too much. Not having a proper GUI is a pain.

**Comment by misterscraper** [comment]
<img width="910" alt="Screenshot 2022-05-31 at 12 53 56" src="https://user-images.githubusercontent.com/33800433/171167184-a96ae318-a5c5-4241-a456-34eff1d0b389.png">

nowhere to be seen...

**Comment by dave2197** [comment]
From the project folder (latest commit, not the v7.6.1 release), run these commands:
```
pip install poetry
poetry install --no-dev
```
Then use this command to launch the script:
`poetry run python ./start_ofd.py`

**Comment by GooseWhoIsLoose** [comment]
> From the project folder (latest commit, not the v7.6.1 release), run these commands:
> 
> ```
> pip install poetry
> poetry install --no-dev
> ```
> 
> Then use this command to launch the script: `poetry run python ./start_ofd.py`

How do you get the latest commit?

**Comment by DIGITALCRIMINALS** [comment]
Just run the update script and you're chilling.
