### ISSUE TITLE
Fansly sub not showing up in subscriber selection

### ISSUE THREAD

**Issue by mediaburnwayne** [DIGITALCRIMINALS/OnlyFans#483]
I am subbed to a creator that does not allow you to follow them even though you are subbed. They do not show up in my list of subs to scrape when running script.

These are my settings

 "fansly": {
      "settings": {
        "auto_profile_choice": "1",
        "auto_model_choice": false,
        "auto_api_choice": true,
        "auto_media_choice": "0",
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "messages": true,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{model_username}/{api_type}/{value}/{media_type}",
        "filename_format": "{date}-{media_id}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%Y-%m-%d",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
        
        
      Creator is https://fansly.com/thegorillagrip

**Comment by Rakshae** [comment]
I'm having a similar issue. Settings below.

```
    "fansly": {
      "settings": {
        "auto_profile_choice": "Default",
        "auto_model_choice": false,
        "auto_api_choice": true,
        "auto_media_choice": "All",
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "messages": false,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{model_username}/{api_type}/{value}/{media_type}",
        "filename_format": "{date}-{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%Y%m%d",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
```

**Comment by DIGITALCRIMINALS** [comment]
Fixed
