### ISSUE TITLE
Fansly dont know what to put in auth.json "autorization"

### ISSUE THREAD

**Issue by passeee** [DIGITALCRIMINALS/OnlyFans#484]
I dont know what cookie or text i should put in there, can anyone share an example please?

Also i cant find any tutorial for fansly

**Comment by wipeyourbuttocks** [comment]
Did you manage to make it work? Need help here

**Comment by passeee** [comment]
Can you chat somewhere else easier? 

You need to open f12 and search for "api" and on the "header" tab there should be named something "authorization" and then look at the comments from me on this one https://github.com/DIGITALCRIMINALS/OnlyFans/issues/438#issuecomment-1147796349
