### ISSUE TITLE
Onlyfans: Not downloading all the content

### ISSUE THREAD

**Issue by bydioeds** [DIGITALCRIMINALS/OnlyFans#485]
I'm having the same issue:

![2022-06-06_17-38](https://user-images.githubusercontent.com/8415008/172262585-5a5acf76-9ec1-420a-9bcc-47fd77408629.png)
![2022-06-06_17-37](https://user-images.githubusercontent.com/8415008/172262587-cee4155f-28cc-487f-b7ed-34bd18a5ab24.png)

in this case was easy to spot as she has few content, this is the missing image:

![Screen Shot 2022-06-06 at 18 03 08](https://user-images.githubusercontent.com/8415008/172263289-32845798-6e8c-46ef-a58f-b6a9a805269e.png)

Tried with https://github.com/k0rnh0li0/onlyfans-dl and seems to be downloading everything:

![2022-06-06_18-21](https://user-images.githubusercontent.com/8415008/172264992-f2ef3bf2-25f0-4f74-8ea7-86c951d23036.png)

**Comment by bydioeds** [comment]
Seems like the post is being saved to the metadata db:

![2022-06-06_18-32](https://user-images.githubusercontent.com/8415008/172265958-24a49d17-1013-4b78-8ca8-0c3745db7a59.png)

the media is not being saved in the db:
![2022-06-06_18-35](https://user-images.githubusercontent.com/8415008/172266288-661c7161-9df6-4d69-90cb-7e5fe889d080.png)

**Comment by bydioeds** [comment]
Removed the model folder and now is not downloading anything :thinking:

**Comment by marcintosch** [comment]
You sure you're in the right git?

**Comment by andrewfree** [comment]
Noticing this too. It will grab content from some providers and not all. If I select specific subscriptions it tends to ignore that too and start downloading others

**Comment by DIGITALCRIMINALS** [comment]
What's her new username?
