### ISSUE TITLE
Onlyfans not working properly

### ISSUE THREAD

**Issue by tim1f1** [DIGITALCRIMINALS/OnlyFans#487]
Ever since I updated the app the other day, onlyfans hasn't been downloading anything. Here's what it looks like when I try
![image](https://user-images.githubusercontent.com/16625605/172613108-b870d1ef-34ad-42b9-b7e8-2343f7d32648.png)
(then it goes through all the subscribed accounts)
![image](https://user-images.githubusercontent.com/16625605/172613210-4adf5b56-7aeb-484b-ae8c-961cd7220e3b.png)
the weird thing is that the account at the end is an expired subscription, but shows up for any account I try to scrape. I've updated the requirements, pip and my profile info, still doesn't work. Here's what my config looks like
![image](https://user-images.githubusercontent.com/16625605/172613460-dd71fee5-27d9-4acd-902c-d78960b884da.png)
It does seem to be updating the account metadata file at least.

**Comment by Rakshae** [comment]
If it's like when I first updated to the latest, it's scraping through your messages history subscribed or not.

**Comment by ilPrudent** [comment]
Same issue. Only getting metadata file. But empty folders.

**Comment by andrewfree** [comment]
Also same ^

**Comment by ilPrudent** [comment]
I made a downloader script that opens up the meta data database file and downloads to the folder. That's how I got around this issue.

**Comment by phishyphun** [comment]
> I made a downloader script that opens up the meta data database file and downloads to the folder. That's how I got around this issue.

Would you be willing to share the script?

**Comment by ilPrudent** [comment]
https://pastebin.com/Er620unz
pass `poorerfans`
