### ISSUE TITLE
X34's Fansly setup guide unavailable

### ISSUE THREAD

**Issue by wipeyourbuttocks** [DIGITALCRIMINALS/OnlyFans#495]
Could not figure out how to setup fansly downloader. Auth 404'ed
![image](https://user-images.githubusercontent.com/57471081/175451017-cedcbc90-37b8-48aa-80a8-2f29384c9340.png)

**Comment by MandoCoding** [comment]
Sexy Egirls has moved to Thotsbay 
https://forum.thotsbay.com/threads/fansly-downloading-a-work-in-progress.10211/post-11422

Doesn't look like X34 has finished updating his guide since the move but maybe it helps

**Comment by wipeyourbuttocks** [comment]
@MandoCoding oh cool.  Do you know where to find the authorization values? The screenshots are missing from the site

**Comment by fxckinghostile** [comment]
@wipeyourbuttocks @LFS900 in chrome login to your account  hit f12 goto the network tab and type api in the search box the info should be at the bottom 
![fs02](https://user-images.githubusercontent.com/38843433/177484360-9c7d67da-4937-42cb-bf24-2511d9104f47.JPG)

**Comment by fxckinghostile** [comment]
yea i'm stuck there as well I posted and issue but havent had a response yet
