### ISSUE TITLE
AttributeError: module 'selenium.webdriver' has no attribute 'Opera'

### ISSUE THREAD

**Issue by jakescroggy** [DIGITALCRIMINALS/OnlyFans#496]
Traceback (most recent call last):
  File "K:\OnlyFans-7.6.1\start_ofd.py", line 24, in <module>
    import datascraper.main_datascraper as main_datascraper
  File "K:\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 6, in <module>
    import modules.onlyfans as m_onlyfans
  File "K:\OnlyFans-7.6.1\modules\onlyfans.py", line 14, in <module>
    import extras.OFLogin.start_ofl as oflogin
  File "K:\OnlyFans-7.6.1\extras\OFLogin\start_ofl.py", line 2, in <module>
    from seleniumwire import webdriver
  File "C:\Users\jake\AppData\Local\Programs\Python\Python310\lib\site-packages\seleniumwire\webdriver\__init__.py", line 1, in <module>
    from selenium.webdriver import *  # noqa
AttributeError: module 'selenium.webdriver' has no attribute 'Opera'

**Comment by davidkeat98** [comment]
I wish I had kept a better record of this but I had the same issue. I solved the problem by either changin seleniumwire to selenium or by changing selenium.webdriver to selenium in start_ofl.py or in the __init__.py referenced in the last error. There's probably a better solution and I wish I had noted which I did specifically.

**Comment by Darius040** [comment]
> I wish I had kept a better record of this but I had the same issue. I solved the problem by either changin seleniumwire to selenium or by changing selenium.webdriver to selenium in start_ofl.py or in the **init**.py referenced in the last error. There's probably a better solution and I wish I had noted which I did specifically.

how to change i am not understand...

**Comment by barthramsay** [comment]
Change this line https://github.com/DIGITALCRIMINALS/OnlyFans/blob/9e3a7f6cab14289ec50a86c387e2fc60fedc36cb/extras/OFLogin/start_ofl.py#L2

to 
```python
from selenium import webdriver
```

**Comment by Darius040** [comment]
> ```python
> from selenium import webdriver
> ```

Thank u so much.Worked!!!
