### ISSUE TITLE
It is not scrapping any OF content, just headers and profiles

### ISSUE THREAD

**Issue by unmystic666** [DIGITALCRIMINALS/OnlyFans#501]
Well, the script seems to work fine, it authenticates, reconizes my subscriptions, etc...
When I choose a specific account and try to scrape all media (or just videos or whatever) I only downloads the profile picture and the header, then goes on and tries to scrape the next account, and so on even when I specifies only one account.

I know there is a similar problem listed here about OF Downloader not scraping paid content. But in my case I cannot download ANYTHING but the profile pic and the header

**Comment by lanzjose** [comment]
Yeah it worked! at least it "scrapes"... Now, it gets stucks when downloading content (in 69% xD)
![1](https://user-images.githubusercontent.com/60416752/177366254-6e5aa72e-9590-4eab-b119-d353f579bdcb.png)

**Comment by Tyemnata** [comment]
> @lanzjose In the .settings\config.json - set "messages" to **false** - (on line 68 - config for onlyfans).
> 
> This fixed it for me and most - it seems to be a glitch when downloading "messages" from a profile

This worked for me.

**Comment by nachoman91** [comment]
Hi guys, I have issues with messages as well. Tried to change my config to set messages = false but I dont have that option.
Added an new row under "jobs" to "scrape_messages": false but broke it.

How do I set this config to false?
{
  "info": {
    "version": 7.2
  },
  "settings": {
    "auto_site_choice": "",
    "export_type": "json",
    "profile_directories": [
      ".profiles"
    ],
    "max_threads": -1,
    "min_drive_space": 0,
    "helpers": {
      "renamer": true,
      "reformat_media": true,
      "downloader": true,
      "delete_empty_directories": false
    },
    "webhooks": {
      "global_webhooks": [],
      "global_status": true,
      "auth_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      },
      "download_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      }
    },
    "exit_on_completion": false,
    "infinite_loop": true,
    "loop_timeout": "0",
    "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
    "proxies": [],
    "cert": "",
    "random_string": "224572985b6011ec899d94e979d58d2a"
  },
  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_media_choice": "",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\\{model_username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\\{model_username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": "",
        "webhook": true
      }
    },
    "fansly": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_media_choice": "",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\\{model_username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\\{model_username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    },
    "starsavn": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_media_choice": "",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape_names": true,
          "scrape_paid_content": true
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}\\{model_username}\\{api_type}\\{value}\\{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}\\{model_username}\\Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    }
  }
}

**Comment by jp1151419** [comment]
@PsyPeke @nachoman91 
I'd recommend doing a fresh install from the latest commit. Keep your auth file and start fresh for the rest, that'll fix the field not appearing in your config.

Your config should state  `"version": 8.0`

**Comment by nachoman91** [comment]
> @PsyPeke @nachoman91 I'd recommend doing a fresh install from the latest commit. Keep your auth file and start fresh for the rest, that'll fix the field not appearing in your config.
> 
> Your config should state `"version": 8.0`

Did this and now it does as OP writes, downloads avatar and header only. Changed the "messages" on row 68 to false but same result. 

     "jobs": {
          "scrape": {
            "subscriptions": true,
            "messages": false,
            "paid_content": true
