### ISSUE TITLE
Errors since today

### ISSUE THREAD

**Issue by djmarioka** [DIGITALCRIMINALS/OnlyFans#503]
Hi,

it's not working, it's showing these errors:

![2022-07-04 18_20_54-start_ofd py - Acceso directo](https://user-images.githubusercontent.com/81478245/177191726-191f5920-15ff-443e-83d1-f21326c4f684.png)

Could you fix it?.

Thanks.

**Comment by lamepennies** [comment]
Is Opera your user agent in your auth.json? Could be that.

**Comment by djmarioka** [comment]
> Is Opera your user agent in your auth.json? Could be that.

No, I don't have even Opera installed in my laptop.

**Comment by fightcancer2** [comment]
Same error here.  Just started last week.

**Comment by fightcancer2** [comment]
> Hi,
> 
> it's not working, it's showing these errors:
> 
> ![2022-07-04 18_20_54-start_ofd py - Acceso directo](https://user-images.githubusercontent.com/81478245/177191726-191f5920-15ff-443e-83d1-f21326c4f684.png)
> 
> Could you fix it?.
> 
> Thanks.

Same error here. Just started last week.

**Comment by fightcancer2** [comment]
> Hi,
> 
> I uninstalled Selenium, with : pip uninstall selenium, and then, it reworked.
> 
> Anyway, I have a bluescreen sometimes, of CLOCK_WATCH_TIMEOUT, when I execute the script, but I think it's a RAM memory issue of my laptop.
> 
> Thanks.

I get a lot of crashes when running this script too.

**Comment by fightcancer2** [comment]
> The issue I found is with Selenium 4.3.0. Edit the **requirements.txt** file to specify Selenium version 4.2.0.
> 
> Change line 15 from `selenium` to `selenium==4.2.0`
> 
> Run the `pip install --upgrade --user -r requirements.txt` command then try running the program again.
> 
> I hope that helps!

Thank you!!!

**Comment by dstwarriors** [comment]
> The issue I found is with Selenium 4.3.0. Edit the **requirements.txt** file to specify Selenium version 4.2.0.
> 
> Change line 15 from `selenium` to `selenium==4.2.0`
> 
> Run the `pip install --upgrade --user -r requirements.txt` command then try running the program again.
> 
> I hope that helps!

Unfortunately this doesn't help for me: I've tried reinstalling the whole thing from a new zip file, tried using several different versions of selenium (4.0.0, 4.2.0, 4.2, etc), and each have been met with the same AttributeError. Is it necessary to restart the computer, PowerShell or Docker?
