### ISSUE TITLE
Poetry could not find a pyproject.toml

### ISSUE THREAD

**Issue by DemonWolfFang** [DIGITALCRIMINALS/OnlyFans#511]
Hi there, I am attempting to install. However after running `pip install poetry` then `poetry install --no-dev` It seems to error with 

```RuntimeError

  Poetry could not find a pyproject.toml file in /home/kai or its parents

  at .local/lib/python3.8/site-packages/poetry/core/factory.py:369 in locate
      365│             if poetry_file.exists():
      366│                 return poetry_file
      367│ 
      368│         else:
    → 369│             raise RuntimeError(
      370│                 "Poetry could not find a pyproject.toml file in {} or its parents".format(
      371│                     cwd
      372│                 )
```

 Very unsure how to fix. Any help would be appreciated, thanks.

As for my OS I am running Zorin 16.1

**Comment by ethanhen** [comment]
make sure you're in the directory where you extracted the code

**Comment by DemonWolfFang** [comment]
Thanks, this has fixed it. However now I am getting `auth` failed errors and can't seem to fix it.

It does look like I have everything done correctly however so this one is stumping me a bit.

**Comment by ethanhen** [comment]
unless you post your auth file there isnt much we can do. make sure you have all the info in the file filled out correctly and there are no extra commas, quotation marks, colons, etc

**Comment by DemonWolfFang** [comment]
Wouldn't that be unsafe? 🤔

**Comment by ethanhen** [comment]
yeah if you leave all your tokens in, sure. but one of the FAQs is "if you're getting an auth loop, quadruple check your auth file cookies and tokens". if it "looks like you've done everything correctly" and it's still not working, it might be that you haven't.

**Comment by DemonWolfFang** [comment]
Alright I did fix it, sorry about that. Where would the content be stored?

**Comment by ethanhen** [comment]
it puts it in the program directory in a folder called .sites by default

**Comment by DemonWolfFang** [comment]
Ah thanks, I didn't see the folder, just me being blind. Thanks so much again!

**Comment by DemonWolfFang** [comment]
And one more thing, if nothing shows up in the `.sites` folder for posts/images, what would that mean? I am subscribed to the users, just doesn't retrieve the pics/videos. Doesn't error.

**Comment by misterscraper** [comment]
> Thanks, this has fixed it. However now I am getting `auth` failed errors and can't seem to fix it.
> 
> It does look like I have everything done correctly however so this one is stumping me a bit.

how did you fix your auth problems? I'm getting these now randomly

**Comment by Darxide23** [comment]
> make sure you're in the directory where you extracted the code

I'm having this exact error and I am in the directory where I extracted the code.
