### ISSUE TITLE
.py just closes?  (OnlyFans)

### ISSUE THREAD

**Issue by Smackdab69** [DIGITALCRIMINALS/OnlyFans#527]
Not sure if something changed with OF this week but lately I cannot get the .py file to run.  It gets through the scraping list, moves on to rename, and just closes.

Is there a log I can check?  It closes too fast for me to see what happens.

Everything was working fine until a few days ago.

**Comment by direttc** [comment]
I'm facing the same problem . This solution fixed it for me https://github.com/DIGITALCRIMINALS/OnlyFans/issues/518#issuecomment-1192966077

**Comment by Smackdab69** [comment]
I don't seem to have a "create_user.py" file...

**Comment by direttc** [comment]
changed it in apis\onlyfans\classes\user_model.py

**Comment by Smackdab69** [comment]
I changed it there and no fix :(
