### ISSUE TITLE
Getting this error when i try to run python start_ofd.py . Someone please help!!

### ISSUE THREAD

**Issue by cuenta111** [DIGITALCRIMINALS/OnlyFans#529]
c:\of>python start_ofd.py
Traceback (most recent call last):
  File "c:\of\start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "c:\of\helpers\main_helper.py", line 35, in <module>
    from apis.fansly import fansly as Fansly
  File "c:\of\apis\fansly\fansly.py", line 3, in <module>
    from apis.api_streamliner import StreamlinedAPI
  File "c:\of\apis\api_streamliner.py", line 6, in <module>
    import apis.fansly.classes as fansly_classes
  File "c:\of\apis\fansly\classes\__init__.py", line 1, in <module>
    from apis.fansly.classes import auth_model, extras, user_model
  File "c:\of\apis\fansly\classes\auth_model.py", line 26, in <module>
    from dateutil.relativedelta import relativedelta
ModuleNotFoundError: No module named 'dateutil'

c:\of>pip3 install deteutil
ERROR: Could not find a version that satisfies the requirement deteutil (from versions: none)
ERROR: No matching distribution found for deteutil

**Comment by cuenta111** [comment]
Someone please help

**Comment by Rhysdabeast** [comment]
`pip3 install python-dateutil`

**Comment by cuenta111** [comment]
> `pip3 install python-dateutil`

c:\of>pip3 install python-dateutil
Collecting python-dateutil
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ---------------------------------------- 247.7/247.7 kB 1.7 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in c:\users\dskter\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil) (1.16.0)
Installing collected packages: python-dateutil
Successfully installed python-dateutil-2.8.2

c:\of>python start_ofd.py
Traceback (most recent call last):
  File "c:\of\start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "c:\of\helpers\main_helper.py", line 35, in <module>
    from apis.fansly import fansly as Fansly
  File "c:\of\apis\fansly\fansly.py", line 3, in <module>
    from apis.api_streamliner import StreamlinedAPI
  File "c:\of\apis\api_streamliner.py", line 6, in <module>
    import apis.fansly.classes as fansly_classes
  File "c:\of\apis\fansly\classes\__init__.py", line 1, in <module>
    from apis.fansly.classes import auth_model, extras, user_model
  File "c:\of\apis\fansly\classes\auth_model.py", line 27, in <module>
    from user_agent import generate_user_agent
ModuleNotFoundError: No module named 'user_agent'

**Comment by cuenta111** [comment]
now getting this error , what to do now brother

**Comment by Rhysdabeast** [comment]
> now getting this error , what to do now brother

`pip3 install user_agent`
Also run `pip3 install --upgrade --user -r requirements.txt` to make sure you have all the other requirements installed

**Comment by cuenta111** [comment]
Brother do you have a telegram or discord where you could guide me. Please really need your help.

kindly message me here on telegram : @vibrantseller or on discord here @VibrantSeller#4374 . 

Or you drop your contact handles, i will message you.

> > now getting this error , what to do now brother
> 
> `pip3 install user_agent` Also run `pip3 install --upgrade --user -r requirements.txt` to make sure you have all the other requirements installed
