### ISSUE TITLE
Getting this error 

### ISSUE THREAD

**Issue by ctrlcmdshft** [DIGITALCRIMINALS/OnlyFans#533]
No idea what happened was working then this started 

```
Traceback (most recent call last):
  File "H:\OnlyFans\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "H:\OnlyFans\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "H:\OnlyFans\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "H:\OnlyFans\datascraper\main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "H:\OnlyFans\helpers\main_helper.py", line 1040, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "H:\OnlyFans\modules\module_streamliner.py", line 84, in start_datascraper
    await self.prepare_scraper(subscription, content_type)
  File "H:\OnlyFans\modules\module_streamliner.py", line 232, in prepare_scraper
    master_set.extend(await self.datascraper.get_all_stories(subscription))
  File "H:\OnlyFans\modules\onlyfans.py", line 388, in get_all_stories
    highlights = await subscription.get_highlights()
  File "H:\OnlyFans\apis\onlyfans\classes\user_model.py", line 283, in get_highlights
    results = [create_highlight(x) for x in results]
  File "H:\OnlyFans\apis\onlyfans\classes\user_model.py", line 283, in <listcomp>
    results = [create_highlight(x) for x in results]
  File "H:\OnlyFans\apis\onlyfans\classes\hightlight_model.py", line 3, in __init__
    self.id: int = option.get("id")
AttributeError: 'str' object has no attribute 'get'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002475F746170>
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by cornerdebug** [comment]
I started get that same error today as well. Ran it just fine last week.

Mainly this part:

 ```
 File "H:\OnlyFans\apis\onlyfans\classes\hightlight_model.py", line 3, in __init__
    self.id: int = option.get("id")
AttributeError: 'str' object has no attribute 'get'
```
I tried a clean git clone and python 3.10 environment and still getting the same error.

**Comment by Theonepremium** [comment]
> No idea what happened was working then this started
> 
> ```
> Traceback (most recent call last):
>   File "H:\OnlyFans\start_ofd.py", line 66, in <module>
>     asyncio.run(main())
>   File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
>     return future.result()
>   File "H:\OnlyFans\start_ofd.py", line 52, in main
>     api = await main_datascraper.start_datascraper(config, site_name)
>   File "H:\OnlyFans\datascraper\main_datascraper.py", line 131, in start_datascraper
>     await default(datascraper)
>   File "H:\OnlyFans\datascraper\main_datascraper.py", line 101, in default
>     await main_helper.process_jobs(datascraper, subscription_list, site_settings)
>   File "H:\OnlyFans\helpers\main_helper.py", line 1040, in process_jobs
>     await datascraper.start_datascraper(authed, subscription.username)
>   File "H:\OnlyFans\modules\module_streamliner.py", line 84, in start_datascraper
>     await self.prepare_scraper(subscription, content_type)
>   File "H:\OnlyFans\modules\module_streamliner.py", line 232, in prepare_scraper
>     master_set.extend(await self.datascraper.get_all_stories(subscription))
>   File "H:\OnlyFans\modules\onlyfans.py", line 388, in get_all_stories
>     highlights = await subscription.get_highlights()
>   File "H:\OnlyFans\apis\onlyfans\classes\user_model.py", line 283, in get_highlights
>     results = [create_highlight(x) for x in results]
>   File "H:\OnlyFans\apis\onlyfans\classes\user_model.py", line 283, in <listcomp>
>     results = [create_highlight(x) for x in results]
>   File "H:\OnlyFans\apis\onlyfans\classes\hightlight_model.py", line 3, in __init__
>     self.id: int = option.get("id")
> AttributeError: 'str' object has no attribute 'get'
> Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002475F746170>
> Traceback (most recent call last):
>   File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
>     self.close()
>   File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
>     self._loop.call_soon(self._call_connection_lost, None)
>   File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
>     self._check_closed()
>   File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
>     raise RuntimeError('Event loop is closed')
> RuntimeError: Event loop is closed
> ```

Getting same error

**Comment by Theonepremium** [comment]
Its works for me

https://github.com/DIGITALCRIMINALS/OnlyFans/pull/524/commits/c15051a1de74995053a72b8ed0ab27da80b382ad

**Comment by cornerdebug** [comment]
> Its works for me
> 
> [c15051a](https://github.com/DIGITALCRIMINALS/OnlyFans/commit/c15051a1de74995053a72b8ed0ab27da80b382ad)

Confirmed, that fixed it for me.

**Comment by ewhgae457yaefgae4** [comment]
Created a fix for it and compiled.
anonfiles com/d379Fe06y3/onlyfansdownloader_exe

**Comment by kieeeee24Self** [comment]
> Its works for me
> 
> [c15051a](https://github.com/DIGITALCRIMINALS/OnlyFans/commit/c15051a1de74995053a72b8ed0ab27da80b382ad)

Now the error does not appear after this, but when downloading a profile it only creates empty folders
