### ISSUE TITLE
Just Flash

### ISSUE THREAD

**Issue by undacovabrutha** [DIGITALCRIMINALS/OnlyFans#536]
Hey Guys, hope all is well.  I'm having an issue now that when I start the program, a black window flashes open then closed.  What could the issue be? Is it a virus or something? I've been using this program for a while now, with no issues...now this! Thanks in advance for your help.

**Comment by kieeeee24Self** [comment]
Try opening in Windows Powershell/Terminal whit commands 

`python start_ofd.py`  `python3 start_ofd.py`  `python3.10 start_ofd.py`  `poetry run python ./start_ofd.py`

**Comment by undacovabrutha** [comment]
Did it! This is what pops up now...

AttributeError: module 'selenium.webdriver' has no attribute 'Opera'

Got a work around?

**Comment by Rhysdabeast** [comment]
> Did it! This is what pops up now...
> 
> C:\Users\bates_pu5jag3\Documents\OF7-2022>python start_ofd.py Traceback (most recent call last): File "C:\Users\bates_pu5jag3\Documents\OF7-2022\start_ofd.py", line 24, in import datascraper.main_datascraper as main_datascraper File "C:\Users\bates_pu5jag3\Documents\OF7-2022\datascraper\main_datascraper.py", line 6, in import modules.onlyfans as m_onlyfans File "C:\Users\bates_pu5jag3\Documents\OF7-2022\modules\onlyfans.py", line 14, in import extras.OFLogin.start_ofl as oflogin File "C:\Users\bates_pu5jag3\Documents\OF7-2022\extras\OFLogin\start_ofl.py", line 2, in from seleniumwire import webdriver File "C:\Users\bates_pu5jag3\AppData\Roaming\Python\Python310\site-packages\seleniumwire\webdriver__init__.py", line 1, in from selenium.webdriver import * # noqa AttributeError: module 'selenium.webdriver' has no attribute 'Opera'
> 
> Got a work around?

Navigate to `extras/OFLogin/start_ofl.py`. Change the line `from seleniumwire import webdriver`  to `from selenium import webdriver`

**Comment by undacovabrutha** [comment]
Thanks, Sir! @Rhysdabeast Your advice helped, as I hadn't gotten this far since my issue started.  I completed your two steps, and the program started. Once I selected the model, this popped up...

Traceback (most recent call last):
  File "C:\Users\bates_pu5jag3\Documents\OF7-2022\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\bates_pu5jag3\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\bates_pu5jag3\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\bates_pu5jag3\Documents\OF7-2022\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\bates_pu5jag3\Documents\OF7-2022\datascraper\main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "C:\Users\bates_pu5jag3\Documents\OF7-2022\helpers\main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "C:\Users\bates_pu5jag3\Documents\OF7-2022\modules\onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "C:\Users\bates_pu5jag3\Documents\OF7-2022\modules\onlyfans.py", line 784, in prepare_scraper
    highlights = await subscription.get_highlights()
  File "C:\Users\bates_pu5jag3\Documents\OF7-2022\apis\onlyfans\classes\create_user.py", line 270, in get_highlights
    results = [create_highlight(x) for x in results]
  File "C:\Users\bates_pu5jag3\Documents\OF7-2022\apis\onlyfans\classes\create_user.py", line 270, in <listcomp>
    results = [create_highlight(x) for x in results]
  File "C:\Users\bates_pu5jag3\Documents\OF7-2022\apis\onlyfans\classes\create_highlight.py", line 3, in __init__
    self.id: int = option.get("id")
AttributeError: 'str' object has no attribute 'get'

Got a trick for that one too? Thanks!!!

**Comment by Rhysdabeast** [comment]
> Thanks, Sir! @Rhysdabeast Your advice helped, as I hadn't gotten this far since my issue started. I completed your two steps, and the program started. Once I selected the model, this popped up...
> 
> Traceback (most recent call last): File "C:\Users\bates_pu5jag3\Documents\OF7-2022\start_ofd.py", line 104, in asyncio.run(main()) File "C:\Users\bates_pu5jag3\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Users\bates_pu5jag3\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete return future.result() File "C:\Users\bates_pu5jag3\Documents\OF7-2022\start_ofd.py", line 86, in main api = await main_datascraper.start_datascraper( File "C:\Users\bates_pu5jag3\Documents\OF7-2022\datascraper\main_datascraper.py", line 94, in start_datascraper await main_helper.process_names( File "C:\Users\bates_pu5jag3\Documents\OF7-2022\helpers\main_helper.py", line 966, in process_names result = await module.start_datascraper(authed, username, site_name) File "C:\Users\bates_pu5jag3\Documents\OF7-2022\modules\onlyfans.py", line 161, in start_datascraper await prepare_scraper(authed, site_name, item) File "C:\Users\bates_pu5jag3\Documents\OF7-2022\modules\onlyfans.py", line 784, in prepare_scraper highlights = await subscription.get_highlights() File "C:\Users\bates_pu5jag3\Documents\OF7-2022\apis\onlyfans\classes\create_user.py", line 270, in get_highlights results = [create_highlight(x) for x in results] File "C:\Users\bates_pu5jag3\Documents\OF7-2022\apis\onlyfans\classes\create_user.py", line 270, in results = [create_highlight(x) for x in results] File "C:\Users\bates_pu5jag3\Documents\OF7-2022\apis\onlyfans\classes\create_highlight.py", line 3, in **init** self.id: int = option.get("id") AttributeError: 'str' object has no attribute 'get'
> 
> Got a trick for that one too? Thanks!!!

Chage line 283 in `apis/onlyfans/classes/user_model.py` from `results = [create_highlight(x) for x in results]` to `results = [create_highlight(x) for x in results.get("data")]`. Hopefully that should be the last issue you have!

**Comment by undacovabrutha** [comment]
Sir, that may just be the problem.  I don't have a user_model.py listed at the path location you listed. I do see a user_model.py in the version I used (7.6.1).  Can I just copy and paste that whole folder over?

**Comment by Rhysdabeast** [comment]
> Sir, that may just be the problem. I don't have a user_model.py listed at the path location you listed. I do see a user_model.py in the version I used (7.6.1). Can I just copy and paste that whole folder over?

If you use the latest commit the line will fixed, probably best to get that.

**Comment by Rhysdabeast** [comment]
> Bro, I'm about to get a sledgehammer and go to work on this pc!
> 
> C:\Users\bates_pu5jag3\Documents\OF7-2022>python start_ofd.py Traceback (most recent call last): File "C:\Users\bates_pu5jag3\Documents\OF7-2022\start_ofd.py", line 9, in from helpers.main_helper import OptionsFormat File "C:\Users\bates_pu5jag3\Documents\OF7-2022\helpers\main_helper.py", line 23, in import orjson ModuleNotFoundError: No module named 'orjson'
> 
> I was so close! Think I should just delete and start all over from scratch?

No, you can fix that by doing `pip install orjson`

**Comment by undacovabrutha** [comment]
Bro Rhysdabeast, thanks so much.  It's working now, somewhat.  Only thing is now that it's not actually scraping the files from the OF page.  All the folders are being created, but not files in them, besides the profile pics. I owe you a beer or something.  Shoot me your cash app.

**Comment by Rhysdabeast** [comment]
> Bro Rhysdabeast, thanks so much. It's working now, somewhat. Only thing is now that it's not actually scraping the files from the OF page. All the folders are being created, but not files in them, besides the profile pics. I owe you a beer or something. Shoot me your cash app.

Drop your discord or telegram so I can help you more and stops clogging this issue with messages.

**Comment by undacovabrutha** [comment]
Roger that! Telegram is UndaCova Brutha

**Comment by Rhysdabeast** [comment]
> Roger that! Telegram is UndaCova Brutha. I'll close out this issue now.

Message me @Rhysdabeast0011
