### ISSUE TITLE
Master version closes when I open it

### ISSUE THREAD

**Issue by cremafina** [DIGITALCRIMINALS/OnlyFans#545]
When I update, or download the master version, if I try to open the start.py it closes automaticly

**Comment by kieeeee24Self** [comment]
try commands in cmd/terminal

`python start_ofd.py`  `python3 start_ofd.py` ` python3.10 start_ofd.py`  `poetry run python`

**Comment by cremafina** [comment]
I get this error:
Traceback (most recent call last):
  File "start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "main_helper.py", line 23, in <module>
    import orjson
ModuleNotFoundError: No module named 'orjson'

**Comment by kieeeee24Self** [comment]
`pip install orjson`

**Comment by kieeeee24Self** [comment]
![image](https://user-images.githubusercontent.com/110026884/181627413-ff226dd3-c787-4478-b812-2bbb08d044b4.png)

**Comment by cremafina** [comment]
thanks!
