### ISSUE TITLE
Stuck on Progress Bar

### ISSUE THREAD

**Issue by josephlopez86** [DIGITALCRIMINALS/OnlyFans#546]
I'm getting the following, its working for other profiles and granted this is a large one but just sits on this screen till eventually goes back to the selection list.

Any ideas

<img width="1037" alt="Screenshot 2022-07-28 at 18 56 35" src="https://user-images.githubusercontent.com/59392114/181605454-06437d40-eec3-4312-b168-c7a1152bbcb5.png">

Creates the folders but they are all empty, bar a jpg in Profile\Headers and Profile\Avatars - the rest are empty

**Comment by josephlopez86** [comment]
To add, that recieved some messages and they've also been downloaded - its just not archived or posts those have images and videos subfolders, but empty.

same on the latest version and on 7.6.1 and both work with other profiles

**Comment by kieeeee24Self** [comment]
This bug has been around for a few days, I don't know if it still works for other people

**Comment by johndsmith1** [comment]
I have the same issue as well!
