### ISSUE TITLE
No module named 'sqlalchemy' on Mac, new to python

### ISSUE THREAD

**Issue by test4890938** [DIGITALCRIMINALS/OnlyFans#549]
Getting the following error:
```
Traceback (most recent call last):
  File "/Users/___/SoapUI-Tutorials/OnlyFans-7.4.1/start_ofd.py", line 12, in <module>
    main_test.check_config()
  File "/Users/___/SoapUI-Tutorials/OnlyFans-7.4.1/tests/main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "/Users/___/SoapUI-Tutorials/OnlyFans-7.4.1/helpers/main_helper.py", line 1, in <module>
    from database.databases.user_data.models.api_table import api_table
  File "/Users/___/SoapUI-Tutorials/OnlyFans-7.4.1/database/databases/user_data/models/api_table.py", line 6, in <module>
    import sqlalchemy
ModuleNotFoundError: No module named 'sqlalchemy'
```
I've been searching around for for people with the same issue and have seen [issue #43 ](https://github.com/DIGITALCRIMINALS/OnlyFans/issues/43), but I can't get past step 5

>  In Build tools, install C++ build tools and ensure the latest versions of MSVCv142 - VS 2019 C++ x64/x86 build tools and Windows 10 SDK (for Windows 11 pick Windows 11 SDK) or are checked.

Can anyone help?

As far as i know, i have the latest python

**Comment by marcintosch** [comment]
Did you install the requirements, pip and poetry?

**Comment by test4890938** [comment]
@marcintosch I did!

**Comment by test4890938** [comment]
@marcintosch when i try to rerun `pip install poetry`, i get a bunch of lines of code that say "Requirement already satisfied", however when I try to run `poetry install --no-dev`, i get the following error `zsh: command not found: poetry`

**Comment by marcintosch** [comment]
Like this?

`pip3.10 install --upgrade --user -r requirements.txt`

**Comment by test4890938** [comment]
Here's what i see when i run `python3.10 start_ofd.py`

```
bz@Bz-MacBook-Pro-2 OnlyFans-7.4.1 % python3.10 start_ofd.py
Execute the script with Python 3.9 
Press enter to continue
bz@Bz-MacBook-Pro-2 OnlyFans-7.4.1 % 
```

**Comment by test4890938** [comment]
My understanding is that i should see new folders called "profile" and "settings", but i don't see that
<img width="244" alt="Screen Shot 2022-07-29 at 12 23 40 PM" src="https://user-images.githubusercontent.com/110257960/181830140-d2430f0a-0916-4bfc-b768-442a47b242ea.png">

**Comment by marcintosch** [comment]
Those folders only appear after the first time running the script.

And you have an outdated build, [7.6.1](https://github.com/DIGITALCRIMINALS/OnlyFans/releases/tag/v7.6.1) is the current one.

**Comment by test4890938** [comment]
@marcintosch so after installing new build, what do i do? try running `python3.10 start_ofd.py ` again?

**Comment by marcintosch** [comment]
yes

**Comment by test4890938** [comment]
@marcintosch done. but now receiving this error:

> Traceback (most recent call last):
>   File "/Users/bz/SoapUI-Tutorials/OnlyFans-7.6.1/start_ofd.py", line 7, in <module>
>     from rich import panel
> ModuleNotFoundError: No module named 'rich'

**Comment by marcintosch** [comment]
Do you have Xcode installed?

**Comment by test4890938** [comment]
Not sure. I just re-ran user requirements and then reran python3.10 start_ofd.py. Got to here:
<img width="714" alt="Screen Shot 2022-07-29 at 12 49 32 PM" src="https://user-images.githubusercontent.com/110257960/181833522-01535af3-da77-4657-a0a4-c94bd58266d7.png">

I don't see something like that in the FAQs, so not quite sure how to move to next step of open and edit .profiles/default/auth.json

**Comment by marcintosch** [comment]
Just close it, the .profiles/defaults/auth.json will be there now. It will open for Fansly and StarsAVN as well the next two times running start_ofd.py

**Comment by test4890938** [comment]
@marcintosch really appreciating your help here. I see a greyed out .settings, but not .profiles
<img width="987" alt="Screen Shot 2022-07-29 at 12 57 57 PM" src="https://user-images.githubusercontent.com/110257960/181834532-57513b33-5064-4cd5-8df8-80745a88e62a.png">

**Comment by marcintosch** [comment]
Just rerun start_ofd.py again.

**Comment by test4890938** [comment]
Getting the Rich error:

> Traceback (most recent call last):
>   File "/Users/bz/SoapUI-Tutorials/OnlyFans-7.6.1/start_ofd.py", line 7, in <module>
>     from rich import panel
> ModuleNotFoundError: No module named 'rich'

**Comment by marcintosch** [comment]
> Do you have Xcode installed?

.

**Comment by test4890938** [comment]
Not sure. how do i check?

**Comment by marcintosch** [comment]
Open the Mac App Store, search for Xcode. Usually it is not installed, but for everything code related it's kinda the must-have to run shells without problems.

**Comment by test4890938** [comment]
ugh i have to download the new OS. brb

**Comment by test4890938** [comment]
ah just figured out i can just download an earlier version of xcode so i dont have to wait for the OS to download & update. downloading now

**Comment by test4890938** [comment]
@marcintosch what do i do once its downloaded?

**Comment by marcintosch** [comment]
Open it once to accept the License Agreement, that's enough.

**Comment by test4890938** [comment]
And then rerun start_ofd.py?

**Comment by test4890938** [comment]
@marcintosch i got it all sorted, but now i have a really stupid question - does this scraper bypass needing to pay for videos, or does it simply allow me to download videos that ive paid for

**Comment by marcintosch** [comment]
The scraper is not meant to download content you don't have paid for. It will download the PPV content you have unlocked, but will - on purpose - ignore locked content.
