### ISSUE TITLE
Stupid question - does this scraper allow for any Free content downloads?

### ISSUE THREAD

**Issue by test4890938** [DIGITALCRIMINALS/OnlyFans#550]
I realized far too late in this process that this scraper seems to only allow us to download content we've already paid for. Does this scraper allow us to access any content we haven't paid for?

**Comment by kieeeee24Self** [comment]
Free suscriptions can be scraped, paid also but only if you pay the suscription.

**Comment by waeel-alsydo** [comment]
I don't think

**Comment by JohnnyTowns94** [comment]
This scraper allows you to download content from your subscriptions. This includes content you have paid for, and "free" posts your subscriptions post. You cannot download paid content for free with this scraper.

**Comment by ARCADEFG** [comment]
are you saying if I paid subscriptions like 1 month and try to scraped, it is not gonna work with this scraper even tho I paid it?
