### ISSUE TITLE
Scraping completes without error but no content downloading 

### ISSUE THREAD

**Issue by AshSha1** [DIGITALCRIMINALS/OnlyFans#557]
I just see folder getting created (post, archive) but no actual content downloading.

**Comment by Throwaway115** [comment]
Had this for 5 days now :c

**Comment by nunga** [comment]
Same. I select one model and it appears to be downloading but it doesn't. Then it proceeds to run through a list of expired models.

**Comment by johndsmith1** [comment]
I have the same issue as well. It allows me to select a model, but the download will either it at 0% or it will download a small amount (anywhere from 18MB  to 300MB randomly) and then permanently stop.

**Comment by Throwaway115** [comment]
I think ive fixed mine!
I set messages and paid content to false and it seems to be downloading content for me.
its not everything but at least its something

![image](https://user-images.githubusercontent.com/77456400/182955688-3cddd219-2059-4713-9c1d-91239b088ab2.png)

**Comment by nunga** [comment]
**This worked for me too!  Thank you.  😃** 


> I think ive fixed mine! I set messages and paid content to false and it seems to be downloading content for me. its not everything but at least its something
> 
> ![image](https://user-images.githubusercontent.com/77456400/182955688-3cddd219-2059-4713-9c1d-91239b088ab2.png)
