### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by takemyseed** [DIGITALCRIMINALS/OnlyFans#558]
To save other people from struggle with this issue.
I'm documenting it here

Initially I thought it might be an issue with my version of python. 
I'm reinstalling this program for a new computer. However even downgrading to python3.10, which is the same version I have on my own computer did not help

Anyways the the error lies in orjson itself.
https://github.com/ijl/orjson/issues/287

I haven't looked much into it but I can confirm install orjson 3.78 fixes the issue
I usually install via repeatingly running the program until all dependencies are installed. This is one case where you need to specifiy what version of the program you want something like 
pip install orjson==3.78

**Comment by iLeeaal** [comment]
For me it gave an error in 3.78, but it worked without specifying the version, thanks 👌
