### ISSUE TITLE
Onlyfan Error

### ISSUE THREAD

**Issue by MillerTimeJones** [DIGITALCRIMINALS/OnlyFans#559]
Great work for this program I had no issues with Onlyfans before and been using it for over 6 months but now I get error everytime (can be seen in image) 

I have not changed anythign setup wise the only edit I have done is the standard for onlyfan log in details.

Can anyone help resolve this please?

Thank You

![onlyfan script error](https://user-images.githubusercontent.com/110180406/182153216-1e2223eb-5887-4aca-81c8-f1c7bdeb75e5.jpg)

**Comment by marcintosch** [comment]
You could at least look into the solved issues before posting a new duplicate. #516

**Comment by MillerTimeJones** [comment]
> You could at least look into the solved issues before posting a new duplicate. #516

This didnt solve my issue

**Comment by interbiznw** [comment]
> > You could at least look into the solved issues before posting a new duplicate. #516
> 
> This didnt solve my issue

You need to update, the updates solve this exact issue

**Comment by MillerTimeJones** [comment]
> > > You could at least look into the solved issues before posting a new duplicate. #516
> > 
> > 
> > This didnt solve my issue
> 
> You need to update, the updates solve this exact issue

Which updates?

I have tried the last build which was almost a year ago released Dec 2021 and many of the solutions people mention the issues are still their.
