### ISSUE TITLE
7.5.1 is not scraping paid content from users you are no longer subscribed to

### ISSUE THREAD

**Issue by JohnnyTowns94** [DIGITALCRIMINALS/OnlyFans#56]
With 7.5.1, I noticed that it doesn't download paid content from users that you are no longer subscribe to. Is this intentional or am I missing something in the config?

**Comment by jeff-geoff** [comment]
> Sounds a lot like #59

This is the behavior I was trying to describe in #59

(I’ll add that I believe it used to scrape all content from DMs, including free content, as well. But I could be wrong about this. However, in the event that content was paid for by tip, and then sent *not* as a PPV, then scraping free content from DMs would be valuable and make sense.)

**Comment by DIGITALCRIMINALS** [comment]
I'd need the full json for the message that isn't getting picked up or access to the account to fix it

**Comment by jeff-geoff** [comment]
Do you mean the entire DM conversation thread from an account I’m no longer subscribed to, but from which I purchased a video in the past? (It’s not account specific btw…)? I can do this later this evening if I know exactly what you need

**Comment by freakish804** [comment]
Exactly same problem. Its scraping partially. like for example If there is purchased 10 videos then its will download just most recent 3/4.

**Comment by JohnnyTowns94** [comment]
> 
> 
> Exactly same problem. Its scraping partially. like for example If there is purchased 10 videos then its will download just most recent 3/4. @DIGITALCRIMINALS

Yeah I just tested this. I re-subscribed to a user and it downloaded all of my older paid content. I bought some new stuff and it downloaded that too. For testing, I unsubscribed from that user and moved all of their content to a different spot and used the scraper to re-download the paid content. It only downloaded the new stuff I paid for and not the older paid stuff.

**Comment by jeff-geoff** [comment]
So it’s scraping some of the things from your unsubscribed user, but not everything?

Happy to supply some json for my situation, but just let me know exactly what you need.

**Comment by freakish804** [comment]
> So it’s scraping some of the things from your unsubscribed user, but not everything?

yeah. more specifically, it’s scraping some most recent things from an unsubscribed user, not all.

**Comment by jeff-geoff** [comment]
> > So it’s scraping some of the things from your unsubscribed user, but not everything?
> 
> yeah. more specifically, it’s scraping some most recent things from an unsubscribed user, not all.

Is there any discernible pattern to what it downloads and what it doesn’t?

**Comment by freakish804** [comment]
> > > So it’s scraping some of the things from your unsubscribed user, but not everything?
> > 
> > 
> > yeah. more specifically, it’s scraping some most recent things from an unsubscribed user, not all.
> 
> Is there any discernible pattern to what it downloads and what it doesn’t?

I havent seen any pattern.

**Comment by DIGITALCRIMINALS** [comment]
You need to open the network tools, then go to the purchased tab on OnlyFans.

Look for a request called "https://onlyfans.com/api2/v2/posts/paid?", click it and copy the response and then send to my email on my main account datahoarders@protonmail.com
