### ISSUE TITLE
Scraper re-install, blacklist not working problem, easy additional scraper, only download stories, speed issues and config text error

### ISSUE THREAD

**Issue by MaH-s9UFaXPEKdLafMHkSGgWUAupTA1xj78S9C7** [DIGITALCRIMINALS/OnlyFans#562]
Hey all

I sadly had to re-install everything, but thanks to your great help, I made it through. However, I am still puzzled about some things, which I hope you can help me out on.

When re-installing or doing "git clone", why doesn't it include the "requirements.txt"? I found out that missing that was what caused the problem. Also is it better to just unzip the files from https://github.com/DIGITALCRIMINALS/OnlyFans/releases/tag/v7.6.1 and then use that instead of "git cloning" and "git pulling". Are there other and/or better ways to update the scrape? When I first started to try using the updater.py, it never worked, so I always reverted to using "git pull".
And since my last install worked without any installing of poetry, is it better to have it uninstalled or not? And if so, how do I uninstall it and for future reference, how do I make a fresh clean install every time I want to?

My blacklist problem is that it keeps trying to scrape and download everything, if it isn't already downloaded, which makes the "all function" useless, when I just want to scrape a select list or rather all, but the blacklisted, who I put an "expired label" on. Yet the scraper still tries to scrape everything. It happened around the time of this edit DIGITALCRIMINALS/OnlyFans/issues/291. What I mean is, if I have two models active, but ten models in total, including the expired subscriptions, the scraper will still scrape and download the profile photos (header and avatar) and any excess material I might have received. The problem for me is, that it significantly increased the scrape and download time, when there are more models and especially if some of them are "spam models" who just post whatever, whenever and I cannot figure out how to completely get rid of my affiliation as it were with them on my onlyfans profile.
Apologies for any mistakes I made in terms of linking and otherwise, as I am quite new to all this.

Also is there an easy way to set up additional scrapers, such that I can choose to download different lists at different times? For instance, so that the free trial pages is downloaded by one scraper and the paid for are downloaded by another scraper. So far I have managed to make it work by doubling my folders with the scraper and it is kind of alright, but a bit of a pain when there is a new release or I need to re-authenticate to make them work. Is there an easier way to do this?
Likewise is there a way to set up the scraper to only download stories, as they are the most often only changing posts, so then I would not miss out on anything, but I wouldn't need to fire the scraper on all models all the time, just to get one or two new story posts?

Also is there any way to change the speed in which the scraper works? I usually get about 10MB/s, depending on the file, but never higher and I believe I've read a post, which said it could increase, but sadly I don't remember the post nor do I know how to do it.

When it comes to the config file, line 58, it reads ""auto_profile_choice": [],", but if you do "auto_profile_choice": [1], it returns an error. However if you change it to ""auto_profile_choice": "1"," it works. Just thought that was a minor change that needed to be made, specifically changing the default in line 58 from ""auto_profile_choice": []," to ""auto_profile_choice": "",", so that it continually works.

I know this is a lot, but I hope you can help me out and that I haven't crossed any guidelines or such. If so, I apologize in advance.

**Comment by DIGITALCRIMINALS** [comment]
We're using poetry to update now, all you just have to do is run the updater.py file.

Blacklist fixed.

You can just create multiple scrapers and set up a config for each of them. You can also symlink the __settings__ and __user_data__ folder to the secondary scrapers.

The speed depends on how many CPU threads you've got.

auto_choices fixed.
