### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by Generic765** [DIGITALCRIMINALS/OnlyFans#568]
I dont know much about scripts and no idea how to fix this or what is happening
![image](https://user-images.githubusercontent.com/69771208/182746608-8c55a904-8e49-4d5d-89de-84122c4b4947.png)

**Comment by Dromar97** [comment]
I just dealt with this bs. Enter this:

python -m pip install yarl

**Comment by Generic765** [comment]
Thanks!!!
