### ISSUE TITLE
Not downloading any media but no errors

### ISSUE THREAD

**Issue by blueoceanwaves** [DIGITALCRIMINALS/OnlyFans#570]
I enter the number of the profile I want to grab, script runs, doesn't download anything, and then says it's scraping other profiles and then at the end gives me the option to choose the type of content to download for a different profile that I did not choose.

![2022-08-04 16_26_15-C__WINDOWS_py exe](https://user-images.githubusercontent.com/110635365/182946454-c4021bc4-9e61-4a60-a0d7-34af53edbb9b.png)
![Untitled-1](https://user-images.githubusercontent.com/110635365/182947100-ec8f7be2-03a6-4384-bacc-c7831b2e2c89.jpg)

`{
  "info": {
    "version": 8.0
  },
  "settings": {
    "auto_site_choice": "",
    "export_type": "json",
    "profile_directories": [
      ".profiles"
    ],
    "max_threads": -1,
    "min_drive_space": 0,
    "helpers": {
      "renamer": true,
      "reformat_media": true,
      "downloader": true,
      "delete_empty_directories": false
    },
    "webhooks": {
      "global_webhooks": [],
      "global_status": true,
      "auth_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      },
      "download_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      }
    },
    "exit_on_completion": false,
    "infinite_loop": true,
    "loop_timeout": 0,
    "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
    "proxies": [],
    "cert": "",
    "random_string": "d748788613c211edb4a838d5472572da"
  },
  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_api_choice": true,
        "auto_media_choice": "",
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "messages": true,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{model_username}/{api_type}/{value}/{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    },
    "fansly": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_api_choice": true,
        "auto_media_choice": "",
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "messages": true,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{model_username}/{api_type}/{value}/{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    },
    "starsavn": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": false,
        "auto_api_choice": true,
        "auto_media_choice": "",
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "messages": true,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          ".sites"
        ],
        "file_directory_format": "{site_name}/{model_username}/{api_type}/{value}/{media_type}",
        "filename_format": "{filename}.{ext}",
        "metadata_directories": [
          ".sites"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": false,
        "text_length": 255,
        "video_quality": "source",
        "overwrite_files": false,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    }
  }
}`

**Comment by Dromar97** [comment]
Deal with the same issues.

**Comment by snortlax** [comment]
try set the auto media to everything. I was having the same issue until I just let it grab everything. I am guessing there is some sort of issue when your model list is too large.

**Comment by blueoceanwaves** [comment]
> try set the auto media to everything. I was having the same issue until I just let it grab everything. I am guessing there is some sort of issue when your model list is too large.

Assuming you mean the following:
"auto_media_choice": "everything"
I just tried this and it did not work. The script behaved a little differently but did not download any image or video media.

**Comment by blueoceanwaves** [comment]
I tried a fix on another post and it seems to be working, I set messages to false

`"jobs": {
          "scrape": {
            "subscriptions": true,
            "messages": false,
            "paid_content": true
          },`

**Comment by Rhysdabeast** [comment]
> > try set the auto media to everything. I was having the same issue until I just let it grab everything. I am guessing there is some sort of issue when your model list is too large.
> 
> Assuming you mean the following: "auto_media_choice": "everything" I just tried this and it did not work. The script behaved a little differently but did not download any image or video media.

If you wanted to get everything you would need to change your auto_media_choice to `"auto_media_choice": `"All"

**Comment by interbiznw** [comment]
Yeah, i see what its doing, its trying to download messages(and maybe content? but some are people who you aren't subbed to anymore) from every single person you've messaged so it goes into some long process, if you disable messages it seems to get past that point and download content again
