### ISSUE TITLE
can this tool record live shows live as they happen?

### ISSUE THREAD

**Issue by left1000** [DIGITALCRIMINALS/OnlyFans#572]
can this tool record live shows live as they happen?

**Comment by cjb900** [comment]
No this tool does not have any way to do that. You would have to use a screen capturing software to capture live shows as they happen.

**Comment by Rhysdabeast** [comment]
You can use this extension to record OF livestreams https://chrome.google.com/webstore/detail/stream-recorder-download/iogidnfllpdhagebkblkgbfijkbkjdmm

**Comment by interbiznw** [comment]
use ctbrec for to record off of many popular streaming sites

**Comment by left1000** [comment]
ctbrec does not support onlyfans.com streams, otherwise I would not have posed the question.

**Comment by DIGITALCRIMINALS** [comment]
No
