### ISSUE TITLE
Fansly Scraper is not populating the text metadata in the Posts table

### ISSUE THREAD

**Issue by A-Random-Mf** [DIGITALCRIMINALS/OnlyFans#577]
The fansly portion of the scraper is not adding post descriptions to the metadata. Im running the latest commit

**Comment by A-Random-Mf** [comment]
@DigitalCriminals Any word on this?

**Comment by BlissfulMayer** [comment]
Same issue here

**Comment by A-Random-Mf** [comment]
> Same issue here

I hope he gets a chance to fix this soon. The reason this script is so good is its metadata collection and formatting
