### ISSUE TITLE
Config.__init__() got an unexpected keyword argument 'auth'

### ISSUE THREAD

**Issue by Generic765** [DIGITALCRIMINALS/OnlyFans#578]
![image](https://user-images.githubusercontent.com/69771208/183745086-2478cee6-57d8-4107-b52c-8e9c23e8a682.png)

this is my config.json:

![image](https://user-images.githubusercontent.com/69771208/183745866-8b408731-15bc-4f86-a7e3-857038151c57.png)

**Comment by Rhysdabeast** [comment]
Your auth values don't go into the `config.json` file. They should be put in `.profiles/Onlyfans/Default/auth.json`

**Comment by Generic765** [comment]
Ty man i m new with this xd
