### ISSUE TITLE
Script still failing after dynamic rules fix and pulling down the latest codeset

### ISSUE THREAD

**Issue by skinnedknees** [DIGITALCRIMINALS/OnlyFans#583]
I ran into issues like the rest of you. I tried modifying my url to the historic version posted in the previous thread but that didn't work for me. Well the dynamic rules url has since been fixed but my script is still crashing. I have also nuked my directory and pulled down the latest codeset, inputing all my auth data and settings fresh, but no go. Here is what the traceback throws...

Traceback (most recent call last):
  File "B:\Cars\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "X:\Users\Freddy\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "X:\Users\Freddy\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "B:\Cars\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "B:\Cars\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "B:\Cars\datascraper\main_datascraper.py", line 55, in default
    await main_helper.process_profiles(api, global_settings)
  File "B:\Cars\helpers\main_helper.py", line 962, in process_profiles
    temp_json_auth = import_json(user_auth_filepath)
  File "B:\Cars\helpers\main_helper.py", line 761, in import_json
    json_file = orjson.loads(json_path.open(encoding="utf-8").read())
orjson.JSONDecodeError: control character (\u0000-\u001F) found while parsing a string at line 7 column 0: line 7 column 1 (char 326)

Any direction would be appreciated. Thx

**Comment by GooseWhoIsLoose** [comment]
Try the original URL again. It's working for me now, after not working last night. Original is as follows:

`https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json`

**Comment by skinnedknees** [comment]
So I got to the bottom of it and I'll post what it was in case it comes up in anyone's future searches.

It was a formatting error in my config.json file. There was a trailing ENTER command after I pasted my user agent, see below...

{
  "auth": {
    "username": "",
    "cookie": "auth_id=xxxxxxxx; sess=xxxxxxxxxxxxxxxxxxxxxxxxxx; auth_hash=; auth_uniq_=; auth_uid_=;",
    "x_bc": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "user_agent": "Mozilla/x.0 (Windows) AppleWebKit/xxx.xx (KHTML, like Gecko) Chrome/xxx.0.0.0 Safari/xxx.xx
",   _<<<(this should've been directly after my user agent above)_
    "email": "",
    "password": "",
    "hashed": false,
    "support_2fa": true,
    "active": true
  }
}

After I deleted that ENTER, everything went smooth. Thx
