### ISSUE TITLE
Publish Container

### ISSUE THREAD

**Issue by AstraLuma** [DIGITALCRIMINALS/OnlyFans#589]
Please publish a first party container image to a registry.

I suggest automating the build with GitHub actions--there should be piles of tutorials that'll work for your repo.

I suggest using either Docker Hub or GitHub Container Registry. Again, both should have a pile of docs.

**Comment by AstraLuma** [comment]
I'm mildly surprised GitHub themselves haven't published actions for this.

**Comment by AstraLuma** [comment]
Oh there it is https://github.com/marketplace/actions/build-and-push-docker-images

**Comment by ElSandu** [comment]
Yes please, I'm Tired of trying to run one build after another and none of them work, we need a first party image.
