### ISSUE TITLE
Doesn’t scrape purchased videos

### ISSUE THREAD

**Issue by jeff-geoff** [DIGITALCRIMINALS/OnlyFans#59]
Purchased videos are not scraped after subscriptions expire.

I started a new archive, and noticed that purchases are no longer included if there’s no active subscription for the model. I believe this used to be standard behavior.

(I had requested that the script scrape free videos and images in conversations from expired subscriptions, but this is a different issue. This one, I believe, is a bug.)

**Comment by americanseeder1865** [comment]
What is weird as that I can't replicate this. 

Alright, back to the basics

Can you answer me some questions real quick:

1. What operating system are you using?
2. Are you using a python virtual environment to run the scraper?
3. Are you on the latest release of the scraper?
4. Are you using Python 3.10?


After those questions are answered, here are some of the next steps I am looking at.

- See if you move the model's download folder to a different place, have the scraper re download the content and see if the issue persists. (Answers whether metadata is interfering)
- Have you install docker and run it that way. (Answers whether you have a python environment issue, plus I think docker is the superior way to run the scraper anyway)

**Comment by jeff-geoff** [comment]
I’m running the scraper in Docker on Debian Linux. I have also tried running it on Ubuntu, with the same results.

I am on the latest release of the scraper, and the container builds off of python 3.10.

The scraper will not create any folders for a model I am not subscribed to. In other words, if I delete the folder after my subscription expires, the scraper will not re-fetch my purchased content. If I re-subscribe, the scraper will download the purchased content once more.

When you are trying to duplicate this do you have all of the following conditions:
1. A video in your purchases tab
2. The video was purchased from a DM
3. The subscription to the model from whom the video was purchased  subscription has now expired
