### ISSUE TITLE
another problem 

### ISSUE THREAD

**Issue by Kira5659** [DIGITALCRIMINALS/OnlyFans#593]
uninstall to try to fix an error and now when I open to try to download the content I get this. Only mistakes always
![Captura de pantalla (984)](https://user-images.githubusercontent.com/85036149/185725137-037d7322-53a8-4c5c-85dc-b00672f95392.png)
.

**Comment by Luke-L** [comment]
dont use opera browser? lol

**Comment by Kira5659** [comment]
> ¿No usas el navegador Opera? jajaja

i always used chrome and i didn't have problem, so should I use opera to working?

**Comment by thecrazypozavnist** [comment]
did you try this?
issue #496

**Comment by Kira5659** [comment]
> did you try this? issue #496

I'll try and then I'll tell you if it worked

**Comment by Kira5659** [comment]
> did you try this? issue #496

my bro thank you very much, it worked perfect for me, really thank you very much

**Comment by Kira5659** [comment]
> did you try this? issue #496

But now when trying to download the content, I have this problem do you know any solution my bro, pleas
![Captura de pantalla (991)](https://user-images.githubusercontent.com/85036149/185757640-d84af955-bc34-4bf8-bd1d-55016d5b152d.png)
e

**Comment by Kira5659** [comment]
> > did you try this? issue #496
> 
> But now when trying to download the content, I have this problem do you know any solution my bro, pleas ![Captura de pantalla (991)](https://user-images.githubusercontent.com/85036149/185757640-d84af955-bc34-4bf8-bd1d-55016d5b152d.png) e

I already solved it with #516
