### ISSUE TITLE
"Something went wrong" error when I try to log in Onlyfans

### ISSUE THREAD

**Issue by djmarioka** [DIGITALCRIMINALS/OnlyFans#596]
Hi,

**I'm having this issue since 2 or 3 days ago, it says: "Something went wrong", when it tries logging with my user:**

![image](https://user-images.githubusercontent.com/81478245/185922012-a307c624-68d4-4eae-8a6b-e4a0da7ddf53.png)

Could you help me?.

Thanks.

**Comment by lEtranger1942** [comment]
Issue posted already here - https://github.com/DIGITALCRIMINALS/OnlyFans/issues/595

Please search before posting a new issue
