### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by ethanforvest** [DIGITALCRIMINALS/OnlyFans#601]
![image](https://user-images.githubusercontent.com/91059346/186161520-6c35683c-d173-4a61-b093-5fbf8e62bc97.png)

**Comment by JamiDEV** [comment]
it seems like setting the api choice has resolved this and many other issues. 

launch your config file and find these lines under onlyfans supported

"settings": {
        "auto_profile_choice": "1",
        "auto_model_choice": false,
        "auto_media_choice": "2,3,4,5,6,7",
        "auto_api_choice": "2,3,4,5,6,7",
        "browser": {
          "auth": true
        },

you dont have to set auto profile or media choice.

**Comment by blairg23** [comment]
> 

Setting `auto_media_choice` and `auto_api_choice` like this fixed this issue for me... Can you explain why? Did the API version update and some items such as `options` and `results` now return strings? Printing them out when they throw exceptions seems to show that they are empty lists inside objects w/o a `data` object.

**Comment by ethanforvest** [comment]
> it seems like setting the api choice has resolved this and many other issues.
> 
> launch your config file and find these lines under onlyfans supported
> 
> "settings": { "auto_profile_choice": "1", "auto_model_choice": false, "auto_media_choice": "2,3,4,5,6,7", "auto_api_choice": "2,3,4,5,6,7", "browser": { "auth": true },
> 
> you dont have to set auto profile or media choice.

I tried modifying it as you said but it didn't work, so I kept my settings as it is.

"settings": {
        "auto_profile_choice": "1",
        "auto_model_choice": false,
        "auto_media_choice": "",
        "auto_api_choice": true,
        "browser": {
          "auth": true
        },

I'm running the version [v7.6.1 ](https://github.com/DIGITALCRIMINALS/OnlyFans/releases/tag/v7.6.1)

Here is how I fixed it,

**apis/onlyfans/classes/user_model.py line 270** 
`results = [create_highlight(x) for x in results]` --> `results = [create_highlight(x) for x in results["list"]]`

**Comment by Bum211** [comment]
@ethanforvest thank you! I followed the post you provided and everything works now!

**Comment by okanshine** [comment]
> results = [create_highlight(x) for x in results["list"]]

works, thanks you sir

**Comment by j-ktz** [comment]
I tried updating my settings  but now  I  get tis:
`Traceback (most recent call last):
  File "/Users/jktz/OnlyFans-7.6.1/start_ofd.py", line 20, in <module>
    main_test.check_config()
  File "/Users/jktz/OnlyFans-7.6.1/tests/main_test.py", line 22, in check_config
    json_config, updated = main_helper.get_config(path)
  File "/Users/jktz/OnlyFans-7.6.1/helpers/main_helper.py", line 826, in get_config
    json_config = ujson.load(open(config_path))
ValueError: Unexpected character in found when decoding object value


`
