### ISSUE TITLE
script just turns off when I select model

### ISSUE THREAD

**Issue by Fall0n** [DIGITALCRIMINALS/OnlyFans#610]
turns off when I select model to get stuff from. Is there a fix for this? Have been like this for 3 days now. Its very quick cant read the error information. How can i fix this problem? i have lates zip

this is the error i get
![IMG_8851(1)](https://user-images.githubusercontent.com/59483617/186842015-fe4db9c9-72e5-453b-9118-b15e157232c8.jpg)

**Comment by GuglPlay** [comment]
**+1**

Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
1
Type: Stories
Traceback (most recent call last):
  File "F:\OnlyFans-master\OnlyFans-master\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "F:\OnlyFans-master\OnlyFans-master\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "F:\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "F:\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "F:\OnlyFans-master\OnlyFans-master\helpers\main_helper.py", line 1026, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "F:\OnlyFans-master\OnlyFans-master\modules\module_streamliner.py", line 84, in start_datascraper
    await self.prepare_scraper(subscription, content_type)
  File "F:\OnlyFans-master\OnlyFans-master\modules\module_streamliner.py", line 232, in prepare_scraper
    master_set.extend(await self.datascraper.get_all_stories(subscription))
  File "F:\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 388, in get_all_stories
    highlights = await subscription.get_highlights()
  File "F:\OnlyFans-master\OnlyFans-master\apis\onlyfans\classes\user_model.py", line 283, in get_highlights
    results = [create_highlight(x) for x in results["data"]]
KeyError: 'data'

F:\OnlyFans-master\OnlyFans-master>

**Comment by Fall0n** [comment]
> **+1**
> 
> Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts 1 Type: Stories Traceback (most recent call last): File "F:\OnlyFans-master\OnlyFans-master\start_ofd.py", line 66, in asyncio.run(main()) File "C:\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete return future.result() File "F:\OnlyFans-master\OnlyFans-master\start_ofd.py", line 52, in main api = await main_datascraper.start_datascraper(config, site_name) File "F:\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 131, in start_datascraper await default(datascraper) File "F:\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 101, in default await main_helper.process_jobs(datascraper, subscription_list, site_settings) File "F:\OnlyFans-master\OnlyFans-master\helpers\main_helper.py", line 1026, in process_jobs await datascraper.start_datascraper(authed, subscription.username) File "F:\OnlyFans-master\OnlyFans-master\modules\module_streamliner.py", line 84, in start_datascraper await self.prepare_scraper(subscription, content_type) File "F:\OnlyFans-master\OnlyFans-master\modules\module_streamliner.py", line 232, in prepare_scraper master_set.extend(await self.datascraper.get_all_stories(subscription)) File "F:\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 388, in get_all_stories highlights = await subscription.get_highlights() File "F:\OnlyFans-master\OnlyFans-master\apis\onlyfans\classes\user_model.py", line 283, in get_highlights results = [create_highlight(x) for x in results["data"]] KeyError: 'data'
> 
> F:\OnlyFans-master\OnlyFans-master>

DIGITALCRIMINALS have tell me that only works on C:\ 

try chenage drive and it might work for you

**Comment by GuglPlay** [comment]
> > **+1**
> > Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts 1 Type: Stories Traceback (most recent call last): File "F:\OnlyFans-master\OnlyFans-master\start_ofd.py", line 66, in asyncio.run(main()) File "C:\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete return future.result() File "F:\OnlyFans-master\OnlyFans-master\start_ofd.py", line 52, in main api = await main_datascraper.start_datascraper(config, site_name) File "F:\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 131, in start_datascraper await default(datascraper) File "F:\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 101, in default await main_helper.process_jobs(datascraper, subscription_list, site_settings) File "F:\OnlyFans-master\OnlyFans-master\helpers\main_helper.py", line 1026, in process_jobs await datascraper.start_datascraper(authed, subscription.username) File "F:\OnlyFans-master\OnlyFans-master\modules\module_streamliner.py", line 84, in start_datascraper await self.prepare_scraper(subscription, content_type) File "F:\OnlyFans-master\OnlyFans-master\modules\module_streamliner.py", line 232, in prepare_scraper master_set.extend(await self.datascraper.get_all_stories(subscription)) File "F:\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 388, in get_all_stories highlights = await subscription.get_highlights() File "F:\OnlyFans-master\OnlyFans-master\apis\onlyfans\classes\user_model.py", line 283, in get_highlights results = [create_highlight(x) for x in results["data"]] KeyError: 'data'
> > F:\OnlyFans-master\OnlyFans-master>
> 
> DIGITALCRIMINALS have tell me that only works on C:\
> 
> try chenage drive and it might work for you

nope, same problem again after copy to с 
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
4
Type: Stories
Traceback (most recent call last):
  File "C:\OnlyFans-master\OnlyFans-master\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\OnlyFans-master\OnlyFans-master\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "C:\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "C:\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "C:\OnlyFans-master\OnlyFans-master\helpers\main_helper.py", line 1026, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "C:\OnlyFans-master\OnlyFans-master\modules\module_streamliner.py", line 84, in start_datascraper
    await self.prepare_scraper(subscription, content_type)
  File "C:\OnlyFans-master\OnlyFans-master\modules\module_streamliner.py", line 232, in prepare_scraper
    master_set.extend(await self.datascraper.get_all_stories(subscription))
  File "C:\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 388, in get_all_stories
    highlights = await subscription.get_highlights()
  File "C:\OnlyFans-master\OnlyFans-master\apis\onlyfans\classes\user_model.py", line 283, in get_highlights
    results = [create_highlight(x) for x in results["data"]]
KeyError: 'data'

C:\OnlyFans-master\OnlyFans-master>

**Comment by Fall0n** [comment]
> > > **+1**
> > > Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts 1 Type: Stories Traceback (most recent call last): File "F:\OnlyFans-master\OnlyFans-master\start_ofd.py", line 66, in asyncio.run(main()) File "C:\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete return future.result() File "F:\OnlyFans-master\OnlyFans-master\start_ofd.py", line 52, in main api = await main_datascraper.start_datascraper(config, site_name) File "F:\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 131, in start_datascraper await default(datascraper) File "F:\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 101, in default await main_helper.process_jobs(datascraper, subscription_list, site_settings) File "F:\OnlyFans-master\OnlyFans-master\helpers\main_helper.py", line 1026, in process_jobs await datascraper.start_datascraper(authed, subscription.username) File "F:\OnlyFans-master\OnlyFans-master\modules\module_streamliner.py", line 84, in start_datascraper await self.prepare_scraper(subscription, content_type) File "F:\OnlyFans-master\OnlyFans-master\modules\module_streamliner.py", line 232, in prepare_scraper master_set.extend(await self.datascraper.get_all_stories(subscription)) File "F:\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 388, in get_all_stories highlights = await subscription.get_highlights() File "F:\OnlyFans-master\OnlyFans-master\apis\onlyfans\classes\user_model.py", line 283, in get_highlights results = [create_highlight(x) for x in results["data"]] KeyError: 'data'
> > > F:\OnlyFans-master\OnlyFans-master>
> > 
> > 
> > DIGITALCRIMINALS have tell me that only works on C:\
> > try chenage drive and it might work for you
> 
> nope, same problem again after copy to с Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts 4 Type: Stories Traceback (most recent call last): File "C:\OnlyFans-master\OnlyFans-master\start_ofd.py", line 66, in asyncio.run(main()) File "C:\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete return future.result() File "C:\OnlyFans-master\OnlyFans-master\start_ofd.py", line 52, in main api = await main_datascraper.start_datascraper(config, site_name) File "C:\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 131, in start_datascraper await default(datascraper) File "C:\OnlyFans-master\OnlyFans-master\datascraper\main_datascraper.py", line 101, in default await main_helper.process_jobs(datascraper, subscription_list, site_settings) File "C:\OnlyFans-master\OnlyFans-master\helpers\main_helper.py", line 1026, in process_jobs await datascraper.start_datascraper(authed, subscription.username) File "C:\OnlyFans-master\OnlyFans-master\modules\module_streamliner.py", line 84, in start_datascraper await self.prepare_scraper(subscription, content_type) File "C:\OnlyFans-master\OnlyFans-master\modules\module_streamliner.py", line 232, in prepare_scraper master_set.extend(await self.datascraper.get_all_stories(subscription)) File "C:\OnlyFans-master\OnlyFans-master\modules\onlyfans.py", line 388, in get_all_stories highlights = await subscription.get_highlights() File "C:\OnlyFans-master\OnlyFans-master\apis\onlyfans\classes\user_model.py", line 283, in get_highlights results = [create_highlight(x) for x in results["data"]] KeyError: 'data'
> 
> C:\OnlyFans-master\OnlyFans-master>

Ok did try help you. sorry it did not work

**Comment by RuneDemomn** [comment]
Im getting this too.

**Comment by slackett** [comment]
I am also getting this same error

**Comment by rando-username** [comment]
https://github.com/DIGITALCRIMINALS/OnlyFans/issues/604#issuecomment-1227648066

**Comment by eclipseo** [comment]
Dup of #604
