### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by Bum211** [DIGITALCRIMINALS/OnlyFans#614]
Anyone getting this? Seems like this is related to when you try to scrap the "Stories".  

Any suggestion is appreciated. Thanks
![Screenshot 2022-08-26 113327](https://user-images.githubusercontent.com/96312987/186969633-543a9c91-7631-4e86-a65e-9cdbd3649e42.jpg)
!

**Comment by ethanforvest** [comment]
#601

**Comment by Bum211** [comment]
@ethanforvest, Thank you! this works!
