### ISSUE TITLE
Filename & Directory Restructure Changes

### ISSUE THREAD

**Issue by Beareschal** [DIGITALCRIMINALS/OnlyFans#616]
I have a quite large collection but was hoping to restructure my directory and change the filename syntax to be more useful. IIRC we could handle that in the past? As of now, I've had no such luck. 

- Directory Format: Utilizing a single model for testing all I've only been able to replace the directory structure with my new syntax but only after completely deleting the old content and metadata.
- Filenames: Deleting the existing files, deleting the metadata, trying multiple different syntax changes, and some setting tweaks in the config file have not changed the filename at all, unfortunately. Even when the previous folder, content, and metadata have been deleted it still picks up the previous structure....

- Did the following two commits remove these capabilities altogether?  - Remove OFSorter, Remove rename_duplicates function

Currently trying to work my way through the code but my Python is amateurish at best.

This is scraping on Fansly so I cut out the Onlyfans section only for the purpose of this post.

{`
  "info": {
    "version": 8.0
  },
  "settings": {
    "auto_site_choice": "",
    "export_type": "json",
    "profile_directories": [
      ".Authentication_Profiles"
    ],
    "max_threads": -1,
    "min_drive_space": 0,
    "helpers": {
      "renamer": true,
      "reformat_media": true,
      "downloader": true,
      "delete_empty_directories": true
    },
    "webhooks": {
      "global_webhooks": [],
      "global_status": true,
      "auth_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      },
      "download_webhook": {
        "succeeded": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        },
        "failed": {
          "webhooks": [],
          "status": null,
          "hide_sensitive_info": true
        }
      }
    },
    "exit_on_completion": false,
    "infinite_loop": false,
    "loop_timeout": 5,
    "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
    "proxies": [],
    "cert": "",
    "random_string": "5dda0696205911edbda22c0da7df2068"
  }
"fansly": {
      "settings": {
        "auto_profile_choice": ["1"],
        "auto_model_choice": false,
        "auto_api_choice": true,
        "auto_media_choice": "0",
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "messages": true,
            "paid_content": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
        "download_directories": [
          ".Downloads"
        ],
        "file_directory_format": "{site_name}/{model_username}/{media_type}",
        "filename_format": "{date}_{value}_{model_username}_{filename}.{ext}",
        "metadata_directories": [
          ".Metadatas"
        ],
        "metadata_directory_format": "{site_name}/{model_username}/Metadata",
        "delete_legacy_metadata": true,
        "text_length": 100,
        "video_quality": "source",
        "overwrite_files": true,
        "date_format": "%d-%m-%Y",
        "ignored_keywords": [],
        "ignore_type": "",
        "blacklists": [],
        "webhook": true
      }
    }

**Comment by DIGITALCRIMINALS** [comment]
No, all the functionality is still there.
If you delete metadata and the user deletes their post, the script loses the ability to rename those media files, so that's why it's probably not working.
