### ISSUE TITLE
Just downloaded, ran the script, and got this error.

### ISSUE THREAD

**Issue by GeasLwo** [DIGITALCRIMINALS/OnlyFans#617]
Traceback (most recent call last):
  File "F:\a\stuff\of\start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "F:\a\stuff\of\helpers\main_helper.py", line 823
    match options_type:
          ^
SyntaxError: invalid syntax

**Comment by Beareschal** [comment]
Can you post your config file?

**Comment by GeasLwo** [comment]
There isn't even a config or auth file cause the script just crashes without creating those files or folders lol.

**Comment by eclipseo** [comment]
Can you post your Python version? You need at least 3.10 I believe for "match" to be available.

**Comment by Gnavihs7** [comment]
![image](https://user-images.githubusercontent.com/110778117/188276262-1435676f-9931-4bb2-8dd2-0437b030b405.png)
getting exact same error

**Comment by GeasLwo** [comment]
I had 3.9 installed initially, but I deleted it and installed 3.10. Dunno if having 3.9 installed first was a problem. I installed poetry with 3.9 so that might be a problem as well.
