### ISSUE TITLE
TRACEBACK (most recent call last):

### ISSUE THREAD

**Issue by Xknight79** [DIGITALCRIMINALS/OnlyFans#618]
Traceback (most recent call last):
  File "C:\OnlyFans\start_ofd.py", line 107, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\OnlyFans\start_ofd.py", line 89, in main
    api = await main_datascraper.start_datascraper(
  File "C:\OnlyFans\datascraper\main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "C:\OnlyFans\helpers\main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "C:\OnlyFans\modules\onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "C:\OnlyFans\modules\onlyfans.py", line 784, in prepare_scraper
    highlights = await subscription.get_highlights()
  File "C:\OnlyFans\apis\onlyfans\classes\create_user.py", line 270, in get_highlights
    results = [create_highlight(x) for x in results.get("data")]
TypeError: 'NoneType' object is not iterable

**Comment by mikebradley** [comment]
This seems to help: https://github.com/DIGITALCRIMINALS/OnlyFans/compare/master...eclipseo:OnlyFans:fix_api

**Comment by slippypete** [comment]
Used the above fix and now when I select a model it will scrape her content, but instead of downloading it starts prompting me to scrape every model I've ever subscribed to.

**Comment by cuenta111** [comment]
> Traceback (most recent call last): File "C:\OnlyFans\start_ofd.py", line 107, in asyncio.run(main()) File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete return future.result() File "C:\OnlyFans\start_ofd.py", line 89, in main api = await main_datascraper.start_datascraper( File "C:\OnlyFans\datascraper\main_datascraper.py", line 94, in start_datascraper await main_helper.process_names( File "C:\OnlyFans\helpers\main_helper.py", line 966, in process_names result = await module.start_datascraper(authed, username, site_name) File "C:\OnlyFans\modules\onlyfans.py", line 161, in start_datascraper await prepare_scraper(authed, site_name, item) File "C:\OnlyFans\modules\onlyfans.py", line 784, in prepare_scraper highlights = await subscription.get_highlights() File "C:\OnlyFans\apis\onlyfans\classes\create_user.py", line 270, in get_highlights results = [create_highlight(x) for x in results.get("data")] TypeError: 'NoneType' object is not iterable

getting same error.  can anyone help with fix?

**Comment by slippypete** [comment]
> Fully updated with the latest commit. Used the above fix and now when I select a model it will scrape her content, but instead of downloading it starts prompting me to scrape every model I've ever subscribed to.

Fixed with this suggestion:

https://github.com/DIGITALCRIMINALS/OnlyFans/issues/619#issuecomment-1230777382

**Comment by copypastaseal** [comment]
> > This seems to help: [master...eclipseo:OnlyFans:fix_api](https://github.com/DIGITALCRIMINALS/OnlyFans/compare/master...eclipseo:OnlyFans:fix_api)
> 
> just need to replace data with list in line 283 ?

The fix worked for me but it was under a different file name.

OnlyFans-7.6.1\apis\onlyfans\classes\create_user.py 

on line 270

**Comment by eclipseo** [comment]
Dup of #604
