### ISSUE TITLE
Any help with the error message listed...? Thanks in advance!

### ISSUE THREAD

**Issue by undacovabrutha** [DIGITALCRIMINALS/OnlyFans#63]
Traceback (most recent call last):
  File "C:\Users\bates_pu5jag3\Downloads\Onlyfans7.5.1\start_ofd.py", line 12, in <module>
    main_test.check_config()
  File "C:\Users\bates_pu5jag3\Downloads\Onlyfans7.5.1\tests\main_test.py", line 21, in check_config
    import helpers.main_helper as main_helper
  File "C:\Users\bates_pu5jag3\Downloads\Onlyfans7.5.1\helpers\main_helper.py", line 2, in <module>
    from apis import api_helper
  File "C:\Users\bates_pu5jag3\Downloads\Onlyfans7.5.1\apis\api_helper.py", line 30, in <module>
    from aiohttp_socks import ProxyConnectionError, ProxyConnector, ProxyError
ModuleNotFoundError: No module named 'aiohttp_socks'

**Comment by Beuge** [comment]
> You need to install libxml2 manually from here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml
> 
> 1. Download lxml‑4.6.3‑cp310‑cp310‑win_amd64.whl
> 2. Open CMD in the directory where you downloaded the file and "pip install lxml-4.6.3-cp310-cp310-win_amd64.whl"

'pip' is not recognized as an internal or external command,
operable program or batch file.

**Comment by dave2197** [comment]
> > You need to install libxml2 manually from here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml
> > 
> > 1. Download lxml‑4.6.3‑cp310‑cp310‑win_amd64.whl
> > 2. Open CMD in the directory where you downloaded the file and "pip install lxml-4.6.3-cp310-cp310-win_amd64.whl"
> 
> 'pip' is not recognized as an internal or external command, operable program or batch file.

You forgot to add Python to PATH. Reinstall Python 3.10 and tick "Add Python 3.10 to PATH" and pip will be working

![Capture](https://user-images.githubusercontent.com/92380483/139532498-5fb23d60-c541-48c1-a3d3-87689b8eed0e.PNG)

**Comment by undacovabrutha** [comment]
It's working!  Thanks, Gentlemen!!!
