### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Wykeless** [DIGITALCRIMINALS/OnlyFans#630]
So It worked before, I left it for like over month, didnt change anything and now im getting this error when running start_ofd.py

File ".\OnlyFans-7.6.1\start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File ".\OnlyFans-7.6.1\helpers\main_helper.py", line 23, in <module>
    import orjson
ModuleNotFoundError: No module named 'orjson'

and running the updater.py gives me this

C:\Python310\lib\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Script has been updated, exiting in 5 seconds

if it means anything...

Windows 11
Python 3.10.5
PIP 22.2.2

**Comment by amajio** [comment]
try pip install orjson

**Comment by Wykeless** [comment]
Okay i redid my auth.json and it works now. 

The only issue that remains is that charset whatever warning, should i worry about that?

**Comment by Wykeless** [comment]
Okay I searched around in the issues and found this [622#](https://github.com/DIGITALCRIMINALS/OnlyFans/issues/622#issuecomment-1232270744) ...changed data to list and it fixed that error above

the only issue that remains is the charset warning, should I be worried about that at all?

**Comment by eclipseo** [comment]
> Okay I searched around in the issues and found this [622#](https://github.com/DIGITALCRIMINALS/OnlyFans/issues/622#issuecomment-1232270744) ...changed data to list and it fixed that error above
> 
> the only issue that remains is the charset warning, should I be worried about that at all?

Try updating request:

`pip3 install --upgrade requests`

**Comment by Wykeless** [comment]
cool that fixed it

**Comment by Wykeless** [comment]
thanks @amajio and @eclipseo for the help..imma close the issue now
