### ISSUE TITLE
Can't locate revision identified by '37c4f2719d65'

### ISSUE THREAD

**Issue by SchmittyWerber** [DIGITALCRIMINALS/OnlyFans#632]
when trying to download content for certain model,s immediately after the ui says the metadata has finished processing, "Can't locate revision identified by '37c4f2719d65' " displays continuously until the terminal is closed.

**Comment by eclipseo** [comment]
Have you deleted a file by mistake? Try recopying the source code in your folder (make a backup of your config files first).

**Comment by untulis** [comment]
I just got this after downloading a fresh 7.6.1...

**Comment by DIGITALCRIMINALS** [comment]
> I just got this after downloading a fresh 7.6.1...

use the latest commit
