### ISSUE TITLE
How to save stories after recent changes?

### ISSUE THREAD

**Issue by GooseWhoIsLoose** [DIGITALCRIMINALS/OnlyFans#634]
Since some recent changes have broken story saving functionality... how do we do it now? Is there a file we can change to make it work again, or is there something else we have to do? Just right clicking the stories doesn't work, OF has that disabled (at least in all the browsers I've tried)

Thanks for your time! :)

**Comment by eclipseo** [comment]
For the right click you can use this extension: https://github.com/lunu-bounir/allow-right-click

**Comment by eclipseo** [comment]
I've made a PR to fix the stories downloading, see my comment on the previous bug #604 

https://github.com/DIGITALCRIMINALS/OnlyFans/issues/604#issuecomment-1236096937
