### ISSUE TITLE
Code just seems to hang

### ISSUE THREAD

**Issue by thisonehasnoame89** [DIGITALCRIMINALS/OnlyFans#64]
Hey all, 

I am totally new to this and have been doing pretty well to follow along I think, but I've got a problem and no clue how to solve it.  The .settings folder populates appropriately. I get the .profiles prompt and can enter my OF info. When it prompts for Fansly, I just hit Enter because I don't have a Fansly and then the script just hangs. Any thoughts?

To answer all the questions. I'm on v.7.5.1, with 3.10. I've got all the the Visual studio stuff and all requirements are met. I'm stuck. I'm pretty well positive that my OF info is entered correctly since I've been following since at least v7.1 and that hasn't changed too much. 

Any help would be appreciated. Thanks in advance.

**Comment by americanseeder1865** [comment]
I am a linux user so ¯\_(ツ)_/¯. 

Want to run it using docker and see if that helps anything?

**Comment by thisonehasnoame89** [comment]
> I am a linux user so ¯_(ツ)_/¯.
> 
> Want to run it using docker and see if that helps anything?

I'm on Windows and I'll be honest I have no clue what that means. Sorry

**Comment by thisonehasnoame89** [comment]
It seems like the fact that I don't have a Fansly is the issue. Is there a way to bypass this? Are other non Fansly having folks having a similar issue?

**Comment by DIGITALCRIMINALS** [comment]
What do you mean by hang?

**Comment by thisonehasnoame89** [comment]
> What do you mean by hang?

I get the prompt to enter my Fansly data (don't have one) and hit enter. No matter how many times I hit enter (or any other key) nothing else happens. It just stays stuck on that prompt until I close the CMD window. No error codes or anything.

**Comment by DIGITALCRIMINALS** [comment]
Ah... I need to remove that part of the code.

**Comment by DIGITALCRIMINALS** [comment]
I need a screenshot of the part that it hangs on

**Comment by thisonehasnoame89** [comment]
> I need a screenshot of the part that it hangs on

![image](https://user-images.githubusercontent.com/83365571/142457020-562b7267-7434-469e-b324-9a663b5bfcfa.png)

This is 7.6, but it looks like it's doing the same thing I was experiencing on 7.5.1 on after the StarsAVN prompt instead. Any ideas on how to solve?

**Comment by thisonehasnoame89** [comment]
> > I need a screenshot of the part that it hangs on
> 
> ![image](https://user-images.githubusercontent.com/83365571/142457020-562b7267-7434-469e-b324-9a663b5bfcfa.png)
> 
> This is 7.6, but it looks like it's doing the same thing I was experiencing on 7.5.1 on after the StarsAVN prompt instead. Any ideas on how to solve?

Here's the beginning of the above attempt if that helps at all. 

![image](https://user-images.githubusercontent.com/83365571/142457972-146b58e1-42e2-4862-9cf9-82826c168df7.png)

**Comment by DIGITALCRIMINALS** [comment]
Does the auth.json get created?

**Comment by thisonehasnoame89** [comment]
> Does the auth.json get created?

yep.

**Comment by DIGITALCRIMINALS** [comment]
Try moving the Onlyfans 7.6 folder to it's separate folder

**Comment by thisonehasnoame89** [comment]
> Try moving the Onlyfans 7.6 folder to it's separate folder

No luck.

**Comment by DIGITALCRIMINALS** [comment]
what did the error look like this time

**Comment by thisonehasnoame89** [comment]
Running into the same issue with 7.6.1. I must be doing something wrong since the move to Python 3.10, but I've got no clue what.

**Comment by DIGITALCRIMINALS** [comment]
If you've got the latest commit, you can run "python start_ofd.py -v" and you may be able to see errors.
