### ISSUE TITLE
Onlyfans only downloading headers and avatars

### ISSUE THREAD

**Issue by rikkiran** [DIGITALCRIMINALS/OnlyFans#645]
When trying to download onlyfans content, it's only downloading the header and avatar photo of any profile I try. It looks like it scrapes all the videos and creates the appropriate folders, but it doesn't download anything, the folders are left blank. I tried changing the user_model.py code to the "list" fix, but that didn't solve it. Anything else I should try? I have the latest version.

**Comment by starboi4eva** [comment]
Getting this exact issue since Friday.

**Comment by Cr3g** [comment]
+1 for this error

**Comment by buzzlightyear1309** [comment]
same here

**Comment by ArionParadox** [comment]
I was able to find a work around by defining some settings in the config.json. `auto_site_choice` = "onlyfans", `auto_media_choice` = "videos" (I only wanted videos), and by added a model's username to `auto_model_choice`. It went through the entire list of all my creators and grabbed their headers and avatars and then after it finished that it came back and started downloading the videos of the model I was after.

**Comment by starboi4eva** [comment]
I ended up fixing the issue by switching to the master branch and using the fix from #604

**Comment by arkinson9** [comment]
@ArionParadox 
Perfect! Thank you for sharing this workaround. And by the way: it also works with pictures. Just set
`auto_media_choice = "2"`.

**Comment by djmarioka** [comment]
I'm now having this same issue, it only downloads avatars and headers. 

I've installed the version with Python 3.10 , latest Python version, and from this site: https://github.com/DIGITALCRIMINALS/OnlyFans.

Please, help me.

Thanks.
