### ISSUE TITLE
Has the OF login issue been mitigated yet?

### ISSUE THREAD

**Issue by Smackdab69** [DIGITALCRIMINALS/OnlyFans#649]
The solution in the previous thread did not work for me, and still I get logged out of OF whenever reloading the sess cookie in my auth.

**Comment by OFfriend** [comment]
`x-bc`, `cookie` and `user-agent` must be the same value like in your browser, otherwise OF invalidates your session.

**Comment by Dudeman456** [comment]
> `x-bc`, `cookie` and `user-agent` must be the same value like in your browser, otherwise OF invalidates your session.

Has it changed? before the recent api fix, in the cookie section I used to put auth_id, sess, auth_uniq, and auth_uid.

Is it the whole cookie field from the browser now?
