### ISSUE TITLE
No module named 'rich'

### ISSUE THREAD

**Issue by Reverand** [DIGITALCRIMINALS/OnlyFans#650]
Heya!  Feel like I could be missing a simple step, but keep getting the following when running 7.6.1

Traceback (most recent call last):
  File "~\OnlyFans-7.6.1\start_ofd.py", line 7, in <module>
    from rich import panel
ModuleNotFoundError: No module named 'rich'

(Truncated the path name when posting this.)

v7.3 was giving me auth issues, and given that I haven't run it in a few months, figured i was do for the update.  Worth noting: did up the auth.json with today's session and x_bc.

**Comment by Rhysdabeast** [comment]
`pip install rich`
