### ISSUE TITLE
AttributeError line 250, in get_stories

### ISSUE THREAD

**Issue by callmedjent** [DIGITALCRIMINALS/OnlyFans#653]
return future.result()
  File "E:\OnlyFans new\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "E:\OnlyFans new\datascraper\main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "E:\OnlyFans new\helpers\main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "E:\OnlyFans new\modules\onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "E:\OnlyFans new\modules\onlyfans.py", line 782, in prepare_scraper
    master_set = await subscription.get_stories()
  File "E:\OnlyFans new\apis\onlyfans\classes\create_user.py", line 250, in get_stories
    results = [create_story("x") for x in results.get("list")]
AttributeError: 'list' object has no attribute 'get'

was working fine for a while and then got this  tried deleting config and scraping with fresh config and then tried setting the 2,3,4,5,6,7 in the config still get this

**Comment by Mxecan** [comment]
I have the same issue.  I updated to the last patch yesterday and still get it.

**Comment by Arko109** [comment]
In `E:\OnlyFans new\apis\onlyfans\classes\create_user.py` change the line 250 to
```python
results = [create_story(x) for x in results]
```

**Comment by callmedjent** [comment]
> In `E:\OnlyFans new\apis\onlyfans\classes\create_user.py` change the line 250 to
> 
> ```python
> results = [create_story(x) for x in results]
> ```

already tried that makes a new error

**Comment by Arko109** [comment]
I just ran the script without errors with that line

**Comment by callmedjent** [comment]
some i can scrape fine and some shows no story but get that error

**Comment by Arko109** [comment]
I've modified the 270 too, like this
```python
results = [create_highlight(x) for x in results.get("list")]
```

**Comment by callmedjent** [comment]
i changed 270 to that lmao i tried just about everything in closed issues
