### ISSUE TITLE
Is this working for anyone anymore? Can you share your install?

### ISSUE THREAD

**Issue by xbbdc** [DIGITALCRIMINALS/OnlyFans#656]
I've cleared out my install and started over and still getting the loop of downloading headers and asking repeatedly to choose an option for the same model or going to a random model and nothing ever downloads no matter if i select all or videos.

I downloaded the 7.6.1 release, then overwrote it using the source and edited the user_model.py line 283 and it just loops.

**Comment by starboi4eva** [comment]
Had a lot of trouble on that commit. Try using the master branch instead.

**Comment by xbbdc** [comment]
> Had a lot of trouble on that commit. Try using the master branch instead.

I am using the branch master and edited the specific file. I just used the wrong word when i said "source"

**Comment by xbbdc** [comment]
Using this source - https://github.com/eclipseo/OnlyFans/archive/refs/heads/fix_message.zip

It does work after the 2nd attempt
