### ISSUE TITLE
Fansly Not Finding Paid Sub

### ISSUE THREAD

**Issue by TyranicalJim** [DIGITALCRIMINALS/OnlyFans#659]
Not sure what the issue is, but when I run the scraper for Fansly, it finds all my free subs and downloads any content, but it's not finding the one person I have a paid sub to. Their account name is not even shown in the list. 

It's seems to be due to the fact the profile doesn't have the option of the "follow" button. 

Any help greatly appreciated.

**Comment by mediaburnwayne** [comment]
It is directly related to not being able to follow. Any subs that do not have follow turned on the scraper totally ignores

**Comment by DIGITALCRIMINALS** [comment]
fixed
