### ISSUE TITLE
OF slowing/stopping this tool from downloading?

### ISSUE THREAD

**Issue by thebigfinch4991** [DIGITALCRIMINALS/OnlyFans#66]
Hey team. Used to be able to download 50+ GB of content from various OnlyFans creators with a consistent download speed of 10-15Mbps. These days, after launching the scraper, the download starts fast and quickly slows. Not sure if this is an OF server issue or if OF is getting wise and artificially slowing down/stopping these kinds of bulk downloads. 

Anyone else experiencing this or have a workaround for this issue?

**Comment by OFfriend** [comment]
sometimes OF server are just slow
