### ISSUE TITLE
Hangs at 0%. 

### ISSUE THREAD

**Issue by AngryRhino69** [DIGITALCRIMINALS/OnlyFans#660]
Hangs at 0%. When re-running the code, more data is downloaded and then hangs.
It initially downloads about 1.1MB/53GB.
Then goes from 1.1 MB downloaded to 3.49/53GB.
I run it a few times before giving up. Any ideas why this would happen? I initially had to manually pip install all of the dependencys.

**Comment by funkova9** [comment]
i have the same issue .... worked for me on another pc though ... i litearlly copied the whole thing to another pc and installed the poetry dependencies and it worked so don't know whats wrong

**Comment by AngryRhino69** [comment]
Poetry doesn't seem to install the required prereqs, so I have to manually install everything. I'm likely missing an install that's effecting the download portion.

**Comment by AngryRhino69** [comment]
If you turn messages and paid content to false in config it seems to work fine

**Comment by nealrobben** [comment]
@AngryRhino69 Which setting exactly turns the messages off in the config? I can find the setting for paid content, but nothing for messages
