### ISSUE TITLE
Blacklist not working properly

### ISSUE THREAD

**Issue by CheeseburgerWithFries** [DIGITALCRIMINALS/OnlyFans#661]
I've tried using the blacklist as described in the Readme with both making a list of models on OF and putting that in the config.json, and just listing the model names in the config, and it doesn't seem to work properly. The first thing the scraper seems to do is run through everyone who has sent you a message and scrape those, whether they're in the blacklist or not. I know that could be prevented by changing line 68 of the config from `"messages": true,"` to be false, but that would prevent the scraping of messages from models that I *do* want to download.

This seems like a case where one option is taking priority, when another should have it instead. If a model is in the blacklist, that should be the top priority of the scraper, nothing from that model should be downloaded, including messages.

**Comment by A-Random-Mf** [comment]
I just block them now

**Comment by rodlong7** [comment]
> by changing line 68 of the config from `"messages": true,"` to be false, but that would prevent the scraping of messages from models that I _do_ want to download.

False.  It will still scrape messages of models to whom your are subscribed.

**Comment by DIGITALCRIMINALS** [comment]
fixed
