### ISSUE TITLE
[Error] poetry install --no-dev

### ISSUE THREAD

**Issue by Texxer** [DIGITALCRIMINALS/OnlyFans#662]
I'm following the tutorial, but I'm failing with the first step. Is there a problem with poetry? Or do I have to install some modules manually?

![explorer_R4NKAJeKDm](https://user-images.githubusercontent.com/22458550/190279366-291698fa-7654-4a28-b692-05362a0b5ab4.png)

**Comment by subjectnorica** [comment]
I had this problem as well. For me, I had to run it with poetry in order to make it recognize the installed dependencies:

`poetry run python .\start_ofd.py`

**Comment by Texxer** [comment]
Thank you, I ended up installing all packages by hand and I can execute start_ofd.py now, but when the scraper runs, it would only create empty folders and not download any posts.

**Comment by Texxer** [comment]
I'm using "onlyfans-scraper" now. It's running for 30 minutes, supports parallel downloading and I was able to set it up in 5 minutes.

**Comment by aeonftw** [comment]
@Texxer  what do you mean by  "onlyfans-scraper" , do you refer to "that scraper"?
