### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by djmarioka** [DIGITALCRIMINALS/OnlyFans#665]
Hi,

I'm having this issue, and I can't access, it says: "Access denied":

![image](https://user-images.githubusercontent.com/81478245/190668078-fb79c7bd-8765-4fdd-be7a-b5cc35157b2c.png)

Please, help me.

Thanks.

**Comment by whoamikyo** [comment]
I was having the same problem, I noticed that after running  `python start_ofd.py`  my onlyfans session in the browser was closed, I changed the password, logged in again, got a new token and it worked.

**Comment by djmarioka** [comment]
I've tried to changing the password, but I'm always disconnected, I don't know if I've been flagged for something, or what, the error now is: "Something went wrong. [BB91C8D6]", and I'm always unlogged when I execute the script start_ofd.py:

![image](https://user-images.githubusercontent.com/81478245/190831587-529cd260-8686-4fd4-b7c1-8216905ab5bf.png)


Please, help me.

Thanks.

**Comment by Dudeman456** [comment]
Are you putting the entire Cookie content in the Auth file?

**Comment by djmarioka** [comment]
> 

The great issue is that I've been unlogged, even when I enter to the web, I'm unlogged in less than 1 minute, I don't know why, maybe that have I been banned?.

**Comment by blade2005** [comment]
Need to copy the cookie, user agent, and the x_bc

**Comment by djmarioka** [comment]
Hi, I cleared all the cookies in Chrome, and with these 2 commands, it worked well:

pip install poetry
poetry install --no-dev

And then, to run the script:

poetry run python ./start_ofd.py

Specially, I think the command that worked well was this one: **poetry install --no-dev** 

Thanks.

**Comment by sivra-d** [comment]
Just to add to this issue, I had to completely blow away my repo to fix this issue. None of the above steps worked for me

**Comment by Luke-L** [comment]
yeah i fixed it too by reinstalling the app. annoying but oh well
