### ISSUE TITLE
Is there a fix for just Scrape 1 model from onlyfans?

### ISSUE THREAD

**Issue by Fall0n** [DIGITALCRIMINALS/OnlyFans#669]
Is there a fix for just Scrape 1 model from onlyfans? And i dont need get from all the one i follow?

**Comment by mikulascapalay** [comment]
Is this a known bug ? I have tried to use the name of the profile in `auto_model_choice` but it doesn't work and I haven't tried to set up profiles. I don't know how.

**Comment by deadcode0815** [comment]
It would be nice if we had a option to do exactly that or any config. I couldn't figure out how to scrape a particular model

**Comment by 666diabolus** [comment]
@DIGITALCRIMINALS there's something wrong with the config file, it keeps scraping all the models even with the auto set to false

**Comment by rodlong7** [comment]
Make sure you have messages as false in your config.json file or it will scrape all messages so looks like it's scraping all models.

"jobs": {
          "scrape": {
            "subscriptions": true,
            "messages": false,
            "paid_content": false

**Comment by rodlong7** [comment]
> there's something wrong with the config file, it keeps scraping all the models even with the auto set to false

Make sure you have messages as false in your config.json file or it will scrape all messages so looks like it's scraping all models.

"jobs": {
"scrape": {
"subscriptions": true,
"messages": false,
"paid_content": false

**Comment by rodlong7** [comment]
> Is there a fix for just Scrape 1 model from onlyfans? And i dont need get from all the one i follow?

Use "auto_model_choice": false, and then just type the number next to the name of the model when it lists them all and will only scrape that model.

**Comment by rodlong7** [comment]
> Is this a known bug ? I have tried to use the name of the profile in auto_model_choice but it doesn't work and I haven't tried to set up profiles. I don't know how.

Profiles are your login account information, not the account you're trying to scrape.

**Comment by trsmith78** [comment]
> 
Hi,
Every time I  edit the config file to add:
"messages": false

When I start the scraper it it rewrites my config.
It opens it in a notepad window asking me to make whatever changes necessary.. Then press any key to continue...
