### ISSUE TITLE
After following all steps in #43 i am still getting error messages - can anyone help

### ISSUE THREAD

**Issue by Newdaymember17** [DIGITALCRIMINALS/OnlyFans#67]
![ofdl problem (2)](https://user-images.githubusercontent.com/93385822/139437034-d89e365a-5866-4960-87a9-e6efbcc6baa7.jpg)
I tried my best to look through other issues and followed all those steps but im still having problems. screenshot above. any help is awesome.

**Comment by americanseeder1865** [comment]
Are you pressing `0`

**Comment by Newdaymember17** [comment]
> Are you pressing `0`

I am yes

**Comment by americanseeder1865** [comment]
> > Are you pressing `0`
> 
> I am yes

Are you sure your're not just pressing the spacebar? That error can only occur when you input something  other than an integer. I am looking at your screen shot and I don't see you pressing 0 on your keyboard.

Press 0 and then hit the space bar

**Comment by Newdaymember17** [comment]
> > > Are you pressing `0`
> > 
> > 
> > I am yes
> 
> Are you sure your're not just pressing the spacebar? That error can only occur when you input something other than an integer. I am looking at your screen shot and I don't see you pressing 0 on your keyboard.
> 
> Press 0 and then hit the space bar

Dude I'm dumb. You still pointed me in the right direction. I must have pressed NumLock somewhere 😂. Works great now thank you.
