### ISSUE TITLE
Can I Edit The Auth File Again

### ISSUE THREAD

**Issue by Xoulzzz** [DIGITALCRIMINALS/OnlyFans#670]
I forgot to add the sess Id is it anyway I could restart the whole thing over or edit the auth.json file again

**Comment by burhanilinux** [comment]
go to Onlyfans folder /.profiles/Onlyfans/default/auth.json   edit it

**Comment by Xoulzzz** [comment]
On Tue, Sep 27, 2022 at 1:55 AM Burhani Linux ***@***.***>
wrote:

> go to Onlyfans folder /.profiles/Onlyfans/default/auth.json edit it
>
i appreciate it but I also had another problem downloading them they said
they were at 100% but none of them downloaded

**Comment by burhanilinux** [comment]
https://github.com/DIGITALCRIMINALS/OnlyFans/issues/663  refer this might help
