### ISSUE TITLE
Issue trying to run poetry install --no-dev

### ISSUE THREAD

**Issue by SarcasticOP** [DIGITALCRIMINALS/OnlyFans#674]
I ran the pip install poetry command in PowerShell and it looks like it ran fine. Then I try to run poetry install --no-dev and I get 

```
poetry : The term 'poetry' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
poetry install --no-dev

CategoryInfo          : ObjectNotFound: (poetry:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException

```
Not sure what I am doing wrong tbh, I am pretty new to Python. I usually have no issues when I follow instructions and can figure it out when I do have issues but I am against a brick wall on this. 

I am running v3.10.7 of Python

**Comment by jamiec101** [comment]
Python isn't in your environment variables. 

Open your environment variables in Windows and under _User Variables for (User)_ , edit the **Path** entry. Add a new entry for;
%USERPROFILE%\AppData\Roaming\Python\Scripts

Also check that this does exist as in my case it didn't. I needed to reinstall Python from github.

**Comment by Pawelecc** [comment]
I have the same problem. Changing "User Variables for (User)" did not help. Python 3.10.8

How to solve it?
