### ISSUE TITLE
Scraper only collects metadata - no media

### ISSUE THREAD

**Issue by dickscheney** [DIGITALCRIMINALS/OnlyFans#676]
I am unable to download any of the content scraped. It just proves the metadata/profile info for the profiles. Does anyone know a solution to this?

**Comment by championofdeath** [comment]
For me it only downloads videos and is ignoring the pictures.. Plus it always checks for all models profiles even if I specify only one.

**Comment by tullybulli** [comment]
Same issue as OP. Worked for me before, and Onlyfans-dl works without issue.
