### ISSUE TITLE
Missing posts...retrying

### ISSUE THREAD

**Issue by miglety** [DIGITALCRIMINALS/OnlyFans#677]
Running into an issue today where as soon as it finishes the first part of the script with the purple bars i get this and cannot figure out what to do to get past it.

Renaming files.
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 57.27it/s]
Scraping Subscriptions
Scrape Processing
Name: removed
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Missing 1000 Posts... Retrying...
Scrape Attempt: 2/100

**Comment by thepetcow** [comment]
I am also experiencing this issue. I've noticed that when it happens and I try and login to OF in the browser, it's making me wait 15 seconds.

**Comment by supergimp** [comment]
Seeing the same. It's hanging up on a subscription that has expired but still shows up in my list of available subs when running the script but the sub is expired and not available on the web. I.e. it's scraping an expired sub and so posts are missing. Happens to be the first one on the list. Once it gets past retrying 100 times it continues properly on the remaining subs.
