### ISSUE TITLE
Can anyone get this work anymore?

### ISSUE THREAD

**Issue by procdaddy11** [DIGITALCRIMINALS/OnlyFans#681]
I keep trying on almost a weekly basis. I'll delete the repo and start from scratch.

It pulls in the models acts like it's scraping and doesn't do any scraping.

Are there new steps I'm missing?

It used to work flawlessly.

**Comment by taux1c** [comment]
I haven't been able to use it in years. I just use the one I maintain now. You may try the docker version and get some luck. That's all I was able to use back then.

**Comment by jp1151419** [comment]
> I haven't been able to use it in years. I just use the one I maintain now. You may try the docker version and get some luck. That's all I was able to use back then.
> 
> That said, what errors do you get?

Does yours still work with message content too? I just can get that part to scrape so I have paid content in messages from both active and expired subs not getting downloaded.

**Comment by hydr0homiee** [comment]
> > I haven't been able to use it in years. I just use the one I maintain now. You may try the docker version and get some luck. That's all I was able to use back then.
> > That said, what errors do you get?
> 
> Does yours still work with message content too? I just can get that part to scrape so I have paid content in messages from both active and expired subs not getting downloaded.

I think that's something on OF's end. I think paid messages are handled differently starting ~June 2022 and the scraper hasn't been adapted to whatever new process OF is using.

I'm able to download all paid content up to June for every account I've tested, but all unlocked paid content after June is skipped. All free/non-locked content from walls and messages get downloaded fine.

**Comment by jp1151419** [comment]
> I'm using the 7.6.1 release with the hotfix, not master.

I tried both amongst other versions but all had the same issue with paid messages. The weird thing is I have recent paid messages that have scraped just fine but older messages only recently unlocked won't scrape.

**Comment by MonkeyKingViper** [comment]
> I keep trying on almost a weekly basis. I'll delete the repo and start from scratch.
> 
> It pulls in the models acts like it's scraping and doesn't do any scraping.
> 
> Are there new steps I'm missing?
> 
> It used to work flawlessly.

Yes I'm using it right now and it's working great. Rolled my IP on my IP so took a min to log in and auth in but everything has always worked (near) flawlessly.

**Comment by soulburn74** [comment]
I went back to the 'base download' 7.6.1. Do not update it. It works for the most part. There's a few bugs that don't seem to work when trying to manipulate the config.json but it works fine in its default config for me, and has for some time. Its when I attempt to update it, that things start go haywire. I think the dev has stopped actively fixing this script to work on his gui-ish version, although I haven't seen any mention of this in a few months by him, so not sure where that stands either.
