### ISSUE TITLE
OnlyFans download speed capped?

### ISSUE THREAD

**Issue by kccomikeyga** [DIGITALCRIMINALS/OnlyFans#687]
I have gigabit fiber internet and scraping any content seems to be capped around 7-8 MB/s. 

I’ve tried running speed tests to confirm it’s not a hardware issue and I’ve also tried to scrape while using a VPN to “mask” the traffic to confirm it’s not an IP blacklist/throttle issue. 

Has anybody else noticed anything like this in the past couple days?

**Comment by hydr0homiee** [comment]
I think it's an issue with your network. I get 15-20MB/s on gigabit with a wired connection.

**Comment by A-Random-Mf** [comment]
Gigabit here as well. Hopefully this is helpful. I used to run the scraper in a Windows vm, only saw sub 15 mb/s . I switched to an ubuntu vm , now seeing speeds between 40 and 90 mb/s. Windows vm had an indirect connection to the host filesystem, ubuntu vm’s connection is much more direct.

**Comment by kccomikeyga** [comment]
I’m going to try moving from a VM to a spare computer I have. Gonna end up scraping to the same share on my NAS.
