### ISSUE TITLE
Stops at the same place every time you download

### ISSUE THREAD

**Issue by NoPatience7** [DIGITALCRIMINALS/OnlyFans#697]
![QQ截图20221112194202](https://user-images.githubusercontent.com/117753653/201472382-a8803067-46aa-41d6-8ed2-4c3244fc7896.png)
Please help me

**Comment by rciptv2019** [comment]
Same

**Comment by Jakeyy22** [comment]
Are you running the script via Double clicking the start_ofd.py file?

I get the same doing it that way, and have to run the script via CMD/Powershell and manually running with the command poetry run python ./start_ofd.py

So seems to be an issue with Poetry not running via double click.
