### ISSUE TITLE
Stuck on Scrape attempt retrying

### ISSUE THREAD

**Issue by tfot1234** [DIGITALCRIMINALS/OnlyFans#705]
Just started getting this when it gets to scraping my subscriptions, happens when I do all or just select a single model. Just keeps retrying until it eventually stops. Things were working fine a couple of days ago.

Scraping Subscriptions
Scrape Processing
Name: trixytaylor
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Missing 4100 Posts... Retrying...
Scrape Attempt: 2/100
Missing 4100 Posts... Retrying...
Scrape Attempt: 3/100
Missing 8200 Posts... Retrying...
Scrape Attempt: 4/100
Missing 10933 Posts... Retrying...
Scrape Attempt: 5/100
Missing 16400 Posts... Retrying...
Scrape Attempt: 6/100
Missing 23680 Posts... Retrying...
Scrape Attempt: 7/100
Missing 4666 Posts... Retrying...
Scrape Attempt: 8/100
Missing 1714 Posts... Retrying...
Scrape Attempt: 9/100
Missing 1100 Posts... Retrying...
Scrape Attempt: 10/100
Missing 1300 Posts... Retrying...
Scrape Attempt: 11/100
Missing 1740 Posts... Retrying...
Scrape Attempt: 12/100
Missing 1818 Posts... Retrying...
Scrape Attempt: 13/100
Missing 3333 Posts... Retrying...
Scrape Attempt: 14/100
Missing 6153 Posts... Retrying...
Scrape Attempt: 15/100
Missing 11428 Posts... Retrying...
Scrape Attempt: 16/100
Missing 21333 Posts... Retrying...
Scrape Attempt: 17/100
Missing 40000 Posts... Retrying...
Scrape Attempt: 18/100
Missing 75294 Posts... Retrying...

**Comment by BathingGorilla** [comment]
Same

**Comment by BathingGorilla** [comment]
Its working now for me now. Must have been an api issue?

**Comment by tfot1234** [comment]
My issue seemed to be that the specific subscription it was stuck on expired today but was still showing up in my subscriptions. Working now.

**Comment by BathingGorilla** [comment]
Youre right. It happened again so I excluded an expired subscription and it started working again.

**Comment by mstiggles** [comment]
I am having this on two subscriptions that are not expired. any help would be great. all other subscriptions are working fine.
