### ISSUE TITLE
dynamic_rules potentially break the routes pagination

### ISSUE THREAD

**Issue by bytadaniel** [DIGITALCRIMINALS/OnlyFans#707]
I ran into a problem when requesting a user's chats. Specifically, I'm confused by this code
```ts
path = query ? `${path}/${query}` : path
```

Due to the fact that query parameters are passed, this route fails with an error.

If you comment out this line, that is, pass only path without query to the hash, then the route request returns 200 and the first 10 chats, but pagination does not work

As I understand it, because the query parameters are not taken into account in sign

### Photo 1 (requesting user chats)
<img width="696" alt="Снимок экрана 2022-12-01 в 22 14 09" src="https://user-images.githubusercontent.com/59475531/205155334-29a847d1-08d2-49cb-8d2f-a1f7700d5785.png">

### Photo 2 (photo 1 logs)
<img width="684" alt="Снимок экрана 2022-12-01 в 22 50 01" src="https://user-images.githubusercontent.com/59475531/205156749-10d29479-3b2c-4c06-b19e-d9784e8025dc.png">

### Photo 3 (create sign headers function)
<img width="743" alt="Снимок экрана 2022-12-01 в 22 14 26" src="https://user-images.githubusercontent.com/59475531/205155385-f14172be-aa3f-4aad-a40d-9176b8e621ea.png">

### Photo 4 (its logs)
<img width="700" alt="Снимок экрана 2022-12-01 в 22 14 35" src="https://user-images.githubusercontent.com/59475531/205155381-62a8400b-c363-4791-8aff-2a86905c5b73.png">

**Comment by bytadaniel** [comment]
Same with subscriptions route.

**Comment by DIGITALCRIMINALS** [comment]
Personally, I use ```https://onlyfans.com/api2/v2/chats?limit={global_limit}&offset={global_offset}&order=desc``` to get the chats

**Comment by bytadaniel** [comment]
It actually works. The point of my problem was the wrong way of using headers. This issue have to be closed
