### ISSUE TITLE
only scraping one image per post?

### ISSUE THREAD

**Issue by penguinpatrol** [DIGITALCRIMINALS/OnlyFans#708]
i have noticed that whenever i scrape images from onlyfans it is only picking a single image from a post instead of all images from a single post i am wondering if there is a way to scrape every image on each post?

**Comment by DIGITALCRIMINALS** [comment]
Are you using the latest commit of the script? Do it still do this?

**Comment by penguinpatrol** [comment]
i sorted the issue as it was deleting any file with the same name i added the post id so each image / video was named differently so it fixed it
