### ISSUE TITLE
Scrapers ignores inactive models

### ISSUE THREAD

**Issue by NoName95x** [DIGITALCRIMINALS/OnlyFans#709]
I have a model with paid content, but she is inactive now. I can still see her stuff by going to the purchased tab.

This scraper seems to ignore her existence, and doesnt get any of her content. 

Is it techinically possible to get her content?

edit:

I set 
```
"auto_model_choice": true,
        "auto_api_choice": true,
```
in my config.json and it grabbed her stuff.
Perhaps this can be implemented in an official way?

**Comment by DIGITALCRIMINALS** [comment]
fixed
