### ISSUE TITLE
Not downloading paid message that was deleted.

### ISSUE THREAD

**Issue by sxdent21** [DIGITALCRIMINALS/OnlyFans#710]
Sorry if this has been asked.

I purchased a message that has been deleted, I can still see it in the purchased tab, but the scraper isn't downloading it. Does anyone know how to fix this?

Here is my config
```json
"settings": {
  "auto_profile_choice": "default",
  "auto_model_choice": [
    "urlilgoddess"
  ],
  "auto_api_choice": true,
  "auto_media_choice": "0",
  "browser": {
    "auth": true
  },
  "jobs": {
    "scrape": {
      "subscriptions": true,
      "messages": true,
      "paid_content": true
    },
    "metadata": {
      "posts": true,
      "comments": true
    }
  },
```

**Comment by jp1151419** [comment]
I have the same annoying issue. You can find the files using the purchased filter on the front page and manually download those odd cases from there.

**Comment by DIGITALCRIMINALS** [comment]
Should be fixed
