### ISSUE TITLE
Please refresh the page

### ISSUE THREAD

**Issue by hammerheaddf** [DIGITALCRIMINALS/OnlyFans#715]
Seems the dynamic rules expired again. I keep getting that error on both my accounts:
```
Auth (V1) Attempt 1/10
Please refresh the page
```

**Comment by sonicshake** [comment]
Looks like dynamic rules have now been updated and it works again

**Comment by xagler** [comment]
> Looks like dynamic rules have now been updated and it works again

Its updated, but still broken

**Comment by sonicshake** [comment]
> > Looks like dynamic rules have now been updated and it works again
> 
> Its updated, but still broken

I'm ripping right now with no probs

**Comment by lordoffools** [comment]
Thanks for the speedy resolution!
