### ISSUE TITLE
IMPROVEMENT SUGGESTION: Download Content Immediately After Scraping

### ISSUE THREAD

**Issue by Nick05491** [DIGITALCRIMINALS/OnlyFans#723]
@DIGITALCRIMINALS,
When "0 = All" is selected, I feel like it would be more logical to download content immediately after scraping, before moving on to scraping the next model.  In other words, 'Scrape ModelX, Download Model X, Scrape Model Y, Download Model Y, Scrape ModelZ, Download ModelZ'.

The issue I see with the current flow of scraping all models and then downloading is that it increases the liklihood that the content found during the scrape will no longer be available when it comes time to download - this is especially true if following many models (I'm at 250+) and/or using an older machine.  Stories in particular are an issue here, but it's also not uncommon for models to have posts and messages that dissapear after say 24hrs.

I recall a response of yours from a while back mentioning that you didn't know any way to scrape and download in parallel.  Note that my suggestion is different from this.  All code execution would be linear, just ran in what I beleve to be a more logical order.  Thoughts?

As always, thanks for your work on this script!

**Comment by DIGITALCRIMINALS** [comment]
I plan to make scraping and downloading asynchronous/threaded, as in once a single post is scraped, it'll immediately start  downloading in the background.
