### ISSUE TITLE
Onlyfans not scraping all messages

### ISSUE THREAD

**Issue by tim1f1** [DIGITALCRIMINALS/OnlyFans#724]
When I scrape a profile and then check the metadata, onlyt he 40 or so most recent messages show up n the "messages" tab. This also means that a bunch of media isn't getting downloaded either.

**Comment by TheMissingPort** [comment]
Bump,

For some reason. not all posts are scraping. Seems like the more recent stuff isn't. And not just messages

**Comment by DIGITALCRIMINALS** [comment]
Messages should be fixed
