### ISSUE TITLE
THE SCREEN CLOSES - ERRORS IN LINES 66, 44, 646, 52, 131, 55, 963

### ISSUE THREAD

**Issue by djmarioka** [DIGITALCRIMINALS/OnlyFans#728]
Hi,

I'm having this error, since several days ago, the screen closes itself, and I can't download anything, it closes at last time, when it starts downloading, the error is this one:

![image](https://user-images.githubusercontent.com/81478245/208969601-e527c1a3-c3ff-4c2b-a33d-e1ceb3afe29c.png)

The errors are in lines 66, 44, 646, 52, 131, 55, 963.

Could anybody help me?.

Thanks.

**Comment by DIGITALCRIMINALS** [comment]
fixed
