### ISSUE TITLE
downloads a single image and then stops

### ISSUE THREAD

**Issue by shiet4brains** [DIGITALCRIMINALS/OnlyFans#732]
Login and scraping appears to work fine.

However when it gets to processing the downloads, only a single file seems to download.

By default it was trying to download like 10 files at a time - and I could see those 'part' files in the download folder. With only a single image completing.

I tried adjusting the threads to reduce the number of downloads, still only a single file appears to download and then it hangs and does nothing else.

When I restart, it downloads another file. Each time I restart it, it downloads a new file.

**Comment by shiet4brains** [comment]
I did some more random testing and... I note that if I select the option "2" to download videos the program actually downloads all of the images and videos from the profile.

If I select option "1" for just images , it downloads a single image and then hangs.

Strange behavior. Anyone else notice?

**Comment by DIGITALCRIMINALS** [comment]
It should be fixed in the latest commit
