### ISSUE TITLE
【Scrape Completed】but didn't download anything

### ISSUE THREAD

**Issue by mjbada** [DIGITALCRIMINALS/OnlyFans#742]
![微信图片_20221229124127](https://user-images.githubusercontent.com/70135133/209904307-926d3ed8-a12d-4e54-b5c0-d4ec821d4138.png)

**Comment by kccomikeyga** [comment]
There's a bunch of us experiencing the same issue and we're patiently waiting for @DIGITALCRIMINALS to release an update.

**Comment by PingOfD32th** [comment]
good news and bad news: 
good news: [THIS WORKS](https://github.com/DIGITALCRIMINALS/OnlyFans/issues/679#issuecomment-1356768986)
bad news: you wont be able to scrape anything you bought/got in messages

**Comment by kccomikeyga** [comment]
So set line 68 to "false" or delete line 68 entirely?

**Comment by savagejimmy85** [comment]
This fix does not appear to be working for me. 
Confirming this is correct from config.json:
  "supported": {
    "onlyfans": {
      "settings": {
        "auto_profile_choice": [],
        "auto_model_choice": "all",
        "auto_api_choice": true,
        "auto_media_choice": "all",
        "browser": {
          "auth": true
        },
        "jobs": {
          "scrape": {
            "subscriptions": true,
            "messages": false,
            "paid_contents": true
          },
          "metadata": {
            "posts": true,
            "comments": true
          }
        },
