### ISSUE TITLE
Won't launch after update

### ISSUE THREAD

**Issue by evilwadewilson** [DIGITALCRIMINALS/OnlyFans#745]
Upon launch I get this error: 
  File "C:\Users\other\OnlyFans-master\start_ofd.py", line 37, in <module>
    config, _updated = main_helper.get_config(config_path)
  File "C:\Users\other\OnlyFans-master\helpers\main_helper.py", line 780, in get_config
    converted_object = make_settings.Config(**new_json_config)
  File "C:\Users\other\OnlyFans-master\classes\make_settings.py", line 262, in __init__
    self.settings = Settings(**settings)
TypeError: Settings.__init__() got an unexpected keyword argument 'tui'

Can anyone help?

**Comment by DIGITALCRIMINALS** [comment]
Download fresh version of script.

**Comment by frustra1** [comment]
> Download fresh version of script.

not op but same problem, ive downloaded a fresh version of the script and i get error use py version 3.9

ive gone back and forth installing and uninstalling different versions of python and that doesnt work at all. found an older version of the script on a hard drive and the script actually boots off of that one but gets stuck at the authorization stage. if i update the script using the update tool i get

Traceback (most recent call last):
  File "F:\OnlyFans-master\start_ofd.py", line 26, in <module>
    main_test.check_config()
  File "F:\OnlyFans-master\tests\main_test.py", line 28, in check_config
    import ultima_scraper_api.helpers.main_helper as main_helper
ModuleNotFoundError: No module named 'ultima_scraper_api'

**Comment by PsychoSid** [comment]
Can you try `poetry update` as per https://github.com/DIGITALCRIMINALS/OnlyFans/issues/746 as this worked for me with missing modules.

**Comment by frustra1** [comment]
> 

I’ve tried it.

**Comment by frustra1** [comment]
> Can you try `poetry update` as per #746 as this worked for me with missing modules.

ive tried and still get the same error

PS C:\Users\Admin\Downloads\Compressed\OnlyFans-master> poetry update
Updating dependencies
Resolving dependencies... (9.5s)

No dependencies to install or update
PS C:\Users\Admin\Downloads\Compressed\OnlyFans-master>

When i try to run the scraper after this it tells me to use python 3.9
