### ISSUE TITLE
Can't open any of the scripts

### ISSUE THREAD

**Issue by AgentBlue14** [DIGITALCRIMINALS/OnlyFans#746]
I've used this script before but now that I have a fresh install of Windows, I can't seem to run any of the scripts without errors.

I have Python 3.10.9 installed, and was able to run the `poetry install --no-dev` command, but when I try to run `poetry run python start_us.py`,  I get the following error:

`Traceback (most recent call last):
  File "C:\Users\[User name]\Downloads\OFS\start_us.py", line 9, in <module>
    from ultima_scraper_api.helpers.main_helper import OptionsFormat
ModuleNotFoundError: No module named 'ultima_scraper_api'`

And when I try `poetry run python start_ofd.py`:

`Traceback (most recent call last):
  File "C:\Users\[User Name]\Downloads\OFS\start_ofd.py", line 7, in <module>
    from rich import print
ModuleNotFoundError: No module named 'rich'`

Not sure what I'm doing wrong (if anything), but I seem to have everything in order and it's not up at all. Any help is appreciated, thanks!

**Comment by DIGITALCRIMINALS** [comment]
Try ```poetry update```

**Comment by AgentBlue14** [comment]
> Try `poetry update`

Thanks for replying!

It looks like my Poetry version was out of date, and that did fix the issue I posted about.

I am running into another one however once I have the `config.json` and `auth.json` files filled out properly:

![image](https://user-images.githubusercontent.com/121831486/210301264-9b8e6182-6114-4726-93da-ccef25961dbd.png)

**Comment by Xknight79** [comment]
> Try `poetry update`

I tried but got this error
C:\Onlyfans 1\OnlyFans-master>poetry update
'poetry' is not recognized as an internal or external command,
operable program or batch file.

**Comment by DIGITALCRIMINALS** [comment]
> > Try `poetry update`
> 
> Thanks for replying!
> 
> It looks like my Poetry version was out of date, and that did fix the issue I posted about.
> 
> I am running into another one however once I have the `config.json` and `auth.json` files filled out properly:
> 
> ![image](https://user-images.githubusercontent.com/121831486/210301264-9b8e6182-6114-4726-93da-ccef25961dbd.png)

There's an unexpected character in your config so it's not filled out properly
