### ISSUE TITLE
Chat Messages (JSON) Downloader

### ISSUE THREAD

**Issue by DenizOzt** [DIGITALCRIMINALS/OnlyFans#75]
Can you add a feature to download chat messages in json

**Comment by DIGITALCRIMINALS** [comment]
Just use the database

**Comment by DIGITALCRIMINALS** [comment]
If you want JSON, you can use https://sqlitebrowser.org/ and export the message table as JSON.

I had to move away from JSON because it was getting messy and it would get corrupted.
