### ISSUE TITLE
Can't find pyproject.toml

### ISSUE THREAD

**Issue by frustra1** [DIGITALCRIMINALS/OnlyFans#750]
Poetry could not find a pyproject.toml file in C:\Users\Admin\Downloads\Compressed\OnlyFans-master\OnlyFans-master or its parents

Script stopped working yesterday, downloaded a new copy ran "pip install poetry" just fine but when I "run poetry install --no-dev" I get the error message in the above comment. Any ideas?

**Comment by DIGITALCRIMINALS** [comment]
You have to use commands in the foldder where the pyproject file is located in

**Comment by frustra1** [comment]
i have been

**Comment by DIGITALCRIMINALS** [comment]
it's start_us.py

**Comment by frustra1** [comment]
just crashes as soon as i open it
