### ISSUE TITLE
Error When Installing Poerty

### ISSUE THREAD

**Issue by Nido21100** [DIGITALCRIMINALS/OnlyFans#753]
Hi all, was wondering if i could get some help. Made the error of updating the script lol but whne im trying to install the poerty repository i keep getting this error, any clues to resolving this?

Package operations: 13 installs, 0 updates, 0 removals

  • Installing user-agent (0.1.10)

  EnvCommandError

  Command "C:\Users\Omega Gaming\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Lb4fMpbo-py3.10\Scripts\pip.exe" install --no-deps file:///C:/Users/Omega%20Gaming/AppData/Local/pypoetry/Cache/artifacts/c0/f1/c7/a620f666a07651ebba6870ff394d9e14e5c8eb2c953490e8c49b3f67c4/user_agent-0.1.10.tar.gz errored with the following return code 1, and output:
  Processing c:\users\omega gaming\appdata\local\pypoetry\cache\artifacts\c0\f1\c7\a620f666a07651ebba6870ff394d9e14e5c8eb2c953490e8c49b3f67c4\user_agent-0.1.10.tar.gz
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'error'
    error: subprocess-exited-with-error

    python setup.py egg_info did not run successfully.
    exit code: 1

    [1 lines of output]
    ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
    [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: metadata-generation-failed

  Encountered error while generating package metadata.

**Comment by DIGITALCRIMINALS** [comment]
Make sure you're using Python 3.10.1+

**Comment by medlhed420** [comment]
@DIGITALCRIMINALS 
I am having this same issue. I was already running Python 3.10.1

I have upgraded to 3.10.9 and I am still getting the error when tying to run the update script.

    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'error'
    error: subprocess-exited-with-error

    python setup.py egg_info did not run successfully.
    exit code: 1

    [1 lines of output]
    ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.

I tried to run pip install setuptools but it says Requirement already satisfied
