### ISSUE TITLE
Scrapper free content

### ISSUE THREAD

**Issue by GreedyGhost1** [DIGITALCRIMINALS/OnlyFans#755]
Could anybody please explain why it only scrapes free content to the .sites folder? If it's user error please let me know. Any hints as to what I'm doing wrong are appreciated

**Comment by basketballhead6** [comment]
The tool doesn't scrape paid posts / contents that you haven't paid for. 

If paid posts / content aren't downloading, make sure paid_contents in config.json is set to true.

**Comment by GreedyGhost1** [comment]
I see, thank you for the response!

**Comment by MillerTimeJones** [comment]
I can't get it to even dump free content let alone pay.

**Comment by kccomikeyga** [comment]
> I can't get it to even dump free content let alone pay.

https://github.com/DIGITALCRIMINALS/OnlyFans/issues/742

**Comment by MillerTimeJones** [comment]
> > I can't get it to even dump free content let alone pay.
> 
> @MillerTimeJones are you getting any error messages? If you are add them below

I didn't see any errors.

**Comment by basketballhead6** [comment]
> > > I can't get it to even dump free content let alone pay.
> 
> > 
> 
> > @MillerTimeJones are you getting any error messages? If you are add them below
> 
> 
> 
> I didn't see any errors.

@MillerTimeJones Have you tried the fixes in #742?
