### ISSUE TITLE
Can I download Avatar/Profile from users I'm not subscribed to?

### ISSUE THREAD

**Issue by Scathachnyx** [DIGITALCRIMINALS/OnlyFans#76]
For instance I want to download her avatar at the original resolution uploaded: https://onlyfans.com/zoemillerof

She's showing her bare breasts which never did on any social media, all of that stuff is paid but she just changed to that avatar. If can't be done with the scrapper I'd love to know any other way I can do that. Thanks!

**Comment by DIGITALCRIMINALS** [comment]
Search for "api" then click her username, you'll see the avatar and header items on the right hand side
![image](https://user-images.githubusercontent.com/89371864/139919598-42e02711-7c6f-4714-ac0b-c7a55843829c.png)
