### ISSUE TITLE
Fansly scraper no longer works

### ISSUE THREAD

**Issue by machinesean** [DIGITALCRIMINALS/OnlyFans#762]
Today Fansly rolled out an "updated app" and seems to have broken the Fansly ripper. Was working just the day before yesterday, so I suspect the latest update is at fault.

**Comment by AlexDucks** [comment]
I'm using the version from September (this commit: 71eb8df900e82382bc344aaef92a5975363caeae) and the Fansly scraper still works fine for me.

If you're using the v7.6.1 "release", then you are probably better off grabbing the code from my version instead: https://github.com/DIGITALCRIMINALS/OnlyFans/tree/71eb8df900e82382bc344aaef92a5975363caeae

Or you could try the latest version on "master", but I'm not sure if it's ready to be used.

**Comment by Max345** [comment]
Working fine for me using latest version
