### ISSUE TITLE
[WinError 3] The system cannot find the file specified

### ISSUE THREAD

**Issue by Telandriq** [DIGITALCRIMINALS/OnlyFans#764]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'OnlyFans\\redacted\\Metadata'

No matter what I've done trying to bypass this user's metadata issue keeps returning this error. This user deleted their onlyfans before my month was up so I assume that's partially where the issue is. I have their metadata in the metadata folder from pulling prior to the deletion.

I moved that user's metadata out of the folder to see if it would redownload the metadata, that didn't work.
I wiped out my metadata folder and allowed it to redownload every user, that didn't work.
I have the user added to the block list and was blocking individually, that didn't work.

Not sure what else I can do as the script seems to run well until it gets to that user.

**Comment by Telandriq** [comment]
https://pastebin.com/aM8YrVRV

here is config.json

**Comment by DIGITALCRIMINALS** [comment]
Does this still happen on the latest commit?

**Comment by Telandriq** [comment]
> Does this still happen on the latest commit?

No, it runs through now with the bug from #817 now.
