### ISSUE TITLE
Scraping creator downloads nothing, skips to next creator

### ISSUE THREAD

**Issue by passeee** [DIGITALCRIMINALS/OnlyFans#767]
I dont get any errors, tried it already with the latest release and code, with "onlyfans-fix_api", "onlyfans-fix_message" but nothing gets downloaded anymore, and update.py doesnt do anything either

Choose Profiles: 0 = All | 1 = default
1
Choose Subscriptions: 0 = All | 1 = therealmissbo | 2 = trippie_bri_free | 3 = nataliereynoldss | 4 = barbora99 | 5 = alyssakulani | 6 = l4e4x4i | 7 = prosexxfreepage | 8 = belindanohemy | 9 = machi.003 | 10 = callmeolivia00 | 11 = danurafree | 12 = jamelizzzzfree | 13 = freedellieisla | 14 = laraaafree | 15 = marybabykitty | 16 = killrktty | 17 = stfusunhiko | 18 = theparisangel | 19 = carolinasamani | 20 = maligoshik.a | 21 = linabelfiore | 22 = miaabrown | 23 = theparisangelfree | 24 = u160864533 | 25 = elenakamperi | 26 = albashy | 27 = ginalaitschek | 28 = hiitssenya | 29 = angelolsen | 30 = chlostar | 31 = diakimeko | 32 = babybellllzzzz | 33 = gwendolynceline | 34 = zirakillz | 35 = hempresskc | 36 = laraaapremium
34
Scraping Subscriptions
Scrape Processing
Name: zirakillz
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
2
Type: Stories
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Processing Scraped Posts
100%|██████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 1590.86it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|██████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 3996.48it/s]
Type: Archived
Type: Chats
Type: Messages
Type: Highlights
Type: MassMessages
Scrape Completed

Scraping Paid Content
Scraping - therealmissbo | 1 / 36
Scraping - trippie_bri_free | 2 / 36
Scraping - nataliereynoldss | 3 / 36
Scraping - barbora99 | 4 / 36
Scraping - alyssakulani | 5 / 36
Scraping - l4e4x4i | 6 / 36
Scraping - prosexxfreepage | 7 / 36
Scraping - belindanohemy | 8 / 36
Scraping - machi.003 | 9 / 36
Scraping - callmeolivia00 | 10 / 36
Scraping - danurafree | 11 / 36
Scraping - jamelizzzzfree | 12 / 36
Scraping - freedellieisla | 13 / 36
Scraping - laraaafree | 14 / 36
Scraping - marybabykitty | 15 / 36
Scraping - killrktty | 16 / 36
Scraping - stfusunhiko | 17 / 36
Scraping - theparisangel | 18 / 36
Scraping - carolinasamani | 19 / 36
Scraping - maligoshik.a | 20 / 36
Scraping - linabelfiore | 21 / 36
Scraping - miaabrown | 22 / 36
Scraping - theparisangelfree | 23 / 36
Scraping - u160864533 | 24 / 36
Scraping - elenakamperi | 25 / 36
Scraping - albashy | 26 / 36
Scraping - ginalaitschek | 27 / 36
Scraping - hiitssenya | 28 / 36
Scraping - angelolsen | 29 / 36
Scraping - chlostar | 30 / 36
Scraping - diakimeko | 31 / 36
Scraping - babybellllzzzz | 32 / 36
Scraping - gwendolynceline | 33 / 36
Scraping - zirakillz | 34 / 36
Processing Scraped Posts
100%|██████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 4000.29it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|██████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 4007.94it/s]
Scraping - hempresskc | 35 / 36
Scraping - laraaapremium | 36 / 36
Scraping Message Content
Scrape Processing
Name: the444thday
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
2
Type: Messages
Processing Scraped Messages
100%|█████████████████████████████████████████████████████████████████████████████| 107/107 [00:00<00:00, 10584.93it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|████████████████████████████████████████████████████████████████████████████████| 93/93 [00:00<00:00, 5459.19it/s]
Scrape Completed

Scrape Processing
Name: the444thday
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts

**Comment by kccomikeyga** [comment]
https://github.com/DIGITALCRIMINALS/OnlyFans/issues/742
