### ISSUE TITLE
scrape attempt, missing posts, retrying

### ISSUE THREAD

**Issue by mstiggles** [DIGITALCRIMINALS/OnlyFans#770]
Hi, I have researched similar posts but still not able to detect how to resolve.

With two of my subscriptions, that are still active, I am getting the scrap attempt, missing posts issue.

I changed max threads from -1 to 1.

Otherwise I'm at a loss.

Scrape Processing
Name: kirsten_price
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Missing 300 Posts... Retrying...
Scrape Attempt: 2/100
Missing 300 Posts... Retrying...
Scrape Attempt: 3/100
Missing 600 Posts... Retrying...
Scrape Attempt: 4/100
Missing 800 Posts... Retrying...
Scrape Attempt: 5/100
Missing 1200 Posts... Retrying...
Scrape Attempt: 6/100
Missing 1920 Posts... Retrying...
Scrape Attempt: 7/100
Missing 3200 Posts... Retrying...
Scrape Attempt: 8/100
Missing 5485 Posts... Retrying...
Scrape Attempt: 9/100
Missing 9600 Posts... Retrying...
Scrape Attempt: 10/100
Missing 17066 Posts... Retrying...
Scrape Attempt: 11/100

**Comment by Proxibyte** [comment]
i had the same issue then updated python to 3.11 and it fixed it for me

**Comment by mstiggles** [comment]
so I installed 3.11 and uninstalled 3.10 but now scraper won't start. :(

**Comment by Proxibyte** [comment]
make sure its in path, rerun the requirements and if you're using win10 remove the shortcut in settings (manage execution aliases)

**Comment by mstiggles** [comment]
I'm sorry. when you say "make sure it in path"? what do you mean?

I'm using Win10 but what shortcut in settings? where is manage execution aliases?

**Comment by Proxibyte** [comment]
when you install python on the first screen it has the option to add directory to path. 

if you didnt or cant remember, search on your start bar for system environmental variables. once opened theres a button on the bottom called environmental variables. Once opened in the top list where it says "User variables for ____" there should be one that says "Path". Select that and hit edit. 
Should open a list of directories, there should be 4 for python:
"C:\Users\*Name*\AppData\Local\Programs\Python\Python311\Scripts\"
"C:\Users\*Name*\AppData\Local\Programs\Python\Python311\"
"C:\Users\*Name*\AppData\Roaming\Python\Python311"
"C:\Users\*Name*\AppData\Roaming\Python\Python311\Scripts"

If they arent there, add them with the "New" button. If there are any old ones there that have the same directories but wrong python number, delete them. Dont delete any others, just the old python ones.

For the shortcut in settings if you have it, open settings and theres a search bar, type in "manage app execution aliases" and open it. If there is a python one there disable it.

That should be it, try run the script again and it should work.

**Comment by Proxibyte** [comment]
when you install python on the first screen it has the option to add directory to path. 

if you didnt or cant remember, search on your start bar for system environmental variables. once opened theres a button on the bottom called environmental variables. Once opened in the top list where it says "User variables for ____" there should be one that says "Path". Select that and hit edit. 
Should open a list of directories, there should be 4 for python:
"C:\Users\*Name*\AppData\Local\Programs\Python\Python311\Scripts\"
"C:\Users\*Name*\AppData\Local\Programs\Python\Python311\"
"C:\Users\*Name*\AppData\Roaming\Python\Python311"
"C:\Users\*Name*\AppData\Roaming\Python\Python311\Scripts"

If they arent there, add them with the "New" button. If there are any old ones there that have the same directories but wrong python number, delete them. Dont delete any others, just the old python ones.

For the shortcut in settings if you have it, open settings and theres a search bar, type in "manage app execution aliases" and open it. If there is a python one there disable it.

That should be it, try run the script again and it should work.

**Comment by mstiggles** [comment]
Thanks so much for this. The scraper is now working again. but I'm still getting the same scrape attempt missing posts retrying with these two models. :(

**Comment by mstiggles** [comment]
? please help?

**Comment by mstiggles** [comment]
any ideas?

**Comment by mstiggles** [comment]
anyone

**Comment by DIGITALCRIMINALS** [comment]
This has been an issue for years, I still don't know to handle it because I don't have access to anyone's account.

**Comment by mstiggles** [comment]
so nothing I can do then?
