### ISSUE TITLE
No module named 'ultima_scraper_api'

### ISSUE THREAD

**Issue by stubblesticker** [DIGITALCRIMINALS/OnlyFans#776]
Hello,

I recently updated using updater.py because it wasn't working, now I get the error:

```
Traceback (most recent call last):
  File "/path/start_us.py", line 9, in <module>
    from ultima_scraper_api.helpers.main_helper import OptionsFormat
ModuleNotFoundError: No module named 'ultima_scraper_api'
```

I think the issue is that the directory is called ultima_scraper, not ultima_scraper_api. When I rename the directory to ultima_scraper_api, I get a different error:

```
Traceback (most recent call last):
  File "/media/root/P/OnlyFans Rips/start_us.py", line 9, in <module>
    from ultima_scraper_api.helpers.main_helper import OptionsFormat
ModuleNotFoundError: No module named 'ultima_scraper_api.helpers'

```
Which seems to indicate that now ultima_scraper_api is being found, but there is no such function "helpers". Maybe ultima_scraper wasn't updated but the main script was?

There's an issue in the old repo for this exact issue:
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1967

**Comment by ClwnMan76** [comment]
Same problem here.

**Comment by Rocket3192** [comment]
> I backed out to https://github.com/DIGITALCRIMINALS/UltimaScraperAPI , downloaded that code manually, unzipped ultima_scraper_api to the OnlyFans directory and now it seems to want to work better, but now I'm missing a module named "dill"

Well you can do pip install dill, then it will do 2 other modules errors, you can install them aswell
Now i'm on a new error I can't fix 
TypeError: config.__init__.<locals>.Settings.__init__() got an unexpected keyword argument 'tui'

**Comment by stubblesticker** [comment]
Ah fuck. It looks like @DIGITALCRIMINALS has changed the entire way the script works again. If you look at the starting page with the readme file, it REQUIRES Python 3.10.1 now instead of 3.10, and requires something called poetry and is now run and installed entirely differently.

**Comment by Rocket3192** [comment]
I'm using poetry it does give another error : module missing jsonpickle, even tho I did install it

**Comment by Rocket3192** [comment]
Well, now that's rich... 
![image](https://user-images.githubusercontent.com/123319690/214611042-a794344e-fad8-47df-82a6-0548f95604c8.png)

**Comment by stubblesticker** [comment]
I'm currently reinstalling the whole shebang. Here's what I've done so far:

All this is on a Linux VM:

1. Downloaded Python 3.11.1 (I know the project requires 3.10.1, but I hoped to get ahead of the curve and download the absolute latest and greatest so I don't get fucked over like this again
2. Installed Python 3.11.1 based off this guide here: https://tecadmin.net/how-to-install-python-3-10-on-debian-11/
3. Downloaded the latest version from https://github.com/DIGITALCRIMINALS/OnlyFans
4. Unzipped to old directory, keeping only ripped sites location, .sites and .profiles folders
5. Downloaded ultima_scraper_api from https://github.com/DIGITALCRIMINALS/UltimaScraperAPI and unzipped the directory ultima_scraper_api into the OF directory from point 4. This should be included in the OF scraper, but it's not.
6. Using the guide https://github.com/DIGITALCRIMINALS/OnlyFans, I installed poetry
7. Set poetry to use python 3.11 with: poetry env use /usr/local/bin/python3.11
8. Discovered that poetry is hard-coded to only work with 3.10.1 in the project, so I changed line 12 of pyproject.toml to read: python = "~3.11.1"
9. Executed script using "poetry run python start_us.py" (how long can we make this?)

The script is now running, but it's asking me, quite annoyingly, to confirm which site, which profile, which creator, which media... now I have to go through the settings and find where all those are again.

It seems to be doing the metadata scraping OK, let's see if it can actually download stuff

> 

>

**Comment by xxx-uploaded** [comment]
E:\python-3.10.5\OnlyFans-master0>poetry run python start_us.py
Choose Profiles: 0 = All | 1 = default
0
Error: {'code': 0, 'message': 'Access denied.'}
Access denied.
Error: {'code': 0, 'message': 'Access denied.'}
Access denied.
Error: {'code': 0, 'message': 'Access denied.'}
Access denied.
Error: {'code': 0, 'message': 'Access denied.'}
Access denied.
Error: {'code': 0, 'message': 'Access denied.'}
Access denied.
Error: {'code': 0, 'message': 'Access denied.'}
Access denied.
Error: {'code': 0, 'message': 'Access denied.'}
Access denied.
Error: {'code': 0, 'message': 'Access denied.'}
Access denied.
Error: {'code': 0, 'message': 'Access denied.'}
Access denied.
Error: {'code': 0, 'message': 'Access denied.'}
Access denied.
Error: {'code': 0, 'message': 'Access denied.'}
Access denied.
Traceback (most recent call last):
  File "E:\python-3.10.5\OnlyFans-master0\start_us.py", line 83, in <module>
    asyncio.run(main())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "E:\python-3.10.5\OnlyFans-master0\start_us.py", line 60, in main
    api = await main_datascraper.start_datascraper(
  File "E:\python-3.10.5\OnlyFans-master0\ultima_scraper\datascraper\main_datascraper.py", line 126, in start_datascraper
    await default(datascraper)
  File "E:\python-3.10.5\OnlyFans-master0\ultima_scraper\datascraper\main_datascraper.py", line 83, in default
    profile_directory = api.base_directory_manager.profile.root_directory
AttributeError: 'DirectoryManager' object has no attribute 'profile'

**Comment by DIGITALCRIMINALS** [comment]
Don't use the `updater.py` script, I'm removing it in future commits. Should just use `poetry update` to update the script.

The only package that's supposed to be in the folder is ultima_scraper and nothing else.

If installed correctly, `ultima_scraper_api` and every other `ultima` dependency will be downloaded and put into the python scripts folder.

**Comment by Rocket3192** [comment]
Well, if we don't use updater.py we don't have the file required by poetry to install dependencies in the tutorial 
>Poetry could not find a pyproject.toml file in

**Comment by DIGITALCRIMINALS** [comment]
I updated the updater.py in the latest commit, so you can just update the script that way.

**Comment by Rocket3192** [comment]
> I updated the updater.py in the latest commit, so you can just update the script that way.
> 
> If you're not running this commit [e936099](https://github.com/DIGITALCRIMINALS/OnlyFans/commit/e9360998f9b2d562b499c483e208369c908ae7e9)
> 
> Just run the updater.py script TWICE and you'll be up to date with the latest updater.py and latest commit.

Well, now it doesn't work anymore
Traceback (most recent call last):
  File "C:\Users\XXX\Downloads\OnlyFans-master\start_us.py", line 27, in <module>
    main_test.check_profiles()
  File "C:\Users\XXX\Downloads\OnlyFans-master\tests\main_test.py", line 43, in check_profiles
    profile_directories = settings.profile_directories
AttributeError: 'Settings' object has no attribute 'profile_directories'
