### ISSUE TITLE
Want to save images with date and filname only but getting random numbers at the end

### ISSUE THREAD

**Issue by 4hench** [DIGITALCRIMINALS/OnlyFans#777]
im using "filename_format": "{date} - {text}#{filename}.{ext}",     its working but  then im getting stuff like 2448x3264_0bae8besd4d171afdc2a1d421048123d at the end???

**Comment by Rocket3192** [comment]
That's the resolution and the file ID

**Comment by 4hench** [comment]
> That's the resolution and the file ID

is it possible to not include it in the filename?

**Comment by DIGITALCRIMINALS** [comment]
> > That's the resolution and the file ID
> 
> is it possible to not include it in the filename?

Nope, but you can use `media_id` instead of `filename` which will generally look like `133742069` instead of `2448x3264_0bae8besd4d171afdc2a1d421048123d`
