### ISSUE TITLE
Incorrect signed request for /api2/v2/init and api2/v2/users/me endpoints

### ISSUE THREAD

**Issue by MrRedbloX** [DIGITALCRIMINALS/OnlyFans#779]
When trying to request **/api2/v2/init** or **api2/v2/users/me** endpoints with the lastest dynamic rules, the sign request produced by the *create_auth* function is not valid.
For example, with `auth_id = 59450453, time = 1674679266505 and path = /api2/v2/users/me`, the resulted value is *611f1f9cfe953f0c1b0caa01764935c9171e86f3* but *fd09e0b46c5bd64c206d0395cc6536f12f1afbed* is expected.  
Note that for */api2/v2/stories* it is working fine.

**Comment by DIGITALCRIMINALS** [comment]
Use an automatically updated provider to get recent updates

https://github.com/DIGITALCRIMINALS/dynamic-rules/blob/main/README.md
