### ISSUE TITLE
'create_post' object has no attribute 'fromUser' error

### ISSUE THREAD

**Issue by djmarioka** [DIGITALCRIMINALS/OnlyFans#785]
Hi,

I've installed the last version, the one that works with Poetry, and it's giving these errors:

![image](https://user-images.githubusercontent.com/81478245/215210670-b5bb47d7-5678-4829-b6f5-930f30a4a517.png)

Could you fix them?.

Thanks.

**Comment by rknightion** [comment]
Same here (using docker version)
```
Skipping virtualenv creation, as specified in config file.
Traceback (most recent call last):
  File "/usr/src/app/./start_us.py", line 82, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/src/app/./start_us.py", line 59, in main
    api = await main_datascraper.start_datascraper(
  File "/usr/src/app/ultima_scraper/datascraper/main_datascraper.py", line 126, in start_datascraper
    await default(datascraper)
  File "/usr/src/app/ultima_scraper/datascraper/main_datascraper.py", line 107, in default
    await datascraper.start_datascraper(job_user_list)
  File "/usr/src/app/ultima_scraper/modules/module_streamliner.py", line 96, in start_datascraper
    identifier=paid_content.fromUser.username,
AttributeError: 'create_post' object has no attribute 'fromUser'```

**Comment by neuri48** [comment]
change "paid_content" to false under the "jobs" section in the settings. 🤷‍♂️ worked for me

**Comment by fukyuchuchu** [comment]
I'm getting this error too. Also latest version with poetry. Changed "paid_content" to false just downloads nothing for me.

**Comment by PsychoSid** [comment]
I got this error, changed `paid_content` to `false` as suggested. Now the script starts but just hangs at:-

```
poetry run python start_us.py
Scrape Attempt: 1/100
Processing Scraped Stories
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 88.50it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
```

Anything else to try ?

**Comment by PsychoSid** [comment]
Breaking out shows the trace as

```
  File "/Volumes/SDP/Misc/OnlyFans/start_us.py", line 82, in <module>
    asyncio.run(main())
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1868, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt
sys:1: RuntimeWarning: coroutine 'StreamlinedDatascraper.prepare_downloads' was never awaited
sys:1: RuntimeWarning: coroutine 'StreamlinedDatascraper.prepare_scraper' was never awaited
```

**Comment by rknightion** [comment]
thanks @neuri48 changing paid_content to false worked for me. @fukyuchuchu you should know there's a bug with the display of progress as I thought in my case it wasn't downloading but low and behold it was downloading everything just fine in the background (except individual paid posts of course but all my follows are monthly subs anyway no ppv so all good)

**Comment by djmarioka** [comment]
> change "paid_content" to false under the "jobs" section in the settings. 🤷‍♂️ worked for me

I did it, but I'm in an endless loop, and it never downloads anything:

![image](https://user-images.githubusercontent.com/81478245/215324175-89c478e7-5d39-44a7-a2b1-347f1c07768e.png)

**Comment by DIGITALCRIMINALS** [comment]
Which models were you trying to scrape

**Comment by neuri48** [comment]
im also just using python start_us.py (no poetry)

**Comment by DIGITALCRIMINALS** [comment]
Then you're probably using an outdated version of ultima_scraper_api, we're on 0.0.1.5 now.

**Comment by Jotund** [comment]
Same thing is happening to me. I've used the updater and all dependencies seem to be fine. No idea what the problem is. Will try a fresh install later.

**Comment by DIGITALCRIMINALS** [comment]
> @PsychoSid. Thanks for referring here. Also having the same issue as @Jotund  and @djmarioka. Stuck in same loop (on poetry, and ran the updater, set paid content to false):
> 
> 
> ![Screenshot 2023-01-30 at 17 25 01](https://user-images.githubusercontent.com/106033128/215549401-b944e37a-409f-404f-87f7-8c6dc70bd067.png)
> 
> 

I don't think this is an infinite loop, set auto_media_choice to True and it should continue as normal.

**Comment by DIGITALCRIMINALS** [comment]
I think it's because some users who you bought paid content from don't exist anymore, could you check?

**Comment by rknightion** [comment]
> I think it's because some users who you bought paid content from don't exist anymore, could you check?

Yep a couple of models that no longer exist. In the past it would cycle through them tries to scrape 100 times then moves onto the next one but since the update it crashes out

**Comment by IanSteg** [comment]
I disabled auto_model_choice and tried scraping a model who's still active and got the same error. Would it still try and scrape those deleted models in that instance?

**Comment by codevisualisations** [comment]
@DIGITALCRIMINALS There's one account that I have on my blocked list. But don't think I've paid content from it.

Also at times when logging in. The `temp_json_auth` dictionary can't seem to find the auth key. Not sure if this has anything to do with it:

![Screenshot 2023-01-30 at 19 38 45](https://user-images.githubusercontent.com/106033128/215579565-bba2c7ab-a6d8-4b9d-b371-e83bb4bd6c93.png)

**Comment by DIGITALCRIMINALS** [comment]
The problem was that there's different types of paid content (Posts, Messages,etc)

You can update the script and it should work

https://github.com/DIGITALCRIMINALS/OnlyFans/pull/801/commits/8e0b49aa36115115faf59447c7c26439043eb7b8

**Comment by Jotund** [comment]
Confirmed working for me now after updating. Thanks a lot.

**Comment by codevisualisations** [comment]
With the settings like this, on the latest commit it scrapes:
![Screenshot 2023-01-30 at 21 36 13](https://user-images.githubusercontent.com/106033128/215601068-4d117676-858c-4b32-b9e3-38334b6c6870.png)

However it sort of does a random scrape? As in scrapes the first few photos of the person you select. Then for the rest scrapes them too, but just leaves a bunch of empty folders

**Comment by DIGITALCRIMINALS** [comment]
> With the settings like this, on the latest commit it scrapes: ![Screenshot 2023-01-30 at 21 36 13](https://user-images.githubusercontent.com/106033128/215601068-4d117676-858c-4b32-b9e3-38334b6c6870.png)
> 
> However it sort of does a random scrape? As in scrapes the first few photos of the person you select. Then for the rest scrapes them too, but just leaves a bunch of empty folders


If it's empty, that means the user has no content

**Comment by PsychoSid** [comment]
I know this is marked as done but after I pulled the latest and set `paid_content` back to `true` the script starts but I get a lot of hangs/noise like:-

```
Error: {'code': 0, 'message': 'Internal error'}
Error: {'code': 0, 'message': 'Internal error'}
Error: {'code': 0, 'message': 'Internal error'}
...
Error: {'code': 0, 'message': 'messages?limit=10&offset=1&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=121&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=161&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=151&order=desc not found'}
```

This is with all models, all media set.

**Comment by Site3op** [comment]
I also tried that and it started to make the onlyfans part hang. Fansly scrapping is still showing the event loop error even with all of the fixes mentioned as well as updating and being on the latest commit.
