### ISSUE TITLE
No paid content, no download statuses, and partial scraping/unknown downloads

### ISSUE THREAD

**Issue by dpuT5** [DIGITALCRIMINALS/OnlyFans#789]
As you can see it doesn't show what is being downloaded or not or who I am downloading from.

Every '0' generates a new folder for a new person but nothing gets scraped/downloaded.

And when it actually does get downloaded, like everyone else Paid content gets ignored.

![ofscrap](https://user-images.githubusercontent.com/91711284/215272937-fbbfa5e6-a92a-4fc6-a689-ab5aa62cbecd.PNG)

**Comment by DIGITALCRIMINALS** [comment]
Yeah, I need to implement a new UI manger so I'm slowly getting rid of it in the ultima_scraper package.

I suggest setting all the automatic options to True, so it can just download everything.
