### ISSUE TITLE
Script hangs on a %USER% with no errors

### ISSUE THREAD

**Issue by randomhappysack** [DIGITALCRIMINALS/OnlyFans#790]
*Currently testing on a set `%USER%`, but this error happens everytime i select `0=All`*
*Hangs here with no error, left it overnight, and it's still in the same spot. seems to hang at the same `%USER%` every time.*

> `Finished processing metadata.`
`Renaming files.`
`100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 351/351 [00:00<00:00, 6062.58it/s]`
`Processing Scraped Messages`
`100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 5682.89it/s]`
`Processing metadata.`
`Finished processing metadata.`
`Renaming files.`
`100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40/40 [00:00<00:00, 9147.38it/s]`
`Scrape Attempt: 1/100`
`Type: Archived Posts`
`Scrape Attempt: 1/100`
`Processing Scraped Posts`
`100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 487/487 [00:00<00:00, 1490.53it/s]`
`Processing metadata.`
`Finished processing metadata.`
`Renaming files.`
`100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:00<00:00, 741.53it/s]`
`Processing Scraped Messages`
`100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [00:00<00:00, 1552.51it/s]`
`Processing metadata.`
`Finished processing metadata.`
`Renaming files.`
`100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 77/77 [00:00<00:00, 711.25it/s]`
`Download Processing`
`Name: %USER% | Type: Posts | Count: 1 | Directory: F:\Setups\Downloaders\DIGITALCRIMINALS\__user_data__\sites`

> `Processing Scraped Stories`
`100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1002.22it/s]`
`Processing metadata.`
`Finished processing metadata.`
`Renaming files.`
`100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 501.29it/s]`
`Scrape Attempt: 1/100`
`Type: Archived Posts`
`Processing Scraped Posts`
`100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 230/230 [00:00<00:00, 1972.01it/s]`
`Processing metadata.`
`Finished processing metadata.`
`Renaming files.`
`100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 231/231 [00:00<00:00, 1023.09it/s]`
`Processing Scraped Messages`
`100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 3881.82it/s]`
`Processing metadata.`
`Finished processing metadata.`
`Renaming files.`
`100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 3984.46it/s]`
`Type: Archived Posts`

*Any help?*

*ill update in the comments whether the set `%USER%` returns a hang or not*

**Comment by randomhappysack** [comment]
*Seems selecting a `%USER%` doesn't produce this hang and allows the script to finish*

**Comment by DIGITALCRIMINALS** [comment]
Yeah I messed up something couple days ago and got the same thing as you. 
Run the updater.py script and it should execute a poetry update command. If it doesn't, just run the updater again.

**Comment by DIGITALCRIMINALS** [comment]
I'm working on 0=All now

**Comment by DIGITALCRIMINALS** [comment]
I seem to have misread the bug. It'll just be for you to give me the username of the model that you think is bugged

**Comment by randomhappysack** [comment]
_I unsubbed from her, just to see and it continuted on to another ill have to re-run the script to see where it hangs again_

**Comment by randomhappysack** [comment]
_actually i have it here, can i post?_

**Comment by DIGITALCRIMINALS** [comment]
Yeah you can post their username here

**Comment by DIGITALCRIMINALS** [comment]
Alright, I got it, I'll work on in today, I gotta fix something else first

**Comment by randomhappysack** [comment]
_Ok, I'm rerunning the script with `0` to see what happens now_ 
_Also, this is what I get straight after selecting `0`, this may be normal behavior or not just thought id put it out there_
`%USERNAME%`
`%USERNAME%`
`%USERNAME%`
`%USERNAME%`
`%USERNAME%`
`%USERNAME%`
`%USERNAME%`
`Missing 1427 Posts... Retrying...`
`Scrape Attempt: 13/100`
`%USERNAME%`
`%USERNAME%`
`%USERNAME%`
`%USERNAME%`
`%USERNAME%`
`%USERNAME%`
`%USERNAME%`
`Missing 1316 Posts... Retrying...`
`Scrape Attempt: 14/100`
`%USERNAME%`
`%USERNAME%`
`%USERNAME%`
`%USERNAME%`
`%USERNAME%`
`%USERNAME%`
`%USERNAME%`
`Missing 1223 Posts... Retrying...`
`Scrape Attempt: 15/100`
`%USERNAME%`

_All usernames are different, and I know the progress bars are broken so maybe that the case_

**Comment by DIGITALCRIMINALS** [comment]
> _All good! too easy, love the work btw!_ _Ok, I'm rerunning the script with `0` to see what happens now_ _Also, this is what I get straight after selecting `0`, this may be normal behavior or not just thought id put it out there_ `%USERNAME%` `%USERNAME%` `%USERNAME%` `%USERNAME%` `%USERNAME%` `%USERNAME%` `%USERNAME%` `Missing 1427 Posts... Retrying...` `Scrape Attempt: 13/100` `%USERNAME%` `%USERNAME%` `%USERNAME%` `%USERNAME%` `%USERNAME%` `%USERNAME%` `%USERNAME%` `Missing 1316 Posts... Retrying...` `Scrape Attempt: 14/100` `%USERNAME%` `%USERNAME%` `%USERNAME%` `%USERNAME%` `%USERNAME%` `%USERNAME%` `%USERNAME%` `Missing 1223 Posts... Retrying...` `Scrape Attempt: 15/100` `%USERNAME%`
> 
> _All usernames are different, and I know the progress bars are broken so maybe that is the case_ _Once it gets close to Scrape attempt 100/100 the bars come back and it starts going through the post/messages/stories/etc_

Thanks, and yes, the UI is messed up

**Comment by randomhappysack** [comment]
_Seems to still be present, I think it may be something on my side, almost like a timeout issue? Do you have a way to get a verbose log at all to see what is timing out?_

_I have Kaspersky anti virus which i don't know if that could block/ cause the timeout_

**Comment by randomhappysack** [comment]
_Heh, found the problem... getting this error when accessing **Onlyfans**!_

`HTTP ERROR 429`

_Hopefully its not permanent_

**Comment by god43** [comment]
yeah looks like its a block after 60 tries

**Comment by DIGITALCRIMINALS** [comment]
> _Heh, I think I found the problem... getting this error when accessing **Onlyfans** after the script hangs!_ `HTTP ERROR 429` _It didn't last long, maybe 3 mins. After that, the website went back to normal. I haven't noticed it before but I don't think I've opened the website on a script hang, but instead just kept trying the script..._ _Maybe it hangs due to **Onlyfans** trying to block the request spam, due to the scrape retries? am I able to disable the scrape retries or reduce them from 100 to like 5?_

Yeah, set max threads to 5 in the config

https://github.com/DIGITALCRIMINALS/OnlyFans/issues/838
