### ISSUE TITLE
`date_format` not being used

### ISSUE THREAD

**Issue by PsychoSid** [DIGITALCRIMINALS/OnlyFans#794]
Hi,

Many thanks for the continued work.

With the latest from `main` I have the following in my OF settings:-

```
        "filename_format": "{model_username}.{date}-{text}-{filename}.OnlyFans.{ext}",
...
        "date_format": "%Y%m%d",
```

However the date in the files pulled is written as `%d-%m-%Y`

Has this setting changed at all ?

Many thanks.

**Comment by DIGITALCRIMINALS** [comment]
Your formats are working perfectly for me

**Comment by PsychoSid** [comment]
Oh I am an idiot I was looking in `./settings/config.json` and now it's `__settings__/config.json`. Sorry.
