### ISSUE TITLE
not grabbing all content

### ISSUE THREAD

**Issue by datnodude** [DIGITALCRIMINALS/OnlyFans#80]
using the latest version for OF, its not grabbing all content. a profile can have 80 timeline vids, its only grabbing 40. i've tried a few different profiles, and they are all incomplete. I don mess with any of the settings, any suggestions?

**Comment by jasterbiggus** [comment]
For myself, it was a a connection issue. Try a new vpn server or a different vpn completely.

**Comment by OFfriend** [comment]
sometimes OF is slower from my Server compared to my home internet

**Comment by datnodude** [comment]
it was the vpn. thanks
