### ISSUE TITLE
Dockerfile needs update - fails to build

### ISSUE THREAD

**Issue by silsmurf** [DIGITALCRIMINALS/OnlyFans#804]
RUN /usr/local/share/pypoetry/bin/poetry install --no-dev:
The `--no-dev` option is deprecated, use the `--only main` notation instead.
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.
Because ultima-scraper depends on ultima-scraper-api (0.0.1.7) which doesn't match any versions, version solving failed.

**Comment by aloysiu3** [comment]
running `python updater.py` and then `poetry install -no-dev` fixed it for me

**Comment by silsmurf** [comment]
> running `python updater.py` and then `poetry install -no-dev` fixed it for me

adding those to the dockerfile seems to have fixed it 👍

is the issue with scraping not working with `"messages": true,` still present?

the lack of progress bars is also confusing, didn't realise anything was happening until i checked network activity 😅

**Comment by rknightion** [comment]
@silsmurf can you share your Dockerfile please? 
As tried adding it in various orders to mine and either it fails as requests isn't installed (part of poetry install I would imagine) but the poetry install can't run because the ultima-scraper-api isn't there

**Comment by fl4shforward** [comment]
It's because ultima-scraper-api version wasn't updated in the [poetry.lock](https://github.com/DIGITALCRIMINALS/OnlyFans/blob/master/poetry.lock) file.
@DIGITALCRIMINALS could you fix it please ? Thanks !
