### ISSUE TITLE
Traceback (most recent call last) Error

### ISSUE THREAD

**Issue by rxpsam420** [DIGITALCRIMINALS/OnlyFans#81]
![Untitled](https://user-images.githubusercontent.com/93736794/140408843-af4a9ed3-b0e0-4525-b6cd-f73d5374c25b.png)

Im getting this error, please help

**Comment by goodboi69** [comment]
Follow this. Also update the requirements aftwards.
https://github.com/DIGITALCRIMINALS/OnlyFans/issues/43
