### ISSUE TITLE
TypeError: check_config() missing 1 required positional argument: 'directory'

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINALS/OnlyFans#814]
> Traceback (most recent call last):
> File "C:\Users\user\Desktop\OnlyFans-master\start_ofd.py", line 26, in
> main_test.check_config()
> TypeError: check_config() missing 1 required positional argument: 'directory'

The fix for this seems to be obvious, but I can't figure it out...

**Comment by DIGITALCRIMINALS** [comment]
`start_ofd.py` is outdated. use the latest commit
