### ISSUE TITLE
Not downlading anything, giving "Choose Medias" prompt over and over

### ISSUE THREAD

**Issue by tim1f1** [DIGITALCRIMINALS/OnlyFans#819]
When I select an OF model to scrcape, the script gives the "Choose MEdias" prompt, but then keeps giving it over and over again
![image](https://user-images.githubusercontent.com/16625605/216024921-91249469-6365-494b-881e-8dc18db87638.png)

> 64
> Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
> 0
> Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
> 0
> Scrape Attempt: 1/100
> Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
> 0
> Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
> 0
> Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
> 0
> Processing Scraped Posts
>   0%|                                                                                                              | 0/176 [00:00<?, ?it/s]C:\Users\tim_f\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-VdS0BOvl-py3.10\lib\site-packages\ultima_scraper_api\helpers\main_helper.py:145: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
>   string = BeautifulSoup(string, html_parser).get_text()
> 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 176/176 [00:00<00:00, 700.21it/s]
> Processing metadata.
> Finished processing metadata.
> Renaming files.
>   0%|                                                                                                              | 0/211 [00:00<?, ?it/s]Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
>

**Comment by e2489** [comment]
Yeah, same issue here.

**Comment by Site3op** [comment]
auto_media_choice to true in your config.

**Comment by Suppen8** [comment]
Same issue here.
@Site3op suggestions is only a workaround. It just deactivates the user madia choice.
But you can also set the value of auto_media_choice to e.g. "Images" to only download the images. Just tried it out for me.

Nevertheless this seems to be a bug to me. Should get fixed

**Comment by 4hench** [comment]
> auto_media_choice to true in your config.

didn't work

**Comment by DenizOzt** [comment]
It created folders for the girls i followed in batches so I had to type "0" and click "Enter" until there were no more girls left to create folders for. Then it started downloading without a download bar so don't close the command prompt when it stops asking you to choose media.

**Comment by ValerioLyndon** [comment]
I can't entirely confirm whether Deniz is correct as I had 20 users to choose from and it only prompted me 11 times. However it did start working after those 11 prompts and waiting a couple of minutes for a loading bar to appear. So the advice still helped.
