### ISSUE TITLE
They do not load the profiles

### ISSUE THREAD

**Issue by Soulol36** [DIGITALCRIMINALS/OnlyFans#82]
Hello good afternoon, I have the following problem:
I had problems with Python 3.10, thanks to the help of @OFfriend (https://github.com/DIGITALCRIMINALS/OnlyFans/issues/43#issue-1028170951)
But, it happens that now they cannot load the profiles, it only stays stuck in the window of the photo that I leave them, it stays there, and after a long time it manages to close completely.
UPDATE: After a long period of time, I get the following message: "https://github.com/DIGITALCRIMINALS/OnlyFans/issues/83#issue-1046233835"
![friz](https://user-images.githubusercontent.com/93793459/140569325-25d0f9fa-614b-45e6-b3d4-f0e2b2a677f8.png)

**Comment by DIGITALCRIMINALS** [comment]
Update the script and try

**Comment by Soulol36** [comment]
> Update the script and try

Done, But still the problema, look.
![Only Issue 2](https://user-images.githubusercontent.com/93793459/144727111-2e03e57e-e4e4-4791-af66-26fd8379aa46.png)

**Comment by DIGITALCRIMINALS** [comment]
You've got thousands or hundreds of subscriptions right?

**Comment by DIGITALCRIMINALS** [comment]
Latest commit should work
