### ISSUE TITLE
Anyway to reduce the retry attempts on missing scrapes?

### ISSUE THREAD

**Issue by Bun-Bun** [DIGITALCRIMINALS/OnlyFans#821]
Having an issue where posts are missing and then the retry attempts are hitting some api limit or something and causing OF to temporarily limit my IP (can't browse the website even comes back error 429). 

Missing 117 Posts... Retrying...
Scrape Attempt: 94/100

I'd like to limit this to 10 and see if the limit issue goes away. 

Or a way to rate limit the scraper?

**Comment by coex177** [comment]
I appear to be having the same issue, I thought there was an issue with OnlyFans, but I just tried connecting through with a VPN and was able to access the site again.

**Comment by god43** [comment]
there are a couple of lines under "api_helper" file if you search for 100 you will find them (it was line 400 something). i think those are what controls the change attempts. idk i changed it and i am running the scrapper again. so we will see.

**Comment by god43** [comment]
looks like that did change it, i only show 20 scrape as my limit. i guess we will see how it works once i hit the retry loop.

**Comment by Bun-Bun** [comment]
Where did you find the api_helper file? I can't seem to find it.

**Comment by god43** [comment]
its under the apis folders, there is one in the root and another one under the ultima_scraper_api.

**Comment by Bun-Bun** [comment]
Found it.

./lib/python3.10/site-packages/ultima_scraper_api/apis/api_helper.py

That change seems to be working. 

I wonder if OF is just having issues today, I'm noticing other weird issues while browsing the site.

**Comment by god43** [comment]
yeah idk it does work, but i still get 429, ill try bringing it down to 5

**Comment by Bun-Bun** [comment]
So far working for me, the retry count hits 20 and then continues on to the next step without causing a rate limit from OF. 

Behavior now is those scrape attempts go super fast where before it would take awhile at each step. Not sure what has changed.

**Comment by god43** [comment]
idk whats going on, but it keeps getting broke, every attempt it just stops after like couple of hours.

**Comment by rknightion** [comment]
OF has clearly implemented rate limiting (hence why when you go to your browser you get a 429 error code which means too many requests). Nothing "wrong" with OF as such just them attempting to avert scraping.

**Comment by DIGITALCRIMINALS** [comment]
I've removed the entirety of "retry attempts" (for now), and I've added in a rate limit in the script. 
Max concurrency will be defined by the number of your CPU threads. I'm comfortably scraping with 32 threads with 0 timeouts.
