### ISSUE TITLE
Onlyfans Scrape 

### ISSUE THREAD

**Issue by Site3op** [DIGITALCRIMINALS/OnlyFans#822]
Since the newest commit and coming over to the poetry version whenever I scrape a single creator it will go through and re-download meta-data of every single creator I've ever subbed to including non-subbed ones and even deleted accounts but not my currently subscribed roster (only downloads them when specifically inputted). This also leads to OnlyFans blocking access to the site with a HTTP ERROR 429 for over 30 minutes.

**Comment by Site3op** [comment]
> The rate limiting on onlyfans end is a change on their end I think.
> 
> I was using an old version of the scraper for a long time without issue until this started happening today. I updated to the latest version with the same result.

Are you having a problem with the old subscribed accounts re-downloading the meta-data after picking a model to scrap?

**Comment by Bun-Bun** [comment]
I've always had that issue. The logic in the scraper has always been wonky and it goes through all model messages no matter what you do.

**Comment by avekifes** [comment]
I seem to be running into the same nonsense. The best part is when I check in an hour later and see an error, like "Story highlight not found."

**Comment by Site3op** [comment]
Seem now when it starts to run through this, it will delete every folder in my sites -> onlyfans and redownload literally everything

**Comment by Bun-Bun** [comment]
That's not normal and not what happens here. It goes through every model in messages no matter what I do (only downloads the ones selected) but it never deletes anything. 

I've rolled back to the commit I was on before, don't remember what it was. But the rate limiting thing is on OFs side, happens with any version of the scraper I try. Not sure why yours is deleting though.
