### ISSUE TITLE
'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by Soulol36** [DIGITALCRIMINALS/OnlyFans#83]
Hello, I have the following error, for some reason the following message managed to appear.
Could someone help me?, Thank you ^^
![frize](https://user-images.githubusercontent.com/93793459/140576587-ac60070d-6fcf-41c5-b1ba-994c634b582a.png)

**Comment by Shingotink** [comment]
I have the same issue. 

t seems to do with a limit to the number of models you are subscribed to.

If you don't mind me asking how many active models do you have? I am at around 1500 models on my main profile and constantly see a similar message.

**Comment by Tileki** [comment]
I received this error but in my case the computer was on the fixed IP and for some reason it was causing this error. I removed the fixed ip and it started working again.

**Comment by Shingotink** [comment]
I recently found out that the fan in my laptop was failing. I now believe this is the reason my larger profile was failing, not anything to do with script.

I have been using a laptop cooling pad as a temporary fix and am having far less issues than I was before.
