### ISSUE TITLE
Multiple model selection

### ISSUE THREAD

**Issue by god43** [DIGITALCRIMINALS/OnlyFans#833]
I didn't see this listed in the documentation, but how to i select multiple models? can i simply choose a number and comma separate them? thanks.

**Comment by puc9** [comment]
Comma separated names. There is a bug in it however, that I just created: #834

**Comment by god43** [comment]
did I, this is all thats written under model choice?

Default = false
Inputs: All, username, etc

If set to true, the script will scrape all the names.

**Comment by puc9** [comment]
Well, this was working with US 2.2, but it's no longer working for 2.3, it attempts to get all the models. I'm using it for Fansly if that makes any difference. Might be related to #824

**Comment by god43** [comment]
ok thanks
