### ISSUE TITLE
Models with underscore in the name ignored when selecting by name

### ISSUE THREAD

**Issue by puc9** [DIGITALCRIMINALS/OnlyFans#834]
When setting "auto_model_choice" to a list of model names only names that validate isalpha() will be selected.

Removing `if x.isalpha()` from https://github.com/DIGITALCRIMINALS/UltimaScraperAPI/blob/87928f25d27d72508f68d72e226a459071126248/ultima_scraper_api/helpers/main_helper.py#L568 fixes it but I don't understand why it was there in the first place so I'm not sure that is the right fix.

**Comment by DIGITALCRIMINALS** [comment]
Yeah, the script no longer uses choice_list anymore. It's redundant.
