### ISSUE TITLE
New to coding and need help 

### ISSUE THREAD

**Issue by kristmd** [DIGITALCRIMINALS/OnlyFans#837]
I was trying to figure out how to set this script up and was following some tutorial and it was pretty helpful up until I ran "start_ofd.py" and got this error: 
Traceback (most recent call last):
  File "F:\OnlyFans-master\start_ofd.py", line 12, in <module>
    main_test.check_config()
TypeError: check_config() missing 1 required positional argument: 'directory'

Any help would be appreciated!

**Comment by TheTrueColonel** [comment]
You set up the script by following the README on the main page...
