### ISSUE TITLE
Beautiful Soup

### ISSUE THREAD

**Issue by xxx-uploaded** [DIGITALCRIMINALS/OnlyFans#840]
:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-uLD8udYt-py3.10\lib\site-packages\ultima_scraper_api\helpers\main_helper.py:140: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
   string = BeautifulSoup(string, html_parser).get_text()

Nothing downloads, freezes and that's it
![Screenshot_1](https://user-images.githubusercontent.com/88721958/217731005-7a196970-fe24-4105-b907-cfc3dff7dfd9.png)

**Comment by bigfranko** [comment]
I'm using a vpn and every time it stops I change the connection location and it start running again.

**Comment by DIGITALCRIMINALS** [comment]
Try latest update
https://github.com/DIGITALCRIMINALS/OnlyFans/issues/838
