### ISSUE TITLE
updater.py hangs on "Resolving dependencies" and gobbles memory

### ISSUE THREAD

**Issue by BlankJakeHall** [DIGITALCRIMINALS/OnlyFans#843]
Python 3.10.2

Running the updater, it hangs at "Resolving dependencies..." and the python.exe process just gobbles up memory. I let it sit for a few minutes and it was up to 2GB and growing. 

![image](https://user-images.githubusercontent.com/125088880/218188950-f1fadabe-25f3-4cbf-ad28-1ed25d6069dd.png)

![image](https://user-images.githubusercontent.com/125088880/218188202-f3a0d831-b07b-4c49-b674-e0cf90d9a02c.png)

**Comment by naodrej** [comment]
you might have an older version of poetry, you'll have to uninstall and reinstall it.

**Comment by BlankJakeHall** [comment]
> you might have an older version of poetry, you'll have to uninstall and reinstall it.

I have version 1.1.13, but I don't think the updater uses poetry anyway. Instructions say just run 'python updater.py'

**Comment by BlankJakeHall** [comment]
No dice, unfortunately. 

`> poetry run python updater.py
Traceback (most recent call last):
  File "C:\Users\Adam\Desktop\New folder\OnlyFans-master\updater.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

**Comment by naodrej** [comment]
the latest version of poetry is 1.3.2. there is an issue with 1.1.1X that will get stuck if you try self update. you have to uninstall and reinstall poetry to get the latest version. do `pip uninstall poetry` and then `pip install poetry`

**Comment by BlankJakeHall** [comment]
I am already using poetry 1.3.2

**Comment by aingwrytew** [comment]
> I don't think the updater uses poetry anyway.

The main thing the updater does is run poetry... to update... `line 50 - subprocess.run(["poetry", "update"])`

> I have version 1.1.13

> I am already using poetry 1.3.2

Which is it?
It's also suggested to install Poetry through the installer rather than pip, so once you uninstall, I'd suggest installing using [this guide](https://python-poetry.org/docs/) to install manually.

**Comment by Anonymeowse** [comment]
I have to do a `poetry install` before running `poetry run python updater.py`.

**Comment by BlankJakeHall** [comment]
Resolved by uninstalling everything (poetry, pip, python) and reinstalling. Also needed to run `pip install ultima_scraper`
