### ISSUE TITLE
new directory path not scraping images/videos

### ISSUE THREAD

**Issue by penguinpatrol** [DIGITALCRIMINALS/OnlyFans#846]
i have set a new download directory which seems to work fine although when i scrape the only thing it collects is the metadata and the profile avatar and header but not images/videos?
![image](https://user-images.githubusercontent.com/117539617/218282774-4c363aef-21ec-4600-ba01-7185fff9b6d0.png)
![image](https://user-images.githubusercontent.com/117539617/218282796-28d2c475-8d41-4067-9013-a2769cd3ded0.png)

**Comment by DIGITALCRIMINALS** [comment]
Update the script
