### ISSUE TITLE
ultima_scraper not found

### ISSUE THREAD

**Issue by MikeBarberry** [DIGITALCRIMINALS/OnlyFans#847]
auth isn't working because dependent package ultima_scraper isn't found in required files.

did you rename it or did it get removed from where it was hosted?

**Comment by DIGITALCRIMINALS** [comment]
It's a PYPI package now

https://pypi.org/project/ultima-scraper-api/
https://github.com/DIGITALCRIMINALS/UltimaScraperAPI

You can also run it locally using the --editable option

https://python-poetry.org/docs/cli/#add
