### ISSUE TITLE
Scrape Doesn't Begin & Creates Blank Profile Folders

### ISSUE THREAD

**Issue by vanillabeer** [DIGITALCRIMINALS/OnlyFans#852]
I'm not getting any errors but when I select a profile and choose what to scrape nothing happens 99% of the time. If I keep spamming 0 to 'scrape all' on a profile I can get it to start scraping for like half a second which will work for a profile that has barely any photos or videos but for someone with thousands of photos or hundreds of vids it's worthless. 

Just says "Scrape attempt 1/100" and then has me "Choose Medias" again so I hit 0 for all and again, half a second scrape. Most of the time I spam 0 I don't even get a progress bar to appear it just says 'Choose Medias' again. Doesn't let me switch profiles after the half second scrape either, maybe because it knows it didn't finish it.

But ontop of that in the "Sites" "Onlyfans" folder it'll start creating folders for other profiles that I am subscribed to but I didn't choose to scrape. It doesn't scrape anything from them no matter how often I spam 0 on the profile I'm actually trying to scrape but it keeps creating folders of other profiles regardless. These folders have no subfolders or metadata or anything in them.

So to summarize... It's not scraping the profile I'm choosing (unless I spam 0 then I get *some* pictures and vids whatever it can grab in literally a second) and at the same time... Creating empty folders for other profiles I am subbed to. 

In my 'auth' file under 'cookie' - "auth_hash=;" theres no value there just like the example photo. But there's a new option "aws-waf-token=" which is also blank and I'm not sure what I'm supposed to put in there. I've never set up 2FA either. Other then that my auth config looks exactly like the example picture.

My laptop died recently so this was all a clean install on a new laptop, Windows 10 running Python 3.11.1. Thought an update might come along and fix it but it hasn't. I haven't changed anything in the settings file, deleted it after each update to be sure everything was set to default. Same issue. Thanks in advance for your time and help!
![scrape](https://user-images.githubusercontent.com/125566882/219372217-46ad82ef-bbbf-45ed-92f7-7fc9f3e46aeb.PNG)

**Comment by Patrick7070** [comment]
I had this too.  If you hit 0 enough times it does 'stick' and download - but that is a pain.

On another thread they suggested this as a workaround (and it works great for me)
If you always download everything from onlyfans just set this line in the config.json (it is in the onlyfans subsection).  This makes it default to download all without prompting.
"auto_media_choice": "0"

**Comment by vanillabeer** [comment]
> I had this too. If you hit 0 enough times it does 'stick' and download - but that is a pain.
> 
> On another thread they suggested this as a workaround (and it works great for me) If you always download everything from onlyfans just set this line in the config.json (it is in the onlyfans subsection). This makes it default to download all without prompting. "auto_media_choice": "0"

So that seems to work but then it just continues scraping and starts scraping profiles I don't want. I have to manually exit the program for it to stop.

**Comment by Poddi** [comment]
> > I had this too. If you hit 0 enough times it does 'stick' and download - but that is a pain.
> > On another thread they suggested this as a workaround (and it works great for me) If you always download everything from onlyfans just set this line in the config.json (it is in the onlyfans subsection). This makes it default to download all without prompting. "auto_media_choice": "0"
> 
> So that seems to work but then it just continues scraping and starts scraping profiles I don't want. I have to manually exit the program for it to stop.

Same here.
It downloads everything after and creates Folders for each followed Performer.Kinda annoying.
Hope for Fix!
