### ISSUE TITLE
OnlyFans rate limiting

### ISSUE THREAD

**Issue by herefromrdt** [DIGITALCRIMINALS/OnlyFans#854]
It seems like OF has introduced some rate limiting. Every time I run the scraper, it works fine for a few minutes, and then completely freezes. While it's frozen (and for a while after I kill it), OF won't even work in the browser. It seems like if requests come too fast, OF temporarily stops responding.
Is there any way to introduce some throttling or an exponential backoff to get around this issue? I haven't been able to run a complete scrape in a while.

**Comment by jp1151419** [comment]
Same issue here

**Comment by Site3op** [comment]
the biggest thing would be once he fixes the metadata issue that will help resolve the rate limiting

**Comment by Tireless82** [comment]
I just installed this for the first time yesterday, and I seem to run into a variant of this issue.

It auths just fine, but after grabbing metadata and 2 or 3 photos, it freezes (in my case I'd say it only works fine for seconds, not minutes).

In my case, the browser OF works just fine while this happens. So not sure if a consequence of this same issue, or a different issue.

**Comment by Patrick7070** [comment]
I have been scraping okay with setting max threads to 5 in the config.json file.
I know this hasn't helped for everyone and it does slow down the scrape but I am not grabbing too much media.
My connection is not superfast (300mbps) and I wonder if the people on gigabit or better are the ones running into this problem.  There is third party software to throttle the speed down maybe that would work for some.

**Comment by Nostang3** [comment]
5 threads didn't work for me but I have a gigabit connection. I also tried 2 threads but it started timing out as well. I'm going to wait a bit and try 1 thread and see if that makes a difference.

**Comment by CannotTouch** [comment]
https://github.com/DIGITALCRIMINALS/OnlyFans/issues/838 for me 5 solved it

**Comment by herefromrdt** [comment]
I think there needs to be a solution other than limiting threads, but I'm going to close this issue, because it does seem like a duplicate of #838
