### ISSUE TITLE
Getting a directory error

### ISSUE THREAD

**Issue by Kenkai87** [DIGITALCRIMINALS/OnlyFans#861]
---Im Using Python 3.10.
---Created the Migration folders.
---Added the migration directories into configs.json as well.

---Error:

Traceback (most recent call last):
line 20, in <module>
    main_test.check_config()
TypeError: check_config() missing 1 required positional argument: 'directory'

**Comment by sweetcatastrophe** [comment]
Did you manage to find a solution to this?  I'm now getting this error too after I ran the updater.

**Comment by DIGITALCRIMINALS** [comment]
Should be fixed

**Comment by Kenkai87** [comment]
Thanks, come to find out I never had poetry initialized in my path
