### ISSUE TITLE
Endless Loop, and I can't download anything

### ISSUE THREAD

**Issue by djmarioka** [DIGITALCRIMINALS/OnlyFans#865]
Hi,

I'm having an endless loop (I attach a screenshot):

![image](https://user-images.githubusercontent.com/81478245/221413838-09604f81-5b2a-43d9-869c-1a541bc204c2.png)

and, because of this, I can't download anything.

Could anything help to fix this issue?.

Thanks.

**Comment by brightpepe** [comment]
Same problem for me. Endlessly asks to confirm media type but nothing ever downloads.

**Comment by Patrick7070** [comment]
See message #852

**Comment by vanillabeer** [comment]
My topic was closed so I was hoping it was fixed but after running the updater... It's not even attempting to scrape the profile about to expire that's currently profile "1" in the list. Just chooses seemingly randomly and starts auto-scraping so I have to close it.

If I don't select set the "auto_media_choice": "0" then it still doesn't work.
