### ISSUE TITLE
issues getting all the message media and message not found error

### ISSUE THREAD

**Issue by brandonerd** [DIGITALCRIMINALS/OnlyFans#870]
when scraping one creator in particular that I selected to scrape, it only returns one paid video, when there are more. this does not error and finishes. they are just not scraped. it is the most recent paid video that is scraped successfully.

when i had scrape messages turned on and it was going through my ~400 creators I have messages with, it will occationally show these errors:
 
Error: {'code': 0, 'message': 'messages?limit=10&offset=30&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=20&order=desc not found'}
Error: {'code': 0, 'message': 'messages?limit=10&offset=10&order=desc not found'}

**Comment by brandonerd** [comment]
just found another creator where it didn't catch paid or free content, the most recently missed was Sep 26, 2022, and everything paid and free prior to that, the only thing downloaded was on Dec 9, 2022.

definitely seems like the script is having issues getting paged content, i see that the requests for older messages currently doing this:
/api2/v2/chats/[chatid12345]/messages?limit=10&order=desc&skip_users=all&id=[messageid12345]

where messageid12345 is the id of the oldest currently returned message, to get more, if the error is an indication of the call its making to get older messages (messages?limit=10&offset=30&order=desc) perhaps it has been changed and needs to be updated.

**Comment by DIGITALCRIMINALS** [comment]
Onlyfans introduced rate limiting.

https://github.com/DIGITALCRIMINALS/OnlyFans/issues/838

**Comment by brandonerd** [comment]
sorry, but i don't believe that fully explains my issue, my max threads is 1, and I am only attempting to download one creator.

I just did an update,
removed creator download/meta data,
was forced to re-login in browser to get new auth data,
and tested it again;

it is not seeing all the paid content in messages.

there are 15 messages in the chat with this creator, 8 paid unlocked, 2 free chats, 5 unpaid

and it only ends up downloading the free chats, and the latest 1 paid chat, missing the rest of the paid chats, and some unpaid chats have free images, they are also not downloaded.

here is the output:

Processing Scraped Posts
100%|████████████████████████████████████████████████████████████████████████████████| 34/34 [00:00<00:00, 1997.88it/s]
Processing metadata.
Finished processing metadata.
Processing Scraped Messages
100%|██████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 1250.54it/s]
Processing metadata.
Finished processing metadata.
Download Processing
Name: creator | Type: Posts | Downloading: 39 | Total: 39 | Duplicates: 0  | Directory: __user_data__\sites

Download Processing
Name: creator | Type: Messages | Downloading: 10 | Total: 10 | Duplicates: 0  | Directory: __user_data__\sites

Archive Completed in 0.8 Minutes
