### ISSUE TITLE
IP Banned

### ISSUE THREAD

**Issue by distantowl** [DIGITALCRIMINALS/OnlyFans#871]
Just a heads up for everyone:

Been using this script without a VPN successfully for almost 2 years at this point. Never had any problems. Ran the script and was getting a weird error where it just hung on login so I went to refresh my auth codes and OF won't load in my browser. Turned on a VPN and it loads just fine. Dunno how long it is, but if I notice that I'm unbanned I'll update this issue. It can be set as closed or whatever.

**Comment by DIGITALCRIMINALS** [comment]
Best to call your ISP and tell them to give you a new IP.

**Comment by distantowl** [comment]
Too bad I have Verizon and calling them is like pulling teeth.

**Comment by Jules-WinnfieldX** [comment]
Doesn't seem to be a full IP ban, just happened to me. Access came back after a few minutes. Looks like they have new bot protections in place.

**Comment by distantowl** [comment]
Looks like you got off light, it's been a couple of hours for me.

**Comment by JohnnyTowns94** [comment]
Seems like it doesn't take much to get timed out from OnlyFans lately. I've been having this issue today. I gotta leave it for about 15-20 minutes then try again.

**Comment by CannotTouch** [comment]
it's just a temporary ban (sure if you have dynamic ip you can reset it changing the ip on the fly)
we are talking about it here: https://github.com/DIGITALCRIMINALS/OnlyFans/issues/838

**Comment by RB1875** [comment]
I've set max_threads to a value of 5 and it hasn't resulted in me being banned yet.

Other suggestions I've seen are to use a separate browser for the scraper cookies (e.g. using details from firefox if you normally use chrome) - also seen others suggesting that you log out of your account prior to starting scraping and to avoid accessing onlyfans while the scraper is running.

**Comment by distantowl** [comment]
I am still banned, about 24hrs later. Will check back in a week.

**Comment by distantowl** [comment]
Unbanned.
