### ISSUE TITLE
don't download anything

### ISSUE THREAD

**Issue by butzen0** [DIGITALCRIMINALS/OnlyFans#880]
PS E:\old OF\OnlyFans-master5> poetry run python start_us.py
Choose Sites: 0 = All | 1 = OnlyFans | 2 = Fansly
1
Choose Profiles: 0 = All | 1 = default
1
Choose Subscriptions: 0 = All | 1 = rubyalexia | 2 = gabis_dz | 3 = enigmamgf | 4 = laararose | 5 = itscayyay | 6 = chalkmoon | 7 = luiesuicide | 8 = sophia_lins | 9 = apollymisg | 10 = shyslut0 | 11 = zanemago | 12 = chloealvarado69 | 13 = nataliemonroe
10
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Scrape Attempt: 1/100
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts

stay in the looping

**Comment by porncritic** [comment]
same issiue i think
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Scrape Attempt: 1/100
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts

**Comment by DIGITALCRIMINALS** [comment]
That's how the script works.

**Comment by butzen0** [comment]
but ok, now i know it changed

**Comment by p0rnb0x** [comment]
same problem.

> That's how the script works if you don't use automatic options.

ok, what is 'automatic options' tho??

**Comment by butzen0** [comment]
> mesmo problema.
> 
> > É assim que o script funciona se você não usar opções automáticas.
> 
> ok, mas o que são 'opções automáticas'??

é para rodar o script sem ter que selecionar nada, ele escolhe tudo como ALL
