### ISSUE TITLE
Cannot Get Past Updater.py phase

### ISSUE THREAD

**Issue by misterscraper** [DIGITALCRIMINALS/OnlyFans#885]
Keep getting the following error

`python3 updater.py
Updating dependencies
Resolving dependencies... (5.4s)

Writing lock file

Package operations: 2 installs, 8 updates, 0 removals

  • Updating urllib3 (1.26.14 -> 1.26.15)
  • Updating setuptools (67.5.1 -> 67.6.0)
  • Updating sqlalchemy (1.4.46 -> 2.0.5.post1)
  • Updating alembic (1.10.1 -> 1.10.2)
  • Updating importlib-metadata (4.13.0 -> 6.0.0)
  • Installing psycopg2 (2.9.5): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  /private/var/folders/n4/3s4nkch53tq9k_6r3jj15h_h0000gn/T/tmp9v2yr2jx/.venv/lib/python3.11/site-packages/setuptools/config/setupcfg.py:516: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
    warnings.warn(msg, warning_class)
  running egg_info
  writing psycopg2.egg-info/PKG-INFO
  writing dependency_links to psycopg2.egg-info/dependency_links.txt
  writing top-level names to psycopg2.egg-info/top_level.txt
  
  Error: pg_config executable not found.
  
  pg_config is required to build psycopg2 from source.  Please add the directory
  containing pg_config to the $PATH or specify the full executable path with the
  option:
  
      python setup.py build_ext --pg-config /path/to/pg_config build ...
  
  or with the pg_config option in 'setup.cfg'.
  
  If you prefer to avoid building psycopg2 from source, please install the PyPI
  'psycopg2-binary' package instead.
  
  For further information please check the 'doc/src/install.rst' file (also at
  <https://www.psycopg.org/docs/install.html>).
  
  

  at /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/poetry/installation/chef.py:152 in _prepare
      148│ 
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│ 
      151│             if error is not None:
    → 152│                 raise error from None
      153│ 
      154│             return path
      155│ 
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with psycopg2 (2.9.5) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "psycopg2 (==2.9.5) ; python_version >= "3.6""'.

  • Updating ultima-scraper-api (0.0.2.3 -> 0.0.2.4)
Script has been updated, exiting in 5 seconds`

**Comment by misterscraper** [comment]
`poetry run python start_us.py
Traceback (most recent call last):
  File "/Users/XXX/Downloads/OnlyFans-master/start_us.py", line 22, in <module>
    main_test.check_start_up()
  File "/Users/XXX/Downloads/OnlyFans-master/tests/main_test.py", line 21, in check_start_up
    from ultima_scraper_collection.managers.filesystem_manager import FilesystemManager
ModuleNotFoundError: No module named 'ultima_scraper_collection'`

**Comment by CannotTouch** [comment]
probably the latest commit 5948e9ddcaffafe653e7307584f27840e85fd751 is just something where he is still working on.

**Comment by Starwalker98** [comment]
I am on a mac, and i was able to get past this by installing postgresql (brew install postgresql). However the script itself is probably bugged, and it doesn't download much, if anything...

**Comment by misterscraper** [comment]
> I am on a mac, and i was able to get past this by installing postgresql (brew install postgresql). However the script itself is probably bugged, and it doesn't download much, if anything...

solved the updater issue, thanks!
