### ISSUE TITLE
All subscriptions have ID 1 & local variable 'authed' referenced before assignment

### ISSUE THREAD

**Issue by bogdanstoian1988** [DIGITALCRIMINALS/OnlyFans#887]
G:\NOPOR\OnlyFans-master>poetry run python start_us.py
Choose Sites: 0 = All | 1 = OnlyFans | 2 = Fansly
0
Choose Profiles: 0 = All | 1 = default
0
Choose Subscriptions: 0 = All | 1 = maeurn1 | 1 = chynabrgsx | 1 = younglaurenvip | 1 = dominant_rina | 1 = duchamprivate | 1 = nakedscarlett | 1 = freshmanevasky | 1 = autumnp0wersxo | 1 = lexyanne | 1 = onlyshams | 1 = naughtymother | 1 = fifigirl9
1
Traceback (most recent call last):
  File "G:\NOPOR\OnlyFans-master\start_us.py", line 71, in <module>
    asyncio.run(main())
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "G:\NOPOR\OnlyFans-master\start_us.py", line 53, in main
    api = await USR.start(
  File "G:\NOPOR\OnlyFans-master\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "G:\NOPOR\OnlyFans-master\ultima_scraper\ultima_scraper.py", line 114, in start_datascraper
    final_job_user_list = await datascraper.configure_datascraper_jobs()
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-LlvxK6Bo-py3.10\lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 134, in configure_datascraper_jobs
    if user.username in authed.blacklist:
UnboundLocalError: local variable 'authed' referenced before assignment

**Comment by Prophaniti86** [comment]
I've got this problem, but it doesn't give me the traceback, it keeps asking  me to choose medias and seems like it does continue with some things

Choose Subscriptions: 0 = All | 1 = goddess-mandy | 1 = eckobelleflexes | 1 = musclequeeen2308 | 1 = larissadominatrix | 1 = andrearosu | 1 = lisaxxxcross
0
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Processing Scraped Messages
100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 333.25it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 83.32it/s]
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Scrape Attempt: 1/100
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Scrape Attempt: 1/100
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Processing Scraped Posts
100%|████████████████████████████████████████████████████████████████████████████| 3640/3640 [00:00<00:00, 4149.57it/s]
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Processing metadata.
Finished processing metadata.
Renaming files.
  0%|                                                                                         | 0/3641 [00:00<?, ?it/s]Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
100%|██████████████████████████████████████████████████████████████████████████████| 3641/3641 [01:00<00:00, 59.76it/s]
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Processing Scraped Messages
100%|████████████████████████████████████████████████████████████████████████████████| 28/28 [00:00<00:00, 3499.11it/s]
Processing metadata.
Finished processing metadata.
Renaming files.
100%|█████████████████████████████████████████████████████████████████████████████████| 25/25 [00:00<00:00, 454.78it/s]

**Comment by DIGITALCRIMINALS** [comment]
Update the script, I still need to fix the "1" bug though.

Just set every automatic option to True.
