### ISSUE TITLE
Cant get it to work because I cant update Pip 

### ISSUE THREAD

**Issue by nomoreheros** [DIGITALCRIMINALS/OnlyFans#9]
im not too sure if it was you but i remember you had uploaded a video on how to install it id appreciate help even tho im a dumbass sorry if im annoying

**Comment by americanseeder1865** [comment]
What OS are you using?

**Comment by nomoreheros** [comment]
I’m using windows

**Comment by americanseeder1865** [comment]
run `python -m pip install --upgrade pip` and see if it fixes things
