### ISSUE TITLE
Please create branches when a new feature is added that breaks stuff..

### ISSUE THREAD

**Issue by twist3dimages** [DIGITALCRIMINALS/OnlyFans#910]
I generally never have this problem but please create branches. I have updated the script and something you added completely breaks it. Makes it incredibly frustrating to fix it because I have to hunt down a zip file I downloaded a few months ago

**Comment by dpsbrdi** [comment]
i mean you could just git checkout sha1here to go back to a older commit...

**Comment by twist3dimages** [comment]
or there could be branches like every other github repo

**Comment by twist3dimages** [comment]
And the test branch is broken so I can't switch to that.. you've broken it a few times. no need to be offended

**Comment by DIGITALCRIMINALS** [comment]
Explain to me, how am I supposed to know if it's broken when no one uses it.

**Comment by twist3dimages** [comment]
Sorry for being aggressive
