### ISSUE TITLE
Am I Missing modules?

### ISSUE THREAD

**Issue by toomanydevils** [DIGITALCRIMINALS/OnlyFans#916]
I've been using the script a while, but not very python smart myself. Had an old release that used the -requirements files to install, and am super lost now with this new Ultima Scraper.

I run into these errors after following the directions, Tried both CMD and PS, cant figure out what I'm doing wrong...

> G:\Downloads\OnlyFans-master\OnlyFans-master>python updater.py
> Traceback (most recent call last):
>   File "G:\Downloads\OnlyFans-master\OnlyFans-master\updater.py", line 50, in <module>
>     subprocess.run(["poetry", "update"])
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 548, in run
>     with Popen(*popenargs, **kwargs) as process:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1024, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1493, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [WinError 2] The system cannot find the file specified

Any help is appreciated.

**Comment by soulburn74** [comment]
The problem I had, was 1. setting the Path statements, so that windows see's where Python and Poetry are, without having to put hte full path when using them in ps, or cmd scripts.  Also don't forget to install poetry...... but Just know, that the current state of things with updated ultima scraper are not fully functional yet either........
*seems like we are in a holding pattern at the moment, until things are fixed*

**Comment by toomanydevils** [comment]
Yeah I tried installing, uninstalling poetry with both PS and CMD, they reported 1.4.1 but neither will recognize poetry as an argument. I just remember sometimes requirements would change if I tried a different release when it was the old versions, and I'd have to search the issues and discussion pages to get them going, but the post here by DC #901 that seems to do what its intended, but still cant get past the running the updater stage,

**Comment by soulburn74** [comment]
the not recognizing as an argument, is definitely due to you needing to configure path statement.

**Comment by toine512** [comment]
You need to run `poetry update`. That's not documented.
#848
