### ISSUE TITLE
Cannot run the scraper.

### ISSUE THREAD

**Issue by hydr0homiee** [DIGITALCRIMINALS/OnlyFans#930]
So I tried to update to the newest verison after running into time out issues due to the new limit. The update got botched somehow so I couldn't run the new or old one any more. I uninstalled Python and deleted all packages, environments, etc. Then reinstalled Python 3.10 and Poetry.

I was able to run the updater fine, but when I go to run the script nothing happens.

```
>> Y:\OF-Ripper> python updater.py
Creating virtualenv ultima-scraper-shYWRsa1-py3.10 in C:\Users\****\AppData\Local\pypoetry\Cache\virtualenvs
Updating dependencies
Resolving dependencies...

Writing lock file

Package operations: 85 installs, 1 update, 0 removals

  • Installing certifi (2022.12.7)
   ...
  • Installing ultima-scraper-renamer (0.1.3)
Script has been updated, exiting in 5 seconds
>> Y:\OF-Ripper> poetry run python start_us.py
>> Y:\OF-Ripper>
```
Windows 10
Python 3.10.10 (installed from python.org, not Windows Store)
Poetry 1.4.2
All variables are added to PATH (`python --version` and `poetry --version` both return the correct values)

**Comment by demib72** [comment]
Try ./start_us.py. Don't know if window's terminal is different than the one in linux in this regard.

**Comment by hydr0homiee** [comment]
I tried that and nothing runs still.

```
>> Y:\OF-Ripper> poetry run python ./start_us.py
>> Y:\OF-Ripper>
```

If I try just `poetry` it asks for args and stuff. I don't know why it won't run any of them though.

**Comment by Bearded-Beard** [comment]
https://github.com/DIGITALCRIMINALS/OnlyFans/issues/902 run the two last posts by me, it should give you a working version of the scraper till DC fixes what ever is going on with current commit

**Comment by hydr0homiee** [comment]
Thanks, that got it mostly working! It seems to crash after restarting but that's something I can deal with
