### ISSUE TITLE
[Fansly] Not scraping paid videos

### ISSUE THREAD

**Issue by dave2197** [DIGITALCRIMINALS/OnlyFans#94]
It scrapes free content flawlessly, but doesn't seem to be scraping paid videos from wall or dm's (dunno about paid pics, and yes, "scrape_paid_content" is set to TRUE).

Can anyone test if i'm the only one experiencing this ?

Thank you!

**Comment by DIGITALCRIMINALS** [comment]
I haven't bought anything from Fansly yet so I wouldn't know how to implement this .-.

**Comment by DIGITALCRIMINALS** [comment]
Update to the latest version, it should work
