### ISSUE TITLE
No file called .profiles/default/auth.json to edit??

### ISSUE THREAD

**Issue by benshandd** [DIGITALCRIMINALS/OnlyFans#97]

**Comment by DIGITALCRIMINALS** [comment]
Are you on Windows?

**Comment by ali-m-github** [comment]
> Are you on Windows?

I am having the same issue, no ./profiles after running the start_ofd.py file.
I am on Windows 10.

**Comment by naniwatiger** [comment]
Same issue as well

**Comment by DIGITALCRIMINALS** [comment]
Probably need to enable hidden folders

**Comment by KevinxFinnerty** [comment]
this is happening to me to. Hidden Folders are already enabled

**Comment by aboredpervert** [comment]
It should automatically open the file for edition now. It doesn't do that?

**Comment by mprup** [comment]
I am having this same issue on Windows 10. Installed the latest version, ran pip3 install --upgrade --user -r requirements.txt and am running Python 3.10. When I click on start.ofd, the window opens, then immediately closes, with no changes taking place in the directory.

**Comment by aboredpervert** [comment]
Run `start_ofd.py` from a console (cmd or PowerShell) so you can see the errors.
