### ISSUE TITLE
Stuck Downloading 

### ISSUE THREAD

**Issue by upr33** [DIGITALCRIMINALS/OnlyFans#98]
Amazing work. I've used it nearly 10 months now, but from recent I cannot download any content. It get stuck every time in this line 

"Download Processing"

I updated pip, I got latest version of python I also got everything that required. I have waited hours. but its still stucked in their. Your help and consideration is highly appreciated. Thanks

![error](https://user-images.githubusercontent.com/75036902/142046917-7e72b0e9-a2f9-427d-a7cb-0cb8d911ceea.png)

**Comment by DIGITALCRIMINALS** [comment]
Update the script via the updater file

**Comment by upr33** [comment]
> Update the script via the updater file

I tried. But still same. In the certain line, something happen to my connection. All my uploads, downloads (such as Mega.nz) instantly reconnect. I checked several times. There is no problem with my connection. But this issue occur only when I run the scraper ( at the above mentioned line )

**Comment by DIGITALCRIMINALS** [comment]
Try latest version of script
